### PR TITLE
Fixed translation display in GUI

### PR DESCRIPTION
**Pull request by MistificaT0r**

### CODE REVIEW

**Review by pfps — COMMENTED** [review]
These changes look reasonable but do they make a difference?

**Comment by pfps** [comment]
As far as I can tell the import changes are not needed.

**Comment by MistificaT0r** [comment]
Without these changes, the translation does not work in the interface.

**Comment by MistificaT0r** [comment]
**Without changes.**
image
image


**With changes.**
image
image

**Comment by pfps** [comment]
OK.  I see what was going on.

**Pull request merged**
