### PR TITLE
dist: change name of light icons and distrbute to correct place

### LINKED ISSUE #2285: PNG icons installed as scalable icons
The 1.1.11 pre-releases install various PNG icons in `/usr/share/icons/hicolor/scalable/apps/`, but the `scalable` hierarchy is reserved for scalable (SVG) icons.

### PR DESCRIPTION
**Pull request by pfps**
Fixes #2285

### CODE REVIEW

**Comment by MattHag** [comment]
It doesn't make sense to convert a rasterized PNG to a scalable SVG, that doesn't work.

 In that particular case, the SVG seems to just wrap the complete PNG. That is not useful and hides, that the SVG is not scalable.

**Comment by pfps** [comment]
These icons are only used for one or two old devices so spending time to make them better is not very useful.

**Comment by MattHag** [comment]
Leave them as they are, they just got bigger and wrapped with another layer hiding what format it actually is. If there is an appropriate folder for rasterized images, then move them there. Otherwise, I'd leave them where they are until a nice solution has been found.

**Comment by pfps** [comment]
Ok, they are now renamed better and moved to the correct place.

**Comment by david-geiger** [comment]
I think you should also do:

sed -i 's|yield 'share/icons/hicolor/32x32/apps', _glob('share/solaar/icons/light_*.png')|yield 'share/icons/hicolor/32x32/apps', _glob('share/solaar/icons/solaar-light_*.png')|' setup.py

**Comment by david-geiger** [comment]
"share/solaar/icons/light_*.png" -> "share/solaar/icons/solaar-light_*.png"

**Comment by pfps** [comment]
Argh.  You are correct.

**Pull request merged**
