### PR TITLE
dist: add git date to version information

### LINKED ISSUE #1852: Add git information in about and console
**Information**
Installed version of solaar::  1.1.7+git1897-9c361c4~ubuntu22.10.1
Distribution: Ubuntu 22.10 + https://launchpad.net/~solaar-unifying/+archive/ubuntu/ppa (git)
Kernel version: Linux 6.1.0-060100rc5-generic x86_64 GNU/Linux

Example:
a)
image

b)
$ solaar show
Solaar version 1.1.7-9c361c4

[...]

### PR DESCRIPTION
**Pull request by pfps**
Fixes #1852

### CODE REVIEW

**Comment by icp1994** [comment]
`typing_extensions` dependency was removed in https://github.com/pwr-Solaar/Solaar/commit/e15b58fdaa9137556e98e618489dffac12de13b8 so should also be edited out from the installation doc.

**Comment by pfps** [comment]
I think that if you are running python3.7 then typing_extensions should be made available, as it is used by an included package.

**Comment by icp1994** [comment]
Oh, I thought it was pulled in the by the optional dependency hid-parser itself.

**Comment by pfps** [comment]
Yes, but this is an account of the system packages needed.

**Pull request merged**
