### PR TITLE
Support for GESTURE_2 settings

### LINKED ISSUE #411: MX Master: Support configuration of thumb wheel sensitivity and direction
Logitech Options on Windows has a slider to control the thumb wheel sensitivity, and toggle to choose whether the direction of the thumb wheel should be inverted. Both options have defaults that are less than great. In particular, the sensitivity is so low that the thumb wheel becomes useless, so it would be nice to be able to configure these from Solaar.

### PR DESCRIPTION
**Pull request by viniciusbm**
Closes #411.
Closes #788.

This is a follow-up to #934 and #788.

I didn't use the set and get methods directly from Gesture because I tried to avoid unnecessary requests, which is possible because we can read and write options that share an offset in a single request. 

@pfps, thank you for writing the code of #934 (upon which this PR is based). I retained your old commit, as I didn't know a good way to replace it with your updates after I made a lot of changes.

So far, I've only implemented the boolean settings. I tried to make the UI look better than that ugly hack I had written (#818), but it still has some alignment issues. The UI changes also apply to KEYBOARD_DISABLE_KEYS. 

Of course, corrections and ideas are welcome.

### CODE REVIEW

**Comment by lukasmichel** [comment]
I just tested this PR on the MX Master 2S. It gives me two toggles: 1 to disable the thumb wheel and one to change the thumb wheel scroll direction. I didn't see any problems so far

**Comment by viniciusbm** [comment]
I'll update this PR soon with the implementation of the params.

**Comment by viniciusbm** [comment]
I've just updated the code, but since I don't have any device to test multiple params and/or params with more than one value (such as left, right, etc.), it's not impossible that there are bugs. 

<details><summary>This is what the UI looks like:</summary>

image
</details>

### Known issues:

**1.** The settings can be collapsed by clicking the button on the right, but the layout gets weird after doing that.

<details><summary>Example</summary>

image
</details>

**2.** If there are many settings, the window can be too large, so ideally they should start collapsed. Implementing this doesn't seem to be trivial: some parts of the UI code don't work if the widgets start hidden.

**3.** @pfps, is the second number supposed to be 2?

```python
SPEC = _NamedInts(
    DVI_field_width=1,
    field_widths=1,
    period_unit=3,
    ...
```

**4.** To do: on the panel, display translatable strings rather than the NamedInts.

**5.** @pfps, do you know if some specs use a different format? I get an error with number 5.
<details><summary>Example (executed manually, not on Solaar):</summary>

image
</details>

**Comment by viniciusbm** [comment]
> I just tested this PR on the MX Master 2S. It gives me two toggles: 1 to disable the thumb wheel and one to change the thumb wheel scroll direction. I didn't see any problems so far

@lukasmichel, thanks for testing this PR. Would you mind having a look at the updated version?

**Comment by lukasmichel** [comment]
I still see Thumbwheel and NaturalScrolling gestures, however, the toggle fields are now much larger than before and also larger than the other  toggles. 
<details>
  <summary>Screenshot</summary>

Screenshot_20200831_114629

</details>

Additionally, the output of `solaar show -d` has changed. It now lists the two gestures and 4 specs:
<details>
<summary>Output</summary>

```
$ ./bin/solaar -d show "MX Master 2S" 
11:41:05,418     INFO [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,3)>: found new device 1 (4069)
  1: Wireless Mouse MX Master 2S
     Device path  : /dev/hidraw2
     USB id       : 046d:4069
     Codename     : MX Master 2S
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 493D1134
        Bootloader: BOT 56.01.B0006
          Firmware: MPM 12.01.B0006
          Firmware: MPM 12.01.B0006
             Other: 
     The power switch is located on the base.
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: CRYPTO ID              {0021}   
         7: BATTERY STATUS         {1000}   
         8: CONFIG DEVICE PROPS    {1806}   internal, hidden
         9: CHANGE HOST            {1814}   
            Change Host: 1:ARCH-Desktop
        10: REPROG CONTROLS V4     {1B04}   
            Actions: {'80': 80, '81': 81, '82': 196, '83': 83, '86': 86, '195': 195, '196': 82}
        11: ADJUSTABLE DPI         {2201}   
            Sensitivity (DPI): 3000
        12: VERTICAL SCROLLING     {2100}   
            Roller type: 3G
            Ratchet per turn: 24
            Scroll lines: 0
        13: SMART SHIFT            {2110}   
            Smart Shift: 11
        14: HIRES WHEEL            {2121}   
            Multiplier: 8
            Has invert
              Normal wheel motion
            Has ratchet switch
              Normal wheel mode
            High resolution mode
            HID notification
            High Resolution Wheel Invert: False
            Wheel Resolution: True
        15: GESTURE 2              {6501}   
            Gestures: {'46': True, '45': True}
        16: DFUCONTROL SIGNED      {00C2}   
        17: unknown:1813           {1813}   internal, hidden
        18: unknown:1830           {1830}   internal, hidden
        19: unknown:1890           {1890}   internal, hidden
        20: unknown:1891           {1891}   internal, hidden
        21: unknown:18A1           {18A1}   internal, hidden
        22: unknown:18C0           {18C0}   internal, hidden
        23: unknown:1DF3           {1DF3}   internal, hidden
        24: unknown:1E00           {1E00}   hidden
        25: unknown:1EB0           {1EB0}   internal, hidden
        26: unknown:1803           {1803}   internal, hidden
        27: unknown:1861           {1861}   internal, hidden
        28: unknown:9001           {9001}   internal, hidden
        29: unknown:9200           {9200}   internal, hidden
        30: unknown:9202           {9202}   internal, hidden
        31: OOBSTATE               {1805}   internal, hidden
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Smart Shift               
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: App Switch Gesture        , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         6: Smart Shift               , default: Smart Shift                 => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Has 2 gesture(s), 0 param(s) and 4 spec(s):
        Thumbwheel                 Enabled (   0): True
        NaturalScrolling           Enabled (   1): True
        period unit                Spec    (   3): 800
        field widths               Spec    (   1): 8
        unknown:0002               Spec    (   2): 8
        resolution                 Spec    (   4): 2048
     Battery: 50%, discharging, next level 20%.
```

</details>

What do those specs mean? I can't see/set/change them in solaar and I also can't link them to any setting/specification of my mouse.

**Comment by viniciusbm** [comment]
@lukasmichel, thank you for your feedback.

> the toggle fields are now much larger than before and also larger than the other toggles. 

I've just updated the code with a potential fix. If it still looks bad, please tell me what desktop environment you use (it looks like KDE?) so that I can test it on a virtual machine. 


> What do those specs mean? I can't see/set/change them in solaar and I also can't link them to any setting/specification of my mouse.

They cannot be changed, but they're shown on the bottom-left corner of your screenshot. By the way, I don't know if adding them to that place was a good idea. Let's see what the project maintainers think.

Regarding their meaning, maybe @pfps has some information. I just implemented them because it was an easy addition, and I don't know if they're going to be kept.

**Comment by pfps** [comment]
@viniciusbm
Fixing the layout probably requires some attention to fillers in the GTK widgets.
Yes, the number for field_widths should be 2.
NamedInts should display as strings if you use %s.
Spec 5 (multiplier) should be a byte-sized integer giving the "distance" that a single click of the wheeel produces.

@lukasmichel
The specs are what the device reports to software about how the gestures are implemented.  They are not changeable.  Showing them in the UI isn't going to be very useful.

**Comment by pfps** [comment]
@viniciusbm I would leave the specs out of the UI.  Showing them in `solaar show` should be sufficient.

**Comment by viniciusbm** [comment]
> NamedInts should display as strings if you use %s.

They were already being displayed as strings, which were the names of the NamedInts. I've changed the labels to translated strings and added tooltips, falling back to the name only if a proper label isn't available. Since I don't know exactly what some of the gestures mean and what action they do, there are still some labels and tooltips to add.

By the way, I've tested the three swipe gestures that my keyboard supports, and they send the following key combinations:

```
LeftEdgeSwipe1Finger2   ->  Ctrl + Super + Backspace
RightEdgeSwipe1Finger2  ->   Alt + Super + XF86TouchPadOff
TopEdgeSwipe1Finger2    ->  Ctrl + Super + XF86TouchPadOff
```

I didn't add this to the tooltips because I don't know if this the gesture actions are the same in every device.

**Comment by viniciusbm** [comment]
> Fixing the layout probably requires some attention to fillers in the GTK widgets.

I think I fixed the layout problem by letting the config panel expand: 
```
     p._config = _config_panel.create()
-    p.pack_end(p._config, False, False, 4)
+    p.pack_end(p._config, True, True, 4)
```

<details>
<summary> Expanded </summary>

image
</details>

<details>
<summary> Collapsed </summary>

image
</details>

**Comment by viniciusbm** [comment]
> Spec 5 (multiplier) should be a byte-sized integer giving the "distance" that a single click of the wheel produces.

That probably doesn't make sense in a touchpad, which has no wheel. However, since the device (incorrectly?) lists spec 5 as supported, I get the following error:

```
ERROR [MainThread] logitech_receiver.base: (4) device 1 error on feature request {0D5F}: 2 = invalid argument
        multiplier                 Spec    (   5): None
```

I catch the exception and set the spec value to `None`, but the log error is generated by `base.py`, so I don't think there's anything reasonable that can be done. @pfps, what do you think?

**Comment by lukasmichel** [comment]
I think one could interpret touchpad scrolling as a wheel. Then this spec would make sense. 

I'll have a look at the UI again later, I am currently only on my phone

**Comment by pfps** [comment]
Solaar generates lots of exceptions that  are caught.   They show up in debug output.  I don't think that's a problem.

**Comment by lukasmichel** [comment]
The toggle widgets now look better, i.e. they are as wide as the others. But now, the whole line is highlighted when hovering over the setting name or the toggle switch instead of only highlighting the switch as for the other settings (see Screenshots below)
<details>
<Summary>Screenshots</Summary>

Hover over Gesture toggle
Hover over other toggle
Note that there is no highlight for the toggle when I only hover over the setting name

</details>

> I've just updated the code with a potential fix. If it still looks bad, please tell me what desktop environment you use (it looks like KDE?) so that I can test it on a virtual machine.

I am indeed using KDE with Breeze-Dark theme.

**Comment by viniciusbm** [comment]
> I think one could interpret touchpad scrolling as a wheel. Then this spec would make sense.

I don't know how a step would be defined in that case, but anyway, it says it has the spec but returns an error if we try to retrieve it. 

> Solaar generates lots of exceptions that are caught. They show up in debug output. I don't think that's a problem.

@pfps, you're right, this isn't something we should worry about. 


> But now, the whole line is highlighted when hovering over the setting name or the toggle switch instead of only highlighting the switch as for the other settings
> I am indeed using KDE with Breeze-Dark theme.

@lukasmichel, thanks for reporting that. I've just fixed it, and it looks right on a VM wtih KDE using Breeze-Dark (and KDE themes enabled for GTK applications).

**Comment by lukasmichel** [comment]
Thanks @viniciusbm, looks great now. 
You're doing an incredible job with this feature implementation, thanks for that. 

> The specs are what the device reports to software about how the gestures are implemented. They are not changeable. Showing them in the UI isn't going to be very useful.

@pfps so that means we probably don't have any option to configure the resolution/speed of the thumb wheel in the MX Master?

**Comment by pfps** [comment]
@lukasmichel Yes, it sure looks as if there is no good way to change the speed of the thumb wheel.  The only way would be to divert and intercept thumb wheel reports and create new input events for them.  Such modification of input events is better done in the Linux input system as far as I am concerned.

**Comment by arigit** [comment]
@lukasmichel @pfps  RE setting the resolution of the thumbwheel, 

https://gitlab.freedesktop.org/xorg/driver/xf86-input-libinput/-/issues/3

This was I think for the older Master MX; I recall being asked by Peter to capture some debug logs and do some measurements on the thumbwheel, and there is this discussion

https://github.com/systemd/systemd/issues/3947

This said I can't recall where all of that landed. I do remember that what I wanted is to be able to set the sensitivity of the thumbwheel as it's not very usable with the default behavior

**Comment by pfps** [comment]
@arigit  The problem is that doesn't seem to be any way to change the resolution of the thumbwheel of the MX Master without reinterpreting the input events coming from the mouse.  GESTURE 2 has a setting that it appears could be used to change the input events coming from the mouse that but it appears that the MX Master doesn't have this setting.  Solaar isn't set up for reinterpreting input events so it looks like users with this mouse will have to fiddle with the Linux input mechanisms to change thumb wheel sensitivity.

If anyone has information showing how Solaar could get the MX Master to change it sensitivity for the thumb wheel please let me know.

**Pull request merged**
