### PR TITLE
Add wired devices to Solaar GUI

### PR DESCRIPTION
**Pull request by pfps**
Adds wired devices that talk HID++ to the Solaar GUI.
Also adds G502 Hero mouse USB information
Also lets config and probe work on wired devices
Also adds more information to show

### CODE REVIEW

**Comment by pfps** [comment]
@doctor64 @barolo @sk8geek @mschilli87 
Please test this out, particularly if you have a Logitech HID++ device that can connect with a USB cable.
Try connecting and disconnecting the receiver and the USB cable.  
Everything should work fine.  The only potential issue that the device might end up with several entries in ~/.config/solaar/config.json   This is due to several ways of determining the identity of the device.  I'm trying to figure out what is the best way to get a serial number for devices.

**Comment by mschilli87** [comment]
@pfps: I plan to have a look but I won't manage before next week. Feel free to ping me again if you don't hear back from me in a reasonable time.

**Comment by muzena** [comment]
@pfps 
Is this patch also for G700s, when is connected via USB cable?

**Comment by pfps** [comment]
@muzen As long as the device talks HID++, yes.  I believe that Logitech device that talk HID++ have three USB interfaces.  So to see if a direct-wired Logitech device talks HID++ look for bInterfaceNumber 2 for that device when connected through the USB cord.

**Comment by muzena** [comment]
@pfps 
Do you mean this?
bInterfaceNumber  0 and 1
<details>
<summary>lsusb -d 046d:c07c -v</summary>

```
Bus 001 Device 003: ID 046d:c07c Logitech, Inc. M-R0017 [G700s Rechargeable Gaming Mouse]
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        32
  idVendor           0x046d Logitech, Inc.
  idProduct          0xc07c M-R0017 [G700s Rechargeable Gaming Mouse]
  bcdDevice           85.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 3 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x003b
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          4 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              498mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      67
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     122
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0014  1x 20 bytes
        bInterval               1

```

</details>

**Comment by pfps** [comment]
Hmm.  No interface 2, but interface 1 looks like it might be an HID++ interface as it doesn't say mouse or keyboard.
To set up this device you will have to add a function like _wired_device but with usb_interface 1.

**Comment by muzena** [comment]
@pfps 
like _wired_device but with usb_interface 1     -  How can I add that?

I add this:
 lib/logitech_receiver/base_usb.py
 WIRED_DEVICE_c07c = _wired_device(0xc08d)  # G700s

WIRED_DEVICE_C07c,

and rule to udev file:
 ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c07c", GOTO="solaar_apply"



solaar show, error:
NameError: name 'WIRED_DEVICE_C07c' is not defined

**Comment by pfps** [comment]
c07c vs C07c !

**Comment by pfps** [comment]
You need to also tell Solaar that your device uses interface 1 - most HID++ devices use interface 2.  The quick-and-dirty way to do this is to use interface 1 for all wired devices (the others won't work, of course) via changing the _wired_device function to:
```
_wired_device = lambda product_id: {'vendor_id': 0x046d, 'product_id': product_id, 'usb_interface': 1, 'isDevice': True}
```
The right way would be to add another function, _wired_device_1 and use that for your device.

**Comment by pfps** [comment]
If your device doesn't understand HID++ on interface 1 you will probably see lots of errors.

**Comment by muzena** [comment]
@pfps 

Now 'solaar show' register g700s mouse but without name.
<details>
<summary>solaar show</summary>

```
EX100 Receiver 27 Mhz
  Device path  : /dev/hidraw1
  USB id       : 046d:c517
  Serial       : None
  Has 2 paired device(s) out of a maximum of 4.
  Notifications: wireless (0x000100)

  1: LX5 Cordless Mouse
     Device path  : /dev/hidraw5
     USB id       : 046d:0036
     Codename     : LX5
     Kind         : mouse
     Protocol     : HID++ 1.0
     Serial number: ?
     The power switch is located on the (unknown).
     Notifications: roller V, mouse extra buttons, battery status, roller H (0x3C0000).
     Features: special buttons, scroll accel (0x420000)
     Battery: good, discharging.

  3: Wireless Keyboard S510
     Device path  : /dev/hidraw4
     USB id       : 046d:0056
     Codename     : S510
     Kind         : keyboard
     Protocol     : HID++ 1.0
     Serial number: ?
     The power switch is located on the (unknown).
     Notifications: keyboard multimedia raw, battery status (0x110000).
     Features: special buttons, scroll accel (0x420000)
     Battery: full, discharging.

Wired Devices
  1: ? (c07c)
     Device path  : /dev/hidraw3
     USB id       : 046d:c07c
     Codename     : ? (c07c)
     Kind         : ?
     Protocol     : HID++ 1.0
     Serial number: 42FBBA880007
          Firmware: 45.00.B0007
        Bootloader: 00.11
             Other: 02.02
     Notifications: (none).
     Features: (none)
     Battery: N/A, full.

```

</details>

**Comment by muzena** [comment]
@pfps 
I noticed that G700s is not shown in solaar GUI but is visible in solaar tray icon in notification area.

**Comment by pfps** [comment]
@muzena There is the assumption that wired devices that talk HID++ talk HID++ 2.0.  Your device talks HID++ 1.0.  Try running `bin/solaar probe 42FBBA880007` after removing the return on line 45.  Maybe this will show how to communicate with such devices.

**Comment by muzena** [comment]
@pfps 

You mean line 45: usb_interface': 1,

<details>
<summary>solaar probe 42FBBA880007</summary>

```
  1: ? (c07c)
     Device path  : /dev/hidraw3
     USB id       : 046d:c07c
     Codename     : ? (c07c)
     Kind         : ?
     Protocol     : HID++ 1.0
     Serial number: 42FBBA880007
          Firmware: 45.00.B0007
        Bootloader: 00.11
             Other: 02.02
     Notifications: (none).
     Features: (none)
     Battery: N/A, full.

```

</details>

**Comment by pfps** [comment]
In probe.py there is a return if the "receiver" is a device.  Remove this return (line 45) so that if the "receiver" is a device it is printed as if it were a receiver.

**Comment by muzena** [comment]
@pfps 
Removing return (line 45) in probe.py gave me this error:
<details>
<summary>solaar probe 42FBBA880007</summary>

```
  1: ? (c07c)
     Device path  : /dev/hidraw3
     USB id       : 046d:c07c
     Codename     : ? (c07c)
     Kind         : ?
     Protocol     : HID++ 1.0
     Serial number: 42FBBA880007
          Firmware: 45.00.B0007
        Bootloader: 00.11
             Other: 02.02
     Notifications: (none).
     Features: (none)
     Battery: N/A, full.
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 199, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/share/solaar/lib/solaar/cli/probe.py", line 47, in run
    _print_receiver(receiver)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 31, in _print_receiver
    paired_count = receiver.count()
AttributeError: 'Device' object has no attribute 'count'

```

</details>

**Comment by pfps** [comment]
OK.  It looks as if your mouse is similar to one I have.  They both talk HID++ of some sort, but not the one that Solaar talks.  I'll see if I can get information on what they do.

**Comment by pfps** [comment]
There are some wired devices that don't talk HID++ 2.0 (or even HID++ 1.0 as Solaar understands it).  The devices that should work when wired are the ones that can either be wired or connect through a receiver.

**Comment by pfps** [comment]
Argh.  I accidentally deleted the branch on my repository that this comes from, which closed this PR and there doesn't seem to be any way to get it back.  I'll create a new PR and put some of the information from here in it.

**Comment by muzena** [comment]
@pfps 
> OK. It looks as if your mouse is similar to one I have.

G700 Gaming Mouse?

**Comment by pfps** [comment]
The one I have is a MX518 Gaming mouse.  The similarity that that they both appear to talk HID++ but not a protocol that Solaar knows.

**Pull request closed without merging**
