### PR TITLE
Add G602 support

### PR DESCRIPTION
**Pull request by rijnhard**
Is based on https://github.com/pfps/Solaar/tree/c537
Requires https://github.com/pwr-Solaar/Solaar/pull/646 to be merged first

Basically I added safety on the  `check_feature` call so that the device can still be detected even if some features are not consistent with spec or what solaar expects.

My test results with c537 and g602:

This is the full output for starting solaar, opening the gui from the app indicator, selecting the g602 and clicking on info.

Screenshot from 2020-02-18 11-33-07

```
sudo python3 ./bin/solaar -dd
11:32:30,958     INFO [MainThread] root: language en_ZA (UTF-8), translations path /Data/OpenSource/Solaar/share/locale
11:32:31,049    DEBUG [MainThread] solaar.ui.tray: using AppIndicator3
11:32:31,059     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
11:32:31,100    DEBUG [MainThread] solaar.ui: startup registered=True, remote=False
11:32:31,101    DEBUG [AsyncUI] solaar.tasks: started
11:32:31,106    DEBUG [MainThread] solaar.ui.icons: sys.path[0] = /Data/OpenSource/Solaar/lib
11:32:31,107    DEBUG [MainThread] solaar.ui.icons: looking for icons in /Data/OpenSource/Solaar/icons
11:32:31,107    DEBUG [MainThread] solaar.ui.icons: looking for icons in /Data/OpenSource/Solaar/share/solaar/icons
11:32:31,107    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/rijnhard/.local/share/solaar/icons
11:32:31,107    DEBUG [MainThread] solaar.ui.icons: looking for icons in /Data/OpenSource/Solaar/share/solaar/icons
11:32:31,107    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/local/share/solaar/icons
11:32:31,107    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
11:32:31,107    DEBUG [MainThread] solaar.ui.icons: icon theme paths: ['/usr/share/solaar/icons', '/Data/OpenSource/Solaar/share/solaar/icons', '/Data/OpenSource/Solaar/share/solaar/icons', '/home/rijnhard/.local/share/icons', '/home/rijnhard/.icons', '/usr/local/share/icons', '/usr/share/icons', '/usr/local/share/pixmaps', '/usr/share/pixmaps']
11:32:31,123    DEBUG [MainThread] solaar.ui.icons: detected icon sets: Mint True, gpm True, oxygen True, gnome True, elementary True
11:32:31,138     INFO [MainThread] solaar.listener: starting receiver listening threads
11:32:31,172     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw1', vendor_id='046d', product_id='c537', serial='', release=b'3400', manufacturer=b'Logitech', product=b'USB Receiver', interface=1, driver='hid-generic')
11:32:31,172    DEBUG [MainThread] logitech_receiver.base: (12) <= w[10 FF 83B5 030000]
11:32:31,174    DEBUG [MainThread] logitech_receiver.base: (12) => r[11 FF 83B5 0384E398F30101070000000000000000]
11:32:31,174    DEBUG [MainThread] logitech_receiver.base: (12) <= w[10 FF 80B2 000000]
11:32:31,175    DEBUG [MainThread] logitech_receiver.base: (12) => r[10 FF 8F80 B20300]
11:32:31,175    DEBUG [MainThread] logitech_receiver.base: (12) device 0xFF error on request {80B2}: 3 = invalid value
11:32:31,175     INFO [ReceiverListener:hidraw1] logitech_receiver.listener: started with <NanoReceiver(/dev/hidraw1,12)> (12)
11:32:31,176     INFO [ReceiverListener:hidraw1] solaar.listener: <NanoReceiver(/dev/hidraw1,12)>: notifications listener has started (12)
11:32:31,176    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 FF 8000 100900]
11:32:31,177    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[10 FF 8000 000000]
11:32:31,177    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 FF 8100 000000]
11:32:31,178    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[10 FF 8100 000900]
11:32:31,178     INFO [ReceiverListener:hidraw1] logitech_receiver.receiver: <NanoReceiver(/dev/hidraw1,12)>: receiver notifications enabled => ('wireless', 'software present')
11:32:31,178    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 FF 8002 020000]
11:32:31,179    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[10 01 4107 122C40]
11:32:31,181    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[10 FF 8002 000000]
11:32:31,181     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <NanoReceiver(/dev/hidraw1,12)>: present, No paired devices. (0) 
11:32:31,181    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 FF 83B5 400000]
11:32:31,182    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 FF 83B5 40044736303200000000000000000000]
11:32:31,182     INFO [ReceiverListener:hidraw1] logitech_receiver.receiver: <NanoReceiver(/dev/hidraw1,12)>: found new device 1 (402C)
11:32:31,182    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 FF 83B5 300000]
11:32:31,183    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 FF 83B5 308D13D0BD0E00000001000000000000]
11:32:31,182     INFO [ReceiverListener:hidraw1] solaar.listener: Notification(1,41,07,122C40) triggered new device <PairedDevice(1,402C,G602,8D13D0BD)> (mouse)
11:32:31,184    DEBUG [ReceiverListener:hidraw1] solaar.configuration: load => {'402C:8D13D0BD': {'_name': 'Wireless Gaming Mouse'}, '_version': '1.0.1'}
11:32:31,184    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) pinging device 1
11:32:31,184    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 001D 0000A5]
11:32:31,187    DEBUG [MainThread] solaar.ui: activate
11:32:31,188    DEBUG [MainThread] solaar.ui: status changed: <NanoReceiver(/dev/hidraw1,12)> (NONE) None
11:32:31,189    DEBUG [MainThread] solaar.ui.window: new receiver row ('/dev/hidraw1', 0, True, 'Nano Receiver', 'preferences-desktop-peripherals', None, None, <NanoReceiver(/dev/hidraw1,12)>)
11:32:31,207    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 001D 0200A500000000000000000000000000]
11:32:31,208    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 000C 000100]
11:32:31,310    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000C 01000000000000000000000000000000]
11:32:31,311    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 010A 000000]
11:32:31,415    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 010A 16000000000000000000000000000000]
11:32:31,415    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 0008 000500]
11:32:31,510    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 0008 03000000000000000000000000000000]
11:32:31,511    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 0309 000000]

(solaar:8421): Gdk-CRITICAL **: 11:32:31.602: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
11:32:31,614    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 0309 15000000000000000000000000000000]
11:32:31,614    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 0318 000000]
11:32:31,719    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 0318 576972656C6573732047616D696E6720]
11:32:31,719    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 031A 100000]
11:32:31,814    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 031A 4D6F7573650000000000000000000000]
11:32:31,815     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <NanoReceiver(/dev/hidraw1,12)>: present, 1 paired device. (0) 
11:32:31,816    DEBUG [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(1,402C,G602,8D13D0BD)>: eQUAD step 4 Gaming connection notification: software=True, encrypted=False, link=True, payload=False
11:32:31,816    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 0009 212000]
11:32:31,816    DEBUG [MainThread] solaar.ui: status changed: <NanoReceiver(/dev/hidraw1,12)> (NONE) None
11:32:31,918    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 0009 00000000000000000000000000000000]
11:32:31,918    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 0009 213000]
11:32:32,014    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 0009 00000000000000000000000000000000]
11:32:32,015    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 0009 212100]
11:32:32,118    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 0009 00000000000000000000000000000000]
11:32:32,119    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 000E 212100]
11:32:32,222    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000E 00000000000000000000000000000000]
11:32:32,222    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 000A 40A000]
11:32:32,318    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000A 00000000000000000000000000000000]
11:32:32,318    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 000D 40A200]
11:32:32,422    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000D 00000000000000000000000000000000]
11:32:32,422    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 000D 40A300]
11:32:32,527    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000D 00000000000000000000000000000000]
11:32:32,527    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 000B 220100]
11:32:32,623    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000B 0D000000000000000000000000000000]
11:32:32,623    DEBUG [ReceiverListener:hidraw1] logitech_receiver.settings_templates: check_feature[ADJUSTABLE DPI] dpi field_name dpi
11:32:32,624    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 0D1A 000000]
11:32:32,727    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 FF0D 1A020000000000000000000000000000]
11:32:32,727    ERROR [ReceiverListener:hidraw1] logitech_receiver.base: (12) device 1 error on feature request {0D1A}: 2 = invalid argument
11:32:32,728    ERROR [ReceiverListener:hidraw1] logitech_receiver.settings_templates: check_feature[ADJUSTABLE DPI] inconsistent feature {'number': 1, 'request': 3354, 'error': 2, 'params': b''}
Traceback (most recent call last):
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/settings_templates.py", line 400, in check_feature
    detected = feature(device)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/settings_templates.py", line 99, in instantiate
    choices = choices_callback(device)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/settings_templates.py", line 267, in _feature_adjustable_dpi_choices
    reply = device.feature_request(_F.ADJUSTABLE_DPI, 0x10)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/receiver.py", line 289, in feature_request
    return _hidpp20.feature_request(self, feature, function, *params)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/hidpp20.py", line 443, in feature_request
    return device.request((feature_index << 8) + (function & 0xFF), *params)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/receiver.py", line 282, in request
    return _base.request(self.receiver.handle, self.number, request_id, *params)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/base.py", line 390, in request
    raise _hidpp20.FeatureCallError(number=devnumber, request=request_id, error=error, params=params)
logitech_receiver.hidpp20.FeatureCallError: {'number': 1, 'request': 3354, 'error': 2, 'params': b''}
11:32:32,731    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 000A 220500]
11:32:32,823    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000A 00000000000000000000000000000000]
11:32:32,823    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 0009 211000]
11:32:32,927    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 0009 00000000000000000000000000000000]
11:32:32,927    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 000D 198200]
11:32:33,031    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000D 00000000000000000000000000000000]
11:32:33,031    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 000A 100000]
11:32:33,127    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000A 05000000000000000000000000000000]
11:32:33,127    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) <= w[10 01 050A 000000]
11:32:33,231    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 050A 32140000000000000000000000000000]
11:32:33,231    DEBUG [ReceiverListener:hidraw1] logitech_receiver.hidpp20: device 1 battery 50% charged, next level 20% charge, status 0 = discharging
11:32:33,231    DEBUG [ReceiverListener:hidraw1] logitech_receiver.status: <PairedDevice(1,402C,G602,8D13D0BD)>: battery 50, discharging
11:32:33,232     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <PairedDevice(1,402C,G602,8D13D0BD)>: paired online, {'LINK ENCRYPTED': False, 'BATTERY LEVEL': 50, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY CHARGING': False, 'ERROR': None} (1) 
11:32:33,232     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <PairedDevice(1,402C,G602,8D13D0BD)>: paired online, {'LINK ENCRYPTED': False, 'BATTERY LEVEL': 50, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY CHARGING': False, 'ERROR': None} (0) 
11:32:33,232    DEBUG [MainThread] solaar.ui: status changed: <PairedDevice(1,402C,G602,8D13D0BD)> (1) None
11:32:33,234    DEBUG [MainThread] solaar.ui.tray: picked device with lowest battery: ('/dev/hidraw1', 1, 'Wireless Gaming Mouse', {'LINK ENCRYPTED': False, 'BATTERY LEVEL': 50, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY CHARGING': False, 'ERROR': None})
11:32:33,239    DEBUG [MainThread] solaar.ui.window: new device row ('/dev/hidraw1', 1, True, 'G602', 'input-mouse', None, None, <PairedDevice(1,402C,G602,8D13D0BD)>) at index 0
11:32:33,247    DEBUG [MainThread] solaar.ui: status changed: <PairedDevice(1,402C,G602,8D13D0BD)> (NONE) None
11:32:33,247    DEBUG [MainThread] solaar.ui.tray: picked device with lowest battery: ('/dev/hidraw1', 1, 'Wireless Gaming Mouse', {'LINK ENCRYPTED': False, 'BATTERY LEVEL': 50, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY CHARGING': False, 'ERROR': None})
11:32:33,248    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 0008 212000]
11:32:33,335    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 0008 00000000000000000000000000000000]
11:32:33,335    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 0008 00000000000000000000000000000000]
11:32:33,335    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 0008 213000]
11:32:33,431    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 0008 00000000000000000000000000000000]
11:32:33,431    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 0008 00000000000000000000000000000000]
11:32:33,432    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 000F 212100]
11:32:33,535    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 000F 00000000000000000000000000000000]
11:32:33,535    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000F 00000000000000000000000000000000]
11:32:33,536    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 000A 212100]
11:32:33,631    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000A 00000000000000000000000000000000]
11:32:33,631    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 000A 00000000000000000000000000000000]
11:32:33,632    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 000B 40A000]
11:32:33,735    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000B 00000000000000000000000000000000]
11:32:33,735    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 000B 00000000000000000000000000000000]
11:32:33,735    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 0009 40A200]
11:32:33,840    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 0009 00000000000000000000000000000000]
11:32:33,840    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 0009 00000000000000000000000000000000]
11:32:33,840    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 0008 40A300]
11:32:33,935    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 0008 00000000000000000000000000000000]
11:32:33,936    DEBUG [MainThread] logitech_receiver.settings_templates: check_feature[ADJUSTABLE DPI] dpi field_name dpi
11:32:33,936    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 0D1F 000000]
11:32:33,936    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 0008 00000000000000000000000000000000]
11:32:34,040    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 FF0D 1F020000000000000000000000000000]
11:32:34,040    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 FF0D 1F020000000000000000000000000000]
11:32:34,040    ERROR [MainThread] logitech_receiver.base: (13) device 1 error on feature request {0D1F}: 2 = invalid argument
11:32:34,040    ERROR [MainThread] logitech_receiver.settings_templates: check_feature[ADJUSTABLE DPI] inconsistent feature {'number': 1, 'request': 3359, 'error': 2, 'params': b''}
Traceback (most recent call last):
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/settings_templates.py", line 400, in check_feature
    detected = feature(device)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/settings_templates.py", line 99, in instantiate
    choices = choices_callback(device)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/settings_templates.py", line 267, in _feature_adjustable_dpi_choices
    reply = device.feature_request(_F.ADJUSTABLE_DPI, 0x10)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/receiver.py", line 289, in feature_request
    return _hidpp20.feature_request(self, feature, function, *params)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/hidpp20.py", line 443, in feature_request
    return device.request((feature_index << 8) + (function & 0xFF), *params)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/receiver.py", line 282, in request
    return _base.request(self.receiver.handle, self.number, request_id, *params)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/base.py", line 390, in request
    raise _hidpp20.FeatureCallError(number=devnumber, request=request_id, error=error, params=params)
logitech_receiver.hidpp20.FeatureCallError: {'number': 1, 'request': 3359, 'error': 2, 'params': b''}
11:32:34,041    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 000F 220500]
11:32:34,144    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000F 00000000000000000000000000000000]
11:32:34,144    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 000F 00000000000000000000000000000000]
11:32:34,145    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 000E 211000]
11:32:34,239    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 000E 00000000000000000000000000000000]
11:32:34,240    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 000D 198200]
11:32:34,240    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000E 00000000000000000000000000000000]
11:32:34,343    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 000D 00000000000000000000000000000000]
11:32:34,343    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000D 00000000000000000000000000000000]
11:32:57,315    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 FF 8102 000000]
11:32:57,316    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[10 FF 8102 000100]
11:32:57,317    DEBUG [MainThread] logitech_receiver.base: (13) => r[10 FF 8102 000100]
11:32:58,823    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 000A 212000]
11:32:58,837    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000A 00000000000000000000000000000000]
11:32:58,837    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 000A 00000000000000000000000000000000]
11:32:58,837    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 000C 213000]
11:32:58,917    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 000C 00000000000000000000000000000000]
11:32:58,917    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 000A 212100]
11:32:58,917    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000C 00000000000000000000000000000000]
11:32:58,933    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 000A 00000000000000000000000000000000]
11:32:58,933    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 000F 212100]
11:32:58,933    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000A 00000000000000000000000000000000]
11:32:58,949    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000F 00000000000000000000000000000000]
11:32:58,949    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 000F 00000000000000000000000000000000]
11:32:58,950    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 000C 40A000]
11:32:58,965    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 000C 00000000000000000000000000000000]
11:32:58,966    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 000F 40A200]
11:32:58,966    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000C 00000000000000000000000000000000]
11:32:59,053    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 000F 00000000000000000000000000000000]
11:32:59,053    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 000A 40A300]
11:32:59,054    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000F 00000000000000000000000000000000]
11:32:59,157    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 000A 00000000000000000000000000000000]
11:32:59,157    DEBUG [MainThread] logitech_receiver.settings_templates: check_feature[ADJUSTABLE DPI] dpi field_name dpi
11:32:59,158    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 0D19 000000]
11:32:59,158    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000A 00000000000000000000000000000000]
11:32:59,253    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 FF0D 19020000000000000000000000000000]
11:32:59,254    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 FF0D 19020000000000000000000000000000]
11:32:59,254    ERROR [MainThread] logitech_receiver.base: (13) device 1 error on feature request {0D19}: 2 = invalid argument
11:32:59,254    ERROR [MainThread] logitech_receiver.settings_templates: check_feature[ADJUSTABLE DPI] inconsistent feature {'number': 1, 'request': 3353, 'error': 2, 'params': b''}
Traceback (most recent call last):
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/settings_templates.py", line 400, in check_feature
    detected = feature(device)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/settings_templates.py", line 99, in instantiate
    choices = choices_callback(device)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/settings_templates.py", line 267, in _feature_adjustable_dpi_choices
    reply = device.feature_request(_F.ADJUSTABLE_DPI, 0x10)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/receiver.py", line 289, in feature_request
    return _hidpp20.feature_request(self, feature, function, *params)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/hidpp20.py", line 443, in feature_request
    return device.request((feature_index << 8) + (function & 0xFF), *params)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/receiver.py", line 282, in request
    return _base.request(self.receiver.handle, self.number, request_id, *params)
  File "/Data/OpenSource/Solaar/lib/logitech_receiver/base.py", line 390, in request
    raise _hidpp20.FeatureCallError(number=devnumber, request=request_id, error=error, params=params)
logitech_receiver.hidpp20.FeatureCallError: {'number': 1, 'request': 3353, 'error': 2, 'params': b''}
11:32:59,255    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 0008 220500]
11:32:59,269    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 0008 00000000000000000000000000000000]
11:32:59,269    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 0008 00000000000000000000000000000000]
11:32:59,269    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 000C 211000]
11:32:59,285    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 000C 00000000000000000000000000000000]
11:32:59,285    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000C 00000000000000000000000000000000]
11:32:59,286    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 01 0008 198200]
11:32:59,301    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 01 0008 00000000000000000000000000000000]
11:32:59,301    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 0008 00000000000000000000000000000000]
11:33:00,998    DEBUG [AsyncUI] logitech_receiver.base: (14) <= w[10 FF 83B5 200000]
11:33:00,999    DEBUG [AsyncUI] logitech_receiver.base: (14) => r[11 FF 83B5 200708402C0701023200000000000000]
11:33:01,000    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 FF 83B5 200708402C0701023200000000000000]
11:33:01,001    DEBUG [AsyncUI] logitech_receiver.base: (14) <= w[10 01 000D 000300]
11:33:01,103    DEBUG [AsyncUI] logitech_receiver.base: (14) => r[11 01 000D 02000000000000000000000000000000]
11:33:01,103    DEBUG [AsyncUI] logitech_receiver.base: (14) <= w[10 01 0209 000000]
11:33:01,103    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 000D 02000000000000000000000000000000]
11:33:01,207    DEBUG [AsyncUI] logitech_receiver.base: (14) => r[11 01 0209 03000000000000000000000000000000]
11:33:01,207    DEBUG [AsyncUI] logitech_receiver.base: (14) <= w[10 01 021E 000000]
11:33:01,207    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 0209 03000000000000000000000000000000]
11:33:01,303    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 021E 0052514D4700001000402C0000000000]
11:33:01,303    DEBUG [AsyncUI] logitech_receiver.base: (14) => r[11 01 021E 0052514D4700001000402C0000000000]
11:33:01,304    DEBUG [AsyncUI] logitech_receiver.base: (14) <= w[10 01 021E 010000]
11:33:01,358    DEBUG [AsyncUI] logitech_receiver.base: (14) => r[11 01 021E 01424C200200000100402C0000000000]
11:33:01,359    DEBUG [AsyncUI] logitech_receiver.base: (14) <= w[10 01 021A 020000]
11:33:01,359    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 021E 01424C200200000100402C0000000000]
11:33:01,374    DEBUG [AsyncUI] logitech_receiver.base: (14) => r[11 01 021A 024857200200000000402C0000000000]
11:33:01,375    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (12) => r[11 01 021A 024857200200000000402C0000000000]
```

### CODE REVIEW

**Comment by FFY00** [comment]
You still need to fix the HID++ 2.0 features. As I said previously, this device doesn't follow the spec on some features.

**Comment by rijnhard** [comment]
Ok

How do I go about doing that? Like walk me through the process
e.g. identify the feature code in this spec then add a constant here and
map it to the appropriate feature here

**Comment by FFY00** [comment]
I think the only feature that we support and the G602 does not follow the spec is `ADJUSTABLE_DPI`.

See https://github.com/libratbag/libratbag/commit/d4d971231678ed7ca5730256a84d0e3ce36f98e3 for details on how the G602 differs from the spec.

**Comment by rijnhard** [comment]
@FFY00 I think I want to give this a stab if I can (not to stop someone else from working on it)

But I do think this change is beneficial to all models that have spec issues, as such can add value on its own, I think the fault I made was naming it g602, so If I make it a separate pr/branch that sole job is to handle non-compliant devices more safely, would you consider it?

**Comment by FFY00** [comment]
Sure but can you please clean up the git branch? Please rebase instead of creating a merge commit.

```
git reset --hard HEAD~1
git rebase -i master
```

Also, we don't appear to be using python's logger module so please don't use it, do it the same way the rest of the code does. Using python's logger module would actually be a great improvement that I would like to see, but that should come in a different PR, for now we should try to keep things consistent.

**Comment by rijnhard** [comment]
Will do, but I copied the logging setup from another
file?  lib/logitech_receiver/base.py

**Comment by rijnhard** [comment]
Superseded by https://github.com/pwr-Solaar/Solaar/pull/688

Closing this for now

**Comment by pfps** [comment]
@rjinhard After PR #688 what else is needed for G602?  

Adding c537 should be easy as well, but the rules file (in rules.d) will need the line
`ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c537", GOTO="solaar_apply"`
in the obvious place.

**Comment by pfps** [comment]
@rjinhard You could also add a file to docs/devices.

**Pull request closed without merging**
