### PR TITLE
settings: keep track of settings that are absent from device

### PR DESCRIPTION
**Pull request by pfps**

### CODE REVIEW

**Comment by pfps** [comment]
@barolo @sk8geek @mschilli87
This PR keeps track of settings that are absent from a device and doesn't check them ever again.  It has the possibility of breaking Solaar for any device that uses HID++ 2.0 or later so it should get some extra testing.
Please take a screenshot of the Solaar main window for each of your devices, or somehow record which settings are present for each of your devices.  Then download and run this PR and check whether the same settings are present.  (They may be in a different order.)   If you have a device with different settings, post the contents of your ~/.config/solaar/config.json and `bin/solaar show` and say which setting has disappeared (or appeared).

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1401, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1401/head:pull_1401
git checkout pull_1401
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1401
git fetch origin pull/1401/head
git reset --hard FETCH_HEAD
```

**Comment by barolo** [comment]
Nothing changed for MX Master 2S and Craft.

**Comment by pfps** [comment]
@barolo Thanks.  
It would be nice to get another tester for this.

**Comment by sk8geek** [comment]
I have the same results as @barolo - no change for MX Keys and Pebble :-)

**Comment by pfps** [comment]
Excellent, thanks.

**Comment by pfps** [comment]
PR #1402 could use some testing as well.

**Comment by sk8geek** [comment]
PR #1402 shows the same settings but the switch controls are taller than they should be:

switch_height
.

**Comment by pfps** [comment]
@sk8geek I'm not sure what you are reporting.  There was a recent change to how the setting locking icons were implemented that probably added a little bit to the height of each setting.  The testing for PR #1402 involves checking Key/Button Diversion (and Key/Button Actions if that setting is available).

**Comment by sk8geek** [comment]
@pfps sorry, the image is split left, Solaar 1.1.0 and right, PR1402. You can see that in PR1402 the switch control is too tall - the "switch" isn't circular - it's stretched vertically.  

I assumed that the test required for 1402 was the same for 1401 - that all of the controls were still visible.  I can set keys to Diverted but I don't know what that is meant to achieve/how to test.

**Comment by pfps** [comment]
@sk8geek When you divert a key or button it should no longer be recognized by Linux.  So you can divert, for example, a key and then press that key to see whether the key still does what it normally does.  If you have the Key/Button Action setting on one of your devices you can change what the key or button does, e.g., changing the back button on your mouse to act like the left button.

I see what you mean by the switch control being stretched a bit.  This is likely due to new treatment of the lock icon.

**Comment by sk8geek** [comment]
Okay, thanks, yeah, that works as expected.  Diverted keys on MX Keys are ignored. For the mouse changing Right Button to Left Click works as expected.  Diverting the middle button causes it to be ignored.

**Comment by pfps** [comment]
Excellent, thanks.

The cause of the oval toggles was indeed the added button box around the lock icons.  Fixing this just requires adding alignment properties to the toggle, which will be added in a moment.

**Comment by pfps** [comment]
@sk8geek Next up might be adding support for persistent key mappings, which would allow remapping the keys on the MX Master and other high-end devices.

**Pull request merged**
