### PR TITLE
Fix test coverage report

### PR DESCRIPTION
**Pull request by MattHag**
- Properly show test coverage
- Introduce minimum test coverage of 40%

### CODE REVIEW

**Comment by MattHag** [comment]
This change requires setup of [codecov](https://about.codecov.io/codecov-free-trial/), then we have coverage reports reachable via GitHub Badge.

**Comment by MattHag** [comment]
@pfps This can be merged and finally gives a good view on the test coverage and easily shows, which code needs further refactoring to achieve unit testable modules.

**Comment by pfps** [comment]
I installed one of the PRs and now others have conflicts that need to be resolved.

**Comment by MattHag** [comment]
Included in #2626

**Pull request closed without merging**
