### PR TITLE
Add K400r PID 404B to descriptors

### PR DESCRIPTION
**Pull request by noabody**
[Logitech K400r](https://support.logi.com/hc/en-us/articles/360023307174-Logitech-Wireless-Touch-Keyboard-K400r-Technical-Specifications)
Path         : /dev/hidraw
Index        : 1
Wireless PID : 404B
Protocol     : HID++ 2.0
Polling rate : 8 ms (125Hz)
Serial       : 
Unit ID      : 00000000
  Firmware   : 

kernel: logitech-hidpp-device 0003:046D:404B.000D: input,hidraw: USB HID v1.11 Keyboard [Logitech K400] on usb-0000:00:13.0-3/input2:1
kernel: logitech-hidpp-device 0003:046D:404B.000D: HID++ 2.0 device connected.

### CODE REVIEW

**Comment by noabody** [comment]
I have a few of these keyboards.  Been building a personal version of Solaar on Debian/Arch for years now using a personal patch to descriptors.py.  

Figure there's no reason not to do a PR, since this variant of the K400 isn't already specifically covered.

**Comment by pfps** [comment]
Many Logitech devices are handled without any information on them in descriptors.py and quite a few of the descriptors there are not really needed.   Does adding the descriptor change how Solaar works in any way?

**Comment by noabody** [comment]
You're right, recognized as K400 without new descriptor and seems to work fine, thanks.

**Comment by pfps** [comment]
OK, are you fine with not merging this PR?

**Comment by noabody** [comment]
That's right.  I think it works better without a stand-alone definition.  Comes up as a combo device, same as the K400.  My bad, thanks again.

**Comment by piranna** [comment]
I have a K400r keyboard but touchpad is not working at all. I have `solaar` 1.1.10 and it's properly identified, with scroll keys and all although they doesn't exist fisically, but touchpad is fully unresponsive. Could this identifier fix it? Maybe the keyboard is broken?

```console
> solaar show
solaar version 1.1.10+dfsg-2

Receptor Unifying
  Device path  : /dev/hidraw1
  USB id       : 046d:C52B
  Serial       : 21299376
    Firmware   : 24.11.B0036
    Bootloader : 03.09
    Other      : AA.AD
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=74

  1: Wireless Touch Keyboard K400
     Device path  : /dev/hidraw4
     WPID         : 4024
     Codename     : K400
     Kind         : keyboard
     Protocol     : HID++ 2.0
     Polling rate : 8 ms (125Hz)
     Serial number: 369C70E0
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RQK 50.01.B0013
     The power switch is located on the edge of top right corner.
     Supports 22 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: FEATURE INFO           {0002} V0     
         3: DEVICE FW VERSION      {0003} V0     
            Firmware: Firmware RQK 50.01.B0013 4024
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         4: DEVICE NAME            {0005} V0     
            Name: Wireless Touch Keyboard K400
            Kind: keyboard
         5: BATTERY STATUS         {1000} V0     
            Battery: 90%, discharging, next level 70%.
         6: REPROG CONTROLS        {1B00} V0     
         7: REPROG CONTROLS V3     {1B03} V0     
         8: WIRELESS DEVICE STATUS {1D4B} V0     
         9: REMAINING PAIRING      {1DF0} V0    hidden 
            Remaining Pairings: 46
        10: unknown:1DF3           {1DF3} V0    internal, hidden 
        11: unknown:1E00           {1E00} V0    hidden 
        12: VERTICAL SCROLLING     {2100} V0     
            Roller type: normal touch pad
            Ratchet per turn: 16
            Scroll lines: 0
        13: HI RES SCROLLING       {2120} V0     
            Hi-res scrolling enabled
            Hi-res scrolling multiplier: 8
            Rueda Alta Resolución (saved): True
            Rueda Alta Resolución        : True
        14: MOUSE POINTER          {2200} V0     
            DPI: 300
            Acceleration: low
            Override OS ballistics
            No vertical tuning, standard mice
        15: FN INVERSION           {40A0} V0     
            Intercambiar función Fx (saved): True
            Intercambiar función Fx        : True
        16: NEW FN INVERSION       {40A2} V0     
            Fn-swap: enabled
            Fn-swap default: enabled
        17: ENCRYPTION             {4100} V0     
        18: KEYBOARD LAYOUT        {4520} V0     
        19: TOUCHPAD FW ITEMS      {6010} V0     
        20: TOUCHPAD SW ITEMS      {6011} V0     
        21: TOUCHPAD WIN8 FW ITEMS {6012} V0     
     Battery: 90%, discharging, next level 70%.
```

**Comment by pfps** [comment]
Solaar is not involved with normal operation of a touchpad so this is very likely a problem with your operating system not recognizing the touchpad.

**Comment by piranna** [comment]
> Solaar is not involved with normal operation of a touchpad so this is very likely a problem with your operating system not recognizing the touchpad.

Interesting... I've found some other issues on this repo talking about some regressions on Linux 3.10, but it was long time ago... Maybe it would make sense what you say, i'll try to test it with a Windows system just to be sure, but if that's the case, I don't know how to fix it.

**Pull request closed without merging**
