### PR TITLE
cli: don't defer saves in cli and don't require gtk in cli

### PR DESCRIPTION
**Pull request by pfps**
Addresses #1816

### CODE REVIEW

**Comment by jirutka** [comment]
Looks good! :+1:

**Comment by pfps** [comment]
Did you try to run `solaar config <device> <setting> <value>` in an environment that doesn't have Gtk?

**Comment by jirutka** [comment]
`solaar config` works, but there’s a problem with `solaar show`:

```
$ solaar show
...
       solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/logitech_receiver/device.py", line 369, in battery
    self.persister['_battery'] = feature
  File "/usr/lib/python3.10/site-packages/solaar/configuration.py", line 167, in __setitem__
    save(defer=True)
  File "/usr/lib/python3.10/site-packages/solaar/configuration.py", line 94, in save
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi'
```

**Comment by pfps** [comment]
Hmm.  Let me figure out what to do.

**Comment by pfps** [comment]
I would like to use something a bit more delicate, but that does require figuring out where configurations can be saved.  Although may be flipping the flag would do the trick.

**Comment by pfps** [comment]
@jirutka I updated the PR so that the default is to not defer saves (and thus not need Gtk/Glib).  When the GUI starts up it flips the switch to allow deferred saves.  This should be more robust.

**Comment by jirutka** [comment]
I tried it, and it works now, thanks!

**Pull request merged**
