### PR TITLE
don't perform on-screen notifications for wireless device status notifications

### LINKED ISSUE #1185: (Option to) Disable notifications on mouse connection
**Is your feature request related to a problem? Please describe.**

When the computer wakes up from standby or my mouse gets connected (it’s a mouse that can use different devices, i.e. M720), I get a useless notification that my mouse is now powered on.

image

In addition to the “battery warning” I also _always_ get although my mouse still works and has 20% – these are two notifications that I just constantly (need to) click away.

**Describe the solution you'd like**
This information is of no value. I know, when I move my mouse that it is connected.

**Describe alternatives you've considered**
If you can, maybe set a very low timeout as an alternative? So the message disappears and does not annoy me.

Or find other ways of notifying the user? E.g. the bottom rectangle GNOME displays when you e.g. change your backlight. (It automatically disappears and is not so disruptive as this notification.)

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by pfps**
Fixes #1185

### CODE REVIEW

**Comment by Vistaus** [comment]
Thanks a lot for implementing this! However, I can't get Solaar to run after compiling Solaar with your PR:

```
╭─xxxxx@xxxxx-PC /home/xxxxx/fromsvngit/Solaar  ‹system›  <pull_1359> 
╰─$ solaar                                                                                                                                                                                                                       ↵ 1
Traceback (most recent call last):
  File "/usr/local/bin/solaar", line 4, in <module>
    __import__('pkg_resources').run_script('solaar==1.1.0', 'solaar')
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 1443, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/solaar' not found in metadata at '/usr/local/lib/python3.7/dist-packages/solaar-1.1.0.dist-info'
╭─xxxxx@xxxxx-PC /home/xxxxx/fromsvngit/Solaar  ‹system›  <pull_1359> 
╰─$
```

**Comment by pfps** [comment]
I'm not sure what you did to get this error.  There is no occurrence of run_script that I can find in the Solaar code.  If you have a clone of Solaar you should not need to do any compiling.  Instead just go to the Solaar directory and run `bin/solaar`.

**Comment by Vistaus** [comment]
That's  exactly what I did.

**Comment by pfps** [comment]
It looks as if you ran just `solaar`, which ran from /usr/local/bin/solaar.
Please try `bin/solaar` from the solaar clone directory.

**Comment by rugk** [comment]
Tested it and seems to work.

Switched the mouse connection and got no error.
grafik

Anyway, don't trust me, I don't know the code base.

**Comment by Klap-in** [comment]
I have this PR also running. There are no notifications anymore in the Gnome notifications area. So that part works fine. 

But I have still one observation. I do not use the MX keys, it disconnects, and it reconnects again if I use it.
This does not give a notification, but still a sound is played. Is this a sound that origins from Solaar as well? If it does, is there a possibility to disable it as well?

```
17:43:44,675     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <Device(2,408A,MX Keys Keyboard,F171A95D)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 20, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 5, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
17:43:44,676     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <Device(2,408A,MX Keys Keyboard,F171A95D)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 20, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 5, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
17:43:44,683     INFO [ReceiverListener:hidraw1] logitech_receiver.notifications: <Device(2,408A,MX Keys Keyboard,F171A95D)>: spurious BATTERY status Notification(11,2,07,10,0404C0060A0000000000000000000000)
17:43:44,690     INFO [ReceiverListener:hidraw1] logitech_receiver.notifications: <Device(1,406F,MX Ergo Multi-Device Trackball ,1496DB8A)>: spurious BATTERY status Notification(11,1,08,10,0404C0780A0000000000000000000000)
17:49:21,056     INFO [ReceiverListener:hidraw1] solaar.listener: connection Notification(10,2,41,04,718A40) for <Device(2,408A,MX Keys Keyboard,F171A95D)> (keyboard)
17:49:21,056     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,17)>: present, 2 gekoppelde apparaten. (0) 
17:49:21,057     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <Device(2,408A,MX Keys Keyboard,F171A95D)>: paired offline, {'BATTERY LEVEL': 20} (0) 
17:49:21,058     INFO [ReceiverListener:hidraw1] logitech_receiver.notifications: <Device(2,408A,MX Keys Keyboard,F171A95D)>: DJ connection: False Notification(20,2,42,01,0000000000000000000000)
17:49:21,059     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <Device(2,408A,MX Keys Keyboard,F171A95D)>: paired offline, {'BATTERY LEVEL': 20} (0) verbinding verbroken
```
After interacting with the keyboard the following message appears, and a sound is played.
```
17:52:03,462     INFO [ReceiverListener:hidraw1] solaar.listener: connection Notification(10,2,41,04,B18A40) for <Device(2,408A,MX Keys Keyboard,F171A95D)> (keyboard)
17:52:03,463     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,17)>: present, 2 gekoppelde apparaten. (0) 
17:52:03,463     INFO [ReceiverListener:hidraw1] logitech_receiver.status: <Device(2,408A,MX Keys Keyboard,F171A95D)> pushing device settings [<Setting([feature:toggle] MX Keys:backlight=True)>, <Setting([feature:toggle] MX Keys:fn-swap=False)>, <Setting([feature:map choice] MX Keys:divert-keys={'10': 0, '110': 0, '111': 0, '191': 0, '199': 0, '200': 0, '209': 0, '210': 0, '211': 0, '224': 0, '225': 0, '226': 0, '227': 0, '228': 0, '229': 0, '230': 0, '231': 0, '232': 0, '233': 0, '234': 0, '235': 0, '236': 0})>, <Setting([feature:multiple toggle] MX Keys:disable-keyboard-keys={'1': False, '16': False, '2': False, '4': False, '8': False})>, <Setting([feature:choice] MX Keys:multiplatform=0)>, <Setting([feature:choice] MX Keys:change-host=1:Plaat)>]
17:52:05,572     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <Device(2,408A,MX Keys Keyboard,F171A95D)>: paired online, {'BATTERY LEVEL': 20, 'LINK ENCRYPTED': True, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 5, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
17:52:05,573     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <Device(2,408A,MX Keys Keyboard,F171A95D)>: paired online, {'BATTERY LEVEL': 20, 'LINK ENCRYPTED': True, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 5, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
17:52:05,573     INFO [ReceiverListener:hidraw1] logitech_receiver.notifications: <Device(2,408A,MX Keys Keyboard,F171A95D)>: DJ connection: True Notification(20,2,42,00,0000000000000000000000)
17:52:05,574     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <Device(2,408A,MX Keys Keyboard,F171A95D)>: paired online, {'BATTERY LEVEL': 20, 'LINK ENCRYPTED': True, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 5, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) verbonden
17:52:05,612     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <Device(2,408A,MX Keys Keyboard,F171A95D)>: paired online, {'BATTERY LEVEL': 20, 'LINK ENCRYPTED': True, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 5, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) powered on
17:52:05,615     INFO [ReceiverListener:hidraw1] logitech_receiver.notifications: <Device(2,408A,MX Keys Keyboard,F171A95D)>: spurious BATTERY status Notification(11,2,07,10,0404C0060A0000000000000000000000)
```

Further, it behaves as expected. Are there still specific points to test?

**Comment by pfps** [comment]
Solaar doesn't generate a sound on connection as far as I know.

**Comment by Klap-in** [comment]
If I disable all notifications of Solaar, via the notifications panel in the Setting, the sound is still played. I'm using the Unifying dongle. I suspected first the bluetooth, but since I using the dongle that is not possible. Does anyone has ideas what further to test, to locate the source of the sound?

**Pull request merged**
