### PR TITLE
setup.py: drop python 2 support

### PR DESCRIPTION
**Pull request by FFY00**
Signed-off-by: Filipe Laíns <lains@archlinux.org>

### CODE REVIEW

**Comment by pfps** [comment]
OK.  I'll give this a look later today.

**Comment by pfps** [comment]
Changes will be needed in installation.md

**Comment by FFY00** [comment]
Sure, feel free to submit a PR for that. We can then merge both PRs at the same time. Or if you feel confortable, you can push directly here.

**Comment by pfps** [comment]
Here are diffs for installation.md

diff --git a/docs/installation.md b/docs/installation.md
index 2958a92..9add566 100644
--- a/docs/installation.md
+++ b/docs/installation.md
@@ -12,12 +12,12 @@ and `hid-logitech-hidpp` loaded.   Also, the `udev` package must be installed
 and the daemon running.  If you have a recent Linux distribution (2017+), you are
 most likely good to go.
 
-Solaar requires Python 2.7.3 or 3.2+ (either version should work),
-and the `python-pyudev`/`python3-pyudev` package. 
+Solaar requires Python 3.2+
+and the `python3-pyudev` package. 
 
 To run the GUI, solaar also requires Gtk3, and its GObject
 Introspection bindings. The Debian/Ubuntu package names are
-`python-gi`/`python3-gi` and `gir1.2-gtk-3.0`; if you're using another
+`python3-gi` and `gir1.2-gtk-3.0`; if you're using another
 distribution the required packages are most likely named something similar.
 If the desktop notifications bindings are also installed (`gir1.2-notify-0.7`),
 you will also get desktop notifications when devices come online/go offline.

**Comment by pfps** [comment]
I manually changed my setup.py and did a local install.  It worked fine.  So all that is needed is installation.md.

**Comment by mickleby** [comment]
Comments https://github.com/pwr-Solaar/Solaar/issues/652#issuecomment-581070267 may be relevant.

It seems "drop support" == "change documentation". I propose something more forceful and explicit. 

Where can I read about the motivation for "drop python 2 support"? I get the idea various random bugs appear in `python2 solaar`, and we wish to use our limited support resources wisely. Does this basically encapsulate the motivation?

**Pull request merged**
