### PR TITLE
support powerplay

### LINKED ISSUE #1690: PowerPlay support
**Information**
- Solaar version: solaar 1.1.4
- Distribution: Arch Linux
- Kernel version: Linux 5.18.16-arch1-1 x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable): none

**Describe the solution you'd like**
Added support for the Logitech G PowerPlay wireless mouse pad.

in the G Hub it is possible to e.g sync RGB with the mouse or set overall RGB intervals etc.
The PowerPlay also has a built-in Lightspeed receiver that lets you pair the mouse in the G Hub.

### PR DESCRIPTION
**Pull request by pfps**
Fixes #1690

### CODE REVIEW

**Comment by pfps** [comment]
@barolo @sk8geek @mschilli87 @viniciusbm  This PR should get some testing.  Just run `bin/solaar -dd` and `bin/solaar show` and check for any new warnings or errors.

**Comment by sk8geek** [comment]
How do I get this code to my machine to test please?

**Comment by pfps** [comment]
Sorry, I usually include these instructions:

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1691, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1691/head:pull_1691
git checkout pull_1691
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1691
git fetch origin pull/1691/head
git reset --hard FETCH_HEAD
```

**Comment by sk8geek** [comment]
Lovely, thank you.  When I run with `-dd` I get lots of INFO and one ERROR:
`ERROR [ReceiverListener:hidraw0] logitech_receiver.settings: invalid choice 0 for 215`

I don't get any errors when running with `show`.  Output from this is below.
```
Solaar version 1.1.4

Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : 633CB9BD
    Firmware   : 24.11.B0036
    Bootloader : 02.09
    Other      : AA.AC
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=35, 2=212

  1: MX Keys Keyboard
     Device path  : /dev/hidraw1
     WPID         : 408A
     Codename     : MX Keys
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Polling rate : 20 ms (50Hz)
     Serial number: F359F7AC
     Model ID:      B35B408A0000
     Unit ID:       F359F7AC
        Bootloader: BL1 08.00.B0011
          Firmware: MPK 12.00.B0011
             Other: 
     The power switch is located on the edge of top right corner.
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Bootloader BL1 08.00.B0011 00008169E8BB
            Firmware: Firmware MPK 12.00.B0011 408A8169E8BB
            Firmware: Other   
            Unit ID: F359F7AC  Model ID: B35B408A0000  Transport IDs: {'btleid': 'B35B', 'wpid': '408A'}
         3: DEVICE NAME            {0005} V0     
            Name: MX Keys Wireless Keyboard
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: RESET                  {0020} V0     
         6: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Keys
         7: BATTERY STATUS         {1000} V1     
            Battery: 50%, discharging, next level 20%.
         8: REPROG CONTROLS V4     {1B04} V4     
            Key/Button Diversion (saved): {Calculator:Regular, Show Desktop:Regular, Lock PC:Regular, Screen Capture/Print Screen:Regular, Brightness Down:Regular, Brightness Up:Regular, Host Switch Channel 1:Regular, Host Switch Channel 2:Regular, Host Switch Channel 3:Regular, Mission Control/Task View:Regular, Dashboard Launchpad/Action Center:Regular, Backlight Down:Regular, Backlight Up:Regular, Previous Fn:Regular, Play/Pause Fn:Regular, Next Fn:Regular, Mute Fn:Regular, Volume Down Fn:Regular, Volume Up Fn:Regular, App Contextual Menu/Right Click:Regular, Right Arrow:Regular, Left Arrow:Regular}
            Key/Button Diversion        : {Calculator:Regular, Show Desktop:Regular, Lock PC:Regular, Screen Capture/Print Screen:Regular, Brightness Down:Regular, Brightness Up:Regular, Host Switch Channel 1:Regular, Host Switch Channel 2:Regular, Host Switch Channel 3:Regular, Mission Control/Task View:Regular, Dashboard Launchpad/Action Center:Regular, Backlight Down:Regular, Backlight Up:Regular, Previous Fn:Regular, Play/Pause Fn:Regular, Next Fn:Regular, Mute Fn:Regular, Volume Down Fn:Regular, Volume Up Fn:Regular, App Contextual Menu/Right Click:Regular, Right Arrow:Regular, Left Arrow:Regular}
         9: CHANGE HOST            {1814} V1     
        10: HOSTS INFO             {1815} V1     
            Host 0 (paired): brandy
            Host 1 (paired): Pixel 2
            Host 2 (paired): devlaptop002
        11: BACKLIGHT2             {1982} V1     
            Backlight (saved): True
            Backlight        : True
        12: K375S FN INVERSION     {40A3} V0     
            Swap Fx function (saved): False
            Swap Fx function        : False
        13: ENCRYPTION             {4100} V0     
        14: LOCK KEY STATE         {4220} V0     
        15: KEYBOARD DISABLE KEYS  {4521} V0     
            Disable keys (saved): {Caps Lock:False, Num Lock:False, Scroll Lock:False, Insert:False, Win:False}
            Disable keys        : {Caps Lock:False, Num Lock:False, Scroll Lock:False, Insert:False, Win:False}
        16: MULTIPLATFORM          {4531} V1     
            Set OS (saved): Windows
            Set OS        : Windows
        17: DFUCONTROL SIGNED      {00C2} V0     
        18: DEVICE RESET           {1802} V0    internal, hidden 
        19: unknown:1803           {1803} V0    internal, hidden 
        20: CONFIG DEVICE PROPS    {1806} V5    internal, hidden 
        21: unknown:1813           {1813} V0    internal, hidden 
        22: OOBSTATE               {1805} V0    internal, hidden 
        23: unknown:1830           {1830} V0    internal, hidden 
        24: unknown:1890           {1890} V5    internal, hidden 
        25: unknown:1891           {1891} V5    internal, hidden 
        26: unknown:18A1           {18A1} V0    internal, hidden 
        27: unknown:1DF3           {1DF3} V0    internal, hidden 
        28: unknown:1E00           {1E00} V0    hidden 
        29: unknown:1EB0           {1EB0} V0    internal, hidden 
        30: unknown:1861           {1861} V0    internal, hidden 
        31: unknown:1A20           {1A20} V0    internal, hidden 
     Has 24 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         2: Host Switch Channel 3     , default: HostSwitch Channel 3        => HostSwitch Channel 3      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         3: Brightness Down           , default: Brightness Down             => Brightness Down           
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:1, group:0, group mask:empty
             reporting: default
         4: Brightness Up             , default: Brightness Up               => Brightness Up             
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:2, group:0, group mask:empty
             reporting: default
         5: Mission Control/Task View , default: Mission Control/Task View   => Mission Control/Task View 
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:3, group:0, group mask:empty
             reporting: default
         6: Dashboard Launchpad/Action Center, default: Dashboard Launchpad/Action Center => Dashboard Launchpad/Action Center
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:4, group:0, group mask:empty
             reporting: default
         7: Show Desktop              , default: Show Desktop                => Show Desktop              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:5, group:0, group mask:empty
             reporting: default
         8: Backlight Down            , default: Backlight Down              => Backlight Down            
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:6, group:0, group mask:empty
             reporting: default
         9: Backlight Up              , default: Backlight Up                => Backlight Up              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:7, group:0, group mask:empty
             reporting: default
        10: Previous Fn               , default: Previous                    => Previous                  
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:8, group:0, group mask:empty
             reporting: default
        11: Play/Pause Fn             , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:9, group:0, group mask:empty
             reporting: default
        12: Next Fn                   , default: Next                        => Next                      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:10, group:0, group mask:empty
             reporting: default
        13: Mute Fn                   , default: Mute                        => Mute                      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:11, group:0, group mask:empty
             reporting: default
        14: Volume Down Fn            , default: Volume Down                 => Volume Down               
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:12, group:0, group mask:empty
             reporting: default
        15: Volume Up Fn              , default: Volume Up                   => Volume Up                 
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        16: Calculator                , default: Calculator                  => Calculator                
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        17: Screen Capture/Print Screen, default: Screen Capture              => Screen Capture            
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        18: App Contextual Menu/Right Click, default: Right Click/App Contextual Menu => Right Click/App Contextual Menu
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        19: Lock PC                   , default: WindowsLock                 => WindowsLock               
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        20: Left Arrow                , default: Keyboard Left Arrow         => Keyboard Left Arrow       
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        21: Right Arrow               , default: Keyboard Right Arrow        => Keyboard Right Arrow      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        22: F Lock                    , default: Do Nothing One              => Do Nothing One            
             is FN, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        23: FN Key                    , default: Do Nothing One              => Do Nothing One            
             nonstandard, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
     Battery: 50%, discharging, next level 20%.

  2: Wireless Mouse Pebble M350
     Device path  : /dev/hidraw2
     WPID         : 4080
     Codename     : Pebble
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 2B442F40
     Model ID:      B02140800000
     Unit ID:       DE12CCD9
          Firmware: MPM 18.00.B0007
             Other: 
     The power switch is located on the base.
     Supports 26 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Firmware MPM 18.00.B0007 4080BEA0D686
            Firmware: Other   
            Unit ID: DE12CCD9  Model ID: B02140800000  Transport IDs: {'btleid': 'B021', 'wpid': '4080'}
         3: DEVICE NAME            {0005} V0     
            Name: M350 Wireless Mouse
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: RESET                  {0020} V0     
         6: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: Logitech Pebble
         7: BATTERY STATUS         {1000} V1     
            Battery: 50%, discharging, next level 20%.
         8: REPROG CONTROLS V4     {1B04} V4     
            Key/Button Actions (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button}
            Key/Button Actions        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button}
            Key/Button Diversion (saved): {Middle Button:Regular, ?}
            Key/Button Diversion        : {Middle Button:Regular}
         9: CHANGE HOST            {1814} V1     
            Change Host        : 1:brandy
        10: ADJUSTABLE DPI         {2201} V1     
            Sensitivity (DPI) (saved): 1000
            Sensitivity (DPI)        : 1000
        11: LOWRES WHEEL           {2130} V0     
            Wheel Reports: HID
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        12: DEVICE RESET           {1802} V0    internal, hidden 
        13: unknown:1803           {1803} V0    internal, hidden 
        14: CONFIG DEVICE PROPS    {1806} V5    internal, hidden 
        15: unknown:1812           {1812} V0    internal, hidden 
        16: OOBSTATE               {1805} V0    internal, hidden 
        17: unknown:1830           {1830} V0    internal, hidden 
        18: unknown:1890           {1890} V4    internal, hidden 
        19: unknown:1891           {1891} V4    internal, hidden 
        20: unknown:18A1           {18A1} V0    internal, hidden 
        21: unknown:1DF3           {1DF3} V0    internal, hidden 
        22: unknown:1E00           {1E00} V0    hidden 
        23: unknown:1EB0           {1EB0} V0    internal, hidden 
        24: unknown:1861           {1861} V0    internal, hidden 
        25: unknown:18B1           {18B1} V0    internal, hidden 
     Has 4 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, reprogrammable, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, reprogrammable, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         3: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:3, group mask:empty
             reporting: default
     Battery: 50%, discharging, next level 20%.
```

**Comment by pfps** [comment]
@sk8geek Can you run the Solaar you normally run as `solaar -dd` and see whether you get the same error?  If so, run `solaar -ddd` and post the output.

**Comment by pfps** [comment]
@sk8geek On closer investigation it looks as if you have some problem with your Solaar configuration file.  Can you post the contents of ~/.config/solaar/config.yaml?

**Comment by sk8geek** [comment]
Here you go.
```
- 1.1.4
- _NAME: Wireless Mouse Pebble M350
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, smart-shift, thumb-scroll-mode, thumb-scroll-invert, pointer_speed, speed-change,
    backlight, fn-swap, disable-keyboard-keys, report_rate, divert-crown, crown-smooth, divert-gkeys, multiplatform, gesture2-gestures, gesture2-params,
    onboard_profiles, backlight-timed, persistent-remappable-keys, m-key-leds, mr-key-led, gesture2-divert, hires-scroll-mode, sidetone, equalizer]
  _battery: 4096
  _modelId: B02140800000
  _sensitive: {divert-keys: false, dpi: false, lowres-smooth-scroll: false, reprogrammable-keys: false}
  _serial: 2B442F40
  _unitId: DE12CCD9
  _wpid: '4080'
  change-host: null
  divert-keys: {82: 0, 215: 0}
  dpi: '1000'
  dpi-sliding: 0
  lowres-scroll-mode: false
  lowres-smooth-scroll: false
  mouse-gestures: 0
  reprogrammable-keys: {80: 80, 81: 81, 82: 82}
- _NAME: MX Keys Keyboard
  _absent: [hi-res-scroll, lowres-smooth-scroll, hires-smooth-invert, hires-smooth-resolution, smart-shift, thumb-scroll-mode, thumb-scroll-invert, dpi,
    dpi-sliding, mouse-gestures, pointer_speed, speed-change, reprogrammable-keys, report_rate, divert-crown, crown-smooth, divert-gkeys, gesture2-gestures,
    gesture2-params, onboard_profiles, backlight-timed, persistent-remappable-keys, m-key-leds, mr-key-led, gesture2-divert, fn-swap, divert-keys, disable-keyboard-keys,
    multiplatform, change-host, lowres-scroll-mode, hires-scroll-mode, sidetone, equalizer]
  _battery: 4096
  _modelId: B35B408A0000
  _sensitive: {backlight: false, disable-keyboard-keys: false, divert-keys: true, fn-swap: false, multiplatform: false}
  _serial: F359F7AC
  _unitId: F359F7AC
  _wpid: 408A
  backlight: true
  disable-keyboard-keys: {1: false, 2: false, 4: false, 8: false, 16: false}
  divert-keys: {10: 0, 110: 0, 111: 0, 191: 0, 199: 0, 200: 0, 209: 0, 210: 0, 211: 0, 224: 0, 225: 0, 226: 0, 227: 0, 228: 0, 229: 0, 230: 0, 231: 0, 232: 0,
    233: 0, 234: 0, 235: 0, 236: 0}
  fn-swap: false
  multiplatform: 0
- _NAME: Bluetooth Multi-Device Keyboard K380
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, pointer_speed, dpi, dpi-sliding, speed-change, mouse-gestures, backlight, backlight-timed, reprogrammable-keys, persistent-remappable-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer]
  _modelId: B34200000000
  _unitId: 7C010100
  change-host: null
  disable-keyboard-keys: {1: false, 4: false, 8: false, 16: false}
  divert-keys: {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 62: 0, 186: 0, 187: 0, 188: 0, 189: 0, 190: 0, 191: 0, 192: 0, 193: 0, 194: 0}
  fn-swap: true
  multiplatform: null
```

**Comment by sk8geek** [comment]
I do indeed get the same error when I run the installed Solaar.  Running with `-ddd` I don't see the ERROR line, but it could be that there are so many DEBUG lines I'm missing it.

**Comment by sk8geek** [comment]
When I move the config folder and run Solaar to create a fresh instance I no longer see the ERROR line.

**Comment by pfps** [comment]
@skgeek It looks as if Solaar is trying to set diversion for a virtual key and that isn't something that can be done.  Can you post the output of `solaar -ddd` so that I can check for sure?

**Comment by pfps** [comment]
Ok, then don't bother with `solaar -ddd` just now.  Instead can you post the new config file?  The problem may have been an old one but your config file is forcing the bad write.

**Comment by sk8geek** [comment]
This is the new config file, created by my installed Solaar
```
- 1.1.4
- _NAME: MX Keys Keyboard
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, pointer_speed, dpi, dpi-sliding, speed-change, mouse-gestures, backlight-timed, reprogrammable-keys, persistent-remappable-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer]
  _battery: 4096
  _modelId: B35B408A0000
  _serial: F359F7AC
  _unitId: F359F7AC
  _wpid: 408A
  backlight: true
  change-host: null
  disable-keyboard-keys: {1: false, 2: false, 4: false, 8: false, 16: false}
  divert-keys: {10: 0, 110: 0, 111: 0, 191: 0, 199: 0, 200: 0, 209: 0, 210: 0, 211: 0, 224: 0, 225: 0, 226: 0, 227: 0, 228: 0, 229: 0, 230: 0, 231: 0, 232: 0,
    233: 0, 234: 0, 235: 0, 236: 0}
  fn-swap: false
  multiplatform: 0
- _NAME: Wireless Mouse Pebble M350
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode, onboard_profiles,
    report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown,
    divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer]
  _battery: 4096
  _modelId: B02140800000
  _serial: 2B442F40
  _unitId: DE12CCD9
  _wpid: '4080'
  change-host: null
  divert-keys: {82: 0}
  dpi: 1000
  dpi-sliding: 0
  lowres-scroll-mode: false
  mouse-gestures: 0
  reprogrammable-keys: {80: 80, 81: 81, 82: 82}
```

**Comment by pfps** [comment]
Yes, I see that the code has been fixed.   The solution is to change
```
  divert-keys: {82: 0, 215: 0}
```
to
```
  divert-keys: {82: 0}
```

**Comment by sk8geek** [comment]
Thank you.

One behaviour that I've observed is that the keyboard backlight comes on for about 5.4 seconds every "few" seconds even when I'm not using it. Just timing it now "few" might be between 5 and 11 seconds.
My understanding is that it should only illuminate when my hands are "in range".  
This used to annoy me more than it does now :-)

**Comment by pfps** [comment]
@sk8geek 
It might be possible to have the backlight work better.  If you are interested open an enhancement issue.

**Pull request merged**
