### PR TITLE
add rule-based processing of HID++ notifications

### LINKED ISSUE #504: Logitech Craft dial keycodes
The dial has the same keycode as the media fn buttons for raise/lower volume.  That means I cannot map the dial to another function without stealing that from the actual raise/lower volume buttons.

### PR DESCRIPTION
**Pull request by pfps**
Fixes #504 #987 #979

Add rule-based processing of HID++ notifications with rules that are sensitive to the notification, the active program, and the keyboard modifier keys.

Comments are wanted on whether this is a good thing to add to Solaar, the basic design, and the implementation details.

The new capabilities are in lib/logitech_receiver/diversion.py
Look there for documentation.

Requires X11, including at least one extension.

To clone and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.

To run PR #988, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/988/head:pull_988
git checkout pull_988
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_988
git fetch origin pull/XXX/head
git reset --hard FETCH_HEAD
```

### CODE REVIEW

**Comment by pfps** [comment]
The current set of rules is just sufficient to show the capabilities of the approach.  They set up the Craft crown to do something useful in Firefox and double the speed of the thumbwheel.  These two features have to be diverted to HID++ for the rules to have notifications to work on.

**Comment by viniciusbm** [comment]
After a quick test, I have a few comments:

- I think this *is* definitely a good thing to add to Solaar. Many users have created issues requesting features that would only be possible to implement by using diversion, and this will be a significant improvement. 
- The function `_process_feature_notification` processes some HID++ notifications just to log them and returns immediately, not calling the new diversion processing function. It's necessary to delete either the `return` statements or the full `if` blocks altogether (`REPROG_CONTROLS_V4`, probably `TOUCHMOUSE_RAW_POINTS`, probably  `HIRES_WHEEL`, maybe others).
- If a rule action is a single-letter key press (e.g. `KeyPress('A')`), an exception occurs at line 334 (`AttributeError: 'str' object has no attribute 'vk'`). That line should probably be:
```python
code = modifier_code(display.keysym_to_keycode(k.vk if isinstance(k, _keyboard.KeyCode) else k))
```
- The method `KeyPress.evaluate` presses **and** releases the key. I think similar (sub-)classes `KeyDown` and `KeyUp` could be very helpful so that it's possible to decide when the key should be released. 
- The feature `REPROG_CONTROLS_V4` uses the fourth byte (`address`) to indicate the type of notification (key, raw coordinates, etc.). In order to use that, maybe we need a trivial class `Address` extending `Condition` that just checks if the address matches. 

I'll do more tests later and report any ideas or suggestions if I have any.

**Comment by pfps** [comment]
@viniciusbm Good points.  

I've fixed up the special notification handling.
I added a Report condition to check for which report of the feature is being processed.
I fixed the bug.
Because of the way that the reports for diverted keys work I had to add some special code to determine when a key is pressed.  I also added a new condition to check whether the current notification is about a key being pressed.

I haven't added KeyDown and KeyUp actions.  When would they be useful?

**Comment by viniciusbm** [comment]
@pfps 
Thanks. 

Now that you implemented `_DIVERT_KEYS`, it's easier for me to test it (I was sending the commands to divert manually using `hidconsole`). 

---

> I haven't added KeyDown and KeyUp actions. When would they be useful?

An example: in some subtitle syncing programs, while the video is playing, the user presses a key when the subtitle line starts and only releases it when the line ends. I don't think I'd use any reprogrammable keys to something like this, but it may be useful and it doesn't look like it would be hard to add. An alternative: do not send release events when the rule was triggered by `Key`; detect the release of the physical key at `process_notification` and only now send the release event. Also, some key actions (such as the arrow keys, increase/decrease volume or brightness, or even regular letters) would work better if a timer could _release it and press it again_ every x milliseconds while the physical key is still pressed (to repeat the action of the key), but maybe this would be too complex and it probably isn't worth implementing now. 

---

An easy idea: an action that runs an arbitrary program, to be used like:
```ProgramExecute('/path/to/program', 'arg1', 'arg2', 'arg3') ```

This could be useful to avoid the intermediate step of mapping a key to a key combination on Solaar and then adding a shortcut to the program using that combination on the system settings. 

---

**Comment by pfps** [comment]
I added some code for KeyDown and KeyUp, but I probably will take it out.  I ended up rebooting my system several times due to the down key autorepeating.

I added Execute to execute a program asynchronously.

**Comment by viniciusbm** [comment]
> I added some code for KeyDown and KeyUp, but I probably will take it out. I ended up rebooting my system several times due to the down key autorepeating.

I thought about it and there seems to be no easy way of implementing that without breaking the rule abstraction or creating dangerous race conditions, so I agree that it's better not to implement key release handling separately (at least for now). 

> I added Execute to execute a program asynchronously.

It's working perfectly. Thank you! 

--- 

A few minor comments:

- If two diverted keys are pressed simultaneously, then one of them is missed: `process_notification` only stores the last new key down on the list. I don't think this is a problem when function keys and volume keys are reprogrammed, as they're rarely pressed simultaneously, and perhaps the same holds for mouse side buttons unless they're used in games.

- Before merging this PR, I think the keys of `CONTROL` (`special_keys.py`) should be changed to follow a capitalisation standard. Changing that later would break the rules created by users.

- I can't test this because I don't have two Logitech devices, but it looks like the rules cannot be defined separately for each device. Maybe users want to restrict some rules to one or more devices (using the model names or the serial numbers). This would probably require some of the global variables to be a dict indexed by the devices. 

- Another thing I cannot test is the interaction between `_DIVERT_KEYS` and `_REPROGRAMMABLE_KEYS` when the same key can be remapped (group and group mask ≠ 0) **and** diverted.

**Comment by pfps** [comment]
According to the Logitech documentation diversion trumps reprogramming.

"Fixing" simultaneous key presses is probably hard.

I toyed with adding a test for the model or device ID.  It would be fairly easy.

I'll look at regularizing the names of the keys.

**Comment by viniciusbm** [comment]
> I'll look at regularizing the names of the keys. DONE

Thanks. (Sorry for nit-picking, but "SLEEP" is still capitalised.)

---

@pfps, do you think this feature deserves a GUI? I started working on it to see how hard it would be, and it doesn't seem to be too difficult:
[diversion_rules.py.txt](https://github.com/pwr-Solaar/Solaar/files/5472814/diversion_rules.py.txt)
(GitHub didn't let me upload the file with extension .py)

It doesn't allow to create rules or change the structure yet, but it already shows the existing structure in a tree and lets the user change some of the parameters.

**Comment by pfps** [comment]
Thanks for noticing SLEEP.  There is a worse problem, though.  The displayed names of keys have spaces, but one needs to use the version with _.  That looks like a bug in NamedInts.  I'm investigating.

A GUI would be nice, but a GUI for creating rules isn't trivial.  I'll look at your rule-display code.

**Comment by viniciusbm** [comment]
> Thanks for noticing SLEEP.

I looked through the full list of names, not just the ones that show up on my device, and I think some of the following might not be consistent with respect to capitalisation, underscores, etc. (Of course, if you think this isn't important, you can disregard it.)

<details>

Help_As_H**id**
Launch_Word_P**ROC**
**I**OS_Home
**I**OS_Virtual_Keyboard
**I**OS_Language_Swich _[missing T?]_
Win7_Monitor_Switch_As_Win_Shift_Left**a**rrow
Win7_Monitor_Switch_As_Win_Shift_Right**a**rrow
Analog_H**s**croll
Metro_App**s**witch
Metro_App**b**ar
Back_H**s**croll
Wi**f**i
Display_**o**ut__**p**roject_**s**creen_
View_**a**ll_**a**pps
Fn_**i**nversion_**c**hange
MultiPlatform_**b**ack
Multi**p**latform_**f**orward
Multi**p**latform_**g**esture_**b**utton
Host_Switch_**c**hannel_1
Host_Switch_**c**hannel_2
Host_Switch_**c**hannel_3
Multiplatform_**s**earch
Cursor_Button_Long_**p**ress
Next_Button_Long**p**ress _[missing underscore?]_
Back_Button_Short**p**ress _[missing underscore?]_
Back_Button_Long**p**ress _[missing underscore?]_
Laser_**b**utton_**s**hort_**p**ress
Laser_**b**utton_**l**ong_**p**ress
L**ed**_Toggle
</details>

---

> The displayed names of keys have spaces, but one needs to use the version with _. That looks like a bug in NamedInts. I'm investigating.

Perhaps `_readable_name` should be called only by `__str__` of `NamedInt` rather than using the readable name as the `NamedInt`'s `name`? 

---

> A GUI would be nice, but a GUI for creating rules isn't trivial. I'll look at your rule-display code.

It's just a draft at the moment, but I think it's a reasonable way of presenting it. It can be confusing when there are too many nested sub-rules, but editing the YAML file directly wouldn't be better, and of course it's always possible to avoid sub-rules if the user isn't familiar with this type of structure. 

--- 

Have you considered adding something like this?

<details>

```python
class Not(Condition):

    def __init__(self, op):
        self.op = op
        if not isinstance(op, Condition):
            _log.warn('rule Not argument not a condition: %s', op)

    def __str__(self):
        return 'NOT: ' + str(self.op)

    def evaluate(self, feature, notification, device, status, last_result):
        return not self.op.evaluate(feature, notification, device, status, last_result)


class Or(Condition):

    def __init__(self, *op):
        self.op = op
        for c in op:
            if not isinstance(c, Condition):
                _log.warn('rule Or argument not a condition: %s', c)

    def __str__(self):
        return 'OR: ' + ', '.join(str(c) for c in op)

    def evaluate(self, feature, notification, device, status, last_result):
        value = False
        for c in self.op:
            value = value or c.evaluate(feature, notification, device, status, last_result)
            if bool(value):
                return value
        return value


class And(Condition):

    def __init__(self, *op):
        self.op = op
        for c in op:
            if not isinstance(c, Condition):
                _log.warn('rule And argument not a condition: %s', c)

    def __str__(self):
        return 'AND: ' + ', '.join(str(c) for c in op)

    def evaluate(self, feature, notification, device, status, last_result):
        value = True
        for c in self.op:
            value = value and c.evaluate(feature, notification, device, status, last_result)
            if not bool(value):
                return value
        return value
``` 
</details>

Some examples of usage:

- `Not`: to create an action that is triggered everywhere **except** on some program (I couldn't find a way of representing that with the current code);
- `Or`: to create an action that **only** occurs in a set of programs (without writing the action once per program);
- `And`: just for the sake of completeness, as `Rule` could be done to achieve this (but an `And` is more readable than `Rule` if it's nested under the other logical operators).

**Comment by pfps** [comment]
I did another pass on the names.  I didn't change IOS to iOS.

The problem with _s is getting the names in rules to match the names in the GUI.  I don't think that moving the readable function to the str code would do that.

We could leave the GUI to a subsequent PR.

I'll think about the boolean functions.  They are probably a good idea.

**Comment by viniciusbm** [comment]
> We could leave the GUI to a subsequent PR.

Right.

---

> I'll think about the boolean functions. They are probably a good idea.

Thanks for adding them. I think line 278 should simply return `result`, so that its value is preserved if it's not a boolean. 

---

The implementation of `Modifiers` isn't working for me — maybe it has to do with my setup, such as the "ABNT2" PT-BR keyboard layout. The value of `event.state` almost always has 0x10 (16) on, even when no modifier keys are pressed. Also, AltGr seems to be 0x80 (128) rather than 0x10 (16), and unlike the other modifier keys, `mod` is `None` when I press it. I obtained the exact same results using another computer. 

I extracted and adapted the relevant code to a separate Python script, but I couldn't find out what is wrong. 

<details>

```python
#!/usr/bin/env python3

from Xlib import X
from Xlib.display import Display
from Xlib.ext import record
from Xlib.protocol import rq
import _thread


# determine current key modifiers
# there must be a better way to do this

display = Display()
context = display.record_create_context(
    0, [record.AllClients], [{
        'core_requests': (0, 0),
        'core_replies': (0, 0),
        'ext_requests': (0, 0, 0, 0),
        'ext_replies': (0, 0, 0, 0),
        'delivered_events': (0, 0),
        'device_events': (X.KeyPress, X.KeyRelease),
        'errors': (0, 0),
        'client_started': False,
        'client_died': False,
    }]
)

modifier_keycodes = display.get_modifier_mapping()
current_key_modifiers = 0


def modifier_code(keycode):
    if keycode == 0:
        return None
    for m in range(0, len(modifier_keycodes)):
        if keycode in modifier_keycodes[m]:
            return m

def key_press_handler(reply):
    global current_key_modifiers
    data = reply.data
    while len(data):
        event, data = rq.EventField(None).parse_binary_value(data, display.display, None, None)
        print('STATE =', event.state)
        if event.type == X.KeyPress:
            mod = modifier_code(event.detail)
            current_key_modifiers = (event.state | 1 << mod) if mod is not None else event.state
            if mod is not None:
                print(f'press (mod={mod})', event.detail, current_key_modifiers)
            else:
                print(f'press (mod=None): changing to event.state ({event.state})')
        elif event.type == X.KeyRelease:
            mod = modifier_code(event.detail)
            current_key_modifiers = (event.state & ~(1 << mod)) if mod is not None else event.state
            if mod is not None:
                print(f'release (mod={mod})', event.detail, current_key_modifiers)
            else:
                print(f'release (mod=None): changing to event.state ({event.state})')

_thread.start_new_thread(display.record_enable_context, (context, key_press_handler))



import time
while True:
    time.sleep(1)
    print('current_key_modifiers:', current_key_modifiers)
```
</details>

**Comment by pfps** [comment]
I fixed Or.
I think that the thing to do is to not have AltGr but Super (Windows key) instead.
Also, the other modifier bits need to be masked out.

**Comment by viniciusbm** [comment]
> I think that the thing to do is to not have AltGr but Super (Windows key) instead.

Windows key has a value of 64 for me, but I don't know if this depends on regional settings. 

---

> Also, the other modifier bits need to be masked out.

In fact, this works for me:

```python
return self.desired & 0x4D == current_key_modifiers & 0x4D
```

---

I adapted your first rule to keys that are present on my device, and if I'm not mistaken, the behaviour of `Rule` is incompatible with that structure.

```python3 
rules = Rule([
    {'Rule': [
        {'Feature': 'REPROG_CONTROLS_V4'},
        {'Report': 0x0},
        {'Rule': [{'Key': 'Volume_Up'},   {'KeyPress': '2'}]},
        {'Rule': [{'Key': 'Volume_Down'}, {'KeyPress': '1'}]},
    ]},
])
```

Since *a rule evaluation is terminated early if a component evaluates to false or the last evaluated component of a sub-component is an action*, a rule such as `{'Rule': [{'Key': 'Volume_Up'},   {'KeyPress': '2'}]}` will always stop the evaluation of the parent rule, so the second key will never work. Am I missing something?

I think I misunderstood the idea of nested rules: I thought the idea was to evaluate every branch, so every path from the root to any leaf would be fully evaluated unless something is false inside the path itself. This would be the equivalent of not stopping at sub-rules, like this:
```python
            if not isinstance(component, Action) and not isinstance(component, Rule) and not result:
                return None if result is None else False
```
I'm not sure if this is the intended behaviour or if it would have unwanted consequences (and of course `And` would have to be implemented separately).

**Comment by pfps** [comment]
The key to shortcutting rule evaluation is the "last evaluated" bit.  Processsing that doesn't get to the KeyPress:2 action doesn't prevent the next rule from being evaluated.

I added in the mask, but as a combination of the modifier bits, not a hard-coded value.

**Comment by pfps** [comment]
To see how rule processing works you have to think of three separate return possibilities.  None, a truthy value, and a falsy value except None.   Actions return None; conditions return other values.  Rules process their components until a non-action returns None (because the last thing evaluated was an action) or a condition returns a falsy value.  They then return None (for the first case) or the value (in the second case).  So a sub-rule only stops further processing if the last thing it does is execute an action.

**Comment by viniciusbm** [comment]
> I added in the mask, but as a combination of the modifier bits, not a hard-coded value.

Of course, the hard-coded value was just a quick way to check that ignoring the other bits was enough. 

---

> Processsing that doesn't get to the KeyPress:2 action doesn't prevent the next rule from being evaluated.

Using the rules from my previous message, and adding `print(component, 'evaluated to', result)` after line 236, I get this:

```
// after pressing Volume Up:
FEATURE: REPROG CONTROLS V4 evaluated to True
REPORT: 0 evaluated to True
KEY: Volume Up evaluated to True
KeyPress: 2 evaluated to None
Rule[KEY: Volume Up, KeyPress: 2] evaluated to None
Rule[FEATURE: REPROG CONTROLS V4, REPORT: 0, Rule[KEY: Volume Up, KeyPress: 2], Rule[KEY: Volume Down, KeyPress: 1]] evaluated to None
2
// [omitted lines about the key release]

// after pressing Volume Down: 
FEATURE: REPROG CONTROLS V4 evaluated to True
REPORT: 0 evaluated to True
KEY: Volume Up evaluated to False
Rule[KEY: Volume Up, KeyPress: 2] evaluated to False
Rule[FEATURE: REPROG CONTROLS V4, REPORT: 0, Rule[KEY: Volume Up, KeyPress: 2], Rule[KEY: Volume Down, KeyPress: 1]] evaluated to False
// [omitted lines about the key release]
```

So, only the first rule works: when `Key` is `False`, the whole `Rule` is stopped.

> Rules process their components until a non-action returns None (because the last thing evaluated was an action) or a condition returns a falsy value. 

That falsy value returned by `Key` is propagated to the parent rule (`result` is `False` at line 236, and it returns `False`). 

I'm sorry if I'm missing some detail, but the code, the observed behaviour and your explanation seem to agree that this happens. 🤔

**Comment by pfps** [comment]
I introduced a bug sometime last night or early this morning.  That I fixed but may not have uploaded.

A rule returning False should not terminate rule processing as it is not a condition.

I've uploaded my current code.

**Comment by viniciusbm** [comment]
I understand now, and the current code works. Thank you.

**Comment by pfps** [comment]
@barolo @sk8geek  This PR is ready for testing.  It is best tested with a Craft or MX Keys keyboard or a mouse with a thumb wheel.  Look for new settings that let you divert the Crown, or some keys, or the thumb wheel and turn some of them on.  The regular function of these keys or wheels should change.  You should be able to use the Craft crown to scroll and switch tabs in Firefox when diverted.  The monitor brightness keys on the Craft and MX Keys should work under the Windows setting when diverted.  Thumb wheels should double the speed when diverted.  Look in lib/logitech-receiver/diversion.py for more information.
Users can write rules to handle diverted notifications. Documentation for this is coming shortly.

**Comment by lukasmichel** [comment]
Is this expected to work with the thumb wheel of the MX Master 2S? Or only with mice that have the THUMB_WHEEL (0x2150) feature?

The HIRES_WHEEL feature (0x2121) provides the possibility to change the reporting of the scroll wheel to HID++. I don't know if that is of interest for this feature, because I was only able to divert it but I don't understand the rules introduced in this PR and the HID++ reports good enough to play with it myself.

**Comment by pfps** [comment]
The current rules are for THUMB_WHEEL, but the capability could be used with HIRES_WHEEL as well.   In fact that would be a good test of how well the capability works.  I'll try a couple of things to incorporate other wheels.

**Comment by barolo** [comment]
Seems that everything is working with Craft, turned it on and I can scroll with crown in Firefox [ usually I have it set as tab switch in browsers and zoom when pressed ].
Can't test it yet with the mouse as I have MX Master 2S

**Comment by viniciusbm** [comment]
@pfps, is it possible to tell if a top-level rule is a built-in rule or comes from the YAML file? I see they're all merged into a single `Rule`. This distinction will be needed if we implement a user interface for diversion, otherwise the built-in rules would also be written to the YAML file when the user makes any change.

**Comment by pfps** [comment]
@viniciusbm Not at the moment but it is an easy fix.  Either there could be separate built-in and user rules or a count of the user rules.  Which would be best?

**Comment by pfps** [comment]
@viniciusbm As well, I should make sure that all rule components retain enough information to print nicely.

**Comment by viniciusbm** [comment]
> @viniciusbm Not at the moment but it is an easy fix. Either there could be separate built-in and user rules or a count of the user rules. Which would be best?

A count is the easiest way, but having separate built-in and user rules will make it easier to add other sources in the future (e.g. some file owned by root, which applies to all users).

**Comment by pfps** [comment]
@viniciusbm 
How about each top-level rule records the file it was read from?

**Comment by viniciusbm** [comment]
> @viniciusbm
> How about each top-level rule records the file it was read from?

That's a good idea.

**Comment by pfps** [comment]
> > @viniciusbm
> > How about each top-level rule records the file it was read from?
> 
> That's a good idea.

Done.

**Comment by viniciusbm** [comment]
@pfps, what do you think about adding a class like this? 

<details>

```python
class MouseClick(Action):

    def __init__(self, args):
        if len(args) == 1 and isinstance(args[0], list):
            args = args[0]
        if not isinstance(args, list):
            args = [args]
        self.button = str(args[0]) if len(args) >= 0 else 'unknown'
        if not hasattr(_mouse.Button, self.button):
            _log.warn('rule MouseClick action: button %s not known', button)
            self.button = 'unknown'
        count = args[1] if len(args) >= 1 else 1
        try:
            self.count = int(count)
        except ValueError | TypeError:
            _log.warn('rule MouseClick action: count %s should be an integer', count)
            self.count = 1

    def __str__(self):
        return 'MouseClick: %d x %s' % (self.count, self.button)

    def evaluate(self, feature, notification, device, status, last_result):
        if _log.isEnabledFor(_INFO):
            _log.info('MouseClick action: %d %s' % (self.count, self.button))
        mouse.click(getattr(_mouse.Button, self.button), self.count)
        return None
```

</details>

The second argument is the number of times the button should be pressed (e.g. 2 for double click), and the first argument is the button name (from `pynput.mouse.Button`):
```
button8, button9, button10, ..., button30
left
middle
right
scroll_down
scroll_left
scroll_right
scroll_up
unknown
```

Of course, scroll wouldn't have to be used with this rule, since there is a specific class for that.

**Comment by viniciusbm** [comment]
> @viniciusbm As well, I should make sure that all rule components retain enough information to print nicely.

@pfps
I agree. I think the constructors of `Feature` and `Key` should store the feature/key name in a separate attribute.

---

I worked on the GUI implementation this past weekend. In order to do that, for each `RuleComponent` class I had to create a method `def data(self)` that returns the `dict` representation in the same format of the built-in rules. I used it to `compile()` a copy of the component, and also to write the contents to the YAML file.

<details> 
<summary>data(self) draft for every component type</summary>

```python3
return {'Rule': [c.data() for c in self.components]}
return {'Not': self.component.data()}
return {'Or': [c.data() for c in self.components]}
return {'And': [c.data() for c in self.components]}
return {'Process': str(self.process)}
return {'Feature': str(self.feature_name)}  # self.feature_name stored by the constructor
return {'Report': self.report}
return {'Modifiers': [str(m) for m in self.modifiers]}
return {'Key': self.key_name}  # self.key_name stored by the constructor
return {'Test': str(self.test)}
return {'KeyPress': [str(k) for k in self.key_symbols]}
return {'MouseScroll': self.amounts[:]}  # do not return a reference to the original list, using [:] to create a copy
return {'Execute': self.args[:]}
```
</details>

Also, to keep the same structure regardless of whether the *divert.yaml* file exists, I changed `_load_config_rule_file()` slightly:

<details>
<summary>_load_config_rule_file() after some small changes</summary>

```python
def _load_config_rule_file():
    global rules
    loaded_rules = []
    if _path.isfile(_file_path):
        try:
            with open(_file_path, 'r') as config_file:
                loaded_rules = []
                for loaded_rule in _yaml_safe_load_all(config_file):
                    rule = Rule(loaded_rule, source=_file_path)
                    if _log.isEnabledFor(_INFO):
                        _log.info('load rule: %s', rule)
                    loaded_rules.append(rule)
                if _log.isEnabledFor(_INFO):
                    _log.info('loaded %d rules from %s', len(loaded_rules), config_file)

        except Exception as e:
            _log.error('failed to load from %s\n%s', _file_path, e)
    loaded_rules.append(rules)
    rules = Rule(loaded_rules)
```
</details>

I'm thinking of creating a PR with the GUI implementation (and possibly the changes above, if they aren't applied to this one). It isn't perfect, but it lets the user view, create, edit and delete all of the current rule components, updating the YAML file automatically when the dialogue is closed.


<details>
<summary>GUI code (draft)</summary>

[diversion_rules.py.txt](https://github.com/pwr-Solaar/Solaar/files/5520827/diversion_rules.py.txt)

</details>

<details>
<summary>Screenshot</summary>

image
</details>

**Comment by pfps** [comment]
@viniciusbm 
> @pfps, what do you think about adding a class like this?
[An action for mouse button presses.]
> Of course, scroll wouldn't have to be used with this rule, since there is a specific class for that.
An excellent idea.  Can you put together a PR for this class and its documentation?

**Comment by pfps** [comment]
@viniciusbm A GUI would also be useful, even if it only allows display of the rules.

**Comment by viniciusbm** [comment]
> An excellent idea. Can you put together a PR for this class and its documentation?

> A GUI would also be useful, even if it only allows display of the rules.

@pfps 
Thank you. I implemented both in #998, and I'll add more details on that PR later.

**Pull request merged**
