### PR TITLE
ui: add a quit button to completely quit from main window

### PR DESCRIPTION
**Pull request by pfps**
Using some code in a suggestion in #662 I added a quit button to the main window.

Should there be a close button as well?

### CODE REVIEW

**Comment by mickleby** [comment]
@pfps my preference is neither button. What is the problem for this solution?

**Comment by pfps** [comment]
#662 is a comment from a user asking for this feature

**Comment by mickleby** [comment]
"What is the problem for this solution?" :D I don't really mean to start a philosophical discussion. Sometimes it's nice to provide features; sometimes KISS is a useful strategy. I'm coming from a Unix background and feel skepticism toward feature creep. I use pipes and sed and awk et al. This is what seems most likely to keep bugs at bay--and allows me to grok the logic fully. Opinions vary.

**Comment by pfps** [comment]
The problem that I was running into was that I would close the Solaar window and start up a new Solaar.  Of course that didn't really start up a new Solaar because closing the window didn't terminate the running Solaar.  So for me it was not simply a matter of convenience.  
That said, I'm not wed to having this extra button.

On a related note, I have changes to make Solaar run without the tray at all.  This would require a bit of a think on how to write the options.

**Comment by pfps** [comment]
Closing in favour of a more general solution to not having a tray.

**Pull request closed without merging**
