### PR TITLE
SJL/add pebble M350

### PR DESCRIPTION
**Pull request by sk8geek**
Added a line to `descriptors.py` for Pebble M350 mouse. On my machine I find that it now shows battery level, `HID++ Scrolling` toggle and a `dpi` control.

### CODE REVIEW

**Comment by pfps** [comment]
Why the change to .gitignore?

**Comment by sk8geek** [comment]
Change to .gitignore is so that Intellij IDEA settings and virtual environment don't get included. (I'm new to Python, I'm a Java dev IRL.)

**Comment by pfps** [comment]
The changes to .gitignore should not be needed as this is a Python project.  Can you rip that commit out of the PR?  Also, adding the device is better as one commit, not two.

**Comment by pfps** [comment]
Also, please label the commit something like
device: add pebble M350

**Comment by FFY00** [comment]
@pfps if you want to move this faster you should be able to push to his branch. If you screw things up just look at `git reflog` and reset to a previous state.

**Comment by pfps** [comment]
This PR doesn't have to get into the RC because, as far as I can tell, it doesn't change the functionality of Solaar.  It's more a matter of having all the known devices recorded in Solaar code.

**Comment by pfps** [comment]
Hmm.  I'm not sure how to push to his branch.  I think I accidentally pushed to a new branch on the main repository.  I think I'll just take from that branch.

@sk8geek Thanks for the PR.  To get the release candidate set up quickly I'll pull from the branch I accidentally created.

**Comment by FFY00** [comment]
You add his froak as remote, lets say you named it `sk8geek`, you checkout the branch and edit it and then `git push sk8geek`.

**Pull request closed without merging**
