### PR TITLE
release: remove packaging directory

### PR DESCRIPTION
**Pull request by pfps**
Its final contents can be seen by checking out 1.0.2-rc1 via
```
git checkout 1.0.2-rc1
```

### CODE REVIEW

**Comment by FFY00** [comment]
Can you just move this to a separate repo, please?

**Comment by pfps** [comment]
You mean remove the entire directory from this repository?

**Comment by FFY00** [comment]
Yes.

**Comment by pfps** [comment]
OK, I removed the packaging directory and left a breadcrumb in the PR description showing how to get its most recent version.  I think that that is sufficient.

**Pull request merged**
