### PR TITLE
Automatically upgrade strings to f-string

### PR DESCRIPTION
**Pull request by MattHag**
Used flynt to convert strings to f-strings, where safely possible.

Related #2372

### CODE REVIEW

**Comment by pfps** [comment]
Looks good, but if it is easy to regenerate let's delay until a couple of in-progress changes are merged in.

**Comment by MattHag** [comment]
Yep, I expected that anyways. That's not a problem.

**Comment by pfps** [comment]
@MattHag This is a good time to update this PR and merge it.

**Review by pfps — APPROVED** [review]
Looks fine

**Pull request merged**
