### PR TITLE
refactor: Apply Model-View-Presenter pattern to pairing dialog 

### PR DESCRIPTION
**Pull request by MattHag**
Related #2395

### CODE REVIEW

**Comment by MattHag** [comment]
WIP: Doesn't trigger the pairing yet.

**Comment by MattHag** [comment]
Second pairing and further, doesn't start discovery in background (No 'Scanning ...')

**Comment by pfps** [comment]
I find the refactored code harder to understand than the un-refactored code.

Admittedly the pairing code is overly complex.  I spent a bit of time cleaning up the code - eliminating a round-trip through GTK at startup.  So the code now sets up the receiver and then puts up a pairing window, depending on whether the setup succeeds or not.  Then the code does a busy wait for changes to the pairing data structure, updating the window as necessary.  On success or failure a final page is shown and the pairing is completed.

This doesn't, after all, change the basic idea underlying the code that it uses the data about a receiver as its model, with the changeable parts of the model being the pairing structure.

As with all GUI code, testing is painful.   But it is possible to test even the GUI interactions as long as GTK can find a display (real or fake).

**Comment by MattHag** [comment]
> I find the refactored code harder to understand than the un-refactored code.

Yeah, there are still some things to improve, which are much easier to handle with some knowledge about the existing implementation.

> Admittedly the pairing code is overly complex. I spent a bit of time cleaning up the code - eliminating a round-trip through GTK at startup.

That sounds great. Where can I find the changes? That's exactly what I need.

> As with all GUI code, testing is painful.

The UI itself is probably the least that needs automated tests. But testing code, that's written with testability in mind, is not painful at all, even if it's GUI related code. That's exactly what the MVP pattern provides. 
And even better, it exposes the business logic (model.py) for pairing a device, can be reused as is with other interfaces like the CLI. So far, all the CLI code looks like completely rewritten like a second code base, whereas it should reuse the same code.

**Comment by pfps** [comment]
PR #2405 cleans up the logic quite a bit.  One major change is to remove the pre-show call back as it can be done with no involvement of Gtk.  As well, the display code has been (mostly?) separated from the control code.

**Comment by pfps** [comment]
This conflicts with the changes in PR #2405

**Comment by MattHag** [comment]
Yeah, this PR needs a bigger update anyways

**Comment by pfps** [comment]
OK, let's close it for now.   It can always be reopened.

**Pull request closed without merging**
