### PR TITLE
Smooth scroll for crown

### PR DESCRIPTION
**Pull request by cm226**
* implemented a switch for swapping between smooth scrolling and ratchet for the crown

### CODE REVIEW

**Comment by cm226** [comment]
Hey, This works for me, don't think there was a way (that I could see) for swapping between ratchet and smooth for the crown.

**Comment by pfps** [comment]
I'm not sure that this is correct.  My understanding is that get is 0x10.  Also byte 1 is diverted and byte 2 is ratchet, so shouldn't there be an offset of 1 byte?  As far as I can tell you are diverting the crown when switching modes.

**Comment by pfps** [comment]
I assume that you used the Logitech public document on the Crown to get the information.

Please also arrange for the style checks to be run.  They are currently failing - I see only one blank line after your new function definition.

But thanks for the work.  This is an interesting feature to support.

**Comment by pfps** [comment]
I tested out this PR with my crown and it does switch the crown to diverted mode.

**Comment by cm226** [comment]
You are probably right about it not being right. I didn't find any Logitech spec for the crown. I guessed at the API from looking at USB traffic. I'll take a look at fixing it tomorrow.

**Comment by pfps** [comment]
Look in 
https://drive.google.com/drive/folders/0BxbRzx7vEV7eWmgwazJ3NUFfQ28?resourcekey=0-dQ-Lx1FORQl0KAdOHQaE1A
for x4600_crown.pdf

**Comment by cm226** [comment]
Thanks for pointing out the spec. I completely missed that :). I think the new commit is correct.

**Comment by pfps** [comment]
This looks better.  I won't be able to test it out for a week or so.

**Comment by pfps** [comment]
I think that now your code turns off crown diversion.  Check by turning on crown diversion, running `solaar show` to show the device and saved state, changing crown smooth scroll, and then running `solaar show` again.  I expect that it will show a change to crown diversion.
I expect that the needed approach is something like 
```
def _feature_k375s_fn_swap():
    validator = _BooleanV(true_value=b'\x01', false_value=b'\x00', read_offset=1)
    return _Setting(_FN_SWAP, _FeatureRW(_F.K375S_FN_INVERSION, prefix=b'\xFF'), validator, device_kind=(_DK.keyboard, ))
```
where reading ignores the first byte and writing inserts an extra byte, which I think should be b'\x00' here.

**Comment by cm226** [comment]
I think that the mask value of '\x00\xff' prevents this from happening? I have tested locally and i think that this is right. the GUI switch for the diverted events doesn't change when I switch the crown mode.

I could change to the read_offset, I did see that when i was making the change but it didn't look like it was applied when writing the value.

**Comment by pfps** [comment]
You are correct.  I wasn't reading the spec right.

There is another problem, though.  Because the mask has zeros in it, Solaar will read from the device before writing so that these other 'bits' are not perturbed, even though this is unnecessary.

What I think is needed to get around this unnecessary read is a one-byte offset on reading and an 0x00 byte prefix on writing.  This correctly ignores the first byte on reading and inserts the 0x00 byte on writing.  Solaar then sees an all-1 bit mask and doesn't read the feature before writing.

**Comment by cm226** [comment]
Ah yes indeed, that would be better I agree. Ill make that change.

**Comment by cm226** [comment]
Actually having thought about it some more, why is that read unnecessary? the bit that's masked out is the diverted crown events setting so we do not want to change that. Reading that from the device seems reasonable. If we were to insert 0x00 on write we would turn off diverting crown events when writing, Im pretty sure?

**Comment by pfps** [comment]
The reason that the read is not needed is that writing 0x0001000000... does not change the diversion setting while setting smooth scrolling.  The first byte is 0x02 to divert, 0x01 to not divert, and 0x00 to leave alone.  Similarly the later bytes use 0x00 for no change.

**Comment by cm226** [comment]
Ah yep, thanks. I missed that.

**Comment by pfps** [comment]
Looks good. I want to try it on crown before I approve, though.

**Comment by cm226** [comment]
yep, sounds good. Thanks for your help.

**Comment by pfps** [comment]
Yeah, well my help hasn't been so good so far.  The prefix stuff is added for both read and write commands, so it's not a great idea to use it here.   Using prefix doesn't hurt here because it adds b'0x0' for read commands, which doesn't make any change to the bits sent.
I think that the real solution involves extending boolean validation so that there is an explicit argument to add extra bytes only on writes, just as for the choices validators.  I'll work on this, and may have an update imminently.

**Comment by pfps** [comment]
PR #1366 adds an extra named argument to the boolean validator that should support the best solution.

**Comment by pfps** [comment]
Please try out PR #1366 and see whether you see any problems when running Solaar with the `-d` option.  You could then base your PR on this, using something like:

```
def _feature_crown_smooth():
    rw = _FeatureRW(_F.CROWN, read_fnid=0x10, write_fnid=0x20)
    validator = _BooleanV(true_value=0x01, false_value=0x02, read_skip_byte_count=1, write_prefix_bytes=b'0x00')
    return _Setting(_CROWN_SMOOTH, rw, validator, device_kind=(_DK.keyboard, ))
```

**Comment by cm226** [comment]
Yep seems to work fine for me. I re based my PR on yours.

**Comment by pfps** [comment]
Could you squash your commits into one?

**Comment by cm226** [comment]
yup np. Done now.

**Review by pfps — APPROVED** [review]
Looks good

**Pull request merged**
