### PR TITLE
receiver: adjust CHANGE_HOST numbers to user-visible ones

### PR DESCRIPTION
**Pull request by pfps**
Internal number are from 0 to n-1, but the ones used in Logitech software that are visible to users are from 1 to n.

### CODE REVIEW

**Comment by barolo** [comment]
It's fine for mouse but keyboard has no numbers now, at all, just name

**Comment by pfps** [comment]
The current setup for the values is:
- if there is no name (maybe because the device doesn't have host names), use the number
- if the name is not duplicated then just use the name
- if the name is duplicated then put the number and colon in front of the name
The entries should be in number order.

**Comment by barolo** [comment]
I think that leaving the numbers would be more accessible and consistent, it's easier to spot what you want too. Of course they're ordered either way, but you should be aiming for the lowest common denominator.

**Comment by pfps** [comment]
The feature isn't tied to three buttons, so it is entirely possible that there are or will be devices with a different number of host connections.  I'm not willing to depend on all devices having three connections.  Also, a radio-button interface would have to be programmed.  Any volunteers?

There is indeed a tension on what to show.  My view is that if the hostname is available, just use that.  Adding the number makes it harder to select using config.

**Comment by pfps** [comment]
The change to external numbers is flawed.  I'll have to think some more on just what to do.

**Comment by barolo** [comment]
I thought about that too, you're probably right.

You mean that it makes it easier to use via CLI? CLI users will figure it out, I'd be worried about the GUI users. My way of thinking about that is; if it makes it easier to be used by a monkey it's possibly better.

**Comment by pfps** [comment]
Agreed, the GUI setup should be easiest.  The way I was hoping it would work is that the GUI would show something nice - either just the name of the system if that was unique, otherwise the name (if any) and the number.  But I also wanted to be able to reliably select in the CLI by just giving either the system name or the number.  
However, that doesn't work because of the internal-external difference.  The CLI allows selection by full external string or internal number.  It seems to me to be bad if the displayed string is "2:MacBook" but `solaar config ... change_host 2` gets a different host.  What I was thinking then was to augment config to match against (just) this kind of prefix, so "2" would match against "2:MacBook".

**Comment by barolo** [comment]
It's all good now

**Pull request merged**
