### PR TITLE
receiver: don't produce pop-up notifications at startup and power on

### LINKED ISSUE #194: Shows a useless notification upon startup
When I start Solaar up, it shows a notification claiming my keyboard is _connected_ (not that I already noticed by typing my password on it…)  This is unnecessary, and especially bad if it’s in autostart, which [happens by default](https://github.com/pwr/Solaar/blob/master/setup.py#L15) (without even asking for permission!)  There should be an option to disable all notifications altogether; or at least the first “connected” notifications should be suppressed.

### PR DESCRIPTION
**Pull request by pfps**
Fixes #194

### CODE REVIEW

**Comment by pfps** [comment]
@barolo Can you test this PR?  When you start Solar there should not be any pop-up notification and neither should there be one when you turn your mouse off and on.

**Comment by barolo** [comment]
Sure, I was arguing with myself if it's more annoying than useful actually, don't really care for being spammed by popups but having a popup on host switch is easier to notice than finding mouse cursor, and in some cases impossible to know with keyboard until you start using it. I think that it would help that guy from #870 to have big red popup in the center of the screen when device becomes available.

**Comment by pfps** [comment]
A pop-up on host switch would be useful, but I don't think that there is any visible difference between a device showing up for host switch and showing up just because it became active.  I don't see anything in the Logitech documentation for the feature.

Were you seeing pop-ups for host switching?  If so, can you post output from `solaar -dd` around when your device switches to the host where Solaar is running?

**Comment by barolo** [comment]
I'm already in bed and will have a nasty day tomorrow. So I will check that later, but if I'm recalling correctly it's the same as when device comes online after powering up. I learned to ignore them.
One of my devices sometimes goes into sleep/suspend after some time of inactivity ( mouse I think ) waking from that causes a popup too.

**Comment by pfps** [comment]
Devices that power off when idle (and thus lose settings) emit a notification asking for the software to set them up.  This currently pops up a notification and there are complaints about the notification.

**Comment by pfps** [comment]
@barolo Have you had a chance to test this PR?

**Comment by pfps** [comment]
@barolo Can you run `bin/solaar -dd` and post the output when your keyboard or mouse switches back to your Linux host?  What I really want to see is any wireless status notification (which will have "wireless status" in it).

**Comment by barolo** [comment]
here you go,  `wireless status` appears at  `20:24:23,307 `
<details>
  <summary>solaar -dd log</summary>
  
  ```    20:24:14,966    DEBUG [AsyncUI] logitech_receiver.settings: change-host: settings write '2' to <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:14,967    DEBUG [AsyncUI] logitech_receiver.settings: change-host: settings prepare write(2) => b'\x02'
20:24:14,967    DEBUG [AsyncUI] logitech_receiver.base: (23) <= w[10 01 081B 020000]
20:24:15,190    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[10 01 4104 726940]
20:24:15,191     INFO [ReceiverListener:hidraw0] solaar.listener: Notification(1,41,04,726940) triggered new device <PairedDevice(1,4069,MX Master 2S,3A64AEB2)> (mouse)
20:24:15,191     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,17)>: present, 2 paired devices. (0) 
20:24:15,191    DEBUG [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>: eQUAD step 4 DJ connection notification: software=True, encrypted=True, link=False, payload=False
20:24:15,191    DEBUG [MainThread] solaar.ui: status changed: <UnifyingReceiver(/dev/hidraw0,17)> (NONE) None
20:24:15,192    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:None = battery-full
20:24:15,191     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>: paired offline, {'BATTERY LEVEL': 90} (0) 
20:24:15,192    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[20 01 4201 0000000000000000000000]
20:24:15,192    DEBUG [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)> (4.5) DJ notification Notification(1,42,01,0000000000000000000000)
20:24:15,193     INFO [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>: ignoring DJ connection: Notification(1,42,01,0000000000000000000000)
20:24:15,193    DEBUG [MainThread] solaar.ui: status changed: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)> (NONE) None
20:24:15,193    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:None = battery-full
20:24:15,193    DEBUG [MainThread] solaar.ui.tray: picked device with lowest battery: ('/dev/hidraw0', 1, 'Wireless Mouse MX Master 2S', {'BATTERY LEVEL': 90})
20:24:15,193    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:None = battery-full
20:24:15,193    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:None = battery-full
20:24:15,194    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:None = battery-full
20:24:15,194    DEBUG [AsyncUI] logitech_receiver.settings: hires-smooth-invert: settings read False from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:15,194    DEBUG [AsyncUI] logitech_receiver.settings: hires-smooth-resolution: settings read True from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:15,195    DEBUG [AsyncUI] logitech_receiver.settings: dpi: settings read '1200' from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:15,195    DEBUG [AsyncUI] logitech_receiver.settings: smart-shift: settings read 0 from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:15,195    DEBUG [AsyncUI] logitech_receiver.settings: reprogrammable-keys: settings read {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86} from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:15,195    DEBUG [AsyncUI] logitech_receiver.settings: change-host: settings read '2' from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,033    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[10 01 4104 B26940]
20:24:23,044     INFO [ReceiverListener:hidraw0] solaar.listener: Notification(1,41,04,B26940) triggered new device <PairedDevice(1,4069,MX Master 2S,3A64AEB2)> (mouse)
20:24:23,044     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,17)>: present, 2 paired devices. (0) 
20:24:23,044    DEBUG [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>: eQUAD step 4 DJ connection notification: software=True, encrypted=True, link=True, payload=True
20:24:23,044    DEBUG [ReceiverListener:hidraw0] logitech_receiver.status: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)> pushing device settings [<Setting([feature:toggle] MX Master 2S:hires-smooth-invert=False)>, <Setting([feature:toggle] MX Master 2S:hires-smooth-resolution=True)>, <Setting([feature:choice] MX Master 2S:dpi=1200)>, <Setting([feature:range] MX Master 2S:smart-shift=0)>, <Setting([feature:map choice] MX Master 2S:reprogrammable-keys={'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86})>, <Setting([feature:choice] MX Master 2S:change-host=2)>]
20:24:23,044    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: hires-smooth-invert: apply False (<PairedDevice(1,4069,MX Master 2S,3A64AEB2)>)
20:24:23,045    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: hires-smooth-invert: settings read False from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,045    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: hires-smooth-invert: settings write False to <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,045    DEBUG [MainThread] solaar.ui: status changed: <UnifyingReceiver(/dev/hidraw0,17)> (NONE) None
20:24:23,045    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:None = battery-full
20:24:23,047     INFO [ReceiverListener:hidraw0] solaar.configuration: saved {'1E40:3A64AEB2': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': '1300', 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '1E40:40163908': {'_name': 'Craft Advanced Keyboard', 'backlight': True, 'disable-keyboard-keys': {'1': True, '16': False, '2': False, '4': True, '8': True}, 'fn-swap': False, 'multiplatform': 0}, '1E40:BC36E202': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': 1000, 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '4066:40163908': {'_name': 'Craft Advanced Keyboard', 'backlight': True, 'disable-keyboard-keys': {'1': True, '16': False, '2': False, '4': True, '8': True}, 'fn-swap': False, 'multiplatform': '0'}, '4069:3A64AEB2': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': '1200', 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '_version': '1.0.3'} to /home/gregory/.config/solaar/config.json
20:24:23,047    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[10 01 0D1D 000000]
20:24:23,073    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 0600 5A320000000000000000000000000000]
20:24:23,081    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 0D1D 00000000000000000000000000000000]
20:24:23,082    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: hires-smooth-resolution: apply True (<PairedDevice(1,4069,MX Master 2S,3A64AEB2)>)
20:24:23,082    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: hires-smooth-resolution: settings read True from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,082    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: hires-smooth-resolution: settings write True to <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,082     INFO [ReceiverListener:hidraw0] solaar.configuration: saved {'1E40:3A64AEB2': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': '1300', 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '1E40:40163908': {'_name': 'Craft Advanced Keyboard', 'backlight': True, 'disable-keyboard-keys': {'1': True, '16': False, '2': False, '4': True, '8': True}, 'fn-swap': False, 'multiplatform': 0}, '1E40:BC36E202': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': 1000, 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '4066:40163908': {'_name': 'Craft Advanced Keyboard', 'backlight': True, 'disable-keyboard-keys': {'1': True, '16': False, '2': False, '4': True, '8': True}, 'fn-swap': False, 'multiplatform': '0'}, '4069:3A64AEB2': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': '1200', 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '_version': '1.0.3'} to /home/gregory/.config/solaar/config.json
20:24:23,083    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[10 01 0D1B 000000]
20:24:23,089    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 0610 0404C0280A0000000000000000000000]
20:24:23,097    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 0D1B 00000000000000000000000000000000]
20:24:23,097    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: BooleanValidator: prepare_write(True, b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00') => 2
20:24:23,097    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: hires-smooth-resolution: settings prepare write(True) => 2
20:24:23,098    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[10 01 0D2D 020000]
20:24:23,105    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 0001 0D000000000000000000000000000000]
20:24:23,113    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 0D2D 02000000000000000000000000000000]
20:24:23,113    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: dpi: apply 1200 (<PairedDevice(1,4069,MX Master 2S,3A64AEB2)>)
20:24:23,114    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: dpi: settings read '1200' from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,114    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: dpi: settings write '1200' to <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,114     INFO [ReceiverListener:hidraw0] solaar.configuration: saved {'1E40:3A64AEB2': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': '1300', 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '1E40:40163908': {'_name': 'Craft Advanced Keyboard', 'backlight': True, 'disable-keyboard-keys': {'1': True, '16': False, '2': False, '4': True, '8': True}, 'fn-swap': False, 'multiplatform': 0}, '1E40:BC36E202': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': 1000, 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '4066:40163908': {'_name': 'Craft Advanced Keyboard', 'backlight': True, 'disable-keyboard-keys': {'1': True, '16': False, '2': False, '4': True, '8': True}, 'fn-swap': False, 'multiplatform': '0'}, '4069:3A64AEB2': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': '1200', 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '_version': '1.0.3'} to /home/gregory/.config/solaar/config.json
20:24:23,114    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: dpi: settings prepare write(1200) => b'\x00\x04\xb0'
20:24:23,115    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[10 01 0A3F 0004B0]
20:24:23,121    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 0D20 02000000000000000000000000000000]
20:24:23,129    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 0A3F 0004B000000000000000000000000000]
20:24:23,129    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: smart-shift: apply 0 (<PairedDevice(1,4069,MX Master 2S,3A64AEB2)>)
20:24:23,129    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: smart-shift: settings read 0 from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,130    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: smart-shift: settings write 0 to <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,130     INFO [ReceiverListener:hidraw0] solaar.configuration: saved {'1E40:3A64AEB2': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': '1300', 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '1E40:40163908': {'_name': 'Craft Advanced Keyboard', 'backlight': True, 'disable-keyboard-keys': {'1': True, '16': False, '2': False, '4': True, '8': True}, 'fn-swap': False, 'multiplatform': 0}, '1E40:BC36E202': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': 1000, 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '4066:40163908': {'_name': 'Craft Advanced Keyboard', 'backlight': True, 'disable-keyboard-keys': {'1': True, '16': False, '2': False, '4': True, '8': True}, 'fn-swap': False, 'multiplatform': '0'}, '4069:3A64AEB2': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': '1200', 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '_version': '1.0.3'} to /home/gregory/.config/solaar/config.json
20:24:23,130    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: smart-shift: settings prepare write(0) => b'\x00'
20:24:23,131    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[10 01 0C1C 010000]
20:24:23,137    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 0001 0D000000000000000000000000000000]
20:24:23,145    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 0C1C 01000000000000000000000000000000]
20:24:23,145    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: reprogrammable-keys: apply {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86} (<PairedDevice(1,4069,MX Master 2S,3A64AEB2)>)
20:24:23,146    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: reprogrammable-keys: settings read {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86} from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,146    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: reprogrammable-keys: settings write {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86} to <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,146     INFO [ReceiverListener:hidraw0] solaar.configuration: saved {'1E40:3A64AEB2': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': '1300', 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '1E40:40163908': {'_name': 'Craft Advanced Keyboard', 'backlight': True, 'disable-keyboard-keys': {'1': True, '16': False, '2': False, '4': True, '8': True}, 'fn-swap': False, 'multiplatform': 0}, '1E40:BC36E202': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': 1000, 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '4066:40163908': {'_name': 'Craft Advanced Keyboard', 'backlight': True, 'disable-keyboard-keys': {'1': True, '16': False, '2': False, '4': True, '8': True}, 'fn-swap': False, 'multiplatform': '0'}, '4069:3A64AEB2': {'_name': 'Wireless Mouse MX Master 2S', 'dpi': '1200', 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}, 'smart-shift': 0}, '_version': '1.0.3'} to /home/gregory/.config/solaar/config.json
20:24:23,146    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: reprogrammable-keys: settings prepare map write(195,195) => b'\x00\x00\xc3'
20:24:23,147    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[11 01 093B 00C30000C30000000000000000000000]
20:24:23,153    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 0D00 080C0000000000000000000000000000]
20:24:23,161    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 093B 00000000000000000000000000000000]
20:24:23,162    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: reprogrammable-keys: settings prepare map write(196,196) => b'\x00\x00\xc4'
20:24:23,162    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[11 01 093E 00C40000C40000000000000000000000]
20:24:23,177    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 093E 00000000000000000000000000000000]
20:24:23,178    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: reprogrammable-keys: settings prepare map write(80,80) => b'\x00\x00P'
20:24:23,178    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[11 01 093F 00500000500000000000000000000000]
20:24:23,193    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 093F 00000000000000000000000000000000]
20:24:23,193    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: reprogrammable-keys: settings prepare map write(81,81) => b'\x00\x00Q'
20:24:23,194    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[11 01 0939 00510000510000000000000000000000]
20:24:23,213    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 0939 00000000000000000000000000000000]
20:24:23,214    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: reprogrammable-keys: settings prepare map write(82,82) => b'\x00\x00R'
20:24:23,214    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[11 01 093B 00520000520000000000000000000000]
20:24:23,227    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 093B 00000000000000000000000000000000]
20:24:23,227    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: reprogrammable-keys: settings prepare map write(83,83) => b'\x00\x00S'
20:24:23,228    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[11 01 093C 00530000530000000000000000000000]
20:24:23,243    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 093C 00000000000000000000000000000000]
20:24:23,243    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: reprogrammable-keys: settings prepare map write(86,86) => b'\x00\x00V'
20:24:23,244    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[11 01 0939 00560000560000000000000000000000]
20:24:23,259    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 0939 00000000000000000000000000000000]
20:24:23,260    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: change-host: apply 2 (<PairedDevice(1,4069,MX Master 2S,3A64AEB2)>)
20:24:23,260    DEBUG [ReceiverListener:hidraw0] logitech_receiver.settings: change-host: settings read '2' from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,260    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[10 01 080B 000000]
20:24:23,275    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 080B 03010100000000000000000000000000]
20:24:23,276    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[10 01 060E 000000]
20:24:23,291    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 060E 5A320000000000000000000000000000]
20:24:23,292    DEBUG [ReceiverListener:hidraw0] logitech_receiver.hidpp20: device 1 battery 90% charged, next level 50% charge, status 0 = discharging
20:24:23,292    DEBUG [ReceiverListener:hidraw0] logitech_receiver.status: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>: battery 90, discharging
20:24:23,292     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>: paired online, {'BATTERY LEVEL': 90, 'LINK ENCRYPTED': True, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 50, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
20:24:23,292     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>: paired online, {'BATTERY LEVEL': 90, 'LINK ENCRYPTED': True, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 50, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
20:24:23,292    DEBUG [MainThread] solaar.ui: status changed: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)> (NONE) None
20:24:23,292    DEBUG [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)> (4.5) DJ notification Notification(1,42,00,0000000000000000000000)
20:24:23,292     INFO [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>: ignoring DJ connection: Notification(1,42,00,0000000000000000000000)
20:24:23,293    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:False = battery-full
20:24:23,293    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) <= w[10 01 011B 040000]
20:24:23,293    DEBUG [MainThread] solaar.ui.tray: picked device with lowest battery: ('/dev/hidraw0', 1, 'Wireless Mouse MX Master 2S', {'BATTERY LEVEL': 90, 'LINK ENCRYPTED': True, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 50, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None})
20:24:23,293    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:False = battery-full
20:24:23,293    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:False = battery-full
20:24:23,294    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:False = battery-full
20:24:23,295    DEBUG [AsyncUI] logitech_receiver.settings: hires-smooth-invert: settings read False from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,295    DEBUG [AsyncUI] logitech_receiver.settings: hires-smooth-resolution: settings read True from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,295    DEBUG [AsyncUI] logitech_receiver.settings: dpi: settings read '1200' from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,295    DEBUG [AsyncUI] logitech_receiver.settings: smart-shift: settings read 0 from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,295    DEBUG [AsyncUI] logitech_receiver.settings: reprogrammable-keys: settings read {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86} from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,295    DEBUG [AsyncUI] logitech_receiver.settings: change-host: settings read NamedInt(1, '2:medius') from <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>
20:24:23,300    DEBUG [MainThread] solaar.ui: status changed: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)> (NONE) None
20:24:23,300    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:False = battery-full
20:24:23,301    DEBUG [MainThread] solaar.ui.tray: picked device with lowest battery: ('/dev/hidraw0', 1, 'Wireless Mouse MX Master 2S', {'BATTERY LEVEL': 90, 'LINK ENCRYPTED': True, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 50, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None})
20:24:23,301    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:False = battery-full
20:24:23,301    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:False = battery-full
20:24:23,301    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:False = battery-full
20:24:23,307    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (17) => r[11 01 011B 1D4B0000000000000000000000000000]
20:24:23,307    DEBUG [ReceiverListener:hidraw0] logitech_receiver.notifications: wireless status: Notification(1,04,00,01010100000000000000000000000000)
20:24:23,308     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>: paired online, {'BATTERY LEVEL': 90, 'LINK ENCRYPTED': True, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 50, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) powered on
20:24:23,308    DEBUG [ReceiverListener:hidraw0] logitech_receiver.status: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>: battery 90, discharging
20:24:23,308  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>: unknown BATTERY Notification(1,06,10,0404C0280A0000000000000000000000)
20:24:23,308  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>: unknown WHEEL Notification(1,0D,20,02000000000000000000000000000000)
20:24:23,308     INFO [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)>: WHEEL: res: 0 periods: 8 delta V:3072
20:24:23,308    DEBUG [MainThread] solaar.ui: status changed: <PairedDevice(1,4069,MX Master 2S,3A64AEB2)> (NONE) powered on
20:24:23,308    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:False = battery-full
20:24:23,308    DEBUG [MainThread] solaar.ui.tray: picked device with lowest battery: ('/dev/hidraw0', 1, 'Wireless Mouse MX Master 2S', {'BATTERY LEVEL': 90, 'LINK ENCRYPTED': True, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 50, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None})
20:24:23,308    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:False = battery-full
20:24:23,309    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:False = battery-full
20:24:23,309    DEBUG [MainThread] solaar.ui.icons: battery icon for 90:False = battery-full

  ```
</details>

**Comment by pfps** [comment]
@barolo  Thanks.  That notification is exactly like a power-on notification.  So there doesn't appear to be any way to distinguish between a device host-changing in and a device coming back from a sleep power-up.  That's too bad.

**Pull request merged**
