### PR TITLE
ui: add lock icon to control whether individual settings can be changed

### LINKED ISSUE #978: Put "dangerous" features under warning
**Is your feature request related to a problem? Please describe.**

I had a particularly hectic conference where I had to switch between the two PCs constantly and fast [ using host switch feature ] and when doing that via GUI I've disabled left mouse click accidentally while being completely oblivious to it,  which was really bad [ as you can imagine ] and took me a bit to figure it out.
[ I will do that guiless next time, just didn't have time to prepare for that particular event ]

**Describe the solution you'd like**
Perhaps put it behind some kind of a pop-up warning about what's to happen?

### PR DESCRIPTION
**Pull request by pfps**
Fixes #978

### CODE REVIEW

**Comment by barolo** [comment]
Yup, that's what I wanted pretty much. Persists between restarts.
Just need better visual indication for enabled/disabled states

**Comment by pfps** [comment]
Updated to grey out the label of insensitive settings.

**Comment by pfps** [comment]
And bug with multiple-setting settings fixed.

Please check again.

**Comment by barolo** [comment]
I don't want to sound nitpicky, it's good as it is for me already but probably someone more experienced in UX should chime in as I don't think that it's discoverable, visible enough for an average user. I'd expect some icon [ a padlock? ] to indicate the state

**Comment by pfps** [comment]
@barolo OK, how about a padlock on the RHS as in the current version of this PR?

**Comment by barolo** [comment]
Yup, lookin nice, pretty much what I had in mind. Works well and is selfexplanatory 

There's some GTK spam in the log

```
<Gtk.EventBox object at 0x7f3f5911fd70 (GtkEventBox at 0x12e49d0)>, <Gtk.Image object at 0x7f3f5911fdc0 (GtkImage at 0x12e4b50)>, <Gtk.Spinner object at 0x7f3f5911fe10 (GtkSpinner at 0xec1ac0)>, <Gtk.Switch object at 0x7f3f5911f870 (GtkSwitch at 0x11db8d0)>, <Gtk.EventBox object at 0x7f3f5911fe60 (GtkEventBox at 0x12e4e20)>]
[<Gtk.EventBox object at 0x7f3f58550320 (GtkEventBox at 0x12e4f90)>, <Gtk.Image object at 0x7f3f58550370 (GtkImage at 0x13eb140)>, <Gtk.Spinner object at 0x7f3f585503c0 (GtkSpinner at 0xec1bf0)>, <Gtk.Switch object at 0x7f3f5911fd70 (GtkSwitch at 0x11dba80)>, <Gtk.EventBox object at 0x7f3f58550410 (GtkEventBox at 0x13eb410)>]
CSB <Gtk.VBox object at 0x7f3f58550dc0 (GtkVBox at 0x1316890)>
CSB [<Gtk.HBox object at 0x7f3f58550aa0 (GtkHBox at 0x1316730)>, <Gtk.ListBox object at 0x7f3f585508c0 (GtkListBox at 0x13cc240)>]
gc <Gtk.Image object at 0x7f3f585507d0 (GtkImage at 0x13eb870)>
[<Gtk.EventBox object at 0x7f3f585543c0 (GtkEventBox at 0x13ebb40)>, <Gtk.Image object at 0x7f3f58554410 (GtkImage at 0x13ebcc0)>, <Gtk.Spinner object at 0x7f3f58554460 (GtkSpinner at 0xec1e50)>, <Gtk.Scale object at 0x7f3f58554280 (GtkScale at 0x13f02a0)>, <Gtk.EventBox object at 0x7f3f585544b0 (GtkEventBox at 0x13ebf90)>]
[<Gtk.EventBox object at 0x7f3f58554820 (GtkEventBox at 0x13d7130)>, <Gtk.Image object at 0x7f3f58554870 (GtkImage at 0x13d72b0)>, <Gtk.Spinner object at 0x7f3f585548c0 (GtkSpinner at 0xec1f80)>, <Gtk.ComboBoxText object at 0x7f3f5911fc80 (GtkComboBoxText at 0x13f04c0)>, <Gtk.EventBox object at 0x7f3f58554910 (GtkEventBox at 0x13d7580)>]
[<Gtk.EventBox object at 0x7f3f58554b40 (GtkEventBox at 0x13d76f0)>, <Gtk.Image object at 0x7f3f58554b90 (GtkImage at 0x13d7870)>, <Gtk.Spinner object at 0x7f3f58554be0 (GtkSpinner at 0x13f9240)>, <Gtk.HBox object at 0x7f3f58554870 (GtkHBox at 0x143c190)>, <Gtk.EventBox object at 0x7f3f58554c30 (GtkEventBox at 0x13d7b40)>]
[<Gtk.EventBox object at 0x7f3f58554c30 (GtkEventBox at 0x13d7cb0)>, <Gtk.Image object at 0x7f3f58554be0 (GtkImage at 0x13d7e30)>, <Gtk.Spinner object at 0x7f3f58554b40 (GtkSpinner at 0x13f95d0)>, <Gtk.ComboBoxText object at 0x7f3f58554b90 (GtkComboBoxText at 0x13f0b50)>, <Gtk.EventBox object at 0x7f3f58554820 (GtkEventBox at 0x1450130)>]
GFSC [<Gtk.VBox object at 0x7f3f58550500 (GtkVBox at 0x1316890)>]
GFSC [<Gtk.HBox object at 0x7f3f58554c30 (GtkHBox at 0x1316730)>, <Gtk.ListBox object at 0x7f3f585508c0 (GtkListBox at 0x13cc240)>]
GFSC [<Gtk.EventBox object at 0x7f3f58554be0 (GtkEventBox at 0x13eb580)>, <Gtk.Image object at 0x7f3f58554b40 (GtkImage at 0x13eb700)>, <Gtk.Spinner object at 0x7f3f58554820 (GtkSpinner at 0xec1d20)>, <Gtk.Button object at 0x7f3f58554d20 (GtkButton at 0x1278f80)>, <Gtk.EventBox object at 0x7f3f58554d70 (GtkEventBox at 0x13eb9d0)>]
GFSC <Gtk.ListBox object at 0x7f3f585508c0 (GtkListBox at 0x13cc240)> <Gtk.Image object at 0x7f3f58554820 (GtkImage at 0x13eb700)> <Gtk.Spinner object at 0x7f3f58554d70 (GtkSpinner at 0xec1d20)>
cgc <Gtk.HBox object at 0x7f3f58554870 (GtkHBox at 0x143c190)> [<Gtk.ComboBoxText object at 0x7f3f58554aa0 (GtkComboBoxText at 0x13f06f0)>, <Gtk.ComboBoxText object at 0x7f3f58554af0 (GtkComboBoxText at 0x13f0920)>]
```

**Comment by pfps** [comment]
Yeah, just left-over debugging output.

**Comment by lukasmichel** [comment]
I just did a quick test. The implementation look nice and the functionality is great.

I think some sort of "master padlock" that can be used to lock/unlock all settings at once could be a good addition. I am unsure if it's actually worth implementing because the same can be achieved by (un-)locking the settings individually, but there are probably people that just want to have a quick shortcut for that.

A small nitpick: The description/label of toggle switches is not greyed out in all cases (one KDE Plasma, using breeze-dark theme.):
Screenshot_20201022_122303

**Comment by pfps** [comment]
@lukasmichel I am unable to duplicate th problem, even with a very similar mouse.  Can you try do duplicate the problem with the current version of this PR?  I have cleaned up the code a bit (which may fix the problem) and added some debugging print statements.  Please run as `bin/solaar -d` so that any errors can be seen.

**Comment by lukasmichel** [comment]
@pfps the problem persists. See below for the log messages when clicking the locks. It also persists for other themes (I tried the _Emacs_ theme that seems to ship with KDE Plasma). I tried with a second device (M705 mouse) and for it, the settings are also not greyed out.

I think it could be possible that something changed with the latest versions of gtk, breeze, kde plasma or something similar. Maybe someone who also uses a rolling release distro like archlinux can check that.

I also see a different, probably unrelated problem (it does **not** persist with themes different from breeze) with the Gestures drop-down button stays after I clicked it and moved the mouse away (see also my screenshot above). It only becomes its usual color again when I click on the name of one of the gesture settings. 


<details><summary>Debug Messages for different Locks</summary>
<p>

Unlock _Scroll Wheel Direction_:
```
New Sensitivity hires-smooth-invert True <Gtk.Switch object at 0x7f409e33f880 (GtkSwitch at 0x556d9971d8c0)>
Change Icon changes-allow <Gtk.Image object at 0x7f409e345ac0 (GtkImage at 0x556d99756e30)>
19:26:13,235     INFO [MainThread] solaar.configuration: saved {'101B:41629AAD': {'_name': 'Marathon Mouse M705 (M-R0009)', '_sensitive': {'side-scroll': False, 'smooth-scroll': False}, 'side-scroll': True, 'smooth-scroll': False}, '4024:25CF31D9': {'_name': 'Wireless Touch Keyboard K400', 'fn-swap': True, 'hi-res-scroll': False}, '4069:493D1134': {'_modelId': 'B01940690000', '_name': 'Wireless Mouse MX Master 2S', '_sensitive': {'change-host': False, 'dpi': False, 'gesture2-gestures': False, 'hires-smooth-invert': True, 'hires-smooth-resolution': False, 'reprogrammable-keys': False, 'smart-shift': False}, '_unitId': '71880364', 'dpi': '3000', 'gesture2-gestures': {'45': True, '46': True}, 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 82, '80': 80, '81': 81, '82': 196, '83': 83, '86': 86}, 'smart-shift': 11, 'tap-to-click-double': False, 'tap-to-click-drag': False, 'tap-to-click-left': False, 'tap-to-click-right': False, 'touchpad-horizontal-scroll': True, 'touchpad-inverted-scroll': False, 'touchpad-vertical-scroll': False}, '4072:DDAE1933': {'_name': 'MX Anywhere 2', 'dpi': '1600', 'hires-smooth-invert': False, 'hires-smooth-resolution': False, 'reprogrammable-keys': {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '91': 91, '93': 93}}, '_version': '1.0.4rc1'} to /home/lukas/.config/solaar/config.json
```
Lock _Scroll Wheel Direction_:
```
New Sensitivity hires-smooth-invert False <Gtk.Switch object at 0x7f409e33f880 (GtkSwitch at 0x556d9971d8c0)>
Change Icon changes-prevent <Gtk.Image object at 0x7f409e33f240 (GtkImage at 0x556d99756e30)>
19:26:51,401     INFO [MainThread] solaar.configuration: saved {'101B:41629AAD': {'_name': 'Marathon Mouse M705 (M-R0009)', '_sensitive': {'side-scroll': False, 'smooth-scroll': False}, 'side-scroll': True, 'smooth-scroll': False}, '4024:25CF31D9': {'_name': 'Wireless Touch Keyboard K400', 'fn-swap': True, 'hi-res-scroll': False}, '4069:493D1134': {'_modelId': 'B01940690000', '_name': 'Wireless Mouse MX Master 2S', '_sensitive': {'change-host': False, 'dpi': False, 'gesture2-gestures': False, 'hires-smooth-invert': False, 'hires-smooth-resolution': False, 'reprogrammable-keys': False, 'smart-shift': False}, '_unitId': '71880364', 'dpi': '3000', 'gesture2-gestures': {'45': True, '46': True}, 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 82, '80': 80, '81': 81, '82': 196, '83': 83, '86': 86}, 'smart-shift': 11, 'tap-to-click-double': False, 'tap-to-click-drag': False, 'tap-to-click-left': False, 'tap-to-click-right': False, 'touchpad-horizontal-scroll': True, 'touchpad-inverted-scroll': False, 'touchpad-vertical-scroll': False}, '4072:DDAE1933': {'_name': 'MX Anywhere 2', 'dpi': '1600', 'hires-smooth-invert': False, 'hires-smooth-resolution': False, 'reprogrammable-keys': {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '91': 91, '93': 93}}, '_version': '1.0.4rc1'} to /home/lukas/.config/solaar/config.json
```

Unlock _Gestures_:
```
New Sensitivity gesture2-gestures True <Gtk.ListBox object at 0x7f409e335800 (GtkListBox at 0x556d998fa310)>
Change Icon changes-allow <Gtk.Image object at 0x7f409e34a900 (GtkImage at 0x556d997789e0)>
19:27:28,896     INFO [MainThread] solaar.configuration: saved {'101B:41629AAD': {'_name': 'Marathon Mouse M705 (M-R0009)', '_sensitive': {'side-scroll': False, 'smooth-scroll': False}, 'side-scroll': True, 'smooth-scroll': False}, '4024:25CF31D9': {'_name': 'Wireless Touch Keyboard K400', 'fn-swap': True, 'hi-res-scroll': False}, '4069:493D1134': {'_modelId': 'B01940690000', '_name': 'Wireless Mouse MX Master 2S', '_sensitive': {'change-host': False, 'dpi': False, 'gesture2-gestures': True, 'hires-smooth-invert': False, 'hires-smooth-resolution': False, 'reprogrammable-keys': False, 'smart-shift': False}, '_unitId': '71880364', 'dpi': '3000', 'gesture2-gestures': {'45': True, '46': True}, 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 82, '80': 80, '81': 81, '82': 196, '83': 83, '86': 86}, 'smart-shift': 11, 'tap-to-click-double': False, 'tap-to-click-drag': False, 'tap-to-click-left': False, 'tap-to-click-right': False, 'touchpad-horizontal-scroll': True, 'touchpad-inverted-scroll': False, 'touchpad-vertical-scroll': False}, '4072:DDAE1933': {'_name': 'MX Anywhere 2', 'dpi': '1600', 'hires-smooth-invert': False, 'hires-smooth-resolution': False, 'reprogrammable-keys': {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '91': 91, '93': 93}}, '_version': '1.0.4rc1'} to /home/lukas/.config/solaar/config.json
```
Lock _Gestures_:
```
New Sensitivity gesture2-gestures False <Gtk.ListBox object at 0x7f409e335800 (GtkListBox at 0x556d998fa310)>
Change Icon changes-prevent <Gtk.Image object at 0x7f40b4ecfc80 (GtkImage at 0x556d997789e0)>
19:27:55,091     INFO [MainThread] solaar.configuration: saved {'101B:41629AAD': {'_name': 'Marathon Mouse M705 (M-R0009)', '_sensitive': {'side-scroll': False, 'smooth-scroll': False}, 'side-scroll': True, 'smooth-scroll': False}, '4024:25CF31D9': {'_name': 'Wireless Touch Keyboard K400', 'fn-swap': True, 'hi-res-scroll': False}, '4069:493D1134': {'_modelId': 'B01940690000', '_name': 'Wireless Mouse MX Master 2S', '_sensitive': {'change-host': False, 'dpi': False, 'gesture2-gestures': False, 'hires-smooth-invert': False, 'hires-smooth-resolution': False, 'reprogrammable-keys': False, 'smart-shift': False}, '_unitId': '71880364', 'dpi': '3000', 'gesture2-gestures': {'45': True, '46': True}, 'hires-smooth-invert': False, 'hires-smooth-resolution': True, 'reprogrammable-keys': {'195': 195, '196': 82, '80': 80, '81': 81, '82': 196, '83': 83, '86': 86}, 'smart-shift': 11, 'tap-to-click-double': False, 'tap-to-click-drag': False, 'tap-to-click-left': False, 'tap-to-click-right': False, 'touchpad-horizontal-scroll': True, 'touchpad-inverted-scroll': False, 'touchpad-vertical-scroll': False}, '4072:DDAE1933': {'_name': 'MX Anywhere 2', 'dpi': '1600', 'hires-smooth-invert': False, 'hires-smooth-resolution': False, 'reprogrammable-keys': {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '91': 91, '93': 93}}, '_version': '1.0.4rc1'} to /home/lukas/.config/solaar/config.json
```
</p></details>

**Comment by pfps** [comment]
@lukasmichel So this happens when you are clicking on the locks?  Is the initial state reasonable?

**Comment by lukasmichel** [comment]
Yes, this happens when I click on the lock. 
What do you mean with "initial state"?

**Comment by pfps** [comment]
When you start Solaar is the control active exactly when the lock is open?

From your screenshot it seems that some settings have the lock the wrong way around, but only some.  Are the other settings fine?  Are the wrong-way-around settings always the wrong way around?

What does ~/.config/solaar/config.json look like when the top lock is open?  When closed?

**Comment by lukasmichel** [comment]
Ok, I'll check that again tomorrow and report back then.

**Comment by barolo** [comment]
His screenshot looks fine to me, locked doesn't mean disabled. What he meant [ I think ] and as I've mentioned before the labels don't grey out [ as in your initial implementation ] with locked state @pfps

**Comment by pfps** [comment]
@barolo So you are saying that the colored toggles are not necessarily sensitive?  In my setup when I lock a toggle (like Scroll Wheel Direction) the toggle changes appearance because it is also marked as not sensitive.  If the toggle is on, the blue background becomes white.  If the toggle is off, the darker background becomes white.  If the device is off, all settings become insensitive and lose their colour.

If the toggles are not sensitive (i.e., clicking on them does nothing) when the lock is on and sensitive when it is off then the fact that they don't change appearance is a problem with the theme's styling, not with Solaar.  To check, change to the standard GTK theme.  You could also turn a receiver-connected device off and see whether the colours change.  If the problem is indeed the theme, then complain to the theme's maintainers.

**Comment by pfps** [comment]
In my setup the toggle for Swap Fx Function and the toggles under Gestures are insensitive and thus de-coloured.
solaar

**Comment by pfps** [comment]
The labels no longer grey out because the lock icon is the indication that changes can be made.  Restoring that behaviour is possible, I guess, but maybe not worth it.

**Comment by barolo** [comment]
Yep, they're not sensitive and I'm also using KDE/Plasma so it might be theme's fault

**Comment by viniciusbm** [comment]
@pfps, the last index at line 493 of config_panel.py should be 3 (or -2). Otherwise, this exception is thrown:

```
AttributeError: 'Spinner' object has no attribute 'set_label'
```

The children are: 
```
0 Gtk.EventBox object
1 Gtk.Image object
2 Gtk.Spinner object
3 Gtk.Button object  ⟵
4 Gtk.EventBox object
```

This is the only error I've found.

This new sensitivity feature is very useful not only to prevent "dangerous" changes, but also to make it easier to find options we change often by greying out the ones we never change.

**Comment by lukasmichel** [comment]
> His screenshot looks fine to me, locked doesn't mean disabled [ because the setting can be active in locked state ] . What he meant [ I think ] and as I've mentioned before the labels don't grey out [ as in your initial implementation ] with locked state @pfps

Yes, this is basically what I wanted to say. The (un-)locking of settings works completely fine, so when some lock is closed, the corresponding setting is insensitive and when it is open, the setting is sensitive.

> The labels no longer grey out because the lock icon is the indication that changes can be made. Restoring that behaviour is possible, I guess, but maybe not worth it.

I think you are right, it is not worth it implementing this. I was just confused because it looks like this happens for the settings that are grouped under _Gestures_, but after thinking about it, the whole coloring looks consistent in that when a setting is locked, the corresponding toggle/slider/... is made insensitive. For the _Gestures_ it just looks different because the whole grouped box is made insensitive.
So, no problem here.

**Comment by pfps** [comment]
@viniciusbm Thanks.  I hadn't encountered that branch in my testing.  The code that sets up the GTK widgets is quite fragile.  It should be changed to use identifiers for the various sub-widgets.

**Comment by pfps** [comment]
OK.  Things seem to be working fine for me.  Please give the current version (bug fixed and debugging statements removed) a try.

**Review by viniciusbm — APPROVED** [review]
a5808f1 works perfectly for me.

**Pull request merged**
