### PR TITLE
startup: Only remain running at startup if a receiver is found

### PR DESCRIPTION
**Pull request by purpleidea**
This changes the .desktop "startup" file so that if this is installed,
solaar will shutdown after initial startup when no receivers are
present. This saves a lot of memory, and removes the icon from view.
This is quite useful for those who dock their mouse, and/or only use it
occasionally. This should to be changed in solaar, because otherwise it
requires overwriting a system file which should ideally only be removed
via package uninstallation, and having this installed for when it is
needed is very useful.

### CODE REVIEW

**Comment by Lekensteyn** [comment]
Hi @purpleidea, I do not think that this is a good idea. Receivers could be inserted after Solaar has started.

If you would like to disable automatic startup, I think there is some autostart folder in your home directory that can be used to override the system one (use the same name for the .desktop file).

**Comment by purpleidea** [comment]
@purpleidea udev should be used to start on plug.

**Comment by FFY00** [comment]
I also don't think this is a good idea.

> @Lekensteyn udev should be used to start on plug.
Could you elaborate?

**Comment by Lekensteyn** [comment]
> This would require the user to install the udev rule manually, and it's not something that we want IMO.

Right, I don't think this is the right approach. Most users likely expect Solaar to be displayed and will be surprised if opening the application has no effect.

**Pull request closed without merging**
