### PR TITLE
`.git-blame-ignore-revs` fix

### PR DESCRIPTION
**Pull request by FFY00**

### CODE REVIEW

**Comment by pfps** [comment]
@FFY00 Argh.  I think I did something bad.  There is now a merge commit here.

**Comment by FFY00** [comment]
Did you try to change something? Or did you just push by mistake?

**Comment by pfps** [comment]
@FFY00 There was some sort of comment in this PR and a suggested fix.  I clicked on the fix and that created a merge commit.  My guess is the first thing to do is to get rid of the merge commit and see what the comment was.

**Comment by FFY00** [comment]
It is asking to sync with master, but the way github does this is by creating a merge commit, *sigh*.

**Pull request merged**
