### PR TITLE
Convert About button to a Menu Bar entry

### PR DESCRIPTION
**Pull request by MattHag**
#2349

### CODE REVIEW

**Comment by pfps** [comment]
Where is this menu entry supposed to show up?  When I run this PR I don't see any way to get to it.

I also see the following messages at startup:
```
idefix Solaar> bin/solaar -ddd
2024-03-01 09:47:06,515,515     INFO [MainThread] solaar.gtk: version 1.1.11-58-ge866fdbc, language en_US (UTF-8)
2024-03-01 09:47:06,520,520    DEBUG [MainThread] hidapi.udev: Starting dbus monitoring

(solaar:154002): Gtk-CRITICAL **: 09:47:06.521: gtk_application_set_app_menu: assertion 'g_application_get_is_registered (G_APPLICATION (application))' failed
2024-03-01 09:47:06,550,550    DEBUG [MainThread] solaar.ui: startup registered=True, remote=False
2024-03-01 09:47:06,551,551    DEBUG [AsyncUI] solaar.tasks: started
```

**Comment by MattHag** [comment]
On Mac it shows up as supposed in the OS native menu bar, where File, Edit, Help etc. Is commonly placed. On Linux it might need a different Menu call.

**Comment by pfps** [comment]
Some Linux window managers don't have this interface, I think.  Any solution will have to work for them.

**Comment by MattHag** [comment]
Windows too and I don't want to introduce a menu row now. I drop that for now.

**Pull request closed without merging**
