### PR TITLE
po: update translation for Swedish

### PR DESCRIPTION
**Pull request by jeblad**
Updated translations for Swedish.
Checked in Ubuntu 20.04 LTS, and it loads as it should.

### CODE REVIEW

**Comment by jeblad** [comment]
Found a few errors, should perhaps be squashed before merged.

**Comment by pfps** [comment]
Can you squash the two commits into one with message `po: update translation for Swedish` and then force-push them?  I think that ends up with a better log than if I squash them.

**Comment by jeblad** [comment]
Can do, but wait until any feedback. Can be more changes..

**Comment by pfps** [comment]
OK, waiting a day or two is fine, but I want to get a release out this weekend and updated translations is a nice thing to have in a release.

**Comment by jeblad** [comment]
Ok, I'll squash them.

**Comment by jeblad** [comment]
I have squashed the commits.

**Pull request merged**
