### PR TITLE
receiver: use report rate feature if available to determine polling rate

### LINKED ISSUE #792: g305 incorrect polling rate value?
**Information**
- Solaar version : 1.0.2
- Distribution: Opensuse Tumbleweed
- Kernel version: `Linux 5.6.12-1-default x86_64 GNU/Linux `
- Output of `solaar show`:
```
Lightspeed Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:c53f
  Serial       : 72359621
    Firmware   : 44.01.B0005
    Bootloader : 00.02
    Other      : AA.DE
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

  1: G305 Lightspeed Wireless Gaming Mouse
     Codename     : G305
     Kind         : mouse
     Wireless PID : 4074
     Protocol     : HID++ 4.2
     Polling rate : 8 ms (125Hz)
     Serial number: 0434D6C4
        Bootloader: BOT 69.00.B0011
          Firmware: RQM 68.00.B0011
     The power switch is located on the base.
     Supports 27 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: BATTERY STATUS         {1000}   
         6: COLOR LED EFFECTS      {8070}   
         7: ONBOARD PROFILES       {8100}   
         8: MOUSE BUTTON SPY       {8110}   
         9: REPORT RATE            {8060}   
        10: MODE STATUS            {8090}   
        11: DFUCONTROL SIGNED      {00C2}   
        12: DEVICE RESET           {1802}   internal, hidden
        13: unknown:1803           {1803}   internal, hidden
        14: CONFIG DEVICE PROPS    {1806}   internal, hidden
        15: unknown:1811           {1811}   internal, hidden
        16: OOBSTATE               {1805}   internal, hidden
        17: unknown:1830           {1830}   internal, hidden
        18: unknown:1890           {1890}   internal, hidden
        19: unknown:1DF3           {1DF3}   internal, hidden
        20: unknown:1E00           {1E00}   hidden
        21: unknown:1EB0           {1EB0}   internal, hidden
        22: unknown:1861           {1861}   internal, hidden
        23: unknown:18B1           {18B1}   internal, hidden
        24: unknown:1E22           {1E22}   internal, hidden
        25: unknown:1801           {1801}   internal, hidden
        26: ADJUSTABLE DPI         {2201}   
     Battery: 90%, discharging.

```

**Describe the bug**
Solaar reports that the mouse is operating at 125HZ polling rate, the mouse was set to 1000HZ on windows and polling rate checker from Benq reports 1000HZ (tested on OpenSUSE). I might not understand something or the value is wrong.

**Additional context**
I have a few questions that I was hoping to get an answer, I hope it's not a crime to do it here:
1. What is high-resolution scrolling? the option is available in Solaar on M345 and M235. I did test it but I don't understand how it works, because it feels like increased scroll sensitivity but it probably is much more than that.
2. does g305 not include high sensitivity scrolling feature? (it's not present in Solaar)
3. why serial number presented in Solaar is different than the one on the mouse's label
4. I paired each m345 and m235 with nano receiver, and both of them has not encrypted connection, is it normal or its receiver mismatch.
5. I am very grateful that you created such a beautiful tool for Linux users, Thank you!

### PR DESCRIPTION
**Pull request by pfps**
Fixes #792

### CODE REVIEW

**Comment by pfps** [comment]
Best tested with a mouse that has feature REPORT RATE 0x8060. Run Solaar and check whether the Polling rate in the information box is correct. Also run solaar show and see whether the Polling rate is correct. But this could be tested even by users without this kind of device, just to check that the new code doesn't cause problems for other devices.

**Comment by pfps** [comment]
@raulcraveiro  @stavfx  @dbond762  @rijnhard You appear to have a mouse with this feature (8060).  Could you test out this PR?

 
To test a pull request, first download Solaar if you have not already done so and cd to the download directory.  The first time you test the pull request, fetch it into a new branch and checkout that branch, as in (where 840 is the number of the pull request):
```
git fetch origin pull/840/head:pull_840
git checkout pull_840
```
To test a new version of the pull request, pull it into your branch for the request, as in (where 840 is the number of the pull request):
```
git checkout pull_840
git pull origin pull/840/head:pull_840
```

**Comment by stavfx** [comment]
I didn't have any luck fetching the PR directly, but I just checked out the `rate2` branch instead.
This is the output from `sudo bin/solaar show`
```
Unifying Receiver
  Device path  : /dev/hidraw6
  USB id       : 046d:c52b
  Serial       : 3EC69FA0
    Firmware   : 12.10.B0032
    Bootloader : 02.14
    Other      : AA.AA
  Has 3 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 3=167

  1: Performance Mouse MX
     Codename     : Performance MX
     Kind         : mouse
     Wireless PID : 101A
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: A0B681A1
     The power switch is located on the base.
     Battery: unknown (device is offline).

  2: Wireless Mouse MX Master
     Codename     : MX Master
     Kind         : mouse
     Wireless PID : 4060
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 25A9C723
     The power switch is located on the base.
     Battery: unknown (device is offline).

  3: Wireless Mouse MX Master 2S
     Codename     : MX Master 2S
     Kind         : mouse
     Wireless PID : 4069
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 68BFA43A
        Bootloader: BOT 56.01.B0006
          Firmware: MPM 12.01.B0006
          Firmware: MPM 12.01.B0006
             Other: 
     The power switch is located on the base.
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: CRYPTO ID              {0021}   
         7: BATTERY STATUS         {1000}   
         8: CONFIG DEVICE PROPS    {1806}   internal, hidden
         9: CHANGE HOST            {1814}   
        10: REPROG CONTROLS V4     {1B04}   
        11: ADJUSTABLE DPI         {2201}   
        12: VERTICAL SCROLLING     {2100}   
            Roller type: 3G
            Ratchet per turn: 24
            Scroll lines: 0
        13: SMART SHIFT            {2110}   
            Smart Shift: 16
        14: HIRES WHEEL            {2121}   
            Multiplier: 8
            Has invert
              Normal wheel motion
            Has ratchet switch
              Normal wheel mode
            High resolution mode
            HID notification
            High Resolution Wheel Invert: False
            Wheel Resolution: True
        15: GESTURE 2              {6501}   
        16: DFUCONTROL SIGNED      {00C2}   
        17: unknown:1813           {1813}   internal, hidden
        18: unknown:1830           {1830}   internal, hidden
        19: unknown:1890           {1890}   internal, hidden
        20: unknown:1891           {1891}   internal, hidden
        21: unknown:18A1           {18A1}   internal, hidden
        22: unknown:18C0           {18C0}   internal, hidden
        23: unknown:1DF3           {1DF3}   internal, hidden
        24: unknown:1E00           {1E00}   hidden
        25: unknown:1EB0           {1EB0}   internal, hidden
        26: unknown:1803           {1803}   internal, hidden
        27: unknown:1861           {1861}   internal, hidden
        28: unknown:9001           {9001}   internal, hidden
        29: unknown:9200           {9200}   internal, hidden
        30: unknown:9202           {9202}   internal, hidden
        31: OOBSTATE               {1805}   internal, hidden
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Button               
             mse, pos:0, group:1, gmask:1
         1: Right Button              , default: Right Click                 => Right Button              
             mse, pos:0, group:1, gmask:1
         2: Middle Button             , default: Mouse Middle Button         => Middle Button             
             mse, reprogrammable, divertable, pos:0, group:3, gmask:7
         3: Back Button               , default: Mouse Back Button           => Back Button               
             mse, reprogrammable, divertable, pos:0, group:2, gmask:3
         4: Forward Button            , default: Mouse Forward Button        => Forward Button            
             mse, reprogrammable, divertable, pos:0, group:2, gmask:3
         5: App Switch Gesture        , default: Gesture Button Navigation   => App Switch Gesture        
             mse, reprogrammable, divertable, pos:0, group:3, gmask:7
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, pos:0, group:3, gmask:7
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, pos:0, group:4, gmask:0
     Battery: 90%, discharging, next level 50%.

Lightspeed Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:c53d
  Serial       : C7A6EBE9
    Firmware   : 43.01.B0009
    Bootloader : 02.10
    Other      : AA.D2
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

  1: G613 Wireless Mechanical Gaming Keyboard
     Codename     : G613
     Kind         : keyboard
     Wireless PID : 4065
     Protocol     : HID++ 4.2
     Polling rate : 1 ms (1000Hz)
     Serial number: 1B3FC305
        Bootloader: BOT 46.00.B0006
          Firmware: MPK 05.02.B0021
             Other: 
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: DEVICE FRIENDLY NAME   {0007}   
         7: BATTERY STATUS         {1000}   
         8: CHANGE HOST            {1814}   
         9: HOSTS INFO             {1815}   
            Host 0 (paired): 
            Host 1 (paired): Stav S20
        10: REPROG CONTROLS V4     {1B04}   
        11: REPORT HID USAGE       {1BC0}   
        12: ENCRYPTION             {4100}   
        13: KEYBOARD DISABLE BY USAGE {4522}   
        14: KEYBOARD LAYOUT 2      {4540}   
        15: GKEY                   {8010}   
        16: REPORT RATE            {8060}   
        17: DFUCONTROL SIGNED      {00C2}   
        18: DEVICE RESET           {1802}   internal, hidden
        19: unknown:1803           {1803}   internal, hidden
        20: CONFIG DEVICE PROPS    {1806}   internal, hidden
        21: unknown:1813           {1813}   internal, hidden
        22: OOBSTATE               {1805}   internal, hidden
        23: unknown:1830           {1830}   internal, hidden
        24: unknown:1890           {1890}   internal, hidden
        25: unknown:1891           {1891}   internal, hidden
        26: unknown:18A1           {18A1}   internal, hidden
        27: unknown:1DF3           {1DF3}   internal, hidden
        28: unknown:1E00           {1E00}   hidden
        29: unknown:1EB0           {1EB0}   internal, hidden
        30: unknown:1861           {1861}   internal, hidden
        31: unknown:18B1           {18B1}   internal, hidden
     Has 2 reprogrammable keys:
         0: Host Switch channel 1     , default: HostSwitch Channel 1        => Host Switch channel 1     
             divertable, persistently divertable, pos:1, group:0, gmask:0
         1: Host Switch channel 2     , default: HostSwitch Channel 2        => Host Switch channel 2     
             divertable, persistently divertable, pos:2, group:0, gmask:0
     Battery: 50%, discharging, next level 20%.
```

**Comment by pfps** [comment]
Excellent.  Thanks.  This shows the right number for your gaming keyboard so the code is working correctly.

**Comment by stavfx** [comment]
(thanks for the edit, I wasn't aware of the "details" tag)

**Comment by Frambooisier** [comment]
I can confirm that the polling rate is now correctly presented.

**Pull request merged**
