### PR TITLE
ui: Reorder buttons and add insert rule button in rules window

### PR DESCRIPTION
**Pull request by MattHag**
Related #2349

### CODE REVIEW

**Comment by pfps** [comment]
In Linux it is common to have a line of buttons at the top of a window, so  I don't think the buttons should be moved to the bottom.

Having "insert new rule" as a button is  good idea but it is not working due to a missing argument.

**Comment by MattHag** [comment]
I'll try to refactor the underlying code before anything else. The existing GUI code is horrible to work with as GUI beginner and probably the same for anyone else.

Common would be menus on top, but a top centered save button is a rather uncommon pattern on any OS for me. Ok/Save/accept on the bottom is a usuall pattern. But the rules intergace needs several tweaks to simplify its use on the short run.

And then probably a complete overhaul dumbing the necessary knowledge down to what Logi Ops and Co. use.

**Comment by MattHag** [comment]
Code is a mess and requires too much overhead for new implementations. Clean up the GUI first and implement improvements.

**Comment by MattHag** [comment]
Code is a mess and requires too much overhead for new implementations. Clean up the GUI first and implement improvements.

**Pull request closed without merging**
