### PR TITLE
add new option to start Solaar with window hidden (default) or visible or without a tray icon

### PR DESCRIPTION
**Pull request by pfps**
`solaar --window=hide` starts with window hidden (old default).  This is the default.
`solaar --window=show` starts with window showing (current default).
`solaar --window-only` starts with window showing and doesn't use the tray at all

Also remove --tray option that was recently added and adjust autostart desktop entry.

### CODE REVIEW

**Comment by pfps** [comment]
Fixes #593

**Comment by FFY00** [comment]
>  `solaar --window=show` starts with window showing (current default).

This does not seem to be the default.

**Comment by pfps** [comment]
The old default was that `solaar` started with the window hidden.   I put in a change, PR #620 so that `solaar` starts with the window showing, and added a --tray option to flip this to the old default, mostly because the --tray option didn't make much sense with the old default.   Wiith --window replacing --tray, the old default again makes more sense.
As part of the --tray PR I fiddled with the global autostart file so that it included the --tray option because when starting Solaar at startup it makes sense to have the window hidden.

**Comment by FdelMazo** [comment]
This may be trivial, but just wanted to point out that the no-tray option is `--window=only`, instead of `--window-only`. It might help whomever comes here from another issue or from any search engine.

**Comment by pfps** [comment]
Fixed, thanks.

**Comment by steakscience** [comment]
Could we have another option hide both the window and tray icon?
Currently, this would not be possible right?

**Comment by pfps** [comment]
You mean to start up with the main window hidden and no system tray icon?  That doesn't seem useful as it would be hard to interact with Solaar.

**Comment by steakscience** [comment]
@pfps Yes, I was planning on using this when autostarting Solaar on boot, and then when I need to make changes I open Solaar without these flags

**Pull request merged**
