### PR TITLE
Drop support for end-of-life Python 3.7

### LINKED ISSUE #2478: Drop support for EOL Python 3.7
**Information**
- Solaar version: 1.1.12

**Describe the solution you'd like**
Drop support for Python 3.7, which is end-of-life since June 2023 and increase minimum supported version to Python 3.8, which is the oldest maintained version till October 2024.

Python 3.8 brought many improvements regarding type hints, which are used for new Solaar code.

https://devguide.python.org/versions/

### PR DESCRIPTION
**Pull request by MattHag**
Fixes #2478

### CODE REVIEW

**Comment by pfps** [comment]
Although 3.7 may be EOL is there a non-EOL Linux distribution that uses it?   If so, it is too soon to require 3.8.

**Comment by MattHag** [comment]
I don't know, and I wouldn't care too much, as this is just an issue of installation. Solaar should be installed with its own dependencies and not rely on the system Python version. The package maintainers wrapping Solaar are responsible to set up an appropriate Python version or drop support for too old releases.

I'd introduce an official package built by GitHub CI and published on every release. [Flatpak with 39 supported distros](https://flatpak.org/setup/) sounds promising to me and is certainly one of the most prominent ones. It should handle the autorun configuration, which the APT package of Solaar already does, but the manual installation via source does not do automatically. An independent packages built with a release would allow immediate updates for flatpak users and could avoid the need for unofficial packages, we don't know what's inside.

**Comment by pfps** [comment]
Distribution via flatpak was tried by someone and there were problems, I think because of the udev rule.

**Review by pfps — APPROVED** [review]
Looks good.

**Pull request merged**
