### PR TITLE
Support logitech g pro x superlight

### PR DESCRIPTION
**Pull request by rbirkelbach**
The title speaks for itself: Add support for the g pro x superlight.

### CODE REVIEW

**Comment by pfps** [comment]
Well, at least support for the lightspeed receiver that the device uses.
Presumably this all works for you.

**Comment by Jarvvski** [comment]
my logitech superlight doesn't seem to work on my host

Is there some setup I need to do first?

**Comment by pfps** [comment]
You need to be running a version of Solaar from after Jun 8, which isn't in any release except 1.0.7rc2 (just out yesterday).  You can either clone from here, use the Solaar git ppa (probably easiest, if you are running something like Ubuntu), or use pip (`pip install solaar==1.0.7rc2`).  For more information see https://pwr-solaar.github.io/Solaar/installation.  Remember to install the udev rule if needed.

**Comment by Jarvvski** [comment]
I've added [this ppa[(https://launchpad.net/~solaar-unifying/+archive/ubuntu/ppa)

However, when I check 'about' in the GUI it still reports 1.0.1
image


Checking via `--version` in the terminal does report 1.0.7rc2 though

```
❯ solaar --version
solaar 1.0.7rc2
```

Either way, the superlight receiver doesn't seem to be detected. Should this work OOTB after first opening the mouse? I.e. I don't first have to use it on another OS? Stupid question, but I'm unsure if the mouse needs to get firmware elsewhere first.

**Comment by Jarvvski** [comment]
I did just run

```
sudo udevadm control --reload-rules
```

And that atleast got the mouse working, so that's great. Though the Solaar GUI still doesn't seem to see the mouse

**Comment by pfps** [comment]
Try running `solaar show`.   This should produce information about your mouse.

How do you start the GUI?  It is entirely possible that the GUI is still the older version of Solaar.  To get the new version you might have to open the GUI and quit Solaar and only then run `solaar`. (Just running `solaar` will not start a new Solaar but instead open up the Solaar that is currently running.)

**Comment by pfps** [comment]
By the way, Solaar should not be needed to make your mouse work under Linux.  Solaar is not a device driver, but instead a program to change the way the mouse works.

**Comment by Jarvvski** [comment]
`Solaar show` seems to work, so that's good

I usually just use dmenu to start the GUI. I've only got one reference to Solaar on the machine, so that should be the one

> By the way, Solaar should not be needed to make your mouse work under Linux. Solaar is not a device driver, but instead a program to change the way the mouse works.

Yeah, you'd think right? But genuinely it didn't work until I ran that udevadm command. I've found in the past that my older _logitech pro_ mouse (i.e. the non superlight one) required solaar before it even worked... I've never bothered to look into it enough to see why that is

**Comment by pfps** [comment]
If `solaar show` shows the mouse then quitting Solaar and running `solaar` should have the mouse show up in the GUI.

**Pull request merged**
