### PR TITLE
add Set rule action to set device settings

### LINKED ISSUE #1327: Allow direct device configuration changes through action in rules
**Information**
- Solaar version: 1.0.7
- Distribution: Mint & Pop!_OS
- Kernel version: 5.4.0 & 5.13.0
- Output of `solaar show` for the target device (if applicable): N/A

**Is your feature request related to a problem? Please describe.**
Binding config changes is only possible through binding key press to execution of Solaar cli, which requires spawning new processes etc. while could be handled internally within the diversions engine.

**Describe the solution you'd like**
Add new action type Config, which would act just like command line and maybe allow choosing device to act on and config option to change from dropdown.

### PR DESCRIPTION
**Pull request by pfps**
Fixes #1327

### CODE REVIEW

**Comment by viniciusbm** [comment]
Using these rules: 

```yaml
---
- Feature: REPROG CONTROLS V4
- Report: 0
- Rule:
  - Key: [Second Left Click, pressed]
  - Execute: [notify-send, HI]
  - Set: [null, fn-swap, '~']
  - Set: [null, disable-keyboard-keys, 'Caps Lock', true]
  - Set: [null, gesture2-gestures, Tap1Finger, true]
  - Set: [null, gesture2-gestures, DoubleTap1Finger, false]
  - Set: [null, gesture2-gestures, DoubleTap1FingerX, false]
  - Set: [null, gesture2-gestures, DoubleTap1Finger, falseX]
  - Set: [null, divert-keys, 'Volume Up', 'Diverted']
  - Set: [null, divert-keys, 'Volume UpX', 'Diverted']
  - Set: [null, divert-keys, 'Volume Up', 'DivertedX']
  - Set: [null, disable-keyboard-keys, 'Caps Lock', 3]
  - Set: [null, gesture2-params, ScaleFactor, 55] # can't set gesture parameters
  - Execute: [notify-send, BYE]
```

Apparently everything is working as expected, including the errors caused by incorrect values:

<details>

<summary>Log:</summary>

```
14:41:00,261     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Execute action: ['notify-send', 'HI']
14:41:00,273     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Set action: [None, 'fn-swap', '~']
14:41:00,274     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Set action: [None, 'disable-keyboard-keys', 'Caps Lock', True]
14:41:00,274     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Set action: [None, 'gesture2-gestures', 'Tap1Finger', True]
14:41:00,274     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Set action: [None, 'gesture2-gestures', 'DoubleTap1Finger', False]
14:41:00,274     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Set action: [None, 'gesture2-gestures', 'DoubleTap1FingerX', False]
14:41:00,274    ERROR [ReceiverListener:hidraw1] logitech_receiver.diversion: Set Action: invalid args ['DoubleTap1FingerX', False] for setting gesture2-gestures of None
14:41:00,274     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Set action: [None, 'gesture2-gestures', 'DoubleTap1Finger', 'falseX']
14:41:00,274    ERROR [ReceiverListener:hidraw1] logitech_receiver.diversion: Set Action: invalid args ['DoubleTap1Finger', 'falseX'] for setting gesture2-gestures of None
14:41:00,274     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Set action: [None, 'divert-keys', 'Volume Up', 'Diverted']
14:41:00,275     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Set action: [None, 'divert-keys', 'Volume UpX', 'Diverted']
14:41:00,275    ERROR [ReceiverListener:hidraw1] logitech_receiver.diversion: Set Action: invalid args ['Volume UpX', 'Diverted'] for setting divert-keys of None
14:41:00,275     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Set action: [None, 'divert-keys', 'Volume Up', 'DivertedX']
14:41:00,280    ERROR [ReceiverListener:hidraw1] logitech_receiver.diversion: Set Action: invalid args ['Volume Up', 'DivertedX'] for setting divert-keys of None
14:41:00,280     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Set action: [None, 'disable-keyboard-keys', 'Caps Lock', 3]
14:41:00,280    ERROR [ReceiverListener:hidraw1] logitech_receiver.diversion: Set Action: invalid args ['Caps Lock', 3] for setting disable-keyboard-keys of None
14:41:00,280     INFO [AsyncUI] solaar.configuration: saved {'_version': '1.1.1', '404D:1131A5C3': {'_name': 'Wireless Touch Keyboard K400 Plus', '_modelId': '404D00000000', '_unitId': '7A1F87C3', '_serial': '1131A5C3', '_absent': ['hi-res-scroll', 'lowres-smooth-scroll', 'hires-smooth-invert', 'hires-smooth-resolution', 'smart-shift', 'thumb-scroll-mode', 'thumb-scroll-invert', 'dpi', 'dpi-sliding', 'mouse-gestures', 'pointer_speed', 'speed-change', 'backlight', 'reprogrammable-keys', 'report_rate', 'divert-crown', 'crown-smooth', 'divert-gkeys', 'multiplatform', 'change-host'], 'fn-swap': True, 'divert-keys': {'184': 1, '84': 1, '34': 1, '8': 1, '79': 1, '62': 1, '110': 1, '145': 1, '149': 1, '40': 1, '6': 1, '4': 1, '5': 1, '183': 1, '3': 0, '1': 1, '2': 0, '64': 0}, 'disable-keyboard-keys': {'1': True, '4': False, '8': False, '16': False}, 'gesture2-gestures': {'1': True, '2': True, '30': True, '10': False, '45': False, '42': True, '43': True, '64': False, '65': False, '67': False, '84': False, '34': False}, 'gesture2-params': {'4': {'scale': 256}}}} to /home/vbm/.config/solaar/config.json
14:41:00,280     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Set action: [None, 'gesture2-params', 'ScaleFactor', 55]
14:41:00,281    ERROR [ReceiverListener:hidraw1] logitech_receiver.diversion: Set Action: invalid args ['ScaleFactor', 55] for setting gesture2-params of None
14:41:00,281     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Execute action: ['notify-send', 'BYE']
14:41:00,296     INFO [AsyncUI] solaar.configuration: saved {'_version': '1.1.1', '404D:1131A5C3': {'_name': 'Wireless Touch Keyboard K400 Plus', '_modelId': '404D00000000', '_unitId': '7A1F87C3', '_serial': '1131A5C3', '_absent': ['hi-res-scroll', 'lowres-smooth-scroll', 'hires-smooth-invert', 'hires-smooth-resolution', 'smart-shift', 'thumb-scroll-mode', 'thumb-scroll-invert', 'dpi', 'dpi-sliding', 'mouse-gestures', 'pointer_speed', 'speed-change', 'backlight', 'reprogrammable-keys', 'report_rate', 'divert-crown', 'crown-smooth', 'divert-gkeys', 'multiplatform', 'change-host'], 'fn-swap': True, 'divert-keys': {'184': 1, '84': 1, '34': 1, '8': 1, '79': 1, '62': 1, '110': 1, '145': 1, '149': 1, '40': 1, '6': 1, '4': 1, '5': 1, '183': 1, '3': 0, '1': 1, '2': 0, '64': 0}, 'disable-keyboard-keys': {'1': True, '4': False, '8': False, '16': False}, 'gesture2-gestures': {'1': True, '2': True, '30': True, '10': False, '45': False, '42': True, '43': True, '64': False, '65': False, '67': False, '84': False, '34': False}, 'gesture2-params': {'4': {'scale': 256}}}} to /home/vbm/.config/solaar/config.json
14:41:00,310     INFO [AsyncUI] solaar.configuration: saved {'_version': '1.1.1', '404D:1131A5C3': {'_name': 'Wireless Touch Keyboard K400 Plus', '_modelId': '404D00000000', '_unitId': '7A1F87C3', '_serial': '1131A5C3', '_absent': ['hi-res-scroll', 'lowres-smooth-scroll', 'hires-smooth-invert', 'hires-smooth-resolution', 'smart-shift', 'thumb-scroll-mode', 'thumb-scroll-invert', 'dpi', 'dpi-sliding', 'mouse-gestures', 'pointer_speed', 'speed-change', 'backlight', 'reprogrammable-keys', 'report_rate', 'divert-crown', 'crown-smooth', 'divert-gkeys', 'multiplatform', 'change-host'], 'fn-swap': True, 'divert-keys': {'184': 1, '84': 1, '34': 1, '8': 1, '79': 1, '62': 1, '110': 1, '145': 1, '149': 1, '40': 1, '6': 1, '4': 1, '5': 1, '183': 1, '3': 0, '1': 1, '2': 0, '64': 0}, 'disable-keyboard-keys': {'1': True, '4': False, '8': False, '16': False}, 'gesture2-gestures': {'1': True, '2': True, '30': True, '10': False, '45': False, '42': True, '43': True, '64': False, '65': False, '67': False, '84': False, '34': False}, 'gesture2-params': {'4': {'scale': 256}}}} to /home/vbm/.config/solaar/config.json
14:41:00,342     INFO [AsyncUI] solaar.configuration: saved {'_version': '1.1.1', '404D:1131A5C3': {'_name': 'Wireless Touch Keyboard K400 Plus', '_modelId': '404D00000000', '_unitId': '7A1F87C3', '_serial': '1131A5C3', '_absent': ['hi-res-scroll', 'lowres-smooth-scroll', 'hires-smooth-invert', 'hires-smooth-resolution', 'smart-shift', 'thumb-scroll-mode', 'thumb-scroll-invert', 'dpi', 'dpi-sliding', 'mouse-gestures', 'pointer_speed', 'speed-change', 'backlight', 'reprogrammable-keys', 'report_rate', 'divert-crown', 'crown-smooth', 'divert-gkeys', 'multiplatform', 'change-host'], 'fn-swap': True, 'divert-keys': {'184': 1, '84': 1, '34': 1, '8': 1, '79': 1, '62': 1, '110': 1, '145': 1, '149': 1, '40': 1, '6': 1, '4': 1, '5': 1, '183': 1, '3': 0, '1': 1, '2': 0, '64': 0}, 'disable-keyboard-keys': {'1': True, '4': False, '8': False, '16': False}, 'gesture2-gestures': {'1': True, '2': True, '30': True, '10': False, '45': False, '42': True, '43': True, '64': False, '65': False, '67': False, '84': False, '34': False}, 'gesture2-params': {'4': {'scale': 256}}}} to /home/vbm/.config/solaar/config.json
14:41:00,384     INFO [AsyncUI] solaar.configuration: saved {'_version': '1.1.1', '404D:1131A5C3': {'_name': 'Wireless Touch Keyboard K400 Plus', '_modelId': '404D00000000', '_unitId': '7A1F87C3', '_serial': '1131A5C3', '_absent': ['hi-res-scroll', 'lowres-smooth-scroll', 'hires-smooth-invert', 'hires-smooth-resolution', 'smart-shift', 'thumb-scroll-mode', 'thumb-scroll-invert', 'dpi', 'dpi-sliding', 'mouse-gestures', 'pointer_speed', 'speed-change', 'backlight', 'reprogrammable-keys', 'report_rate', 'divert-crown', 'crown-smooth', 'divert-gkeys', 'multiplatform', 'change-host'], 'fn-swap': True, 'divert-keys': {'184': 1, '84': 1, '34': 1, '8': 1, '79': 1, '62': 1, '110': 1, '145': 1, '149': 1, '40': 1, '6': 1, '4': 1, '5': 1, '183': 1, '3': 0, '1': 1, '2': 0, '64': 0}, 'disable-keyboard-keys': {'1': True, '4': False, '8': False, '16': False}, 'gesture2-gestures': {'1': True, '2': True, '30': True, '10': False, '45': False, '42': True, '43': True, '64': False, '65': False, '67': False, '84': False, '34': False}, 'gesture2-params': {'4': {'scale': 256}}}} to /home/vbm/.config/solaar/config.json
```
</details>

I spotted some side effects. I think only the first one is relevant, because the other two only occur if I press the triggering button quickly several times in a row, which probably isn't an expected use case. 

- If an affected setting was previously set to be ignored or locked, the padlock is opened automatically, and it resets to the normal state if I unselect the device on the left and select it again. 

- Sometimes the collapse/expand buttons lose their labels, which may or may not reappear after being clicked. 

- Sometimes Solaar crashes, but the log messages (when present) are different each time and perhaps we can blame Gtk or some lower level thing. 

<details>

<summary> Last lines before each crash: </summary>

```
14:43:31,201     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Execute action: ['notify-send', 'BYE']
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

```
14:52:43,951    DEBUG [AsyncUI] logitech_receiver.settings: disable-keyboard-keys: settings prepare key value write(1,True) => b'\r'
14:52:43,951    DEBUG [AsyncUI] logitech_receiver.base: (16) <= w[11 01 0B2F 0D000000000000000000000000000000]
14:52:43,956    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (15) => r[11 01 091D 00010000000000000000000000000000]
Gdk-Message: 14:52:43.961: solaar: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.0.
```

```
15:03:42,365     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Execute action: ['notify-send', 'HI']
15:03:42,369     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Set action: [None, 'fn-swap', '~']
15:03:42,370    DEBUG [ReceiverListener:hidraw1] logitech_receiver.settings: fn-swap: settings read False from <Device(1,404D,Wireless Touch Keyboard K400 Plus,1131A5C3)>
*** BUG ***
In pixman_op: The expression r1 != r1_end was false
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_op: The expression r1 != r1_end was false
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region_append_non_o: The expression y1 < y2 was false
Set a breakpoint on '_pixman_log_error' to debug
```

```
15:19:25,643     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Execute action: ['notify-send', 'HI']
15:19:25,646     INFO [ReceiverListener:hidraw1] logitech_receiver.diversion: Set action: [None, 'fn-swap', '~']
15:19:25,647    DEBUG [ReceiverListener:hidraw1] logitech_receiver.settings: fn-swap: settings read False from <Device(1,404D,Wireless Touch Keyboard K400 Plus,1131A5C3)>
```
(no special messages shown in the last one) 

</details>

**Comment by pfps** [comment]
Some of the crashes look as if they might be caused by concurrent threads working at cross purposes.  I'll take a look into this.

**Comment by pfps** [comment]
> If an affected setting was previously set to be ignored or locked, the padlock is opened automatically, and it resets to the normal state if I unselect the device on the left and select it again.

This should be fixed in the current version of the PR.  Please try it out.

**Comment by pfps** [comment]
> Sometimes the collapse/expand buttons lose their labels, which may or may not reappear after being clicked.

Can you provide more information on this?

**Comment by pfps** [comment]
The crashes all appear to be coming from low-level components.  Do any of them generate a Python backtrace?  
Please try to recreate the bugs and capture as much output as possible from them.

**Comment by viniciusbm** [comment]
> This should be fixed in the current version of the PR. Please try it out.

I can confirm that the padlock problem was fixed. 

> The crashes all appear to be coming from low-level components. Do any of them generate a Python backtrace?

No, they don't. 

> Please try to recreate the bugs and capture as much output as possible from them.

I renamed _config.json_ to have a fresh configuration, started Solaar, enabled the diversion of a button and pressed it quickly a lot of times until the program crashed.

[1.log](https://github.com/pwr-Solaar/Solaar/files/7850251/1.log)
[2.log](https://github.com/pwr-Solaar/Solaar/files/7850267/2.log)


> > Sometimes the collapse/expand buttons lose their labels, which may or may not reappear after being clicked.
> 
> Can you provide more information on this?

image
[3.log](https://github.com/pwr-Solaar/Solaar/files/7850277/3.log)

This time, it didn't crash, and I closed the program as soon as the button labels went blank. The labels reappeared when I clicked the buttons and the UI was refreshed, so it was a temporary glitch.

<hr> 

[4.log](https://github.com/pwr-Solaar/Solaar/files/7850366/4.log)

This time, I pressed the button slowly, and again it didn't crash, but the labels went blank and the two buttons stopped working. 

<hr> 

[5.log](https://github.com/pwr-Solaar/Solaar/files/7850367/5.log)

This time, I pressed the button slowly, and after some time the Solaar window froze. The rules were still working, including the Set actions (I checked the behaviour of F1 before and after pressing the button that triggered Fn swap). I had to kill it with Ctrl+C.

**Comment by pfps** [comment]
The coredumps are concerning.  There is a rework of the setting GUI code in the works.  I'll add that to this PR so that you can test it out and see whether it eliminates the core dumps.

The missing labels tests all look different.  There is one that shows a GTK error but the others don't.  It is possible that there is some race condition in the Solaar code that is causing problems.  This may also be addressed by the GUI update.

So expect a new PR for testing in a few days.

**Comment by pfps** [comment]
The changes were relatively quick to reconcile so please try again.

**Comment by viniciusbm** [comment]
Now it was harder to make it crash. 

There are some suspicious error messages: 
```
(solaar:105807): Gtk-CRITICAL **: 19:23:20.041: solaar+ui+config_panel+MapChoiceControl 0x2919430 returned a widget path for type (null), but child is GtkComboBoxText

(solaar:105807): Gtk-CRITICAL **: 19:23:20.041: gtk_style_provider_get_style_property: assertion 'g_type_is_a (gtk_widget_path_get_object_type (path), pspec->owner_type)' failed
```

And the last message was:
```
Gdk-Message: 19:23:21.375: solaar: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.0.
```

Full log: [6.log](https://github.com/pwr-Solaar/Solaar/files/7858364/6.log)

**Comment by pfps** [comment]
My guess is that these are threading issues.  Let me see how to get a thread-safe GLib in Python.

**Comment by viniciusbm** [comment]
Similar to 5.log, frozen window: [7.log](https://github.com/pwr-Solaar/Solaar/files/7858448/7.log)

**Comment by viniciusbm** [comment]
Due to the random nature of the problem, I'm not sure if this is a real solution, but I can't reproduce the errors after changing this: 

```diff
diff --git a/lib/solaar/ui/config_panel.py b/lib/solaar/ui/config_panel.py
index e62a5fc..5a6047b 100644
--- a/lib/solaar/ui/config_panel.py
+++ b/lib/solaar/ui/config_panel.py
@@ -22,7 +22,8 @@ from gi.repository import Gdk, GLib, Gtk
 from logitech_receiver.settings import KIND as _SETTING_KIND
 from logitech_receiver.settings import SENSITIVITY_IGNORE as _SENSITIVITY_IGNORE
 from solaar.i18n import _, ngettext
-from solaar.ui import ui_async as _ui_async
+# from solaar.ui import ui_async as _ui_async
+_ui_async = GLib.idle_add
 
 #
 #
@@ -39,6 +40,10 @@ def _read_async(setting, force_read, sbox, device_is_online, sensitive):
 
 def _write_async(setting, value, sbox, sensitive=True, key=None):
     def _do_write(s, v, sb, key):
+        sb._control.set_sensitive(False)
+        sb._failed.set_visible(False)
+        sb._spinner.set_visible(True)
+        sb._spinner.start()
         if key is None:
             v = setting.write(v)
         else:
@@ -47,11 +52,6 @@ def _write_async(setting, value, sbox, sensitive=True, key=None):
         if sb:
             GLib.idle_add(_update_setting_item, sb, v, True, sensitive, priority=99)
 
-    if sbox:
-        sbox._control.set_sensitive(False)
-        sbox._failed.set_visible(False)
-        sbox._spinner.set_visible(True)
-        sbox._spinner.start()
     _ui_async(_do_write, setting, value, sbox, key)
```

However, I don't know much about Gtk, and perhaps there's some reason why `GLib.idle_add` was not used instead of `ui_async`.

**Comment by pfps** [comment]
I made a change that should have the same effect, but without the potential blocking.   Write interaction with the device is in a separate thread to lessen UI blocking.  Anyway, please try out the current version of this PR.

**Comment by viniciusbm** [comment]
Using another computer that I have in a different place (with an identical keyboard and receiver), I managed to make the window freeze running 521bc33, but not with e835cc3. I'll test it again tomorrow on the same PC I used to run the previous tests.

There's another (probably simpler) issue that occurred once now, but it isn't caused by the last commit because I had noticed it  before: a write error makes the spinner stay visible and prevents the corresponding widgets from working properly. I don't know if it's a bug or a communication glitch.

```
1:49:45,372    DEBUG [AsyncUI] logitech_receiver.base: (16) => r[11 01 FF0D 2A020000000000000000000000000000]
21:49:45,372    DEBUG [ReceiverListener:hidraw1] logitech_receiver.base: (15) => r[11 01 FF0D 2A020000000000000000000000000000]
21:49:45,372    ERROR [AsyncUI] logitech_receiver.base: (16) device 1 error on feature request {0D2A}: 2 = invalid argument
21:49:45,372    ERROR [AsyncUI] solaar.tasks: calling <function _write_async.<locals>._do_write at 0x7f1938191dc0>
Traceback (most recent call last):
  File "/var/tmp/Solaar/lib/solaar/tasks.py", line 65, in run
    function(*args, **kwargs)
  File "/var/tmp/Solaar/lib/solaar/ui/config_panel.py", line 45, in _do_write
    v = setting.write_key_value(key, v)
  File "/var/tmp/Solaar/lib/logitech_receiver/settings.py", line 500, in write_key_value
    reply = self._rw.write(self._device, b)
  File "/var/tmp/Solaar/lib/logitech_receiver/settings.py", line 564, in write
    reply = device.feature_request(self.feature, self.write_fnid, self.prefix, data_bytes, no_reply=self.no_reply)
  File "/var/tmp/Solaar/lib/logitech_receiver/device.py", line 396, in feature_request
    return _hidpp20.feature_request(self, feature, function, *params, no_reply=no_reply)
  File "/var/tmp/Solaar/lib/logitech_receiver/hidpp20.py", line 997, in feature_request
    return device.request((feature_index << 8) + (function & 0xFF), *params, no_reply=no_reply)
  File "/var/tmp/Solaar/lib/logitech_receiver/device.py", line 384, in request
    return _base.request(
  File "/var/tmp/Solaar/lib/logitech_receiver/base.py", line 453, in request
    raise _hidpp20.FeatureCallError(number=devnumber, request=request_id, error=error, params=params)
logitech_receiver.hidpp20.FeatureCallError: {'number': 1, 'request': 3370, 'error': 2, 'params': b'\x02\x01\x07\x02'}
```

Full logs:
[e835cc3_ok.log](https://github.com/pwr-Solaar/Solaar/files/7858966/e835cc3_ok.log)
[e835cc3_spinning.log](https://github.com/pwr-Solaar/Solaar/files/7858968/e835cc3_spinning.log)
[521bc33_freeze.log](https://github.com/pwr-Solaar/Solaar/files/7858969/521bc33_freeze.log)

**Comment by viniciusbm** [comment]
> Write interaction with the device is in a separate thread to lessen UI blocking.

Thanks for explaining. Because of its name, I had assumed that `ui_async` was somehow related to Gtk and the GUI code, but I looked into the source now and found it's basically a blocking queue in a separate thread defined in _tasks.py_ and created by _ui/\_\_init\_\_.py_ at startup. So I guess the "ui" in `ui_async` just means it's used by the UI, and it makes sense now.

**Comment by pfps** [comment]
Your spinning log looks like a similar problem that very infrequently has hit others.   I think that the write that is failing is for the Gestures feature, but please provide the output of `bin/solaar show` for the device that you are using in issue #1318.  The result of a failure here should not make the setting unusable this way, instead the failure widget should show..  I'll see about making this fix.

**Comment by pfps** [comment]
The newest version of the PR should  have the spinning problem fixed, but this is only a fix for the UI.  Please try it out anyway.  A fix to the underlying problem will involve a fix to the code that implements the Gesture setting, which is what is going wrong in #1318.

**Comment by pfps** [comment]
Everything should be working now, except that you can't edit the Set rules in the GUI.    (And the spinning problem is a separate issue.)
Please try running with the current version of this PR and let me know if you encounter any problems.

**Comment by viniciusbm** [comment]
I can't reproduce any of the errors now, and I tried for a longer time (the log is so large that I had to compress it, and there are no lines mentioning GTK or any unexpected error).

[8.log.gz](https://github.com/pwr-Solaar/Solaar/files/7866292/8.log.gz)

**Comment by pfps** [comment]
Excellent.  There is no GUI for this rule component, but I think the PR can be added to Solaar.

**Pull request merged**
