### PR TITLE
test: Test base product information

### PR DESCRIPTION
**Pull request by MattHag**
Related #1097

### CODE REVIEW

**Comment by MattHag** [comment]
Needs fix of setup for Ubuntu and macOS installation. `import gi` is not available as is.

**Comment by pfps** [comment]
This is not related to this PR, but when I run pytest I get an error about importing

```
idefix Solaar> pytest
======================================================================================== test session starts ========================================================================================
platform linux -- Python 3.12.2, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/local/SoftwareDownloads/Solaar
plugins: anyio-4.0.0, mock-3.12.0, cov-4.1.0
collected 8 items / 1 error                                                                                                                                                                         

============================================================================================== ERRORS ===============================================================================================
_____________________________________________________________________ ERROR collecting tests/logitech_receiver/test_hidpp10.py ______________________________________________________________________
ImportError while importing test module '/home/local/SoftwareDownloads/Solaar/tests/logitech_receiver/test_hidpp10.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/logitech_receiver/test_hidpp10.py:3: in <module>
    from logitech_receiver import hidpp10, hidpp10_constants
E   ImportError: cannot import name 'hidpp10_constants' from 'logitech_receiver' (/home/pfps/.local/lib/python3.12/site-packages/logitech_receiver/__init__.py)
====================================================================================== short test summary info ======================================================================================
ERROR tests/logitech_receiver/test_hidpp10.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================================= 1 error in 0.16s ==========================================================================================
```

**Comment by MattHag** [comment]
The Ubuntu and macOS install needs to be extended. This issue blocks several tests from being merged and raising test coverage to roughly 20%. Furthermore, the Ubuntu and macOS install commands in the Makefile are not complete, but I couldn't determine what's missing for _gi_.

**Comment by pfps** [comment]
An Ubuntu build log is shown in https://launchpadlibrarian.net/715460060/buildlog_ubuntu-noble-amd64.solaar_1.1.11~ubuntu24.04.1_BUILDING.txt.gz

You might be able to figure out what packages need to be added from there.

**Comment by MattHag** [comment]
Yesss, it works again.

**Pull request merged**
