### PR TITLE
Implementation of KEYBOARD_DISABLE_KEYS

### PR DESCRIPTION
**Pull request by viniciusbm**
This is a follow-up to #788 \([comment](https://github.com/pwr-Solaar/Solaar/pull/788#issuecomment-645964578)\).

I used an ugly hack in config_panel.py to have a temporary working UI using the elements created for reprogrammable keys, so it needs some improvement.

### CODE REVIEW

**Comment by barolo** [comment]
Keys disabling should work for Mx Keys and Craft too

**Comment by pfps** [comment]
@barolo Do you have either of these devices to check out this pull request?

**Comment by barolo** [comment]
@pfps I have Craft/MX Keys, this pull is only implemented for K400+ isn't it?

**Comment by pfps** [comment]
@barolo No.   As soon as there is an implementation of an HID++ 2.0 feature in Solaar, all devices with that feature are covered.  Well, except that the implementation might only implement part of the feature so either nothing useful shows or maybe even nothing shows.  (So if your device has the reprogrammable keys feature but Solaar can't actually reprogram any keys you won't see any new setting.)   Adding the feature to the descriptors file is only an optimization that speeds up startup (a little bit).
So if your device has the feature with number 4521 this PR should let you disable some keys (a subset of the Windows, Insert, Scroll Lock, Num Lock, and Caps Lock keys).

**Comment by barolo** [comment]
@pfps I do have that feature [ 4521 ]  but the UI is empty, I'm on fresh master

**Comment by pfps** [comment]
Hmm.  You should be seeing something, I think.

**Comment by barolo** [comment]
oh, wait, this isn't merged. I have to check viniciusbm's branch correct?

**Comment by pfps** [comment]
Indeed.  :-)

**Comment by barolo** [comment]
@pfps It works! all of them. You won't be missed CapsLock...

**Comment by pfps** [comment]
@barolo Excelllent!  Which keys can you try to disable?  Are all of the actually disabled when you try?
The names of the keys are from Logitech, but maybe that key could be called Win_Meta or something like that.

**Comment by pfps** [comment]
OK, so this looks to be ready to go, all that is needed is for me to either live with the GUI hack or implement something better.  If I don't get a fixed GUI setup, I'll put this in in a day or so.

**Comment by barolo** [comment]
@pfps Caps Lock, Num Lock, Scroll Lock, Insert, Win. That's what I have and they all work

**Comment by pfps** [comment]
@barolo That's all of them.  Thanks.

**Comment by viniciusbm** [comment]
@barolo, thanks for testing. As my keyboard doesn't have Num Lock, it's nice that you checked that disabling that key works well. 

@pfps, thank you for analysing the PR. Regarding the UI, even though a checkbox or toggle could _look better_ than a combobox with False and True, it could make the meaning _less clear_ for some users: enabling the option would disable the key. At least the current appearance doesn't have that problem, as it looks like a T/F question (of course it's logically equivalent, but I think it's easier to understand). I don't have a better idea, so I think it can stay as it is for now.

**Comment by pfps** [comment]
@viniciusbm I have a change to config_panel.py to handle maps to toggles.   I think I'll merge in your change and think about whether my changes make sense.

**Comment by pfps** [comment]
@barolo @viniciusbm If either of you want to be able to officially test and review PRs let me know and I'll get you set up to do so (provided that I can figure out how to do that).

**Comment by viniciusbm** [comment]
> I think I'll merge in your change...

Thanks for merging! @pfps, did you see my review request on this PR about a line I forgot to delete? 

> @viniciusbm I have a change to config_panel.py to handle maps to toggles. 

That seems good! Regardless of whether the toggles will be applied to this feature, they'll certainly be very useful for other features (such as GESTURE_2, which has lots of binary settings).

>  @barolo @viniciusbm If either of you want to be able to officially test and review PRs let me know and I'll get you set up to do so (provided that I can figure out how to do that).

I only have one Logitech device, so I don't think I'd be of much help; however, I'll be happy to review any changes that I can test on my keyboard.

**Comment by pfps** [comment]
@viniciusbm No, what is the line to change?

**Comment by viniciusbm** [comment]
> @viniciusbm No, what is the line to change?

Line 527 of settings_templates.py.

This was the text of the request: 
> @pfps, sorry for accidentally leaving this line that I added for debugging purposes! Should I add a commit removing that line? If so, should it amend the old one or be a new commit?

**Comment by pfps** [comment]
Oops.  I'll yank that out.  The easy way to do this would have been to amend the commit and use a force-push to change the PR.  (But amending old commits requires some non-trivial knowledge about git.)

**Comment by barolo** [comment]
> @barolo @viniciusbm If either of you want to be able to officially test and review PRs let me know and I'll get you set up to do so (provided that I can figure out how to do that).

sure, I can do MX Keys/Craft and MX Master 2S, I have K340 laying around too

**Comment by pfps** [comment]
@barolo @viniciusbm I'm still trying to find out if there is a reasonable level of extra status to give you.  I think that the easiest thing for now is for me to just ask you to review pull requests.   I'll say what needs to be checked out in the pull request comment.

**Comment by barolo** [comment]
There's serious bug I think, if you disable Caps Lock when it's on it's going to be stuck in that state

**Comment by viniciusbm** [comment]
> There's serious bug I think, if you disable Caps Lock when it's on it's going to be stuck in that state

If you mean that caps lock isn't automatically turned off when you disable the key, then that's not a bug: it's the expected behaviour. It's the same on Windows with Logitech Options. The feature is about disabling the Caps Lock **key** on that specific keyboard, not the caps lock feature on the system. It can still be toggled using another keyboard, on-screen virtual keyboard, system command, etc. 

However, if you mean that you cannot re-enable the key on Solaar after disabling it, then it is a bug that I cannot reproduce here, so you may want to post some logs.

**Comment by barolo** [comment]
I meant that: ? press Caps Lock key, it's ON -> disable key in solar -> it's still ON [ you write in caps ] -> press it -> it's disabled | it doesn't change state Caps Lock still is on  [ I have a LED indicator on it and it will be ON continuously from now on ]
I guess that it makes sense somewhat , but it's not disabled then/turned off, it's forced ON

**Comment by viniciusbm** [comment]
As far as I know, that's how it's expected to work, and that's not different from what you'd get from Logitech Options. When you enable/disable the key, I don't think the caps lock state should be changed by the program: all it's supposed to do is to send the command for the keyboard to do nothing when you press that key from now on until you re-enable the key.

**Comment by barolo** [comment]
Oh, ok, bit weird if you ask me. Forever Rage Mode™

**Pull request merged**
