### PR TITLE
Added some missing known feature names and list of implemented features

### PR DESCRIPTION
**Pull request by doctor64**
See #582 for discussion

### CODE REVIEW

**Comment by FFY00** [comment]
I added a commit making the table nice when we are not using a markdown interpreter.

I would be good to replace all the names with the names from https://github.com/Logitech/cpg-docs/tree/master/hidpp20 but I understand if you don't have time or don't want to do it. This is a nitpick.

Could you split your commit in two? One for the docs and one adding the features to the code?

**Comment by FFY00** [comment]
This last commit removes the outer lines, making it easier to edit the table in the future.

**Comment by FFY00** [comment]
Btw, preview: https://github.com/doctor64/Solaar/blob/add_feat_names/docs/features.md

**Comment by doctor64** [comment]
@FFY00 I specially use ID's from source code, to make source code navigation easier.I can split commit, but earlier maintainer ask me to squash commits to single commit. Yeah, your checkmarks looks good!

**Comment by FFY00** [comment]
> I specially use ID's from source code, to make source code navigation easier

Yes what I meant by that was to rename it in both code and documentation. But that can come in other PR.

> I can split commit, but earlier maintainer ask me to squash commits to single commit. Yeah, your checkmarks looks good!

Please split your commit and squash all of my commits with together your commit adding `features.md`.

The history should look something like this:
```
hidpp20: add IDs from missing features
docs: add supported HID++ 2.0 feature status
```

**Comment by FFY00** [comment]
Can you resolve conflicts?

**Comment by doctor64** [comment]
@FFY00 Conflict resolved. Terrible sorry for being missed for some time, I have some health problems.
Do you still needed to split commit to two parts?

**Pull request merged**
