### PR TITLE
upgrade battery support and add support for ADC MEASUREMENT feature

### PR DESCRIPTION
**Pull request by pfps**

### CODE REVIEW

**Comment by pfps** [comment]
@barolo @sk8geek @mschilli87 @viniciusbm  This PR changes how battery information is determined and shown.  Could you try it out?  Run the Solaar GUI and see whether the battery information shows up correctly.  Run `solaar -dd show` and see whether the battery information shows up correctly and whether there are any warnings.  Thanks.



To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1643, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1643/head:pull_1643
git checkout pull_1643
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1643
git fetch origin pull/1643/head
git reset --hard FETCH_HEAD
```

**Review by viniciusbm — APPROVED** [review]
On my K400+, both the GUI and the command `show` are working as expected without warnings.

> Run the Solaar GUI and see whether the battery information shows up correctly.

image

> Run solaar -dd show and see whether the battery information shows up correctly and whether there are any warnings. 

With `-ddd`:

```
22:08:16,539    DEBUG [MainThread] logitech_receiver.base: (4) <= w[11 01 060F 00000000000000000000000000000000]
22:08:16,559    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 060F 5A320000000000000000000000000000]
22:08:16,559    DEBUG [MainThread] logitech_receiver.hidpp20: battery status 90% charged, next 50%, status discharging
     Battery: 90%, discharging, next level 50%.
```

I don't know if the features changed by this PR are used by devices with rechargeable batteries (which I don't have), but I think they'd be more useful to test different levels and charging states.

**Comment by pfps** [comment]
@viniciusbm There are four different battery features, with different characteristics.  The code for each of them has changed so wide testing is indicated.

**Comment by viniciusbm** [comment]
> @viniciusbm There are four different battery features, with different characteristics. The code for each of them has changed so wide testing is indicated.

Sorry, I forgot to check feature 0x1000:

```
6: BATTERY STATUS         {1000}   
            Battery: 90%, discharging, next level 50%.
```

There aren't any battery-related warnings. Is there anything else I can test on this device? I don't have any weak AA batteries, so I can't check other levels. 

<details>
<summary>
solaar -dd show:
</summary>

```
22:26:52,277     INFO [MainThread] logitech_receiver.base: New lock 3
22:26:52,320     INFO [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,3)>: found new device 1 (404D)
22:26:52,320     INFO [MainThread] logitech_receiver.base: New lock 4
22:26:53,394     INFO [MainThread] logitech_receiver.device: <Device(1,404D,Wireless Touch Keyboard K400 Plus,6DC5C81C)>: unitId 641487CF does not match serial 6DC5C81C
22:26:55,756    ERROR [MainThread] logitech_receiver.base: (4) device 1 error on feature request {072A}: 2 = invalid argument
22:26:55,756    ERROR [MainThread] logitech_receiver.hidpp20: Exception in _getCidReporting on device <Device(1,404D,Wireless Touch Keyboard K400 Plus,6DC5C81C)>: 
Traceback (most recent call last):
  File "/var/tmp/Solaar/lib/logitech_receiver/hidpp20.py", line 431, in _getCidReporting
    mapped_data = feature_request(self._device, FEATURE.REPROG_CONTROLS_V4, 0x20, *tuple(_pack('!H', self._cid)))
  File "/var/tmp/Solaar/lib/logitech_receiver/hidpp20.py", line 1106, in feature_request
    return device.request((feature_index << 8) + (function & 0xFF), *params, no_reply=no_reply)
  File "/var/tmp/Solaar/lib/logitech_receiver/device.py", line 413, in request
    return _base.request(
  File "/var/tmp/Solaar/lib/logitech_receiver/base.py", line 456, in request
    raise _hidpp20.FeatureCallError(number=devnumber, request=request_id, error=error, params=params)
logitech_receiver.hidpp20.FeatureCallError: {'number': 1, 'request': 1834, 'error': 2, 'params': b'\x00P'}
22:26:55,776    ERROR [MainThread] logitech_receiver.base: (4) device 1 error on feature request {072F}: 2 = invalid argument
22:26:55,776    ERROR [MainThread] logitech_receiver.hidpp20: Exception in _getCidReporting on device <Device(1,404D,Wireless Touch Keyboard K400 Plus,6DC5C81C)>: 
Traceback (most recent call last):
  File "/var/tmp/Solaar/lib/logitech_receiver/hidpp20.py", line 431, in _getCidReporting
    mapped_data = feature_request(self._device, FEATURE.REPROG_CONTROLS_V4, 0x20, *tuple(_pack('!H', self._cid)))
  File "/var/tmp/Solaar/lib/logitech_receiver/hidpp20.py", line 1106, in feature_request
    return device.request((feature_index << 8) + (function & 0xFF), *params, no_reply=no_reply)
  File "/var/tmp/Solaar/lib/logitech_receiver/device.py", line 413, in request
    return _base.request(
  File "/var/tmp/Solaar/lib/logitech_receiver/base.py", line 456, in request
    raise _hidpp20.FeatureCallError(number=devnumber, request=request_id, error=error, params=params)
logitech_receiver.hidpp20.FeatureCallError: {'number': 1, 'request': 1839, 'error': 2, 'params': b'\x00Q'}
Solaar version 1.1.4

Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:C52B
  Serial       : BE57977A
    Firmware   : 24.11.B0036
    Bootloader : 02.09
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=119

  1: Wireless Touch Keyboard K400 Plus
     Device path  : /dev/hidraw2
     WPID         : 404D
     Codename     : K400 Plus
     Kind         : keyboard
     Protocol     : HID++ 4.1
     Polling rate : 8 ms (125Hz)
     Serial number: 6DC5C81C
     Model ID:      404D00000000
     Unit ID:       641487CF
        Bootloader: BOT 22.02.B0002
          Firmware: RQK 63.02.B0016
             Other: 
     The power switch is located on the top edge.
     Supports 23 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 22.02.B0002 404D6217AD40
            Firmware: Firmware RQK 63.02.B0016 404D6217AD40
            Firmware: Other   
            Unit ID: 641487CF  Model ID: 404D00000000  Transport IDs: {'wpid': '404D'}
         3: DEVICE NAME            {0005}   
            Name: Wireless Touch Keyboard K400 Plus
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
            Battery: 90%, discharging, next level 50%.
         7: REPROG CONTROLS V4     {1B04}   
            Key/Button Diversion (saved): {Volume Up:Regular, Volume Down:Regular, Mute:Regular, Play/Pause:Regular, Next:Regular, Previous:Regular, Application Switcher:Regular, My Home:Regular, Media Player:Regular, Search:Regular, Sleep:Regular, Contextual Menu:Regular, Back:Regular, Show Desktop:Regular, Maximize Window:Regular, Switch Screen:Regular, Fn Left Click:Regular, Second Left Click:Regular}
            Key/Button Diversion        : {Volume Up:Regular, Volume Down:Regular, Mute:Regular, Play/Pause:Regular, Next:Regular, Previous:Regular, Application Switcher:Regular, My Home:Regular, Media Player:Regular, Search:Regular, Sleep:Regular, Contextual Menu:Regular, Back:Regular, Show Desktop:Regular, Maximize Window:Regular, Switch Screen:Regular, Fn Left Click:Regular, Second Left Click:Regular}
         8: SWAP BUTTON CANCEL     {2005}   
         9: NEW FN INVERSION       {40A2}   
            Fn-swap: enabled
            Fn-swap default: enabled
            Swap Fx function (saved): True
            Swap Fx function        : True
        10: ENCRYPTION             {4100}   
        11: KEYBOARD DISABLE KEYS  {4521}   
            Disable keys (saved): {Caps Lock:False, Scroll Lock:False, Insert:False, Win:False}
            Disable keys        : {Caps Lock:False, Scroll Lock:False, Insert:False, Win:False}
        12: TOUCHPAD RAW XY        {6100}   
        13: GESTURE 2              {6501}   
            Gestures (saved): {1: True, 2: True, 10: True, 30: True, 34: False, 42: True, 43: True, 45: False, 64: False, 65: False, 67: False, 84: True}
            Gestures        : {1: True, 2: True, 30: True, 10: True, 45: False, 42: True, 43: True, 64: False, 65: False, 67: False, 84: True, 34: False}
            Gestures Diversion (saved): {1: False, 2: False, 10: False, 44: False, 64: False, 65: False, 67: False, 84: False, 85: False, 100: False}
            Gestures Diversion        : {1: False, 2: False, 10: False, 44: False, 64: False, 65: False, 67: False, 84: False, 85: False, 100: False}
            Gesture params (saved): {4: {'scale': 256}}
            Gesture params        : {4: {'scale': 256}}
        14: DFUCONTROL UNSIGNED    {00C1}   
        15: unknown:1811           {1811}   internal, hidden
        16: unknown:1830           {1830}   internal, hidden
        17: unknown:1890           {1890}   internal, hidden
        18: unknown:1DF3           {1DF3}   internal, hidden
        19: unknown:1E00           {1E00}   hidden
        20: unknown:1EB0           {1EB0}   internal, hidden
        21: unknown:1861           {1861}   internal, hidden
        22: unknown:18B0           {18B0}   internal, hidden
     Has 20 reprogrammable keys:
         0: Second Left Click         , default: Left Click                  => Left Click                
             mse, divertable, pos:0, group:0, group mask:empty
             reporting: default
         1: Back                      , default: Mouse Back Button           => Mouse Back Button         
             is FN, FN sensitive, reprogrammable, divertable, pos:1, group:0, group mask:empty
             reporting: default
         2: My Home                   , default: HomePage                    => HomePage                  
             is FN, FN sensitive, reprogrammable, divertable, pos:2, group:0, group mask:empty
             reporting: default
         3: Application Switcher      , default: Application Switcher        => Application Switcher      
             is FN, FN sensitive, reprogrammable, divertable, pos:3, group:0, group mask:empty
             reporting: default
         4: Contextual Menu           , default: Right Click                 => Right Click               
             is FN, FN sensitive, reprogrammable, divertable, pos:4, group:0, group mask:empty
             reporting: default
         5: Search                    , default: Search Files                => Search Files              
             is FN, FN sensitive, reprogrammable, divertable, pos:5, group:0, group mask:empty
             reporting: default
         6: Show Desktop              , default: Show Desktop                => Show Desktop              
             is FN, FN sensitive, reprogrammable, divertable, pos:6, group:0, group mask:empty
             reporting: default
         7: Maximize Window           , default: Maximize Window             => Maximize Window           
             is FN, FN sensitive, reprogrammable, divertable, pos:7, group:0, group mask:empty
             reporting: default
         8: Switch Screen             , default: Switch Presentation/Switch Screen => Switch Presentation/Switch Screen
             is FN, FN sensitive, reprogrammable, divertable, pos:8, group:0, group mask:empty
             reporting: default
         9: Media Player              , default: Music                       => Music                     
             is FN, FN sensitive, reprogrammable, divertable, pos:9, group:0, group mask:empty
             reporting: default
        10: Previous                  , default: Previous                    => Previous                  
             is FN, FN sensitive, divertable, pos:10, group:0, group mask:empty
             reporting: default
        11: Play/Pause                , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, divertable, pos:11, group:0, group mask:empty
             reporting: default
        12: Next                      , default: Next                        => Next                      
             is FN, FN sensitive, divertable, pos:12, group:0, group mask:empty
             reporting: default
        13: Fn Left Click             , default: ShowUI                      => ShowUI                    
             divertable, pos:0, group:0, group mask:empty
             reporting: default
        14: Left Button               , default: Left Click                  => Left Click                
             mse, pos:0, group:0, group mask:empty
             reporting: default
        15: Right Button              , default: Right Click                 => Right Click               
             mse, pos:0, group:0, group mask:empty
             reporting: default
        16: Mute                      , default: Mute                        => Mute                      
             nonstandard, divertable, pos:0, group:0, group mask:empty
             reporting: default
        17: Volume Up                 , default: Volume Up                   => Volume Up                 
22:26:56,362    ERROR [MainThread] logitech_receiver.base: (4) device 1 error on feature request {0D5D}: 2 = invalid argument
             nonstandard, divertable, pos:0, group:0, group mask:empty
             reporting: default
        18: Volume Down               , default: Volume Down                 => Volume Down               
             nonstandard, divertable, pos:0, group:0, group mask:empty
             reporting: default
        19: Sleep                     , default: Sleep                       => Sleep                     
             reprogrammable, divertable, pos:0, group:0, group mask:empty
             reporting: default
     Has 17 gesture(s), 1 param(s) and 5 spec(s):
        Track1Finger               Enabled(None): None   Diverted:(None) None
        TapGestures                Enabled(None): None   Diverted:(None) None
        Tap1Finger                 Enabled(   0): True   Diverted:(   0) False
        Tap2Finger                 Enabled(   1): True   Diverted:(   1) False
        TapDrag1Finger             Enabled(   2): True   Diverted:(None) None
        DoubleTap1Finger           Enabled(   3): True   Diverted:(   2) False
        Scroll2FingerStateless     Enabled(None): None   Diverted:(   3) False
        NaturalScrolling           Enabled(   4): False  Diverted:(None) None
        Scroll2FingerHoriz         Enabled(   5): True   Diverted:(None) None
        Scroll2FingerVert          Enabled(   6): True   Diverted:(None) None
        LeftEdgeSwipe1Finger2      Enabled(   7): False  Diverted:(   4) False
        RightEdgeSwipe1Finger2     Enabled(   8): False  Diverted:(   5) False
        TopEdgeSwipe1Finger2       Enabled(   9): False  Diverted:(   6) False
        Zoom2FingerStateless       Enabled(  10): True   Diverted:(   7) False
        FnClickGestureSuppression  Enabled(  11): False  Diverted:(None) None
        TwoFingersPresent          Enabled(None): None   Diverted:(   8) False
        DeviceSpecificRawData      Enabled(None): None   Diverted:(   9) False
        ScaleFactor                Value  (   0): 256 [Default: 256]
        period unit                Spec   (   3): 2048
        DVI field width            Spec   (   1): 8
        field widths               Spec   (   2): 8
        multiplier                 Spec   (   5): None
        resolution                 Spec   (   4): 4
     Battery: 90%, discharging, next level 50%.


```
</details>


I see an error about feature 0x0D5D, but I don't think it's related to this PR.

**Comment by pfps** [comment]
@viniciusbm I see two separate errors.  The first is occurring when Solaar is querying the reprogrammable key information and happens twice.  As far as I can tell this is a device error - the device should be able to respond about the current state of the left and right mouse buttons.  But maybe because there is nothing that can be done with these buttons the device isn't set up to provide their state.  In any case nothing breaks as far as I can tell so it probably isn't worthwhile changing anything here.

The other error is for gestures.  Can you open a separate issue for that and provide the output of `solaar -ddd show?

**Pull request merged**
