### PR TITLE
change mouse gestures from boolean to choice setting

### LINKED ISSUE #1108: Add support of mouse gestures
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): 1.0.5
- Distribution: KUbuntu 20.10
- Kernel version (ex. `uname -srmo`): Linux 5.8.0-44-generic x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):

<details>

```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : C3C1108B
    Firmware   : 24.11.B0036
    Bootloader : 02.09
    Other      : AA.AC
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=79, 2=247

  1: MX Keys Keyboard
     Device path  : /dev/hidraw1
     WPID         : 408A
     Codename     : MX Keys
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Polling rate : 20 ms (50Hz)
     Serial number: D853A210
     Model ID:      B35B408A0000
     Unit ID:       D853A210
        Bootloader: BL1 08.00.B0011
          Firmware: MPK 12.00.B0011
             Other: 
     The power switch is located on the edge of top right corner.
     Supports 33 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BL1 08.00.B0011 00008169E8BB
            Firmware: Firmware MPK 12.00.B0011 408A8169E8BB
            Firmware: Other   
            Unit ID: D853A210  Model ID: B35B408A0000  Transport IDs: {'btleid': 'B35B', 'wpid': '408A'}
         3: DEVICE NAME            {0005}   
            Name: MX Keys Wireless Keyboard
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: DEVICE FRIENDLY NAME   {0007}   
         7: BATTERY STATUS         {1000}   
            Battery: 100%, discharging, next level 50%.
         8: REPROG CONTROLS V4     {1B04}   
            Key/Button Diversion: {'209': 0, '210': 0, '211': 0, '199': 1, '200': 1, '224': 0, '225': 0, '110': 0, '226': 0, '227': 0, '228': 0, '229': 0, '230': 0, '231': 0, '232': 0, '233': 0, '10': 0, '191': 0, '234': 0, '111': 0, '236': 0, '235': 0}
         9: CHANGE HOST            {1814}   
            Change Host: 3:DESKTOP-BMCVF52
        10: HOSTS INFO             {1815}   
            Host 0 (paired): ANTIX-PC
            Host 1 (unpaired): 
            Host 2 (paired): DESKTOP-BMCVF52
        11: BACKLIGHT2             {1982}   
            Backlight: True
        12: K375S FN INVERSION     {40A3}   
            Сменить поведение Fx: False
        13: ENCRYPTION             {4100}   
        14: LOCK KEY STATE         {4220}   
        15: KEYBOARD DISABLE KEYS  {4521}   
            Disable keys: {'1': False, '2': False, '4': False, '8': False, '16': False}
        16: MULTIPLATFORM          {4531}   
            Set OS: Windows
        17: DFUCONTROL SIGNED      {00C2}   
        18: DEVICE RESET           {1802}   internal, hidden
        19: unknown:1803           {1803}   internal, hidden
        20: CONFIG DEVICE PROPS    {1806}   internal, hidden
        21: unknown:1813           {1813}   internal, hidden
        22: OOBSTATE               {1805}   internal, hidden
        23: unknown:1830           {1830}   internal, hidden
        24: unknown:1890           {1890}   internal, hidden
        25: unknown:1891           {1891}   internal, hidden
        26: unknown:18A1           {18A1}   internal, hidden
        27: unknown:1DF3           {1DF3}   internal, hidden
        28: unknown:1E00           {1E00}   hidden
        29: unknown:1EB0           {1EB0}   internal, hidden
        30: unknown:1861           {1861}   internal, hidden
        31: unknown:1A20           {1A20}   internal, hidden
        32: unknown:18B0           {18B0}   internal, hidden
     Has 24 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         2: Host Switch Channel 3     , default: HostSwitch Channel 3        => HostSwitch Channel 3      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         3: Brightness Down           , default: Brightness Down             => Brightness Down           
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:1, group:0, group mask:empty
             reporting: diverted
         4: Brightness Up             , default: Brightness Up               => Brightness Up             
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:2, group:0, group mask:empty
             reporting: diverted
         5: Mission Control/Task View , default: Mission Control/Task View   => Mission Control/Task View 
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:3, group:0, group mask:empty
             reporting: default
         6: Dashboard Launchpad/Action Center, default: Dashboard Launchpad/Action Center => Dashboard Launchpad/Action Center
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:4, group:0, group mask:empty
             reporting: default
         7: Show Desktop              , default: Show Desktop                => Show Desktop              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:5, group:0, group mask:empty
             reporting: default
         8: Backlight Down            , default: Backlight Down              => Backlight Down            
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:6, group:0, group mask:empty
             reporting: default
         9: Backlight Up              , default: Backlight Up                => Backlight Up              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:7, group:0, group mask:empty
             reporting: default
        10: Previous Fn               , default: Previous                    => Previous                  
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:8, group:0, group mask:empty
             reporting: default
        11: Play/Pause Fn             , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:9, group:0, group mask:empty
             reporting: default
        12: Next Fn                   , default: Next                        => Next                      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:10, group:0, group mask:empty
             reporting: default
        13: Mute Fn                   , default: Mute                        => Mute                      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:11, group:0, group mask:empty
             reporting: default
        14: Volume Down Fn            , default: Volume Down                 => Volume Down               
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:12, group:0, group mask:empty
             reporting: default
        15: Volume Up Fn              , default: Volume Up                   => Volume Up                 
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        16: Calculator                , default: Calculator                  => Calculator                
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        17: Screen Capture/Print Screen, default: Screen Capture              => Screen Capture            
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        18: App Contextual Menu/Right Click, default: Right Click/App Contextual Menu => Right Click/App Contextual Menu
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        19: Lock PC                   , default: WindowsLock                 => WindowsLock               
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        20: Left Arrow                , default: Keyboard Left Arrow         => Keyboard Left Arrow       
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        21: Right Arrow               , default: Keyboard Right Arrow        => Keyboard Right Arrow      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        22: F Lock                    , default: Do Nothing One              => Do Nothing One            
             is FN, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        23: unknown:0034              , default: Do Nothing One              => Do Nothing One            
             nonstandard, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
     Battery: 100%, discharging, next level 50%.

  2: MX Vertical Wireless Mouse
     Device path  : /dev/hidraw2
     WPID         : 407B
     Codename     : MX Vertical
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: D8F09E6A
     Model ID:      B020407BC08A
     Unit ID:       B7847ED4
        Bootloader: BOT 78.00.B0009
          Firmware: MPM 16.00.B0009
             Other: 
     Supports 34 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 78.00.B0009 AAE28E5B17FF
            Firmware: Firmware MPM 16.00.B0009 407B8E5B17FF
            Firmware: Other   
            Unit ID: B7847ED4  Model ID: B020407BC08A  Transport IDs: {'btleid': 'B020', 'wpid': '407B', 'usbid': 'C08A'}
         3: DEVICE NAME            {0005}   
            Name: MX Vertical Advanced Ergonomic Mouse
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: CRYPTO ID              {0021}   
         7: DEVICE FRIENDLY NAME   {0007}   
         8: BATTERY STATUS         {1000}   
            Battery: 90%, discharging, next level 50%.
         9: unknown:1002           {1002}   
        10: REPROG CONTROLS V4     {1B04}   
            Key/Button Actions: {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '253': 253}
            Key/Button Diversion: {'82': 0, '83': 0, '86': 0, '253': 1, '215': 0}
        11: PERSISTENT REMAPPABLE ACTION {1C00}   
        12: CHANGE HOST            {1814}   
            Change Host: 3:DESKTOP-BMCVF52
        13: HOSTS INFO             {1815}   
            Host 0 (unpaired): ANTIX-PC
            Host 1 (unpaired): 
            Host 2 (unpaired): DESKTOP-BMCVF52
        14: unknown:2250           {2250}   
        15: unknown:18B1           {18B1}   internal, hidden
        16: VERTICAL SCROLLING     {2100}   
            Roller type: standard
            Ratchet per turn: 24
            Scroll lines: 0
        17: LOWRES WHEEL           {2130}   
            Wheel Reports: HID
            Scroll Wheel HID++ Scrolling: False
        18: ADJUSTABLE DPI         {2201}   
            Чувствительность (DPI): 1000
        19: DEVICE RESET           {1802}   internal, hidden
        20: unknown:1803           {1803}   internal, hidden
        21: CONFIG DEVICE PROPS    {1806}   internal, hidden
        22: unknown:1813           {1813}   internal, hidden
        23: OOBSTATE               {1805}   internal, hidden
        24: unknown:1830           {1830}   internal, hidden
        25: unknown:1890           {1890}   internal, hidden
        26: unknown:1891           {1891}   internal, hidden
        27: unknown:18A1           {18A1}   internal, hidden
        28: unknown:1DF3           {1DF3}   internal, hidden
        29: unknown:1E00           {1E00}   hidden
        30: unknown:1EB0           {1EB0}   internal, hidden
        31: unknown:1E22           {1E22}   internal, hidden
        32: unknown:1861           {1861}   internal, hidden
        33: unknown:18C0           {18C0}   internal, hidden
     Has 7 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, reprogrammable, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, reprogrammable, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, persistently divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, persistently divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, persistently divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: DPI Switch                , default: DPI Switch                  => DPI Switch                
             mse, reprogrammable, divertable, persistently divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: diverted
         6: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:3, group mask:empty
             reporting: default
     Battery: 90%, discharging, next level 50%.
```
</details>

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Would be nice to be able to configure simple mouse gestures (up/down/left/right) via rules editor in Solaar like you can in Logitech Options.

**Describe alternatives you've considered**
https://github.com/PixlOne/logiops can configure gestures (but w/o UI) for mouses that have separate special gesture on/off button. But not for mouses that don't have this button like mx vertical. Logitech Options uses Fn button from keyboard (e.g. mx keys). 
(As a side note - when gesture button is pressed mouse pointer freezes, which is convenient/safe.)

Anyway solutions like easystroke or built-in kde gestures do not allow to use keyboard as an initiator of mouse gesture (at least not in a way like Logitech Options does).

Thanks for hearing me out.

**Additional context**
logitech-options-custom-gesture-preset
duolink

### PR DESCRIPTION
**Pull request by pfps**
Fixes #1108

Instead of having mouse gestures be a boolean setting allow picking a key to trigger mouse gestures.

### CODE REVIEW

**Comment by pfps** [comment]
@barolo @sk8geek @mschilli87  Testing of this PR would be useful.

Can be tested with any mouse that has a reprogrammable key that has the divert and raw XY flags.

To test start the Solaar GUI and look for the Mouse Gestures setting for the mouse.  Change the value to one of the keys shown.  Depress the key and move the mouse.  The mouse pointer should not move and the key should not perform its normal action (because movement and key are being diverted to create a mouse gesture notification).  Change the value to Off.   Depress the key and move the mouse.  The mouse pointer should move and the key should perform its normal action.

You can write Solaar rules that trigger on these mouse gestures.  The mouse-left, mouse-right, mouse-up, and mouse-down tests will trigger on a mouse gesture that moves more than about 1cm in the appropriate direction.


To download and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1148, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1148/head:pull_1148
git checkout pull_1148
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1148
git fetch origin pull/1148/head
git reset --hard FETCH_HEAD
```

**Comment by barolo** [comment]
I'm trying to test it with MX Master 2S, the gesture button is the one in the base under thumb, pressing it freezes cursor.

image

It has only one function "App Switch"
I have no idea how to assign direction to it via rules editor, I'm thoroughly confused by it XD

**Comment by pfps** [comment]
The cursor-freezing is what should happen, just as happens with Logitech software.

The way you make a mouse gesture is push the button, move the mouse (cursor doesn't move), and release the button.  While the button is down the total physical mouse movement is computed and a mouse cursor notification is sent to the Solaar rule system.  If you don't have a rule that triggers on mouse movements you won't see anything happen at all.  The mouse-left rule test triggers if the mouse is moved left more than about 1cm.  Similarly for other directions.

**Comment by pfps** [comment]
A good action to check the setting is to execute notify-send with the direction as argument.   That is, if you have notify-send installed.

**Comment by barolo** [comment]
Gonna play with it in the evening. I am a bit confused by the names too, 'App Switcher Gesture' ,' Virtual Gesture Button', the virtual thingy is the actual button, correct?

**Comment by pfps** [comment]
The names are direct from Logitech.  :-)

It would be possible to change the names, particularly App Switch Gesture.  Virtual Gesture Button is a virtual "button", a way for software to trigger changes to the device, and shouldn't be showing up in the GUI.

**Comment by pfps** [comment]
I change App_Switch_Gesture to something better and removed virtual keys from the diversion setting.

**Comment by antonsoroko** [comment]
@pfps 

Thank you very much.

I did some tests and looks like gestures are working well. 

I used `DPI Switch` button:
image

Rules:
image

the only thing is missing is 
>And one of the rules should be for no-op (no movement) so it can be assigned to the original button action (or any action).

so user will not loose 1 button on the mouse that have only few buttons, like mine MX Vertical.

because if after gestures rules i add 

image

then if i do gesture it also does action for the button.

(if i add it before gestures rules - gestures does not work).

so i think we need a `Test` called like `mouse-noop` so it can be used instead of `Key`. (like `direction: "None";` in logiops)


also i guess it would be nice to have "change dpi" action in rules (like `type: "CycleDPI"; dpis: [800, 1200, 1600];` in logiops)

**Comment by pfps** [comment]
For the DPI sliding setting, just clicking switches with the last DPI value set by sliding.  This is done by Solaar.

For a button diverted to mouse gestures I don't think that there is any way to trigger the action that the button would do if not diverted in all cases.  However, a mouse-noop test would allow users to program some action for just clicking the button if the action can be done by a Solaar rule.   This might be enough when using something like the back button, but of course it wouldn't be adequate for a button that had a drag effect implemented in the Linux input drivers.

**Comment by pfps** [comment]
OK.   I added the mouse-noop test and made a rule that sends a button8 (back button) mouse click on mouse-noop.  That gets most of the back button functionality so you could use the Vertical's back button for gestures and still have part of the button's regular functionality.

**Comment by antonsoroko** [comment]
>For the DPI sliding setting, just clicking switches with the last DPI value set by sliding. 

sorry, i did not really understand what you wanted to say.

just to clarify, what i meant is: to have an original action of `DPI Switch` button as possible action in solaar rules. so like in your example with `back` it also will be possible to do the same for `DPI Switch`.

i personally don't use `DPI Switch` but i just assumed that some people would like to use this button as a gesture activation button but also at the same time as original `DPI Switch`.

P.S.  actually I don't really understand how  `DPI Switch` works in solaar since there is no any pop-up or at least reflection of new DPI value in UI. Physically i can feel that it changes to some higher value (one time), but without any cycling (not going back to smaller value), even with sliding option enabled, so i just remapped it to some "keys shortcut".

**Comment by antonsoroko** [comment]
i tested new changes, mouse-noop works good.

btw, it there a way to understand that `button8` is `back`?
maybe `DPI Switch` is also some `buttonN` so in this case maybe there is no need for special `DPI Switch` action.

**Comment by pfps** [comment]
Linux (X11) button numbers are listed in several places, including http://xahlee.info/linux/linux_x11_mouse_button_number.html

The normal action of the DPI switch (if any) is carried out on the mouse itself.  As far as I can tell, no input is generated.  I also don't see any effect from just clicking the button when DPI sliding is off.

**Comment by antonsoroko** [comment]
yeah, i don't see in in `xev` for example (unlike `back`)

with solaar turned off, i can see in `bin/solaar show 2 | grep -i DPI` output that dpi button actually works, but it only changes between last saved value and max value (1000 and 1600 in my case).
and with solaar on - it also works (w/ and w/o sliding) - but also in the same manner (switch between last saved and max).
so i just was not able to feel the difference between 1000 and 1600 :-)

but i guess for sliding it should be more than just 2 values. maybe a bug?

anyway, back to the topic:

so i guess it is not possible to use "click" `DPI Switch` in rules. then i guess 
> to have an original action of DPI Switch button as possible action in solaar rules. so like in your example with back it also will be possible to do the same for DPI Switch.
>(like type: "CycleDPI"; dpis: [800, 1200, 1600]; in logiops)

is the only way to get back functionality of the `DPI Switch` button.
but since i don't really use this functionality, i will leave it to you to decide if it is a valuable feature :-)

thank you.

**Pull request merged**
