### PR TITLE
Update header of readme

### PR DESCRIPTION
**Pull request by MattHag**
Related #2328

### CODE REVIEW

**Comment by pfps** [comment]
This PR changes docs/index.md.  It would be better to have a separate README.md, which would be shorter, and reference index.md.   As well, HTML should be kept to the very minimum as this is a markdown document.

**Comment by pfps** [comment]
See #2338
I copied your changes and made a lot of modifications.   There is a problem with getting two images on the same line.  Maybe using more HTML is the solution.

**Comment by MattHag** [comment]
> See #2338 I copied your changes and made a lot of modifications. There is a problem with getting two images on the same line. Maybe using more HTML is the solution.

The need a wrapping element it seems.

**Comment by pfps** [comment]
Yeah #2339 appears to have fixed things.

**Pull request closed without merging**
