### PR TITLE
Setup automated macOS tests using GitHub action

### PR DESCRIPTION
**Pull request by MattHag**
Related #1244

### CODE REVIEW

**Review by pfps — APPROVED** [review]
Looks good.

**Comment by pfps** [comment]
Is it reasonable to set up a semi-automatic build process for MacOS?

**Comment by MattHag** [comment]
Yes, that's what is implicitly included here.

**Comment by pfps** [comment]
Can that be put in something like a make file for MacOS?

**Comment by MattHag** [comment]
Yes, both Linux and macOS commands should be moved to the Makefile in a later change. Thus, they can be reused locally.

**Comment by pfps** [comment]
OK, I'll pull this in now.

**Comment by markopy** [comment]
@MattHag I noticed you install and start dbus via homebrew in this PR. Is that actually needed? Since we removed dbus-python Solaar isn't actually using anything dbus, right?

**Comment by MattHag** [comment]
Yes it will be at least neceaary for the local setup.

**Comment by markopy** [comment]
What is it needed for though? dbus seems to only be used for listening to UPower events on Linux which doesn't exist on macos so I see no need for installing dbus on macos?

**Comment by markopy** [comment]
I would guess those error you saw messages no longer appear now that we have excluded dbus-python from being installed on macos. The only warning you should get is `failed to register suspend/resume callbacks` which would be expected since there is no code to implement suspend/resume detection for macos at the moment.

**Comment by MattHag** [comment]
Okay, then feel free to remove it.

**Comment by markopy** [comment]
It's your PR man. I'm just helping you out because @pfps asked for it. Nowhere in the instructions for macos does it say to install dbus so you shouldn't have added that in the first place.

**Pull request merged**
