### PR TITLE
Fix and add Mint icon theme battery level, keeping compatibility with regular icons

### LINKED ISSUE #84: Status icon could be conflated with that of system power.
Currently, Solaar appears to use the some generic battery icon as is used by the systems default power indicator. I'd suggest switching to the gpm/xfpm-mouse-\* icons in stead, to avoid conflating the two. I realise of course that solaar caters to keyboards and other devices besides mouses/mice_, but I would imagine that there are a hell of a lot more wireless logitech mouses/mice_ out there than keyboards, etc. Besides, gpm/xfpm-mouse-\* looks a damn sight better than gpm/xfpm-keyboard-\* (at least with respect to Ubuntu's default icon theme).

*For the love of atheismo, which is it?! ;-)

P.S.: Thank you for taking the time to develop this. This is one functionality that I have sorely missed since switching to linux some years ago. It's long overdue.

### LINKED ISSUE #145: Solaar did not detect icon theme
Solaar installed on my arch system with kde did not detect my oxygen theme.

Solaar version: 0.9.2

Here is the log of solaar started with debugging from the cli

$ solaar -ddd
15:57:47,404     INFO [MainThread] root: language de_DE (UTF-8), translations path None
15:57:47,409     INFO [MainThread] solaar.ui: application /io/github/pwr/solaar, registered True
15:57:47,412    DEBUG [MainThread] solaar.ui.icons: sys.path[0] = /usr/bin
15:57:47,412    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/icons
15:57:47,412    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
15:57:47,412    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/teissler/.local/share/solaar/icons
15:57:47,412    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
15:57:47,412    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
15:57:47,413    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/local/share/solaar/icons
15:57:47,413    DEBUG [MainThread] solaar.ui.icons: icon theme paths: ['/usr/share/solaar/icons', '/usr/share/solaar/icons', '/usr/share/solaar/icons', '/home/teissler/.local/share/icons', '/home/teissler/.icons', '/usr/share/icons', '/usr/share/icons', '/usr/local/share/icons', '/usr/share/pixmaps', '/usr/share/pixmaps', '/usr/local/share/pixmaps']
15:57:47,417    DEBUG [MainThread] solaar.ui.icons: detected icon sets: gpm False, oxygen False, gnome False, elementary False
15:57:47,417  WARNING [MainThread] solaar.ui.icons: failed to detect a known icon set
15:57:47,447    ERROR [MainThread] root: Could not find any typelib for AppIndicator3
15:57:47,447     INFO [MainThread] solaar.ui.tray: using StatusIcon
15:57:47,447     INFO [MainThread] solaar.ui.notify: starting desktop notifications
15:57:47,479  WARNING [MainThread] solaar.upower: failed to register suspend/resume callbacks
15:57:47,479     INFO [MainThread] solaar.listener: starting receiver listening threads

$ ls -al /usr/share/icons/oxygen/48x48/status/battery-*
-rw-r--r-- 1 root root 1784 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-040.png
-rw-r--r-- 1 root root 1929 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-060.png
-rw-r--r-- 1 root root 2065 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-080.png
-rw-r--r-- 1 root root 2056 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-100.png
-rw-r--r-- 1 root root 1676 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-caution.png
-rw-r--r-- 1 root root 3041 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-charging-040.png
-rw-r--r-- 1 root root 3227 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-charging-060.png
-rw-r--r-- 1 root root 3374 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-charging-080.png
-rw-r--r-- 1 root root 2973 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-charging-caution.png
-rw-r--r-- 1 root root 3014 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-charging-low.png
-rw-r--r-- 1 root root 3399 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-charging.png
-rw-r--r-- 1 root root 1671 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-low.png
-rw-r--r-- 1 root root 2813 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-missing.png

If you need more informations just let me know.

### LINKED ISSUE #324: Missing system-tray icon on Wayland (Fedora 25)
With Fedora's default wayland desktop, Solaar's system try icon is not visible, hence the app can't be invoked once it was launched

This is with the latest git code. I see some warnings when launching from a terminal

> solaar
/usr/lib/python2.7/site-packages/solaar/gtk.py:34: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
/usr/lib/python2.7/site-packages/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/site-packages/solaar/ui/tray.py:148: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3

### LINKED ISSUE #369: Linux Mint System Tray Issue
I am currently on Linux Mint 18.2 Cinnamon and am having issues with Solaar inconsistently showing up in the System Tray. When I reboot, sometimes the icon is visible and sometimes it is invisible (if I click over the area, "Unifying Receiver" applet options show up, but not the tray icon).

In addition, I have a paired mouse and keyboard, which always function appropriately. However, when I open Solaar, sometimes it may indicate 1 or 0 paired devices and the left window pane may show "Unifying Receiver" without any devices shown below.

I am new to Linux so any help would be greatly appreciated.

solaar_002

### LINKED ISSUE #435: MX Master 2S low in power notification
Hello!

I've received notification about 10% of MX Master 2S mouse power, but in GUI I see 20%.

Something is incorrect.

image

### LINKED ISSUE #456: Wrong icons in GNOME 3
Adwaita (full default): 

image

[Materia](https://github.com/nana-4/materia-theme) + [Paper icons](https://github.com/snwh/paper-icon-theme):

image

It was light-gray, as others. 

I think it's not theme issue because it's black with any theme, even default.

After upgrade from `r961.59b7285` to `r985.b852903`.

### PR DESCRIPTION
**Pull request by rgarcia7**
Now you can use Mint icons, that provide a nice looking icon for keyboards, mice and generic periferals

And if is not Mint, it uses the default ones

Fixes #456 
Fixes #435 
Fixes #369 
Fixes #324 
Fixes #145 
Fixes #84 
Mint Example:
Window:
window-example

Taskbar:
task-bar-example

Mouse Icons:
mouse-battery-empty
mouse-battery-medium
mouse-battery-full

Keyboard Icons:
keyboard-battery-empty
keyboard-battery-medium
keyboard-battery-full

When checking for icons, current Solaar version only takes into account if the icon file exists, but not if it was loaded with the current theme

The solution:
This PR, adds a way to check the current icon theme, and if the query fails or is not Mint, it loads the common icons available to all themes and distros

### CODE REVIEW

**Comment by FFY00** [comment]
```
No such schema “org.cinnamon.desktop.interface”
No such schema “org.cinnamon.desktop.interface”
Traceback (most recent call last):
  File "/home/anubis/git/Solaar/lib/solaar/ui/__init__.py", line 100, in _startup
    window.init()
  File "/home/anubis/git/Solaar/lib/solaar/ui/window.py", line 732, in init
    Gtk.Window.set_default_icon_from_file(_icons.icon_file(NAME.lower()))
  File "/home/anubis/git/Solaar/lib/solaar/ui/icons.py", line 261, in icon_file
    _init_icon_paths()
  File "/home/anubis/git/Solaar/lib/solaar/ui/icons.py", line 108, in _init_icon_paths
    _current_icon_theme = subprocess.check_output('gsettings get org.cinnamon.desktop.interface icon-theme',shell=True)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'gsettings get org.cinnamon.desktop.interface icon-theme' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/anubis/git/Solaar/lib/solaar/ui/__init__.py", line 111, in _activate
    app.add_window(window._window)
TypeError: Argument 1 does not allow None as a value
```

Please fix this on non-cinamon environments. I am using i3-gaps fwiw.

**Comment by FFY00** [comment]
Can you revisit this?

**Comment by FFY00** [comment]
Closing. Feel free to open again if you want.

**Comment by rgarcia7** [comment]
Hi @FFY00 , let me take a look
I was on holidays and had to complete some work on my job

Can you describe which distribution and desktop environment are you using?
I will try to create a Virtual Machine to test the config, as I only have Linux Mint physically to test
Regards

**Comment by pfps** [comment]
Why not use the same method as is done for device types?  The list of icon names is generated without regards to which theme is current in some desirability order and then each is looked up in the current theme.   With theme cache files this should be relatively fast.

**Comment by raveit65** [comment]
Yes, application crashed if cinnamon gsettings keys aren't installed.
And can you add a check for Mate desktop please?
`org.mate.interface icon-theme`
All Mate installations in distros except linunxmint are using mate-icon-theme.
With current version of solaar i see only unwanted symbolic icons from `_has_mint_icons` check with Mate in fedora.

**Pull request closed without merging**
