### PR TITLE
Refactor receiver

### PR DESCRIPTION
**Pull request by MattHag**

### CODE REVIEW

**Comment by pfps** [comment]
I see that this is an extension of #2355.   Perhaps #2355 could have been removed when this PR was created.

**Comment by MattHag** [comment]
Now everything is cleaned up

**Comment by pfps** [comment]
Excellent.

**Comment by pfps** [comment]
There are two problems with subclassing Receiver that I see.  First, some Logitech receivers are not known to Solaar.   It is unclear whether any of these actually use the HID++ protocol and thus are suitable for use in Solaar at all.  Second, the behaviour of older receivers are not completely known.

The first could be solved, I suppose, by splitting off code for the minimal feature set that Solaar needs.  This would eliminate the gathering of some information that is useful but not completely necessary.  The second could be then addressed by judicious augmentations that do the minimum of probing.  

The easiest cases are for Unifying and Bolt receivers.  Their behaviour is well known and reasonably documented.  What's good skeleton code to do this conditional creation?

One strange aspect of all this is that there is information about important parts of receiver behaviour, but it is only accessible in information associated with connected devices and seems divorced from the receiver itself although it seems certain that a particular receiver would only support one behaviour style here.   So, for example, it would be weird that a Bolt receiver supports Unifying pairing registers.   Right now Solaar ignores this information but ideally it could be used to augment the information known about the receiver and reducing the number of messages sent to receivers that now only result in error responses.

**Comment by MattHag** [comment]
I think we can keep all the functionality, including a default implementation. The interface for all subclasses needs to be the same, but some functions can just do nothing. That's how I think this could be implemented. I see this as a refactoring task, where the behavior should not change. Problems will be identified during implementation, just start this and try it out.

During [testing of _product_information_](https://github.com/pwr-Solaar/Solaar/issues/1097) I have seen, that the Lightspeed receiver has no _device_kind_ entry and seems to act as _unknown_. Is this supposed to be like that?

Getting rid of dictionaries, namedtuples and using dataclasses is another goal for me and uniform data helps with that.

**Comment by pfps** [comment]
A potential default implementation is to do what is being done now, so that the setup is very defensive.  Subclasses could be optimized to not do things that aren't  necessary for that kind of receiver.   I'm not keen on this solution though.

**Comment by pfps** [comment]
The entry for Lighspeed Receivers is  missing the receiver kind (not device kind).  I'm putting in a PR for this.

**Pull request merged**
