### PR TITLE
diversion: implement pressed and released action on Key condition

### PR DESCRIPTION
**Pull request by nishanthkarthik**
- Track `key_up` key in addition to `key_down`
- Support `pressed` or `released` action in `Key` condition
- Add radio button to KeyUI to represent `pressed` or `released`

#### Use case

Push to talk with a mouse button: Bind `pressed` and `released` events to microphone unmute and mute commands respectively

Implements #1186

### CODE REVIEW

**Comment by nishanthkarthik** [comment]
**UI**

image

**Comment by pfps** [comment]
When this is done it will probably go in as one commit, so you probably should just have one commit and force-push it.

**Comment by pfps** [comment]
Looks good except that there needs to be code for key_up for G keys.  We can't test this but it'll be better than not implementing something that is documented.

**Comment by nishanthkarthik** [comment]
Will do.

---

On an unrelated note, the G keys support in `process_notification` method supports 8 keys. I tried to look up more on how many G keys are present. Different keyboards seem to have different ways of decoding the bytes? Do you know of an official documentation you look these up on?

> Another example are gaming keyboards, such as the Logitech G15 Gaming
keyboard, which has 18 "G"aming keys labeled "G1" to G18"

https://patchwork.kernel.org/project/linux-input/patch/20190821205937.4929-2-hdegoede@redhat.com/

```c
/* G1 - G18 */
for (i = 0; i < 18; i++) {
    val = data[i / 8 + 1] & (1 << (i % 8));
    input_report_key(g15->input, KEY_MACRO1 + i, val);
}
```

https://patchwork.kernel.org/project/linux-input/patch/20190821205937.4929-6-hdegoede@redhat.com/

```c
/* G1 - G6 */
for (i = 0; i < 6; i++) {
    val = data[i + 1] & (1 << i);
    input_report_key(g15->input, KEY_MACRO1 + i, val);
}
/* G7 - G12 */
for (i = 0; i < 6; i++) {
    val = data[i + 2] & (1 << i);
    input_report_key(g15->input, KEY_MACRO7 + i, val);
}
/* G13 - G17 */
for (i = 0; i < 5; i++) {
    val = data[i + 1] & (4 << i);
    input_report_key(g15->input, KEY_MACRO13 + i, val);
}
```

https://patchwork.kernel.org/project/linux-input/patch/20190821205937.4929-3-hdegoede@redhat.com/

**Comment by pfps** [comment]
The code has multiple problems.   I have documentation on the feature, but I can't share it.  The field is 32 bits, not 8.  The code in special_keys.py is also not even correct for 8 G keys.  The change in special_keys.py is to change from 7 to 33 in
```
for i in range(1, 7):  # add in G keys - these are not really Logitech Controls
    CONTROL[0x1000 + i] = 'G' + str(i)
```

My guess is that this was done for a 6-key gaming keyboard.

The code in diversion.py needs to extract 32 bits, not 8.  But the ordering is a bit weird - the first byte is keys 1-8, etc., the low-order bit in each byte is the lowest key number of the group of keys.  So you can't just extract a 32-bit field and easily shift to get the correct bit.  Perhaps the best way to go is to extract four bytes and then shift within the correct byte.

**Comment by pfps** [comment]
I think the first code snippet you included has the correct logic (except that you have to add one to get the key name).

**Comment by nishanthkarthik** [comment]
Thanks for the detailed explanation :)

Do you have any other comments on the code changes?

**Comment by nishanthkarthik** [comment]
Would you like me to rebase on master and force push?

**Comment by pfps** [comment]
Yes please

**Comment by nishanthkarthik** [comment]
Rebased the branch on master. Can you please review again?

**Comment by pfps** [comment]
My earlier review had a comment that needs to be adressed.  Otherwise a key test can make Solaar think that an action was executed and thus not run any more rules.

**Comment by nishanthkarthik** [comment]
Sorry, my bad. I missed that. 

Is it this one

> Looks good except that there needs to be code for key_up for G keys. We can't test this but it'll be better than not implementing something that is documented.

or this one?

>  Perhaps the best way to go is to extract four bytes and then shift within the correct byte.

I implemented key_up for G keys

**Comment by nishanthkarthik** [comment]
Does the reading of bits in diversion.py look correct to you?

**Comment by pfps** [comment]
Oops, I forgot about those.   The problem that I am running into is that there is a comparison in the execute function and that can return None, which has a special meaning.  So it needs to be wrapped in a bool(...)

**Comment by pfps** [comment]
The expanded G-key code looks good.

**Comment by nishanthkarthik** [comment]
e973181abbb05a4b8ac716a90f5797f93be39e23 is the change you are looking for, right?

**Review by pfps — APPROVED** [review]
Looks good now.

**Pull request merged**
