### PR TITLE
Added Norwegian Nynorsk translation

### PR DESCRIPTION
**Pull request by jeblad**
This is a translation for the minor Norwegian language form “Nynorsk”, used by about half a million Norwegians.

### CODE REVIEW

**Comment by pfps** [comment]
This PR also has the Swedish translation changes.

**Comment by jeblad** [comment]
Yes, not sure why…

**Comment by pfps** [comment]
If the inclusion is unintended it needs to be removed.
I think you should be able to copy the Swedish translation from the master branch to a different file, checkout your translation branch, and copy the master Swedish translation on top of the changed Swedish translation.  Then amend your commit and force push it.

**Comment by pfps** [comment]
You don't need to update your branch if it is out of date.  That just adds a mostly useless merge commit.

**Comment by jeblad** [comment]
I'll open new pull requests later.

**Pull request closed without merging**
