### PR TITLE
settings: add crown diversion setting

### PR DESCRIPTION
**Pull request by pfps**
Addresses #504

### CODE REVIEW

**Comment by barolo** [comment]
I have the button now, for diversion. What's it supossed to do?

**Comment by pfps** [comment]
Well, nothing by itself, but this provides a good way to divert the crown so that prefiks code can then handle the HID++ messages.

**Comment by barolo** [comment]
Ah, gotcha I've tested **prefiks's** daemon and it works nicely after fixing some bugs, basicaly giving 5 bindings per app plus operation mode switch, which is really really nice.

**Comment by pfps** [comment]
Part of diversion processing PR.

**Pull request closed without merging**
