### PR TITLE
Translation for Norwegian Bokmål

### PR DESCRIPTION
**Pull request by jeblad**
Note that I have not been able to run Solaar with this translation, due to some unrelated error.

### CODE REVIEW

**Comment by pfps** [comment]
What error?

**Comment by jeblad** [comment]
Unrelated to this translation.

**Comment by pfps** [comment]
It is something that needs to be fixed in Solaar?

**Comment by jeblad** [comment]
It is an unrelated local problem, but it blocks final verification by using the translation.

**Comment by jeblad** [comment]
Manually verified in Ubuntu 20.04 LTS.

**Comment by jeblad** [comment]
Should be fixed now. As soon as it is merged I'll take a look on another Scandinavian language.

**Comment by pfps** [comment]
I'm planning on setting up release 1.0.3 this weekend.  If you are going to have another translation ready about then, I'll wait to include it in the release.

**Pull request merged**
