### PR TITLE
better handling of icon search paths and better icon handling

### PR DESCRIPTION
**Pull request by pfps**
Only add one path to theme paths because all the extra icons are in one directory.
Don't use a :-joined list of paths in appindicator.

Can be tested by anyone.  Check that icons show up correctly both in the main window and in the tray, particularly the solaar icons.

### CODE REVIEW

**Comment by pfps** [comment]
@barolo @sk8geek @mschilli87 Can you please test this PR?

To test, run Solaar and check whether the tray and other icons are reasonable.


To download and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1129, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1129/head:pull_1129
git checkout pull_1129
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1129
git fetch origin pull/1129/head
git reset --hard FETCH_HEAD
```

**Comment by sk8geek** [comment]
Hi, icons look fine for me in Fedora 33 :-)

**Comment by pfps** [comment]
@sk8geek Excellent.  Which window manager do you use?  Also, when you upgrade to F34 please checkout out this PR again if you are not already running with it.

**Comment by sk8geek** [comment]
Hi, Gnome, and yep, will do.

**Comment by pfps** [comment]
@sk8geek What, if anything, did you have to do to get a system tray under Gnome?

**Comment by sk8geek** [comment]
@pfps Hi Peter, not sure what you mean by system tray. I see that I have `solaar.desktop` in `/usr/share/applications` so perhaps I just copied that from the distribution?

**Comment by pfps** [comment]
The system tray, a.k.a., status indicator, is the area where the Solaar icon appears, almost certainly along with other icons, e.g., for the power manager and bluetooth device manager.  There is likely to be a specific program managing that part of the screen.   (In XFCE it is a panel plugin, but I'm not sure whether there is a panel in Gnome.)

I think that in Gnome 4 the package you need to install is gnome-shell-extension-appindicator but maybe there is some other package in other versions of Gnome.

**Comment by sk8geek** [comment]
Oh, right, Solaar doesn't appear there. I get notifications about devices powering on (which frankly are rather annoying). Gnome is 3.38.5.

**Comment by pfps** [comment]
@sk8geek 
So how do you open up Solaar once you have closed the main window?  Or maybe you don't ever close the main window?

**Comment by sk8geek** [comment]
Start key and start typing Solar 😀

**Comment by pfps** [comment]
@sk8geek Hah!  I hadn't thought of doing that.

**Pull request merged**
