### PR TITLE
Update about.py to bump copyright years

### PR DESCRIPTION
**Pull request by alxndr13**
Update Copyright Timeframe

### CODE REVIEW

**Review by pfps — COMMENTED** [review]
Daniel is not participating in the effort, so some other copyright line is probably better.  What is the accepted practice in this case?

**Comment by pfps** [comment]
In https://www.linuxfoundation.org/en/blog/copyright-notices-in-open-source-software-projects/ there are suggestions to use something like "Copyright Contributors to the Solaar project" and to not change existing copyright notices.   This leads to something like
```
Copyright (C) 2012-2013  Daniel Pavel 
Revisions Copyright (C) Contributors to the Solaar project.
```
and
```
     about.set_copyright('© 2012-2021 Daniel Pavel and contributors to the Solaar project')
```

**Comment by alxndr13** [comment]
> ```
>      about.set_copyright('© 2012-2021 Daniel Pavel and contributors to the Solaar project')
> ```

looks good to me. :)

**Comment by pfps** [comment]
OK.  I'll put that in the update for the next release.

**Review by pfps — APPROVED** [review]
Looks good now.

**Pull request merged**
