### PR TITLE
i18n: Updated Norwegian Nynorsk (nn)

### PR DESCRIPTION
**Pull request by jeblad**
Should be merged after the Norwegian Bokmål patch, and will then have a minor conflict in model.py

### CODE REVIEW

**Comment by jeblad** [comment]
The merge conflict should be gone now.

**Review by pfps — APPROVED** [review]
Thanks

**Comment by pfps** [comment]
Hmm.  Github is still showing conflicts.

**Comment by jeblad** [comment]
Shows no conflicts here…

**Comment by pfps** [comment]
Cleared now.  Probably a caching error.

**Pull request merged**
