### PR TITLE
Upgrade theme for GitHub documentation

### LINKED ISSUE #2502: Docs: Switch theme to enable page navigation and search
The documentation on GitHub Pages lacks an overview and navigation structure to find all pages. Furthermore, it is common to have a search.

## Solution
Switch to a common theme with left sidebar for navigation and built-in search like [just-the-docs](https://github.com/just-the-docs/just-the-docs). This theme even supports mermaid for the diagrams.

With that change, the `jekyll` folder should be unified and merged into `docs`.

### PR DESCRIPTION
**Pull request by MattHag**
Fixes #2502

### CODE REVIEW

**Comment by pfps** [comment]
Solaar is licensed under GPL.   There should not be any other license files included.

**Comment by MattHag** [comment]
MIT is already the do whatever you want license, so most themes will use that. That shouldn't be an issue for the documentation theme. Most likely the same license already applies to the current doc theme.

**Comment by MattHag** [comment]
It is. The license only covers the theme, otherwise the whole world would be screwed and nobody could use sphinx or mkdocs with themes in companies.

**Comment by pfps** [comment]
The license file is ambiguous as to what it covers.  It is a free-standing file in a directory where not all of the files should be covered.  What the license covers should be made explicit, either by putting into one or more files, or being explicit about which files it covers.

**Comment by MattHag** [comment]
Used mkdocs for a better documentation, that supports static pages and generation from docstrings.

**Comment by MattHag** [comment]
Solaar has always used an MIT license for the doc creation
https://github.com/jekyll/jekyll/blob/master/LICENSE

**Comment by MattHag** [comment]
> Solaar is licensed under GPL. There should not be any other license files included.

Solaar has always and still uses an MIT license for the doc creation
https://github.com/jekyll/jekyll/blob/master/LICENSE

**Pull request closed without merging**
