### PR TITLE
Show pytest coverage in GitHub CI tests

### PR DESCRIPTION
**Pull request by MattHag**
Related #1097

### CODE REVIEW

**Comment by pfps** [comment]
For right after 1.1.11?

**Comment by MattHag** [comment]
This can be merged right now. Just adds a pytest dependency and outputs more info in GitHub CI tests.

**Comment by pfps** [comment]
Yes, but it won't show anything useful until there are real tests, right?

**Comment by MattHag** [comment]
Yes, it should show that no code is touched by tests and thus 0% coverage is reached on every module.

**Comment by MattHag** [comment]
@pfps This one first

**Pull request merged**
