### PR TITLE
Fix reading and storing DPI in config settings

### LINKED ISSUE #328: Incorrectly commiting DPI value to config.json
Hi,

Let me just start off by saying that I really appreciate your work, Solaar is quite frankly a necessity for anyone using  a Logitech peripheral.

Alright, onto the issue: I believe that Solaar incorrectly writes the dpi information in its config file (that is `~/.config/solaar/config.json`). The auto-generated version looks like this:

```javascript
{
  "4041:ADFAA385": {
    "_name": "Wireless Mouse MX Master",
    "dpi": "1600",
    "smart-shift": 50
  },
  "_version": "0.9.2"
}
```

Note the quotation marks around the dpi value but not around the value for smart-shift. I had an issue whereby Solaar didn't apply the dpi settings on device wake, but removing these quotation marks made it work.

This is using a freshly built version from GitHub, by the way (specifically the `solaar-git` package from the Arch AUR).

Thanks,

### LINKED ISSUE #356: MX Master: DPI value resets to 1000 after turning off mouse / mouse wake
```bash
$ solaar config 1 dpi 800
# dpi
dpi = NamedInt(800, '800')

# turn mouse off and on
$ solaar config 1 dpi
# dpi
#   possible values: one of [ 400, 600, 800, 1000, 1200, 1400, 1600 ], or higher/lower/highest/max/lowest/min
dpi = NamedInt(1000, '1000')

$ cat .config/solaar/config.json
{
  "4060:54420744": {
    "_name": "Wireless Mouse MX Master",
    "dpi": "800",  # unquoting this doesn't help
    "smart-shift": 50
  },
  "_version": "0.9.2"
}
```
Tried also to unquote the DPI value in `config.json` as suggested in #328 to no avail.

Any idea what's going on?

```
$ solaar show
Unifying Receiver
  Device path  : /dev/hidraw4
  USB id       : 046d:c52b
  Serial       : 5562921B
    Firmware   : 24.01.B0023
    Bootloader : 01.08
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=201

  1: Wireless Mouse MX Master
     Codename     : MX Master
     Kind         : mouse
     Wireless PID : 4060
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 54420744
        Bootloader: BOT 18.05.B0018
          Firmware: MPM 11.05.B0018
          Firmware: MPM 11.05.B0018
             Other: 
     The power switch is located on the base.
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
         7: unknown:1806           {1806}   internal, hidden
         8: CHANGE HOST            {1814}   
         9: REPROG CONTROLS V4     {1B04}   
        10: ADJUSTABLE DPI         {2201}   
        11: VERTICAL SCROLLING     {2100}   
        12: SMART SHIFT            {2110}   
        13: HIRES WHEEL            {2121}   
        14: GESTURE 2              {6501}   
        15: DFUCONTROL 2           {00C1}   
        16: unknown:1813           {1813}   internal, hidden
        17: unknown:1830           {1830}   internal, hidden
        18: unknown:1890           {1890}   internal, hidden
        19: unknown:1891           {1891}   internal, hidden
        20: unknown:18A1           {18A1}   internal, hidden
        21: unknown:18C0           {18C0}   internal, hidden
        22: unknown:1DF3           {1DF3}   internal, hidden
        23: unknown:1E00           {1E00}   hidden
        24: unknown:1EB0           {1EB0}   internal, hidden
        25: unknown:1803           {1803}   internal, hidden
        26: unknown:1861           {1861}   internal, hidden
        27: unknown:9000           {9000}   internal, hidden
        28: unknown:9200           {9200}   internal, hidden
        29: unknown:9240           {9240}   internal, hidden
        30: unknown:1805           {1805}   internal, hidden
     Battery: 90%, discharging.
```

### LINKED ISSUE #545: DPI and smart shift values are not stored in the config file (MX Master 2s)
I've set the DPI and the Smart Shift values but when you close solaar and then check `~/.config/solaar/config.json` the values are not written to the config file.

Version: 1.0.1
https://build.opensuse.org/request/show/719864 (I've updated the openSUSE package)

### PR DESCRIPTION
**Pull request by cryptomilk**
Fixes #328
Fixes #356
Fixes #545

### CODE REVIEW

**Comment by Cabbagec** [comment]
Thanks, now it really works!

**Comment by oryband** [comment]
Hi @FFY00. Can we release a new version that includes this fix please?

**Comment by FFY00** [comment]
Yeah, I am just gonna probably wait 1 or 2 days to see if the conflicts in the other PRs are resolved. This way they will also be included in the new release.

**Comment by oryband** [comment]
Thanks.

**Pull request merged**
