### PR TITLE
receiver: gather and show battery next level where available

### LINKED ISSUE #683: Solaar only shows 20%, 50%, and 90% levels for MX Ergo - show next level
**Information**

- Solaar version: 1.0.1
- Distribution: Fedora
- Kernel version (ex. `uname -srmo`): Linux 5.4.18-100.fc30.x86_64 x86_64 GNU/Linux
- Output of `solaar show`:

This is immediately after charging has completed.

```
Unifying Receiver
  Device path  : /dev/hidraw5
  USB id       : 046d:c52b
  Serial       : A027983A
    Firmware   : 12.09.B0030
    Bootloader : 04.16
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=112

  1: MX Ergo Multi-Device Trackball 
     Codename     : MX Ergo
     Kind         : trackball
     Wireless PID : 406F
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: BD87365D
        Bootloader: BOT 49.00.B0001
          Firmware: MPM 06.03.B0022
             Other: 
     The power switch is located on the base.
     Supports 36 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: unknown:0007           {0007}   
         6: RESET                  {0020}   
         7: unknown:0021           {0021}   
         8: BATTERY STATUS         {1000}   
         9: LED CONTROL            {1300}   
        10: REPROG CONTROLS V4     {1B04}   
        11: unknown:1C00           {1C00}   
        12: unknown:2006           {2006}   
        13: POINTER SPEED          {2205}   
            Pointer Speed: 1.0
        14: VERTICAL SCROLLING     {2100}   
            Roller type: standard
            Ratchet per turn: 18
            Scroll lines: 0
        15: unknown:00C2           {00C2}   
        16: unknown:1802           {1802}   internal, hidden
        17: unknown:1803           {1803}   internal, hidden
        18: unknown:1806           {1806}   internal, hidden
        19: unknown:1805           {1805}   internal, hidden
        20: unknown:1813           {1813}   internal, hidden
        21: CHANGE HOST            {1814}   
        22: unknown:1815           {1815}   
        23: unknown:1830           {1830}   internal, hidden
        24: unknown:1861           {1861}   internal, hidden
        25: unknown:1890           {1890}   internal, hidden
        26: unknown:1891           {1891}   internal, hidden
        27: unknown:18A1           {18A1}   internal, hidden
        28: unknown:1DF3           {1DF3}   internal, hidden
        29: unknown:1E00           {1E00}   hidden
        30: unknown:1EB0           {1EB0}   internal, hidden
        31: unknown:18B1           {18B1}   internal, hidden
        32: unknown:1850           {1850}   internal, hidden
        33: unknown:1F03           {1F03}   internal, hidden
        34: unknown:18C0           {18C0}   internal, hidden
        35: LOWRES WHEEL           {2130}   
            Wheel Reports: HID
     Has 9 reprogrammable keys:
         0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             mse, reprogrammable, pos:0, group:1, gmask:1
         1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             mse, reprogrammable, pos:0, group:1, gmask:1
         2: MIDDLE BUTTON             , default: MiddleMouseButton           => MIDDLE BUTTON             
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         3: BACK AS BUTTON 4          , default: BackEx                      => BACK AS BUTTON 4          
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         4: FORWARD AS BUTTON 5       , default: BrowserForwardEx            => FORWARD AS BUTTON 5       
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         5: unknown:00ED              , default: unknown:00C4                => unknown:00ED              
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         6: LEFT SCROLL AS AC PAN     , default: HorzScrollLeftSet           => LEFT SCROLL AS AC PAN     
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         7: RIGHT SCROLL AS AC PAN    , default: HorzScrollRightSet          => RIGHT SCROLL AS AC PAN    
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         8: unknown:00D7              , default: unknown:00B4                => unknown:00D7              
             divertable, virtual, pos:0, group:3, gmask:0
     Battery: 90%, discharging.
```

**Describe the bug**
While discharging over time, the only levels that solaar show ever shows is 90%, 50%, and 20%.  I have a strong feeling that might be the only levels that are reported by the device and this isn't a solaar issue but is there any way I can tell?  Some additional debug in solaar show?

Anything I can do here to help would be good, I always charge at 50% because I feel 20% is too low, so more granularity would be good, but it might not be possible.

I have my own logs from querying the device every 5 minutes, if that's useful at all.  I've had this device a few years, it's always been like this.  Of course I've removed a ton of duplicate lines from here, but this is essentially the charging status from full to 20% over time with the duplicate levels removed.

Sun Nov 19 10:00:01 EST 2017,1511103603,90
Sat Dec 23 16:00:01 EST 2017,1514062803,50
Sat Dec 23 19:00:01 EST 2017,1514073603,20

These logs are old, but this is the last time I really let it get to 20%, like I said above, I charge at 50%, my https://gitlab.com/khaytsus/mxergo scripts alert me.

For giggles, since I have git master as of right now pulled down, I checked that, same, 90%.  I can keep comparing if more data is useful.

**To Reproduce**
1. Watch solaar show as the device discharges over time
2. Note that it only shows 90, 50, or 20 levels

### PR DESCRIPTION
**Pull request by pfps**
Fixes #683

### CODE REVIEW

**Comment by pfps** [comment]
It works for me with my M510v2.

**Comment by chrivers** [comment]
Problems with my MX Master 3:

```
solaar show
...
         6: unknown:00C4              , default: unknown:009D                => unknown:00C4
             divertable, mse, reprogrammable, pos:0, group:3, gmask:7
         7: unknown:00D7              , default: unknown:00B4                => unknown:00D7
             divertable, virtual, pos:0, group:4, gmask:0
solaar: error: name '_NamedInt' is not defined
```

I'm not sure exactly where this `_NamedInt` error originates, but I have verified that is it not present in upstream master

**Comment by pfps** [comment]
Yeah, that's a silly bug on my part.  It's due to a misplaced import. Fix should be coming shortly.

**Comment by pfps** [comment]
@chrivers OK, I pushed a new version that should fix the bug.  Please test it out.

**Comment by chrivers** [comment]
@pfps Negative result - same error I'm afraid

**Comment by chrivers** [comment]
I commented the general exception handler to get a backtrace of the problem:

```
Traceback (most recent call last):
  File "/usr/local/bin/solaar", line 4, in <module>
    __import__('pkg_resources').run_script('solaar==1.0.2', 'solaar')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/solaar-1.0.2-py3.7.egg/EGG-INFO/scripts/solaar", line 57, in <module>
    solaar.gtk.main()
  File "/usr/local/lib/python3.7/dist-packages/solaar-1.0.2-py3.7.egg/solaar/gtk.py", line 101, in main
    return _cli.run(args.action, args.hidraw_path)
  File "/usr/local/lib/python3.7/dist-packages/solaar-1.0.2-py3.7.egg/solaar/cli/__init__.py", line 163, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/local/lib/python3.7/dist-packages/solaar-1.0.2-py3.7.egg/solaar/cli/show.py", line 212, in run
    _print_device(dev)
  File "/usr/local/lib/python3.7/dist-packages/solaar-1.0.2-py3.7.egg/solaar/cli/show.py", line 185, in _print_device
    text = _battery_text(level)
  File "/usr/local/lib/python3.7/dist-packages/solaar-1.0.2-py3.7.egg/solaar/cli/show.py", line 62, in _battery_text
    elif isinstance(level, _NamedInt):
NameError: name '_NamedInt' is not defined
```

(freshly run ./setup.py install for each test)

I can see that `lib/solaar/cli/show.py` has this on line 183:

`			from logitech_receiver.common import NamedInt as _NamedInt`

I'm guessing that's missing (or should be moved top-level, maybe) from line 62

**Comment by chrivers** [comment]
There's a problem, here:

```
			nextText = '' if next is None else ', next level ' +_battery_text(next)
```

A variable `next` is referred to, but never defined. So the built-in function `next` is caught instead. Python is having a wee bit of trouble converting a built-in function to an integer.

But if I change `s/next/nextLevel/` (just a guess), there are other problems. The string `nextText` is formatted into a `%x` fmt spec, which will not work either.

Looks like this part of the code needs a bit of rework.

**Comment by pfps** [comment]
Duh.   I forgot to commit before I force-pushed.  Should work now.

**Comment by lukasmichel** [comment]
Works now for me with an MX Master 2S

**Comment by pfps** [comment]
Excellent.

**Comment by chrivers** [comment]
Works for me now, MX Master 3.

Idea for improvement:

`Battery: 100%, discharging, next level 50%.`

Wouldn't it make more sense to display this as:

`Battery: discharging, level 50-100%` ?

**Comment by pfps** [comment]
That is certainly a possibility and would be better if the battery level was in that range, but I don't know whether the number reported is a maximum or an approximation, so I used wording that could work for both.

**Comment by chrivers** [comment]
Wait, if if `nextLevel` isn't the next SoC level we are going to reach, what is it?

I mean, what does this number even *mean*, then?

Displaying just "a number" we get from the hardware is, IMHO, useless, unless we can use it to provide improve the information the user receives. Or did I misunderstand you?

**Comment by pfps** [comment]
As far as I know, the numbers returned are only approximations to a reality that cannot be easily measured, or maybe cannot be exactly measured at all.   (Even the numbers reported for laptop batteries are not to be fully trusted, and laptop batteries are much more sophisticated than the batteries in mice and keyboards.)   So, for example, my M510v2 reports 70% soon after a new battery is installed.  I don't think that this is really any different from the "good" that my M510 reports.

So in my opinion the best thing to do is to just report the returned value as a level, and not imply that it is a max or min.

**Comment by chrivers** [comment]
@pfps I think we've come to a misunderstanding.

I agree completely, that the actual percentage numbers are a rough estimation, at best. Depending on the complexity of the battery charge controller, this can be more or less refeined, but will always be based on a simple mathematical model of the battery charge curve, with the state typically inferred through a voltage measurement.

What I'm talking about is how we present these estimates.

If we get this output:

`Battery: 100%, discharging, next level 50%.`

What does that tell the user? The way I understand it, the battery is at the "100% level" of charge, currently discharging, and the next update will happen when it crosses the 50% threshold.

Is that also how you interpret these numbers?

If my understanding is correct, that means the device is telling us that we are between 100% and 50% charge - or in other words, `50-100%` charge.

I just think the latter is easier to read, and more user-friendly.

Do you follow my argument? Do you agree?

**Comment by pfps** [comment]
My belief is that these results are triggered off voltage levels and probably tied to alkaline battery expected voltage levels.  So the 100% just means that the voltage is very close to 1.5V, the 70% just means that the voltage is in the part of the discharge curve where the voltage decreases slowly, and the 5% means that the voltage has dropped past this flatish part of the curve.   Further, the values are for some idealized battery, not the battery that was put in the mouse.  I also don't expect that there is any attempt to figure out just what kind of a battery is being used, so reporting may be worse, or better, for NiMH batteries and other rechargeables.

Given all this uncertainty I deem it best just to report the results, with no attempt to make them look like maximums or minimums.

**Comment by chrivers** [comment]
Sure, I agree with the first part.

Honestly, I'm not trying to be difficult here. I'm just pointing out that from this:

`Battery: 100%, discharging, next level 50%.`

I don't understand what information is being presented here. What does `next level 50%` *mean*?

Is this just an opaque readout, presented raw and as-is to the user, because the exact meaning is not known for sure yet?

Or does it mean something like "the next known level of charge the battery will reach, will be at the 50% mark"?

Or something else entirely?

**Comment by Klap-in** [comment]
‘Next level’ is the next value your Logitech device will report if the device discharges further. So it gives a simple impression of its resolution. (Some numbers by heart: e.g. some devices can just report the values 90/50/20/5%, by the telling next level 50% it shares something about how course the scale is)

**Comment by chrivers** [comment]
Thank you - I wasn't sure if my intuition matched reality.

So in this case, I would argue that the battery will be in the 50-100% range, at least according to the hardware. No?

If the results had been:

`Battery: 50%, discharging, next level 20%.`

then would be reasonable to say the battery is in the `20-50%` range. At least in my opinion.

In any case, just a suggestion. I'm not here to derail the pull request :)

**Comment by pfps** [comment]
Incorprated in PR #802

**Pull request closed without merging**
