### PR TITLE
Extract constants and exception into a module

### PR DESCRIPTION
**Pull request by MattHag**
Does not change any behavior, just reducing dependencies on low level modules in order to get the device module testable.

Related #1097

### CODE REVIEW

**Comment by pfps** [comment]
Is this going to conflict with PR #2265

**Comment by MattHag** [comment]
Yes, that can happen, but I think this one is an important step towards cleaner and testable code. I can add some comment there, but I would not move constants and Exceptions into any of the hidpp modules as these are static things, loaded by several other files. By extracting these to their own modules, it lowers the code, that relies on the hidpp modules.

**Comment by pfps** [comment]
Yes, this should be done, but after the imports fixes, as it touches the same place that the imports fixes do.  You could download that PR and build on it.

**Comment by pfps** [comment]
@MattHag There are a few conflicts that need to be cleaned up.

**Comment by pfps** [comment]
DEVICE_KIND from HID++ 2.0 is mapped to DEVICE_KIND from HID++ 1.0 in device.py and then the 1.0 version is used everywhere else.   I wonder if therefore DEVICE_KIND should be put somewhere else (common?) so that it is not identified as an HIDPP 1.0-only enumeration, and the mapping itself moved into hidpp20.py.

But perhaps the best way forward is to get this PR cleaned up and merged, and then do any fine-tuning.

**Comment by pfps** [comment]
I tried to fix the conflicts here but had to download them, fix them, and then create PR #2317.

**Pull request closed without merging**
