### PR TITLE
receiver: add initial support for GESTURE_2

### PR DESCRIPTION
**Pull request by pfps**

### CODE REVIEW

**Comment by viniciusbm** [comment]
I've fixed the errors in this PR:

[fixing-577d305.patch.txt](https://github.com/pwr-Solaar/Solaar/files/5144731/fixing-577d305.patch.txt)

If I'm not mistaken, you can apply the changes locally by saving this file outside the repository and running `git apply /path/to/fixing-577d305.patch.txt`.


<details>

<summary>This is the relevant part of the output of `solaar show`, after the fix:</summary> 

```
 Has 17 gestures:
         0: Track1Finger               Enabled: None
         0: TapGestures                Enabled: None
         0: Tap1Finger                 Enabled: True
         1: Tap2Finger                 Enabled: True
         2: TapDrag1Finger             Enabled: True
         3: DoubleTap1Finger           Enabled: True
         0: Scroll2FingerStateless     Enabled: None
         4: NaturalScrolling           Enabled: False
         5: Scroll2FingerHoriz         Enabled: True
         6: Scroll2FingerVert          Enabled: True
         7: LeftEdgeSwipe1Finger2      Enabled: False
         8: RightEdgeSwipe1Finger2     Enabled: False
         9: TopEdgeSwipe1Finger2       Enabled: False
        10: Zoom2FingerStateless       Enabled: False
        11: FnClickGestureSuppression  Enabled: False
         0: TwoFingersPresent          Enabled: None
         0: unknown:0064               Enabled: None
```
</details>

<details>
<summary>With `-dd`:</summary> 

```00:27:42,959    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D0D 000000]
00:27:42,979    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D0D 4203410141020400320480148C21A301]
00:27:42,979    DEBUG [MainThread] logitech_receiver.hidpp20: Unimplemented GESTURE_2 spec field  3 66 found.
00:27:42,979    DEBUG [MainThread] logitech_receiver.hidpp20: Unimplemented GESTURE_2 spec field  1 65 found.
00:27:42,979    DEBUG [MainThread] logitech_receiver.hidpp20: Unimplemented GESTURE_2 spec field  2 65 found.
00:27:42,979    DEBUG [MainThread] logitech_receiver.hidpp20: Unimplemented GESTURE_2 group field  0 4 found.
00:27:42,979  WARNING [MainThread] logitech_receiver.hidpp20: Unimplemented GESTURE_2 field 4 50 found.
00:27:42,980    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D0F 000800]
00:27:42,999    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D0F A302A11EA30A4105822C852DAD2AAD2B]
00:27:43,000    DEBUG [MainThread] logitech_receiver.hidpp20: Unimplemented GESTURE_2 spec field  5 65 found.
00:27:43,000    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D0B 001000]
00:27:43,019    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D0B 8F408F418F434204AF54912282558264]
00:27:43,020    DEBUG [MainThread] logitech_receiver.hidpp20: Unimplemented GESTURE_2 spec field  4 66 found.
00:27:43,020    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D0E 001800]
00:27:43,039    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D0E 01000000000000000000000000000000]
     Has 17 gestures:
         0: Track1Finger               Enabled: None
         0: TapGestures                Enabled: None
00:27:43,040    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D1B 000101]
00:27:43,059    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D1B 01000000000000000000000000000000]
         0: Tap1Finger                 Enabled: True
00:27:43,060    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D1F 000102]
00:27:43,079    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D1F 02000000000000000000000000000000]
         1: Tap2Finger                 Enabled: True
00:27:43,080    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D19 000104]
00:27:43,099    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D19 04000000000000000000000000000000]
         2: TapDrag1Finger             Enabled: True
00:27:43,100    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D1F 000108]
00:27:43,119    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D1F 08000000000000000000000000000000]
         3: DoubleTap1Finger           Enabled: True
         0: Scroll2FingerStateless     Enabled: None
00:27:43,120    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D1F 000110]
00:27:43,139    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D1F 00000000000000000000000000000000]
         4: NaturalScrolling           Enabled: False
00:27:43,140    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D1E 000120]
00:27:43,161    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D1E 20000000000000000000000000000000]
         5: Scroll2FingerHoriz         Enabled: True
00:27:43,162    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D1E 000140]
00:27:43,181    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D1E 40000000000000000000000000000000]
         6: Scroll2FingerVert          Enabled: True
00:27:43,182    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D18 000180]
00:27:43,201    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D18 00000000000000000000000000000000]
         7: LeftEdgeSwipe1Finger2      Enabled: False
00:27:43,202    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D1E 010101]
00:27:43,221    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D1E 00000000000000000000000000000000]
         8: RightEdgeSwipe1Finger2     Enabled: False
00:27:43,222    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D1E 010102]
00:27:43,241    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D1E 00000000000000000000000000000000]
         9: TopEdgeSwipe1Finger2       Enabled: False
00:27:43,242    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D1C 010104]
00:27:43,261    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D1C 00000000000000000000000000000000]
        10: Zoom2FingerStateless       Enabled: False
00:27:43,262    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 01 0D18 010108]
00:27:43,281    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 01 0D18 00000000000000000000000000000000]
        11: FnClickGestureSuppression  Enabled: False
         0: TwoFingersPresent          Enabled: None
         0: unknown:0064               Enabled: None
```
</details>

**Comment by pfps** [comment]
I was wondering why there were only six fields listed per retrieval in what I saw when eight fit into the message.

**Comment by pfps** [comment]
@viniciusbm 
I've updated and extended this PR to handle params (including the one you found).  I also fiddled with the gesture and param classes so that they can (hopefully) be used as reader/writers in setting templates.  This should make creating the setting templates easier.
Feel free to take over this commit and create a new PR including it.

**Comment by viniciusbm** [comment]
Thank you. I'll start working on it now.

**Comment by pfps** [comment]
@viniciusbm There is one other gesture I found:
```
    DeviceSpecificRawData=100,
```
I'm updating the PR but feel free to just edit your branch (ideally in the initial commit).

**Pull request closed without merging**
