### PR TITLE
Release 1.1.7

### PR DESCRIPTION
**Pull request by pfps**

### CODE REVIEW

**Comment by paper42** [comment]
Why is typing_extensions a dependency now? I don't see it used anywhere in the code.

**Comment by pfps** [comment]
It's used by hid-parser.  

It may be that Solaar shouldn't have the dependency and count on hid-parser depending on it, or maybe put it in the report-descriptor option,  but I seem to remember having a problem at one time when it wasn't included.   I'll investigate.

**Comment by pfps** [comment]
Aaah, typing_extensions is only needed in Python 3.7 for hid-parser.
If you have Python 3.8 or later it is not needed.

A better line there would be
        'typing_extensions (>=4.0.0) ; python_version<"3.8"',
which will be added soon.

**Comment by paper42** [comment]
`hid_parser` already has the dependency, so I think this project should not depend on something it itself doesn't use.
https://github.com/usb-tools/python-hid-parser/blob/4b7944f4999e152c678cd7fa76278b7e2535c3ff/setup.cfg#L21
```
install_requires =
    typing-extensions; python_version < '3.8'
```

This was added in https://github.com/usb-tools/python-hid-parser/commit/e0dfe5901a2693beb41149b595a8e72f2dcc6c84 which happened before the first release of `hid_parser`, so there should be no way a user could end up with hid_parser installed, but not typing-extensions and with Python 3.7.

**Comment by pfps** [comment]
I somehow missed that.  Now I'm wondering how I ever got an error on that package.

So out it goes.

**Pull request merged**
