### PR TITLE
Fix deprecated GitHub actions

### PR DESCRIPTION
**Pull request by MattHag**
Upgrade actions leveraging Node.js 20

#2256, #2284

### CODE REVIEW

**Comment by pfps** [comment]
OK, now that 1.1.11 is out it is time to merge several PRs.   Is there any particular order in which they need to be merged?

**Comment by MattHag** [comment]
This one on top of the extended makefile.

**Comment by pfps** [comment]
Thanks.

**Comment by pfps** [comment]
@MattHag Given that you are putting in work, it seems reasonable to make you a member of the Solaar developers in GitHub.  If you are interested, let me know.

**Pull request merged**
