### PR TITLE
receiver: use recursive locks to serialize access to receiver and device objects

### PR DESCRIPTION
**Pull request by pfps**

### CODE REVIEW

**Comment by FFY00** [comment]
What is the reasoning behind this? Are we having issues with communication collisions?

**Comment by pfps** [comment]
Maybe.    I was seeing some unexplained behaviour that might have been caused by lack of serialization.  (It was a while ago - I wish I had better records of what I did see.)  I'm not merging this, as I'm not sure that lack of serialization was the problem.

**Comment by FFY00** [comment]
If we are running parallel code we should use a lock on `logitech_receiver.base.request`, there is no need to add a lock in a bunch of places like this :grin:

**Comment by pfps** [comment]
I don't know if that is sufficient.  There have been bug reports from Fedora what seem to indicate that Solaar is trying to access devices that have already been removed.   The timeline might be that a device is unpaired or turns off, the user initiates some command, Solaar tears down the device, then Solaar does the command using the device structure from before it was torn down.  I put in some defensive code to lessen the time interval where this can happen but I don't think that this is a complete solution.

**Comment by FFY00** [comment]
Then we should check if the device is valid or not at the start of `logitech_receiver.base.request` and use the same lock in the teardown process when we mark it as invalid.

**Comment by FFY00** [comment]
Is there anything I am missing there?

**Comment by pfps** [comment]
Not sure.  I'll have to think about all this as it's been a while since I did the analysis.

**Pull request closed without merging**
