### PR TITLE
cli: set keyed settings with config

### LINKED ISSUE #1032: Command line to activate specific option
It is more a question than a feature request (but I don't know where to ask).

I know how to set the value of parameter "fn-lock" with a command: `~/Solaar/bin/solaar config 1 fn-swap 0`
 
However, I can't find how to fix "Natural scrolling" or "Zoom with two fingers" using a command. I found that "Natural scrolling corresponds to the parameter of id 45 in parameter gesture2-gestures but I did not find how to set it. 

Less important questions:
- how does "Tap and drag" works? After several tests I was not able to drag anything (I am using the last version of Solaar with a keyboard logitech K400+ on Ubuntu 20.04.1) ;
- what does "Swipe from the left edge" do? It does not seem to change anything when I activate it.

Thank you for this great tool!

### PR DESCRIPTION
**Pull request by pfps**
Fixes #1032

### CODE REVIEW

**Comment by pfps** [comment]
To test, just run `bin/solaar config` to set various settings for your devices, particularly settings that have multiple values, like key and button diversion and reprogramming, key disabling, and gestures.

**Comment by pfps** [comment]
@barolo @sk8geek @mschilli87 Can you test this PR?

**Comment by sk8geek** [comment]
Hi,

Sure. Just running with config with a device number seems to correctly give a list of available options, and then with just the option and no changes lists values/settings.  
With Pebble M350 I changed the dpi from 1000 to 2000 to 3000 and back and that worked.  
With MX Keys I enabled and disabled backlight and set/reset fn-swap, both of these worked correctly. I tried to disabled keys but I can't guess what format the command is expecting. I tried various combinations but failed to find the correct one.
Changes on the command line are correctly reflected in the GUI.
Cheers
Steven

**Comment by pfps** [comment]
If you enter `bin/solaar config M350` you get a list of settings, which gives the config (internal) names for all the settings.    Then `bin/solaar config M350 disable-keyboard-keys` gives you the value for this setting.  Then (and this should be easier but it isn't) you can get the number-to-name correspondence from the GUI.  So to turn off the Caps Lock key you can either do `bin/solaar config M350 disable-keyboard-key "Caps Lock" true` or `bin/solaar config M350 disable-keyboard-key 1 true`.

Well, you could, but there is a bug that is now fixed.  You'll have to copy the PR again if you already have copied it.

**Comment by sk8geek** [comment]
Okay, so on commit b4a6d9f the command `./bin/solaar config 1 disable-keyboard-keys 1 true` does indeed disable caps lock key. In order to see that change in the GUI I needed to kill/reload it.

**Comment by mschilli87** [comment]
@pfps: Sorry for not getting back. Life is stressful at times. Feel free to keep pinging me in the future. I hope to have more time again 'soon'. :wink:

**Pull request merged**
