### PR TITLE
update German translation

### PR DESCRIPTION
**Pull request by Danfro**

### CODE REVIEW

**Comment by Danfro** [comment]
It seems to me that all translation files need to be updated by using po-update.py. I only did commit the changes for the German translation because I am not sure how you handle this.

Also I had to edit line [13](https://github.com/pwr-Solaar/Solaar/blob/master/tools/po-update.sh#L13) and [14](https://github.com/pwr-Solaar/Solaar/blob/master/tools/po-update.sh#L14) to use python3 instead of python. Otherwise it would not work with my current setup. But I admit I do not understand enough of the setup if that is just the case with me or a general issue.

**Comment by pfps** [comment]
po-update.sh gets new strings to translate, and is part of the translation process as described in docs/i18n.md

**Comment by Danfro** [comment]
> po-update.sh gets new strings to translate, and is part of the translation process as described in docs/i18n.md

Ah, thanks a lot. I entirely missed that. Too many files in that docs folder. 

A _contribution_ section or a link in main readme might help if I may suggest that.

**Comment by pfps** [comment]
Good idea.

**Pull request merged**
