### PR TITLE
Use mkdocs for public documentation

### LINKED ISSUE #2502: Docs: Switch theme to enable page navigation and search
The documentation on GitHub Pages lacks an overview and navigation structure to find all pages. Furthermore, it is common to have a search.

## Solution
Switch to a common theme with left sidebar for navigation and built-in search like [just-the-docs](https://github.com/just-the-docs/just-the-docs). This theme even supports mermaid for the diagrams.

With that change, the `jekyll` folder should be unified and merged into `docs`.

### PR DESCRIPTION
**Pull request by MattHag**
Build a better documentation with navigation that shows all pages, a search and includes developer documentation from Python code.

Fixes #2502, #2503

### CODE REVIEW

**Comment by pfps** [comment]
How can this be tested before merging?

**Comment by MattHag** [comment]
The resulting docs are visivle on my branch and should be downloadable as artifact.

**Comment by pfps** [comment]
Where is the analogue of https://pwr-solaar.github.io/Sofixlaar/capabilities

**Comment by MattHag** [comment]
The deployed version is not the latest. The artifact with the rendered HTML is available at https://github.com/MattHag/Solaar/actions/runs/9726854392.

**Comment by MattHag** [comment]
Here they are
https://matthag.github.io/Solaar/

**Review by pfps — APPROVED** [review]

**Comment by MattHag** [comment]
There are still some deployments via GitHub Actions triggered with a wrong theme, which overwrites the public Solaar documentation.

**Pull request merged**
