### PR TITLE
Fix macOS runner and reenable it

### PR DESCRIPTION
**Pull request by MattHag**
Related #1244

### CODE REVIEW

**Comment by MattHag** [comment]
Failed tests seem to be due to too many imports caused by some "unit tests" which basically rely on every module.

**Comment by pfps** [comment]
So the MacOS test harness is failing?   The solution is to not enable testing on MacOS or fix the harness, not to remove test that work on Linux.

**Comment by MattHag** [comment]
No they don't fail, they cause segfaults on import of a dependency. As these tests import everything, as the underlying code is still not ready for proper unit tests (a unit is a module and not 10 modules), it will always be a pain to update them, when the code is further simplified.

**Comment by pfps** [comment]
Segfaulting is a failure of the harness.

**Comment by pfps** [comment]
The second commit is fine.  But the way forward is not to remove tests that work in Linux but to set things up in MacOS so that all tests work there.

**Comment by MattHag** [comment]
The problem with these tests is, that they load too many dependencies (still a problem of solaar, which I am steadily trying to improve), where at least one is not compatible with macOS. Instead of steadily adding tests and finding bugs with macOS, it is now necessary to fix all new dependencies loaded by the test. I don't know how many parts fail and need to be worked on in order to fix them.
It is no longer possible to gradually add tests, which work for both and fix issues in small iterations, when adding a test.

**Comment by pfps** [comment]
Then the way forward is to fix things so that they work on MacOS but not just remove the tests.

**Comment by MattHag** [comment]
Yes, anyone can pick this up and fix it. Don't know if I am motivated enough in the near future to do a much harder work to get it up and running again. Might need to sit there and wait until solaar has fewer dependencies between its modules.

**Comment by MattHag** [comment]
Replaced by #2490

**Pull request closed without merging**
