### PR TITLE
Add more robust mouse gesture support

### PR DESCRIPTION
**Pull request by ApeironTsuka**
- Remove existing mouse-* Test types
- Add new 'Mouse Gesture' Condition
- Implement Rule Editor UI for it
- Add support for diverted buttons in gestures
- Added diagonal mouse gesture directions (up-left, down-right, etc)

Allows you to chain multiple movements/buttons (for instance, moving the mouse up and then left) together into a single mappable gesture.

### CODE REVIEW

**Comment by ApeironTsuka** [comment]
Hopefully it's acceptable - I'm not very well-versed in Python.

An example chain...
Mouse Up: mapped to Page Up
Mouse Up -> Mouse Up: mapped to Home
Tilt Left -> Tilt Left: double-clicking left tilt

**Comment by pfps** [comment]
This is going to need documentation in https://pwr-solaar.github.io/Solaar/rules
As this is more complex than the usual rules, the dcumenation will have to be more than just a phrase.

**Comment by ApeironTsuka** [comment]
I'll be honest... I completely forgot about the documentation. Updated that.

**Comment by pfps** [comment]
@antonsoroko Can you try out this PR and see whether you like the added functionality?

**Comment by pfps** [comment]
Please fix the problems reported by the style checkers.

**Comment by pfps** [comment]
See also issue #1108

**Comment by ApeironTsuka** [comment]
I think I fixed them? At least the indenting.

**Comment by pfps** [comment]
You should set up git to run the style checks when you commit.  
@FFY00 Can you remind us how that is done?

**Comment by FFY00** [comment]
`pre-commit install` to install the hook, but you can run `pre-commit run --all-files` to run the hooks manually.

See https://pre-commit.com/#usage.

**Comment by ApeironTsuka** [comment]
There, that should be the pre-commit passing now. Sorry about that.

**Comment by antonsoroko** [comment]
@ApeironTsuka 
Hi.
Just curious, if noop still exists after these changed? For situation when I diverted some button to be a gesture button, but also want to use this button as is (without gesture, like I just clicked it, so called noop).

**Comment by pfps** [comment]
OK, this is passing the style checks now.  But can you squash all this into one commit and then force-push so that the style commits don't show up?

I generally like the idea.  

The main problem I have is that the information is encoded into a notification and then decoded.   Yes that's what I did for the simple mouse movements, but maybe it is time to do something better.   Let me think about how that would work.

It also would be nice to keep the old mouse tests around.   Let me think about how that would work.

**Comment by antonsoroko** [comment]
okay, looks like instead of `noop` i just need to delete gesture action (click delete button). if action is just empty - it will not work - maybe we can threat empty action as noop as well.
i mean `MouseGesture: []` vs `MouseGesture: ''` (respectively)

so i did some migration of my current rules - works ok.

image
image



obviously people would hate to migrate their rules, but i think separate condition called "mouse gesture" makes more sense than "test" condition. i do not think that it would make much sense to preserve old gesture-related tests. (it will probably only complicate the code)


@ApeironTsuka 
btw, for mouse gesture text box - it would be nice to have dropdown (like for tests) to see available options. or at least filter non gestures from the list - but this is still inconvenient, since you need to guess what to type to see something.

also looks like 
>Added diagonal mouse gesture directions (up-left, down-right, etc)

does not work as described. `Mouse Up-right` is not diagonal, i had to do move mouse Up and then move mouse Right. like to draw `г`.

and
>Allows you to chain multiple movements/buttons (for instance, moving the mouse up and then left) together into a single mappable gesture.

does not work or i did not understand how to use it (i used `And`)

image


but in general it looks good! thank you.
---
>But can you squash all this into one commit and then force-push so that the style commits don't show up?

you also can squash commits when you will merge PR. it is probably easier than do rebase and force-push.

**Comment by ApeironTsuka** [comment]
@antonsoroko
Diagonals should work. Rather than moving in an r shape, you should be able to move in a straight, diagonal line. Small movements aren't terribly accurate with how I do the maths, though.

As for chaining, click 'Add action' next to the text box to add another Action and set it as necessary. This will show as, for instance, 'Mouse Up -> Mouse Right' on the rule. In this example, the gesture would be to move the mouse up, pause for a short period (roughly a tenth of a second is enough), and then move the mouse to the right.

For no-op, it does work as-is. You can click the 'Delete' button under the text box to delete the Action. I should change it to say 'No-op' or similar in such a case, I suppose, rather than remaining blank. I'll do that now.

**Comment by antonsoroko** [comment]
i re-tested:
1. diagonal movement started to work. i dunno why it was not working before.
2. chaining works.
3. now i can see "no-op" in ui.

all good, thank you.

**Comment by antonsoroko** [comment]
@ApeironTsuka @pfps 

btw, will it be possible to implement somehow "continuous scroll" via gesture?
like, if action is scroll, then do scroll not after gesture was finished, but every 200ms.
e.g. you hold gesture button and then slide it down continuous - you get continuous scroll.
just curious. thank you.

**Comment by ApeironTsuka** [comment]
With the way it works presently; no. When you hold the gesture button down, it begins recording and only processes that when you release the button. To support something like that would mean you wouldn't be able to use that movement (in your example, mouse down) in any other gesture as it would be triggering the scroll rule every time you try to use it.

**Comment by viniciusbm** [comment]
> btw, for mouse gesture text box - it would be nice to have dropdown (like for tests) to see available options. or at least filter non gestures from the list - but this is still inconvenient, since you need to guess what to type to see something.

(I haven't got any devices supporting this feature, but I'm answering because this suggestion is just about the input field.)

To have a drop-down list showing only the mouse gestures, but still display diverted buttons as auto-complete suggestions:

<details>
<summary>diff</summary>

```diff 
diff --git a/lib/solaar/ui/diversion_rules.py b/lib/solaar/ui/diversion_rules.py
index 13b3c01..f398ddd 100644
--- a/lib/solaar/ui/diversion_rules.py
+++ b/lib/solaar/ui/diversion_rules.py
@@ -1077,7 +1077,8 @@ class TestUI(ConditionUI):
 class MouseGestureUI(ConditionUI):
 
     CLASS = _DIV.MouseGesture
-    MOVE_NAMES = list(map(str, _CONTROL)) + ['Mouse Up', 'Mouse Down', 'Mouse Left', 'Mouse Right', 'Mouse Up-left', 'Mouse Up-right', 'Mouse Down-left', 'Mouse Down-right']
+    MOUSE_GESTURE_NAMES = ['Mouse Up', 'Mouse Down', 'Mouse Left', 'Mouse Right', 'Mouse Up-left', 'Mouse Up-right', 'Mouse Down-left', 'Mouse Down-right']
+    MOVE_NAMES = list(map(str, _CONTROL)) + MOUSE_GESTURE_NAMES
 
     def create_widgets(self):
         self.widgets = {}
@@ -1088,7 +1089,10 @@ class MouseGestureUI(ConditionUI):
         self.widgets[self.add_btn] = (1, 0, 1, 1)
 
     def _create_field(self):
-        field = CompletionEntry(self.MOVE_NAMES, halign=Gtk.Align.CENTER, valign=Gtk.Align.END, hexpand=True, vexpand=True)
+        field = Gtk.ComboBoxText.new_with_entry()
+        for g in self.MOUSE_GESTURE_NAMES:
+            field.append(g, g)
+        CompletionEntry.add_completion_to_entry(field.get_child(), self.MOVE_NAMES)
         field.connect('changed', self._on_update)
         self.fields.append(field)
         self.widgets[field] = (len(self.fields) - 1, 0, 1, 1)
@@ -1119,7 +1123,7 @@ class MouseGestureUI(ConditionUI):
             if f.get_visible():
                 icon = 'dialog-warning' if i < len(self.component.movements
                                                    ) and self.component.movements[i] not in self.MOVE_NAMES else ''
-                f.set_icon_from_icon_name(Gtk.EntryIconPosition.SECONDARY, icon)
+                f.get_child().set_icon_from_icon_name(Gtk.EntryIconPosition.SECONDARY, icon)
 
     def show(self, component):
         n = len(component.movements)
@@ -1131,7 +1135,7 @@ class MouseGestureUI(ConditionUI):
         for i in range(n):
             field = self.fields[i]
             with self.ignore_changes():
-                field.set_text(component.movements[i])
+                field.get_child().set_text(component.movements[i])
             field.set_size_request(int(0.3 * self.panel.get_toplevel().get_size()[0]), 0)
             field.show_all()
             self.del_btns[i].show()
@@ -1141,7 +1145,7 @@ class MouseGestureUI(ConditionUI):
         self.add_btn.set_valign(Gtk.Align.END if n >= 1 else Gtk.Align.CENTER)
 
     def collect_value(self):
-        return [f.get_text().strip() for f in self.fields if f.get_visible()]
+        return [f.get_active_text().strip() for f in self.fields if f.get_visible()]
 
     @classmethod
     def left_label(cls, component):

```
</details>

**Comment by ApeironTsuka** [comment]
Yeah, I agree it's a better approach. Thanks for that, @viniciusbm.

**Comment by pfps** [comment]
I still need to take a close look at this.  Hopefully soon.

**Comment by pfps** [comment]
In the meantime, can you create a single commit with a label like "device: add more robust mouse gesture support"?   Thanks.

**Comment by antonsoroko** [comment]
or you can squash all commits to one on merge :-)

**Review by pfps — APPROVED** [review]
Looks good

**Pull request merged**
