### PR TITLE
Add support for process condition under wayland using solaar-gnome-extension

### LINKED ISSUE #1747: Fix for lack of Process condition in Wayland
Currently solaar doesn't support Process or Mouse process condition since the X11 api that we use for it is not available on Wayland,
one way we can implement it is by building a gnome extension that exposes the current wm_class value and the mouse over wm_class values over a dbus api maybe ?
I have seen this being done by some application to workaround this exact same issue but don't remember the name of it.

If this is okay then I can take ownership of building the gnome extension.

And then we can use the api made available by it in solaar for wayland users and add info in the docs and maybe when somewhere in rules editor that the corresponding gnome extension will need to be installed for some rules to work.

Let me know if this works or if you have any other approach in mind.

### PR DESCRIPTION
**Pull request by sidevesh**
This utilises https://github.com/sidevesh/solaar-gnome-extension gnome extension to get wm_class of focus and pointer focus window under wayland in gnome-shell.
Also, let me know if @pfps you would want to include the source of the gnome extension in this repo or org.
Closes #1747

### CODE REVIEW

**Comment by sidevesh** [comment]
@pfps Have tested this to be working, this is good to go

**Comment by pfps** [comment]
Some style check appears to be failing.

**Comment by sidevesh** [comment]
Fixed styling issues

**Review by pfps — APPROVED** [review]
Looks good.

**Review by pfps — APPROVED** [review]

**Comment by sidevesh** [comment]
@pfps the gnome extension will have to be published so pthers could use it, also docs update to mention it and where to get it from.
Do you want me to publish it myself ?

**Comment by pfps** [comment]
It's your extension so please can you publish it and update the docs.

**Comment by 360path** [comment]
Hello,
thanks for Solaar and the Solaar Gnome Extension. I'm pretty new to using Linux. I'm using ZorinOS 18 (which is based on Ubuntu and is running Gnome and Wayland) with a MX Master 3S.
I've installed Solaar, still in the process of setting it up and setting rules, but getting there.
I read through the docs:
> Rule features known not to work under Wayland include process and mouse process conditions, although on GNOME desktop under Wayland, you can use those with the Solaar Gnome extension installed, You can install it from `https://extensions.gnome.org/extension/6162/solaar-extension`.

So, I've now installed the solaar-gnome-extension. But I can't figure out how to use the Process condition. To test, I've entered `gnome-text-editor` as the Process and Test `thumb_wheel_up 12` to Key press `u`. Eventually I'd like to use the Thumb Wheel to switch tabs. Without the Process condition the letter "u" gets written in the text editor, but not with it.

What else do I need to do?

**Comment by pfps** [comment]
You should post your rules and the output of `solaar show`.  Otherwise others cannot see what you are doing.

**Comment by 360path** [comment]
My rules:
```
%YAML 1.3
---
- Rule:
  - KeyIsDown: Mouse Gesture Button
  - KeyPress:
    - Super_L
    - depress
- Rule:
  - Key: [Mouse Gesture Button, released]
  - KeyPress:
    - Super_L
    - release
...
---
- Key: [Smart Shift, released]
- KeyPress:
  - [Control_L, w]
  - click
...
---
- Process: gnome-text-editor
- Test: [thumb_wheel_up, 12]
- KeyPress:
  - u
  - click
...
---
- Active: FA6B15F2
- Test: [thumb_wheel_down, 12]
- KeyPress:
  - d
  - click
...
```

The output of `solaar show`:
```
rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed
solaar version 1.1.16+202510301932


MX Master 3S
     Device path  : /dev/hidraw0
     USB id       : 046d:B034
     Codename     : MX Master 3S
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      B03400000000
     Unit ID:       FA6B15F2
                 1: BL1 69.00.B0003
                 0: RBM 22.00.B0003
                 3: 
     Supports 36 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V4     
            Firmware: 1 BL1 69.00.B0003 B03438FCA4E6
            Firmware: 0 RBM 22.00.B0003 B03438FCA4E6
            Firmware: 3   
            Unit ID: FA6B15F2  Model ID: B03400000000  Transport IDs: {'btleid': 'B034'}
         3: DEVICE NAME            {0005} V0     
            Name: MX Master 3S
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
            Configuration: 11000000000000000000000000000000
         6: CRYPTO ID              {0021} V1     
         7: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Master 3S
         8: UNIFIED BATTERY        {1004} V3     
            Battery: 40%, BatteryStatus.DISCHARGING.
         9: REPROG CONTROLS V4     {1B04} V5     
            Key/Button Actions (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Actions        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Diversion (saved): {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Mouse Gestures, Smart Shift:Diverted}
            Key/Button Diversion        : {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Diverted, Smart Shift:Diverted}
        10: CHANGE HOST            {1814} V1     
            Change Host        : 3:******-Z
        11: HOSTS INFO             {1815} V2     
            Host 0 (paired): ******
            Host 1 (paired): ****** SHIFTphone 8
            Host 2 (paired): ******-Z
        12: XY STATS               {2250} V1     
        13: ADJUSTABLE DPI         {2201} V2     
            Sensitivity (DPI) (saved): 1000
            Sensitivity (DPI)        : 1000
        14: SMART SHIFT            {2110} V0     
            Scroll Wheel Ratcheted (saved): Ratcheted
            Scroll Wheel Ratcheted        : Ratcheted
            Scroll Wheel Ratchet Speed (saved): 10
            Scroll Wheel Ratchet Speed        : 10
        15: HIRES WHEEL            {2121} V1     
            Multiplier: 15
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): True
            Scroll Wheel Resolution        : True
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        16: THUMB WHEEL            {2150} V0     
            Thumb Wheel Direction (saved): False
            Thumb Wheel Direction        : False
            Thumb Wheel Diversion (saved): True
            Thumb Wheel Diversion        : True
        17: WHEEL STATS            {2251} V0     
        18: DFUCONTROL             {00C3} V0     
        19: DEVICE RESET           {1802} V0     
        20: unknown:1803           {0318} V0    internal, hidden, unknown:000010 
        21: CONFIG DEVICE PROPS    {1806} V8     
        22: unknown:1816           {1618} V0    internal, hidden, unknown:000010 
        23: OOBSTATE               {1805} V0     
        24: unknown:1830           {3018} V0    internal, hidden, unknown:000010 
        25: unknown:1891           {9118} V0    internal, hidden, unknown:000008 
        26: unknown:18A1           {A118} V0    internal, hidden, unknown:000010 
        27: unknown:1E00           {001E} V0    hidden 
        28: unknown:1E02           {021E} V0    internal, hidden 
        29: unknown:1602           {0216} V0     
        30: unknown:1EB0           {B01E} V0    internal, hidden, unknown:000010 
        31: unknown:1861           {6118} V0    internal, hidden, unknown:000010 
        32: unknown:9300           {0093} V0    internal, hidden, unknown:000010 
        33: unknown:9001           {0190} V0    internal, hidden, unknown:000010 
        34: unknown:1E22           {221E} V0    internal, hidden, unknown:000010 
        35: unknown:9205           {0592} V0    internal, hidden, unknown:000010 
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             analytics_key_events, mse, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             analytics_key_events, mse, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             analytics_key_events, raw_xy, divertable, reprogrammable, mse, pos:0, group:2, group mask:g1,g2
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             analytics_key_events, raw_xy, divertable, reprogrammable, mse, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             analytics_key_events, raw_xy, divertable, reprogrammable, mse, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Mouse Gesture Button      , default: Gesture Button Navigation   => Gesture Button Navigation 
             analytics_key_events, raw_xy, divertable, reprogrammable, mse, pos:0, group:2, group mask:g1,g2
             reporting: ['raw_xy_diverted', 'diverted']
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             analytics_key_events, raw_xy, divertable, reprogrammable, mse, pos:0, group:2, group mask:g1,g2
             reporting: ['diverted']
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             force_raw_xy, raw_xy, virtual, divertable, pos:0, group:3, group mask:empty
             reporting: default
     Battery: 40%, BatteryStatus.DISCHARGING.

MX Keys Mini
     Device path  : /dev/hidraw1
     USB id       : 046d:B369
     Codename     : MX Keys Mini
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      B36900000000
     Unit ID:       DBC2ACB8
                 1: BL1 53.01.B0006
                 0: RBK 73.04.B0016
                 3: 
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V4     
            Firmware: 1 BL1 53.01.B0006 B369FD70F4
            Firmware: 0 RBK 73.04.B0016 B3698C0A7514
            Firmware: 3   
            Unit ID: DBC2ACB8  Model ID: B36900000000  Transport IDs: {'btleid': 'B369'}
         3: DEVICE NAME            {0005} V0     
            Name: MX Keys Mini
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
            Configuration: 11000000000000000000000000000000
         6: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Keys Mini
         7: UNIFIED BATTERY        {1004} V2     
            Battery: 65%, BatteryStatus.DISCHARGING.
         8: REPROG CONTROLS V4     {1B04} V5     
            Key/Button Diversion (saved): {Backlight Down:Regular, Backlight Up:Regular, Play/Pause:Regular, Mute Sound:Regular, Volume Down:Regular, Volume Up:Regular, Dictation:Regular, Emoji:Regular, Screen Capture:Regular, Delete:Regular, Mute Microphone:Regular}
            Key/Button Diversion        : {Backlight Down:Regular, Backlight Up:Regular, Play/Pause:Regular, Mute Sound:Regular, Volume Down:Regular, Volume Up:Regular, Dictation:Regular, Emoji:Regular, Screen Capture:Regular, Delete:Regular, Mute Microphone:Regular}
         9: CHANGE HOST            {1814} V2     
            Change Host        : 3:******-Z
        10: HOSTS INFO             {1815} V2     
            Host 0 (paired): ******
            Host 1 (paired): ****** SHIFTphone 8
            Host 2 (paired): ******-Z
        11: BACKLIGHT2             {1982} V3     
            Backlight (saved): Automatic
            Backlight        : Automatic
            Backlight Level (saved): 4
            Backlight Level        : 2
            Backlight Delay Hands Out (saved): 30
            Backlight Delay Hands Out        : 30
            Backlight Delay Hands In (saved): 60
            Backlight Delay Hands In        : 60
            Backlight Delay Powered (saved): 60
            Backlight Delay Powered        : 60
        12: K375S FN INVERSION     {40A3} V0     
            Swap Fx function (saved): True
            Swap Fx function        : True
        13: LOCK KEY STATE         {4220} V0     
        14: KEYBOARD DISABLE KEYS  {4521} V0     
            Disable keys (saved): {Caps Lock:False, Insert:False, Win:False}
            Disable keys        : {Caps Lock:False, Insert:False, Win:False}
        15: MULTIPLATFORM          {4531} V1     
            Set OS (saved): Linux
            Set OS        : Linux
        16: DFUCONTROL             {00C3} V0     
        17: DEVICE RESET           {1802} V0     
        18: unknown:1803           {0318} V0    internal, hidden, unknown:000010 
        19: CONFIG DEVICE PROPS    {1806} V8     
        20: unknown:1816           {1618} V0    internal, hidden, unknown:000010 
        21: OOBSTATE               {1805} V0     
        22: unknown:1830           {3018} V0    internal, hidden, unknown:000010 
        23: unknown:1891           {9118} V0    internal, hidden, unknown:000008 
        24: unknown:18A1           {A118} V0    internal, hidden, unknown:000010 
        25: unknown:1E00           {001E} V0    hidden 
        26: unknown:1E02           {021E} V0    internal, hidden 
        27: unknown:1602           {0216} V0     
        28: unknown:1EB0           {B01E} V0    internal, hidden, unknown:000010 
        29: unknown:1861           {6118} V0    internal, hidden, unknown:000010 
        30: unknown:1A20           {201A} V0    internal, hidden, unknown:000010 
        31: unknown:18B0           {B018} V0    internal, hidden, unknown:000010 
     Has 16 reprogrammable keys:
         0: Host Switch Channel 1     , default: Hostswitch Channel 1        => Hostswitch Channel 1      
             analytics_key_events, fn_sensitive, is_fn, pos:1, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: Hostswitch Channel 2        => Hostswitch Channel 2      
             analytics_key_events, fn_sensitive, is_fn, pos:2, group:0, group mask:empty
             reporting: default
         2: Host Switch Channel 3     , default: Hostswitch Channel 3        => Hostswitch Channel 3      
             analytics_key_events, fn_sensitive, is_fn, pos:3, group:0, group mask:empty
             reporting: default
         3: Backlight Down            , default: Backlight Down              => Backlight Down            
             analytics_key_events, divertable, reprogrammable, fn_sensitive, is_fn, pos:4, group:0, group mask:empty
             reporting: default
         4: Backlight Up              , default: Backlight Up                => Backlight Up              
             analytics_key_events, divertable, reprogrammable, fn_sensitive, is_fn, pos:5, group:0, group mask:empty
             reporting: default
         5: Dictation                 , default: Voice Dictation             => Voice Dictation           
             analytics_key_events, divertable, reprogrammable, fn_sensitive, is_fn, pos:6, group:0, group mask:empty
             reporting: default
         6: Emoji                     , default: Open Emoji Panel            => Open Emoji Panel          
             analytics_key_events, divertable, reprogrammable, fn_sensitive, is_fn, pos:7, group:0, group mask:empty
             reporting: default
         7: Screen Capture            , default: Snipping Tool               => Snipping Tool             
             analytics_key_events, divertable, reprogrammable, fn_sensitive, is_fn, pos:8, group:0, group mask:empty
             reporting: default
         8: Mute Microphone           , default: Mute Microphone             => Mute Microphone           
             analytics_key_events, divertable, reprogrammable, fn_sensitive, is_fn, pos:9, group:0, group mask:empty
             reporting: default
         9: Play/Pause                , default: Play Pause                  => Play Pause                
             analytics_key_events, divertable, reprogrammable, fn_sensitive, is_fn, pos:10, group:0, group mask:empty
             reporting: default
        10: Mute Sound                , default: Mute                        => Mute                      
             analytics_key_events, divertable, reprogrammable, fn_sensitive, is_fn, pos:11, group:0, group mask:empty
             reporting: default
        11: Volume Down               , default: Volume Down                 => Volume Down               
             analytics_key_events, divertable, reprogrammable, fn_sensitive, is_fn, pos:12, group:0, group mask:empty
             reporting: default
        12: Volume Up                 , default: Volume Up                   => Volume Up                 
             analytics_key_events, divertable, reprogrammable, nonstandard, pos:0, group:0, group mask:empty
             reporting: default
        13: Delete                    , default: Delete                      => Delete                    
             analytics_key_events, divertable, reprogrammable, nonstandard, pos:0, group:0, group mask:empty
             reporting: default
        14: F Lock                    , default: Do Nothing One              => Do Nothing One            
             analytics_key_events, pos:0, group:0, group mask:empty
             reporting: default
        15: FN Key                    , default: Do Nothing One              => Do Nothing One            
             , pos:0, group:0, group mask:empty
             reporting: default
     Battery: 65%, BatteryStatus.DISCHARGING.
```

**Pull request merged**
