### PR TITLE
Release script

### PR DESCRIPTION
**Pull request by FFY00**

### CODE REVIEW

**Comment by pfps** [comment]
Hmm.  I can't figure out how to put a comment next to a change.  
There is a tyop - cantidates

**Comment by FFY00** [comment]
Just hover the line, click on the plus sign and leave your comment. You can either leave a single comment or a review, if you choose a review you can add more comments and when you are finished you go to the top right corner and click finish review.

**Comment by pfps** [comment]
Elegant.

**Comment by pfps** [comment]
Hmm.  I pulled, and I can see 
```
commit b2f3b56c315850f698616ea52f5db64837fecd99
Author: Filipe Laíns <lains@archlinux.org>
Date:   Mon Mar 16 20:57:35 2020 +0000

    release 1.0.2-rc1
    
    Signed-off-by: Filipe Laíns <lains@archlinux.org>
```
in the logs, but no tag for 1.0.2-rc1.
```
idefix Solaar> git describe --tags
1.0.1-117-g4056f5b
```

Is this what is supposed to happen (because this is a RC)?

**Comment by FFY00** [comment]
You need to fetch the tags.

```
git fetch origin --tags
```

Th tag is there.

```
$ git ls-remote origin
...
32751eb97ca5f56d5ad77213ccb9fd17d30ece94	refs/tags/1.0.2-rc1
b2f3b56c315850f698616ea52f5db64837fecd99	refs/tags/1.0.2-rc1^{}
```

**Comment by pfps** [comment]
Aah.  So cloning picks up all the tags but pulling doesn't.
So all is well (in Solaar-land if not in the real world).

**Comment by FFY00** [comment]
Yes, and you can verify the tag.

```
$ git tag -v 1.0.2-rc1
object b2f3b56c315850f698616ea52f5db64837fecd99
type commit
tag 1.0.2-rc1
tagger Filipe Laíns <lains@archlinux.org> 1584392351 +0000

release 1.0.2-rc1

* Look up tray icon filenames to get around a bug in libappindicator.
* Make the default behavior be to show the main window at startup.
* Support c537 nano receiver
* Add logind signals for suspend/resume.
* Remove solaar-gnome3 package
* Ignore features for devices that don't follow feature specification
* Add probe command to command-line interface to dump receiver registers
* Don't terminate on malformed or unknown messages
* Create fewer internal notifications for messages from devices
* Add a button to the main window to terminate (quit) Solaar
* Set up nano receivers as receivers with no unpairing and with re-pairing
* Set up c534 as receiver with max 2 pairings, no unpairing, re-pairing
* Better support receivers that do not unpair or when pairing replace existing pairings
* Add information about receiver pairing to receiver data structure
* Better support devices that only allow a limited number of total re-pairings
* Add --window option to control main window visibility and tray usage
* Ignore receiver if USB id is not retrieved
* Fix bug with double deleting when devices are disconnected
* Determine some receiver information from data structure for USB ids
* Treat battery level of 0 as unknown
* Fix bug on devices with no serial number
* Drop support for python2, and use python3 throughout
* Fix bug in remembering features discovered from device reports
* Show icons in main window device list
* Count offline devices when determining whether pairing is possible
* Update French, Dutch, German, and Croation translations
* Better icons for battery levels
* Support DPI, Backlight 2, Battery Voltage features
* Support M585, M590, M330, MX Master 2s and 3, new M310, new K800, craft keyboard
* Documentation improvements
* Clean up directory structure and remove unused files
gpg: Signature made Mon 16 Mar 2020 08:59:11 PM WET
gpg:                using RSA key D235B495EAACDF78327ED8B0F893C674816AA95D
gpg: Good signature from "Filipe Laíns (FFY00) <lains@archlinux.org>" [unknown]
gpg:                 aka "Filipe Laíns (FFY00) <lains@aurorafoss.org>" [unknown]
gpg:                 aka "Filipe Laíns (FFY00) <filipe.lains@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 3DCE 51D6 0930 EBA4 7858  BA41 46F6 33CB B0EB 4BF2
     Subkey fingerprint: D235 B495 EAAC DF78 327E  D8B0 F893 C674 816A A95D
```

**Comment by pfps** [comment]
Excellent.

**Pull request merged**
