### PR TITLE
Refactor receiver using subclasses

### PR DESCRIPTION
**Pull request by MattHag**
#2350

### CODE REVIEW

**Comment by pfps** [comment]
This needs updating to fix a conflict.

**Comment by MattHag** [comment]
This shouldn't change the behavior, except that self._devices only contains devices from a specific subclass. I am not sure how this is used, so either it's fine as is or the _device needs to be a class attribute of Receiver.

**Comment by pfps** [comment]
I've built quite a few changes on this PR, except for the last, somewhat-unrelated commit.  I'm not sure how to get git and GitHub to give you credit for parts of the change, though.

**Comment by MattHag** [comment]
I don't know, but you can directly use that PR, when there are no additional changes. 

The last one simplifies testing a but, but is not the last step for towards testability and simplification of code. If necessary it could be related to another ticket.

**Comment by pfps** [comment]
If it is alright with you I'll use the copy I have of this PR and create a new PR, referencing this PR.  That might put your authorship behind a link.

**Comment by MattHag** [comment]
Yeah, I don't care.

**Pull request closed without merging**
