### PR TITLE
Updated Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
Fixed/Corrected a few minor things.

### CODE REVIEW

**Comment by Lekensteyn** [comment]
Could you rebase this and resolve any potential conflicts?

```
git remote add upstream https://github.com/pwr-Solaar/Solaar
git fetch upstream
git rebase upstream/master
git push -f
```

**Comment by FFY00** [comment]
Just waiting for the author to rebase.

**Comment by pfps** [comment]
@Vistaus Could you rebase as suggested by Lekensteyn?

**Comment by FFY00** [comment]
Gonna close this for now. Please rebase and re-open :)

**Pull request closed without merging**
