### PR TITLE
Improvements on testability

### PR DESCRIPTION
**Pull request by MattHag**
Increase code coverage,
Refactor modules to use a clean interface to tlk between packages
Remove need for patching
Enable all tests on MacOS again

### CODE REVIEW

**Comment by MattHag** [comment]
That's the latest version which includes all changes deviating from Solaar master from yesterday

**Comment by pfps** [comment]
I see a lot of conflicts.

**Comment by MattHag** [comment]
Yes, because this should just be merged as is instead of the other single changes.

**Comment by pfps** [comment]
This branch cannot be merged because it conflicts with the PR that was recently merged.

**Comment by MattHag** [comment]
Replaced by 2626

**Pull request closed without merging**
