### PR TITLE
udev: Add "static_node=uinput" option

### PR DESCRIPTION
**Pull request by pszemus**
I noticed that on every boot `/dev/uinput` is recreated without ACL set. `setfacl -m u:${USER}:rw /dev/uinput` helps but only till the next boot (I'm on Fedora 36 with Wayland).

I've found that the Steam client was suffering the similar issue (ValveSoftware/steam-for-linux#4794, especially this comment explains in detail: https://github.com/ValveSoftware/steam-for-linux/issues/4794#issuecomment-327006061) and they fixed it by adding the `OPTIONS+="static_node=uinput"` to udev rules.
I tried that on my system and it works fine (no need to run `facl` on every boot any more).

### CODE REVIEW

**Comment by pfps** [comment]
This looks reasonable but what happens if the system boots without a Logitech device installed?  Perhaps the option should  be a separate rule that is always run?  

It would be useful to see the current Steam udev rule file.

**Comment by pfps** [comment]
So maybe a better solution is to have something like:

```
# User access to /dev/uinput
KERNEL=="uinput", SUBSYSTEM=="misc", TAG+="uaccess", OPTIONS+="static_node=uinput"
```

near the beginning of the udev file.  

I suggest an alternative udev file with this rule in it so that Solaar doesn't always add user access to /dev/uinput but users can if they want install this rule instead.

**Comment by pszemus** [comment]
@pfps: I've replaced the original `TAG+="uaccess", TAG+="udev-acl"` line with
```
KERNEL=="uinput", SUBSYSTEM=="misc", TAG+="uaccess", TAG+="udev-acl", OPTIONS+="static_node=uinput"
```
(added `TAG+="udev-acl"` for compatibility with old Ubuntu systems)
but Solaar now displays an error message:
> Found a Logitech Receiver (/dev/hidraw3), but did not have permission to open it.

Looking again at [Steam's rule file](https://github.com/ValveSoftware/steam-devices/blob/master/60-steam-input.rules), I think that now there's some `KERNEL=="hidraw*"` missing in Solaar's rule file.

**Comment by pszemus** [comment]
OK, sorry for the misunderstanding. After adding the above line under the initial comment, in the rule file, all Solaar rules, as well as the Solaar itself, work fine.

**Comment by pfps** [comment]
I created PR #1614 that includes an alternative udev rule and documentation on when to use it.

As the idea came from you, feel free to grab the changes and put them in this PR, if you care about authorship here.

**Pull request closed without merging**
