### PR TITLE
po/i18n: update zh_TW translation 

### PR DESCRIPTION
**Pull request by ifurther**
- add po~ to ignore
- po/i18n: update zh_TW translation

### CODE REVIEW

**Comment by pfps** [comment]
Thanks.

**Review by pfps — APPROVED** [review]

**Comment by pfps** [comment]
It looks as if you need to rebase your changes on the current master.

**Comment by ifurther** [comment]
How can I do ?

**Comment by pfps** [comment]
The problem is a conflict in solaar.pot.  The easiest solution is for me to grab your commits and create a new pull request with your changes, if that is acceptable for you.

**Pull request closed without merging**
