### PR TITLE
Add support for C537 Nano Receiver

### PR DESCRIPTION
**Pull request by rijnhard**
addresses https://github.com/pwr-Solaar/Solaar/issues/128

### CODE REVIEW

**Comment by pfps** [comment]
The receiver changes seem OK, but the testing in #128 is producing errors.  The errors are likely only from mouse G602, but it would be nice to get a full test of the GUI that doesn't have any errors.

**Comment by pfps** [comment]
I think that a line needs to be added to 42-logitech-unify-permissions.rules

**Comment by FFY00** [comment]
The C537 is only used for the G602 IIRC and the G602 does not follow the spec in some cases. We don't have any sort of API to handle this quirks so I'm not sure if we want to merge this.

**Comment by pfps** [comment]
I tend to agree.  I think it is only worth adding these if they are no too hard to add *and* the standard parts of Solaar do something useful for them.  I'm checking both these out in my c537 branch.

**Comment by rijnhard** [comment]
let me know when I can help or test again or what changes I need to make and test (or which PR's I should kill)

**Comment by pfps** [comment]
There are several changes that are in various stages that need to be Solaar before it makes any sense to add support for the c537 and G602.  PR #658 is needed to clean up some related code concerning receivers.  That should go in in a week or two.   Then I need to finish off my c534 branch to better handle nano receivers and it needs to go in.  After these are in it will be easy to add c537 as a nano receiver.  PR #646 is needed to clean up some code concerning notifications.  Then it will be easy to handle the 80xxxxxxxx messages.  But then there is the whole issue with whether you will actually get any significant benefit from Solaar.  That depends on whether you can pair devices, which you need to test at some time.
If you want to help to set the stage for possible inclusion of the c537/G602, I think the best thing for you to do is to try out the two PRs above.  If you only have the c537/G602 you could try out my branches c537 (which includes PR #646) and nano-c537 (which includes PR #658) and report your experiences in the comments on these two PRs.

**Comment by rijnhard** [comment]
@pfps done, should I kill this PR?

**Comment by pfps** [comment]
@rijnhard Let's leave it around for a bit, just in case my changes end up not being merged in.

**Comment by rijnhard** [comment]
No Longer needed, superseded by #646 and other changes

**Comment by pfps** [comment]
Yes, most of this is superseded.
Is the G602 causing any errors with PR #688?  If not, then a simple PR to add the c537 would be worthwhile, I think.  Note that this would need to add the c537 in base_usb.py and also in the dbus rules.

**Pull request closed without merging**
