### PR TITLE
Add NixOS flake.

### PR DESCRIPTION
**Pull request by Svenum**
This PR adds the ability to install solaar as a [flake](https://nixos.wiki/wiki/Flakes) in NixOS bzw. with the Nix-Package-Manger. With this feature you can be on the latest stable or development version in NixOS without waiting to be merged into the default NixOS-Code base.

### CODE REVIEW

**Comment by Svenum** [comment]
Sorry but nix flakes work like this. It pulls the git (normaly an extra branch with the stable Version ref) or the Sourcecode tar.gz file and reads the flake.nix. Maybe its possible to open a second repo for the nix flake. The source code doesnt need to be in it only needs the nix files. Maybe "pwr-solaar/solaar-flake"?

**Comment by pfps** [comment]
It would be possible to set up a separate github repository for this purpose.   The problem with putting it in the main Solaar repository is that it is a new thing to be maintained and I don't have any facility for testing whether it works.

**Comment by Svenum** [comment]
A new repo would be fine for me.

**Comment by pfps** [comment]
You should be able to do that yourself (once you have set up a GitHub account that can create and update repositories).

**Comment by pfps** [comment]
You can just use the fork of Solaar that you have already created.   (It may be that you have set up everything needed to easily push to this repository - I had to do some extra stuff to control this repository but that may be part of setting up any repository now.)

**Comment by Svenum** [comment]
So should I left my Nix things in my fork or should I contribute it to this repo? The only think needed to port to a Nix Flake is this flake.nix (Meta description of the Package), the flake.lock (state of thirdparty needed things) an the default.nix (the build instruction). 
FIrst you said that I have to make my own repo and then you say I maybe have to set up a bit to contribute here. Sorry but I am a little confused :sweat:

**Comment by pfps** [comment]
If all you want to do is to have something for Nix then you should be all set up - just use your repository as the source.  

But you probably also want to grab new releases of Solaar so you should put yourself on the notification list for new releases.  (It's somewhere on the release page for Solaar - I've never done it.)  

And you may be contributing to the Solaar code itself if there are problems in Solaar itself  that are discovered by using Nix.   I think that you are fine there as well as you put together this PR.


Sorry I can't be fully helpful.  I've done some of this several years ago but GitHub changes how things work on an irregular basis.

**Comment by Svenum** [comment]
Updated My PR and only added link to my repo https://github.com/Svenum/Solaar-Flake

**Review by pfps — APPROVED** [review]
This looks good

**Pull request merged**
