### PR TITLE
Switch to ruff linter and formatter

### PR DESCRIPTION
**Pull request by MattHag**
#2295

### CODE REVIEW

**Comment by pfps** [comment]
I see you did some manual fixup.   Should this go in before or after the other pending PRs?  Is there some way to not do any more manual work to get them in?  The reason to worry is that the change in quoting touches a lot of code.

**Comment by MattHag** [comment]
We can merge any other open requests before, this one will only need a rerun of auto formatting.

**Comment by pfps** [comment]
@MattHag OK, let's go that way.

**Comment by MattHag** [comment]
Done

**Pull request merged**
