### PR TITLE
Test diversion rules

### PR DESCRIPTION
**Pull request by MattHag**

### CODE REVIEW

**Comment by pfps** [comment]
There is a failing test here.  Can you find out what is going wrong?

**Comment by pfps** [comment]
I was just getting around to looking at this PR and I found a problem with Solaar on my Bluetooth keyboard.  I'll have to look at this first.

**Comment by MattHag** [comment]
> There is a failing test here. Can you find out what is going wrong?

The gtk dependencies. You can check out the latest pull request that works. The modules need to get more independent for these new tests to work.

**Comment by pfps** [comment]
So should this PR be marked as work in progress

**Comment by MattHag** [comment]
Replaced by #2626

**Pull request closed without merging**
