### PR TITLE
Add wired devices to Solaar GUI

### PR DESCRIPTION
**Pull request by pfps**
Adds wired devices that talk HID++ 2.0 to the Solaar GUI.
Also adds G502 Hero mouse USB information
Also lets config and probe work on wired devices
Also adds more information to show

Replaces #952

### CODE REVIEW

**Comment by pfps** [comment]
@doctor64 @barolo @sk8geek @mschilli87
Please test this out, particularly if you have a Logitech HID++ 2.0 device that can connect with a USB cable.
Try connecting and disconnecting the receiver and the USB cable.
Everything should work fine.

**Review by barolo — APPROVED** [review]
Can't test the wired functionality as I don't have any such device, other than that everything works properly with my MX keyboard and mouse

**Comment by pfps** [comment]
Reliably identifying Logitech devices is complicated.  I just added extra code so that multiple entries are not created for a device.  If you are testing this PR first look through your ~/.config/solaar/config.json file to see if there are any unusual entries.  If there are you can just remove them from the file.  Then run this PR and see if any unusual entries show up.

All device entries should have been of the form "XXXX:YYYYYYYY" where XXX is the WPID and YYYYYYYY is the serial number of a device you have had.  There now can be entries of the form "XXXXXXXXXXXX:YYYYYYYY" for devices that have never shown up to Solaar when connected via a receiver.  Other entries are unusual.

@barolo Can you check this PR again?

**Review by barolo — APPROVED** [review]
Tested with MX Craft/Keys and MX Master 2S. Config.json is clean, no weird entries. All UI functionality is intact.

**Pull request merged**
