### PR TITLE
Add MX Master 3S (Bolt) as supported mouse

### PR DESCRIPTION
**Pull request by MattHag**
#2328

### CODE REVIEW

**Comment by pfps** [comment]
The list of supported devices in this file is known and stated to be incomplete.

That said, adding devices there does little harm.

**Comment by pfps** [comment]
Adding more devices here does have the (slight) implication that other devices are not supported.  As more and more devices are added, the implication becomes stronger and stronger.

**Comment by MattHag** [comment]
The implication, that MX Master 3S and any other recent release is nowhere to be found supprted by Solaar is far worse.

**Comment by pfps** [comment]
Incorrect.

**Pull request closed without merging**
