### PR TITLE
settings: re-apply settings after device sleep or power on (issue #1125)

### PR DESCRIPTION
**Pull request by mrtimdog**

### CODE REVIEW

**Comment by mrtimdog** [comment]
I've added a issue for this, which I don't have permissions to link: https://github.com/pwr-Solaar/Solaar/issues/1125

**Comment by pfps** [comment]
I instrumented the function in question.  When a device is turned on, the power-on notification is often the third notification, resulting in the settings being pushed twice with your change.

**Comment by mrtimdog** [comment]
Yes, that is true, they are pushed twice, but the first push, at least for the settings I am expecting, are not persisted after the first push. After the second push the settings are persisted. Not having followed the code through the individual settings push calls it seems that the settings are pushed successfully (as the second works and both pushes use the same calls to apply them), but either the first set of pushes are ignored, or they are cleared sometime before the second push.

**Comment by pfps** [comment]
I still don't know why your device isn't having its settings applied correctly or why your fix helps so I'm very reluctant to merge  this PR, particularly as it adds a decided burden on all devices (double pushing).

**Comment by pfps** [comment]
I'm still very reluctant to merge this PR as I don't understand why it works.

That said, the way to update it is to pull the current master branch, rebase your change branch on that updated branch, and then push your change branch to your upstream with the --force flag.

**Comment by mrtimdog** [comment]
Hi Peter, yes, sorry, I should have been pushing these on a branch, not on my master, and pushing my odd changes to another branch again. I've not had a chance to get back to investigating this yet.

**Comment by pfps** [comment]
@mrtimdog I think PR #1204 makes this fix obsolete.  If you agree, please close this.

**Comment by pfps** [comment]
I think that this PR fixes a problem caused by the race condition fixed by PR #1204.  With this race condition fixed I believe that there is no reason to incorporate this extra push of device settings.
If you agree please close this PR.  Otherwise I'll leave it open.

**Pull request closed without merging**
