### PR TITLE
device: set current host name if not current host

### LINKED ISSUE #1120: Host name for linux machine paired with solaar shows up empty
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): `solaar 1.0.5`
- Distribution: Elementary OS 5 (Ubuntu 18.04)
- Kernel version (ex. `uname -srmo`): `Linux 4.20.17-042017-generic x86_64 GNU/Linux`
- Output of `solaar show`: 

<details>

```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : 05529561
    Firmware   : 12.11.B0032
    Bootloader : 04.16
    Other      : AA.AA
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=39, 2=187

  1: Wireless Keyboard K375s
     Device path  : None
     WPID         : 4061
     Codename     : K375s
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Polling rate : 20 ms (50Hz)
     Serial number: 06E177DF
     Model ID:      B34C40610000
     Unit ID:       58EFD8E0
        Bootloader: BOT 42.01.B0003
          Firmware: MPK 03.04.B0014
             Other: 
     The power switch is located on the base.
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 42.01.B0003 0000B5877FBE01
            Firmware: Firmware MPK 03.04.B0014 4061B5877FBE01
            Firmware: Other   
            Unit ID: 58EFD8E0  Model ID: B34C40610000  Transport IDs: {'btleid': 'B34C', 'wpid': '4061'}
         3: DEVICE NAME            {0005}   
            Name: K370s/K375s Multi-Device Wireless Keyboard
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: DEVICE FRIENDLY NAME   {0007}   
         7: BATTERY STATUS         {1000}   
            Battery: 90%, discharging, next level 50%.
         8: CHANGE HOST            {1814}   
            Change Host: 1:Swapnils-ASUS-VivoBook
         9: HOSTS INFO             {1815}   
            Host 0 (paired): 
            Host 1 (paired): Swapnil’s MacBook Air
            Host 2 (paired): Swapnil's Tab S6 Lite
        10: REPROG CONTROLS V4     {1B04}   
            Key/Button Diversion: {'209': 0, '210': 0, '211': 0, '213': 1, '214': 1, '189': 0, '6': 0, '4': 0, '5': 0, '3': 0, '2': 0, '1': 0, '191': 0, '212': 1, '10': 1, '221': 1, '193': 0, '192': 0}
        11: PERSISTENT REMAPPABLE ACTION {1C00}   
        12: K375S FN INVERSION     {40A3}   
            Swap Fx function: False
        13: ENCRYPTION             {4100}   
        14: LOCK KEY STATE         {4220}   
        15: KEYBOARD DISABLE KEYS  {4521}   
            Disable keys: {'1': False, '2': False, '4': False, '8': False, '16': False}
        16: MULTIPLATFORM          {4531}   
            Set OS: Windows
        17: DFUCONTROL SIGNED      {00C2}   
        18: unknown:1803           {1803}   internal, hidden
        19: CONFIG DEVICE PROPS    {1806}   internal, hidden
        20: OOBSTATE               {1805}   internal, hidden
        21: unknown:1813           {1813}   internal, hidden
        22: unknown:1830           {1830}   internal, hidden
        23: unknown:1861           {1861}   internal, hidden
        24: unknown:1890           {1890}   internal, hidden
        25: unknown:1891           {1891}   internal, hidden
        26: unknown:18A1           {18A1}   internal, hidden
        27: unknown:1DF3           {1DF3}   internal, hidden
        28: unknown:1E00           {1E00}   hidden
        29: unknown:1EB0           {1EB0}   internal, hidden
        30: unknown:18B0           {18B0}   internal, hidden
     Has 20 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             is FN, FN sensitive, divertable, persistently divertable, pos:1, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             is FN, FN sensitive, divertable, persistently divertable, pos:2, group:0, group mask:empty
             reporting: default
         2: Host Switch Channel 3     , default: HostSwitch Channel 3        => HostSwitch Channel 3      
             is FN, FN sensitive, divertable, persistently divertable, pos:3, group:0, group mask:empty
             reporting: default
         3: MultiPlatform Home/Mission Control, default: Multiplatform Home/Mission Control => Multiplatform Home/Mission Control
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:4, group:0, group mask:empty
             reporting: diverted
         4: MultiPlatform Menu/Show/Hide Virtual Keyboard/Launchpad, default: Multiplatform Menu/Launchpad => Multiplatform Menu/Launchpad
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:5, group:0, group mask:empty
             reporting: diverted
         5: Multiplatform Back        , default: MultiPlatform Back          => MultiPlatform Back        
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:6, group:0, group mask:empty
             reporting: default
         6: Previous                  , default: Previous                    => Previous                  
             is FN, FN sensitive, divertable, persistently divertable, pos:7, group:0, group mask:empty
             reporting: default
         7: Play/Pause                , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, divertable, persistently divertable, pos:8, group:0, group mask:empty
             reporting: default
         8: Next                      , default: Next                        => Next                      
             is FN, FN sensitive, divertable, persistently divertable, pos:9, group:0, group mask:empty
             reporting: default
         9: Mute                      , default: Mute                        => Mute                      
             is FN, FN sensitive, divertable, persistently divertable, pos:10, group:0, group mask:empty
             reporting: default
        10: Volume Down               , default: Volume Down                 => Volume Down               
             is FN, FN sensitive, divertable, persistently divertable, pos:11, group:0, group mask:empty
             reporting: default
        11: Volume Up                 , default: Volume Up                   => Volume Up                 
             is FN, FN sensitive, divertable, persistently divertable, pos:12, group:0, group mask:empty
             reporting: default
        12: Screen Capture/Print Screen, default: Screen Capture              => Screen Capture            
             is FN, reprogrammable, divertable, persistently divertable, pos:0, group:0, group mask:empty
             reporting: default
        13: MultiPlatform Search      , default: Multiplatform Search        => Multiplatform Search      
             is FN, reprogrammable, divertable, persistently divertable, pos:0, group:0, group mask:empty
             reporting: diverted
        14: Calculator                , default: Calculator                  => Calculator                
             is FN, reprogrammable, divertable, persistently divertable, pos:0, group:0, group mask:empty
             reporting: diverted
        15: Multi Platform Language Switch, default: Multiplatform Language Switch => Multiplatform Language Switch
             is FN, reprogrammable, divertable, persistently divertable, pos:0, group:0, group mask:empty
             reporting: diverted
        16: Fn Up                     , default: unknown:0070                => unknown:0070              
             is FN, divertable, persistently divertable, pos:0, group:0, group mask:empty
             reporting: default
        17: Fn Down                   , default: unknown:006F                => unknown:006F              
             is FN, divertable, persistently divertable, pos:0, group:0, group mask:empty
             reporting: default
        18: F Lock                    , default: Do Nothing One              => Do Nothing One            
             is FN, pos:0, group:0, group mask:empty
             reporting: default
        19: unknown:0034              , default: Do Nothing One              => Do Nothing One            
             nonstandard, pos:0, group:0, group mask:empty
             reporting: default
     Battery: 90%, discharging, next level 50%.

  2: Multi Device Silent Mouse M585/M590
     Device path  : None
     WPID         : 406B
     Codename     : M585/M590
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 95138309
     Model ID:      B01B406B0000
     Unit ID:       25F556B4
        Bootloader: BOT 48.01.B0002
          Firmware: MPM 05.10.B0011
             Other: 
     The power switch is located on the base.
     Supports 35 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 48.01.B0002 0000AE5E7277
            Firmware: Firmware MPM 05.10.B0011 406BAE5E7277
            Firmware: Other   
            Unit ID: 25F556B4  Model ID: B01B406B0000  Transport IDs: {'btleid': 'B01B', 'wpid': '406B'}
         3: DEVICE NAME            {0005}   
            Name: M585/M590 Multi-Device Mouse
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: CRYPTO ID              {0021}   
         7: DEVICE FRIENDLY NAME   {0007}   
         8: BATTERY STATUS         {1000}   
            Battery: 90%, discharging, next level 50%.
         9: CHANGE HOST            {1814}   
            Change Host: 1:Swapnil’s MacBook Air
        10: HOSTS INFO             {1815}   
            Host 0 (paired): Swapnil’s MacBook Air
            Host 1 (paired): Swapnil’s MacBook Air
        11: REPROG CONTROLS V4     {1B04}   
            Key/Button Actions: {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '91': 83, '93': 86}
            Key/Button Diversion: {'82': 0, '83': 1, '86': 1, '91': 0, '93': 0, '215': 0}
        12: PERSISTENT REMAPPABLE ACTION {1C00}   
        13: POINTER SPEED          {2205}   
            Pointer Speed: 1.0
            Sensitivity (Pointer Speed): 256
        14: VERTICAL SCROLLING     {2100}   
            Roller type: standard
            Ratchet per turn: 18
            Scroll lines: 0
        15: DFUCONTROL SIGNED      {00C2}   
        16: DEVICE RESET           {1802}   internal, hidden
        17: unknown:1803           {1803}   internal, hidden
        18: CONFIG DEVICE PROPS    {1806}   internal, hidden
        19: OOBSTATE               {1805}   internal, hidden
        20: unknown:1813           {1813}   internal, hidden
        21: unknown:1830           {1830}   internal, hidden
        22: unknown:1861           {1861}   internal, hidden
        23: unknown:1890           {1890}   internal, hidden
        24: unknown:1891           {1891}   internal, hidden
        25: unknown:18A1           {18A1}   internal, hidden
        26: unknown:1DF3           {1DF3}   internal, hidden
        27: unknown:1E00           {1E00}   hidden
        28: unknown:1EB0           {1EB0}   internal, hidden
        29: unknown:18B1           {18B1}   internal, hidden
        30: unknown:1850           {1850}   internal, hidden
        31: unknown:1E22           {1E22}   
        32: unknown:1F03           {1F03}   internal, hidden
        33: unknown:18C0           {18C0}   internal, hidden
        34: LOWRES WHEEL           {2130}   
            Wheel Reports: HID
            Scroll Wheel HID++ Scrolling: False
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, reprogrammable, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, reprogrammable, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: diverted
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: diverted
         5: Left Tilt                 , default: Mouse Scroll Left Button    => Mouse Back Button         
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         6: Right Tilt                , default: Mouse Scroll Right Button   => Mouse Forward Button      
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:3, group mask:empty
             reporting: default
     Battery: 90%, discharging, next level 50%.
```
</details>

**Describe the bug**
As is visible in the above `solaar show` output, the host name for my machine shows up as empty,
```
         9: HOSTS INFO             {1815}   
            Host 0 (paired): 
            Host 1 (paired): Swapnil’s MacBook Air
            Host 2 (paired): Swapnil's Tab S6 Lite
```
The other devices paired using bluetooth or Logitech Options on Mac show up with proper name.
In Logitech Options on the Mac, in Easy-Switch also the hostname for the linux machine shows up as empty.

I see that there is a `set_host_name` function in `hidpp20.py` but seems like it isn't used anywhere or during / after the pairing process.

**To Reproduce**
1. Run `solaar show`
2. Check HOSTS_INFO for any device paired using solaar
3. The hostname for the linux machine paired with solaar shows up as empty
4. Check the same on Logitech Options in Easy-Switch page and there also it shows up as empty

### PR DESCRIPTION
**Pull request by pfps**
Fixes #1120

### CODE REVIEW

**Comment by sidevesh** [comment]
This fixed both the missing hostname in `solaar show` as well as the name in Easy-Switch in Logitech Options,
although in Easy-Switch page the name is truncated at 14 chars and in the code I see that only first 14 chars of hostname is sent,
any reason for that and can the limit be removed ?
Rest of the devices in Easy-Switch have way bigger than 14 char names and seems to show those fine.

Also, Easy-Switch shows the OS version of the host and due to previously connecting the receiver that I am using in my linux laptop on my MacBook once it now shows OS X as the OS,
the hostname got updated after this PR but the OS name as OS X still remains,
any way we can make it reflect the actual OS name (Linux with/without kernel version or Elementary OS / Ubuntu) or at the very least reset the OS info so it shows up with only hostname, like it was before I plugged the receiver into MacBook once.

**Comment by pfps** [comment]
The maximum name length for my keyboard is 24, not much more than 14, but I'll look into getting up to that length.

**Comment by pfps** [comment]
The new version should be able to set host names longer than 14 characters.  For it to be merged you need to check it out with a host name longer than 14 characters.  Provide output of `solaar show` with such a host name as the active host.

**Comment by sidevesh** [comment]
```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : 05529561
    Firmware   : 12.11.B0032
    Bootloader : 04.16
    Other      : AA.AA
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=176, 2=77

  1: Wireless Keyboard K375s
     Device path  : None
     WPID         : 4061
     Codename     : K375s
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Polling rate : 20 ms (50Hz)
     Serial number: 06E177DF
     Model ID:      B34C40610000
     Unit ID:       58EFD8E0
        Bootloader: BOT 42.01.B0003
          Firmware: MPK 03.04.B0014
             Other: 
     The power switch is located on the base.
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 42.01.B0003 0000B5877FBE01
            Firmware: Firmware MPK 03.04.B0014 4061B5877FBE01
            Firmware: Other   
            Unit ID: 58EFD8E0  Model ID: B34C40610000  Transport IDs: {'btleid': 'B34C', 'wpid': '4061'}
         3: DEVICE NAME            {0005}   
            Name: K370s/K375s Multi-Device Wireless Keyboard
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: DEVICE FRIENDLY NAME   {0007}   
         7: BATTERY STATUS         {1000}   
            Battery: 90%, discharging, next level 50%.
         8: CHANGE HOST            {1814}   
            Change Host        : 1:Swapnils-ASUS-VivoBook
         9: HOSTS INFO             {1815}   
            Host 0 (paired): Swapnils-ASUS-VivoBook
            Host 1 (paired): Swapnil’s MacBook Air
            Host 2 (paired): Swapnil's Tab S6 Lite
        10: REPROG CONTROLS V4     {1B04}   
            Key/Button Diversion (saved): {'1': 0, '10': 1, '189': 0, '191': 0, '192': 0, '193': 0, '2': 0, '209': 0, '210': 0, '211': 0, '212': 1, '213': 1, '214': 1, '221': 1, '3': 0, '4': 0, '5': 0, '6': 0}
            Key/Button Diversion        : {'209': 0, '210': 0, '211': 0, '213': 0, '214': 0, '189': 0, '6': 0, '4': 0, '5': 0, '3': 0, '2': 0, '1': 0, '191': 0, '212': 0, '10': 0, '221': 0, '193': 0, '192': 0}
        11: PERSISTENT REMAPPABLE ACTION {1C00}   
        12: K375S FN INVERSION     {40A3}   
            Swap Fx function (saved): True
            Swap Fx function        : False
        13: ENCRYPTION             {4100}   
        14: LOCK KEY STATE         {4220}   
        15: KEYBOARD DISABLE KEYS  {4521}   
            Disable keys (saved): {'1': False, '16': False, '2': False, '4': False, '8': False}
            Disable keys        : {'1': False, '2': False, '4': False, '8': False, '16': False}
        16: MULTIPLATFORM          {4531}   
            Set OS (saved): 0
            Set OS        : Windows
        17: DFUCONTROL SIGNED      {00C2}   
        18: unknown:1803           {1803}   internal, hidden
        19: CONFIG DEVICE PROPS    {1806}   internal, hidden
        20: OOBSTATE               {1805}   internal, hidden
        21: unknown:1813           {1813}   internal, hidden
        22: unknown:1830           {1830}   internal, hidden
        23: unknown:1861           {1861}   internal, hidden
        24: unknown:1890           {1890}   internal, hidden
        25: unknown:1891           {1891}   internal, hidden
        26: unknown:18A1           {18A1}   internal, hidden
        27: unknown:1DF3           {1DF3}   internal, hidden
        28: unknown:1E00           {1E00}   hidden
        29: unknown:1EB0           {1EB0}   internal, hidden
        30: unknown:18B0           {18B0}   internal, hidden
     Has 20 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             is FN, FN sensitive, divertable, persistently divertable, pos:1, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             is FN, FN sensitive, divertable, persistently divertable, pos:2, group:0, group mask:empty
             reporting: default
         2: Host Switch Channel 3     , default: HostSwitch Channel 3        => HostSwitch Channel 3      
             is FN, FN sensitive, divertable, persistently divertable, pos:3, group:0, group mask:empty
             reporting: default
         3: MultiPlatform Home/Mission Control, default: Multiplatform Home/Mission Control => Multiplatform Home/Mission Control
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:4, group:0, group mask:empty
             reporting: default
         4: MultiPlatform Menu/Show/Hide Virtual Keyboard/Launchpad, default: Multiplatform Menu/Launchpad => Multiplatform Menu/Launchpad
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:5, group:0, group mask:empty
             reporting: default
         5: Multiplatform Back        , default: MultiPlatform Back          => MultiPlatform Back        
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:6, group:0, group mask:empty
             reporting: default
         6: Previous                  , default: Previous                    => Previous                  
             is FN, FN sensitive, divertable, persistently divertable, pos:7, group:0, group mask:empty
             reporting: default
         7: Play/Pause                , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, divertable, persistently divertable, pos:8, group:0, group mask:empty
             reporting: default
         8: Next                      , default: Next                        => Next                      
             is FN, FN sensitive, divertable, persistently divertable, pos:9, group:0, group mask:empty
             reporting: default
         9: Mute                      , default: Mute                        => Mute                      
             is FN, FN sensitive, divertable, persistently divertable, pos:10, group:0, group mask:empty
             reporting: default
        10: Volume Down               , default: Volume Down                 => Volume Down               
             is FN, FN sensitive, divertable, persistently divertable, pos:11, group:0, group mask:empty
             reporting: default
        11: Volume Up                 , default: Volume Up                   => Volume Up                 
             is FN, FN sensitive, divertable, persistently divertable, pos:12, group:0, group mask:empty
             reporting: default
        12: Screen Capture/Print Screen, default: Screen Capture              => Screen Capture            
             is FN, reprogrammable, divertable, persistently divertable, pos:0, group:0, group mask:empty
             reporting: default
        13: MultiPlatform Search      , default: Multiplatform Search        => Multiplatform Search      
             is FN, reprogrammable, divertable, persistently divertable, pos:0, group:0, group mask:empty
             reporting: default
        14: Calculator                , default: Calculator                  => Calculator                
             is FN, reprogrammable, divertable, persistently divertable, pos:0, group:0, group mask:empty
             reporting: default
        15: Multi Platform Language Switch, default: Multiplatform Language Switch => Multiplatform Language Switch
             is FN, reprogrammable, divertable, persistently divertable, pos:0, group:0, group mask:empty
             reporting: default
        16: Fn Up                     , default: unknown:0070                => unknown:0070              
             is FN, divertable, persistently divertable, pos:0, group:0, group mask:empty
             reporting: default
        17: Fn Down                   , default: unknown:006F                => unknown:006F              
             is FN, divertable, persistently divertable, pos:0, group:0, group mask:empty
             reporting: default
        18: F Lock                    , default: Do Nothing One              => Do Nothing One            
             is FN, pos:0, group:0, group mask:empty
             reporting: default
        19: unknown:0034              , default: Do Nothing One              => Do Nothing One            
             nonstandard, pos:0, group:0, group mask:empty
             reporting: default
     Battery: 90%, discharging, next level 50%.

  2: Multi Device Silent Mouse M585/M590
     Device path  : None
     WPID         : 406B
     Codename     : M585/M590
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 95138309
     Model ID:      B01B406B0000
     Unit ID:       25F556B4
        Bootloader: BOT 48.01.B0002
          Firmware: MPM 05.10.B0011
             Other: 
     The power switch is located on the base.
     Supports 35 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 48.01.B0002 0000AE5E7277
            Firmware: Firmware MPM 05.10.B0011 406BAE5E7277
            Firmware: Other   
            Unit ID: 25F556B4  Model ID: B01B406B0000  Transport IDs: {'btleid': 'B01B', 'wpid': '406B'}
         3: DEVICE NAME            {0005}   
            Name: M585/M590 Multi-Device Mouse
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: CRYPTO ID              {0021}   
         7: DEVICE FRIENDLY NAME   {0007}   
         8: BATTERY STATUS         {1000}   
            Battery: 90%, discharging, next level 50%.
         9: CHANGE HOST            {1814}   
            Change Host        : 1:Swapnils-ASUS-VivoBook
        10: HOSTS INFO             {1815}   
            Host 0 (paired): Swapnils-ASUS-VivoBook
            Host 1 (paired): Swapnil’s MacBook Air
        11: REPROG CONTROLS V4     {1B04}   
            Key/Button Actions (saved): {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '91': 83, '93': 86}
            Key/Button Actions        : {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '91': 91, '93': 93}
            Key/Button Diversion (saved): {'215': 0, '82': 0, '83': 1, '86': 1, '91': 0, '93': 0}
            Key/Button Diversion        : {'82': 0, '83': 0, '86': 0, '91': 0, '93': 0, '215': 0}
        12: PERSISTENT REMAPPABLE ACTION {1C00}   
        13: POINTER SPEED          {2205}   
            Pointer Speed: 1.0
            Sensitivity (Pointer Speed) (saved): 256
            Sensitivity (Pointer Speed)        : 256
        14: VERTICAL SCROLLING     {2100}   
            Roller type: standard
            Ratchet per turn: 18
            Scroll lines: 0
        15: DFUCONTROL SIGNED      {00C2}   
        16: DEVICE RESET           {1802}   internal, hidden
        17: unknown:1803           {1803}   internal, hidden
        18: CONFIG DEVICE PROPS    {1806}   internal, hidden
        19: OOBSTATE               {1805}   internal, hidden
        20: unknown:1813           {1813}   internal, hidden
        21: unknown:1830           {1830}   internal, hidden
        22: unknown:1861           {1861}   internal, hidden
        23: unknown:1890           {1890}   internal, hidden
        24: unknown:1891           {1891}   internal, hidden
        25: unknown:18A1           {18A1}   internal, hidden
        26: unknown:1DF3           {1DF3}   internal, hidden
        27: unknown:1E00           {1E00}   hidden
        28: unknown:1EB0           {1EB0}   internal, hidden
        29: unknown:18B1           {18B1}   internal, hidden
        30: unknown:1850           {1850}   internal, hidden
        31: unknown:1E22           {1E22}   
        32: unknown:1F03           {1F03}   internal, hidden
        33: unknown:18C0           {18C0}   internal, hidden
        34: LOWRES WHEEL           {2130}   
            Wheel Reports: HID
            Scroll Wheel HID++ Scrolling (saved): False
            Scroll Wheel HID++ Scrolling        : False
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, reprogrammable, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, reprogrammable, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Left Tilt                 , default: Mouse Scroll Left Button    => Mouse Scroll Left Button  
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         6: Right Tilt                , default: Mouse Scroll Right Button   => Mouse Scroll Right Button 
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:3, group mask:empty
             reporting: default
     Battery: 90%, discharging, next level 50%.
```

**Comment by sidevesh** [comment]
Can comfirm that the name now shows up untruncated on Easy-Switch as well as `solaar show` :+1:

**Comment by sidevesh** [comment]
Any idea on whether the OS info can be removed or updated so that it doesn't say OS X for the linux laptop host on Easy-Switch ?

**Comment by pfps** [comment]
Well, it is probably going to be truncated at about 24 characters, but that's longer than the name you are using.  I'll merge in this PR and close the issue.

**Comment by pfps** [comment]
Solaar is just reporting on what is stored in the device, and now updating the name of the current host if that is not the nodename of the current machine.  Solaar doesn't know what is going on for other hosts so it shouldn't be changing anything for them.

**Comment by sidevesh** [comment]
Screen Shot 2021-03-29 at 9 26 24 PM 1
Here you can see that the linux laptop (VivoBook) has the correct hostname but it says OS X 11.0 before the name, even though the receiver isn't plugged into MacBook,
seems like some value was set on the receiver or the keyboard that one time I plugged the receiver into MacBook and that value isn't getting reset by Solaar, unlike the hostname.
Do we know how the OS info is being set on the device and if we can reset that ?

**Comment by pfps** [comment]
I don't know where the Logitech software is getting that information, or even whether that information is even stored on the device.

**Comment by sidevesh** [comment]
ah okay, that's fine, this is too minor of an issue :)

**Pull request merged**
