### PR TITLE
chore: specify example of desktop autostart file in docs

### PR DESCRIPTION
**Pull request by froblesmartin**

### CODE REVIEW

**Comment by pfps** [comment]
The commit message should be something like `docs: provide pointer to ...`
Also the pointer should either be a relative file name (i.e., remove the leading slash) or the URL of the file in the github repository or both.

**Comment by froblesmartin** [comment]
Updated

**Review by pfps — APPROVED** [review]
Looks good.

**Comment by pfps** [comment]
Ooops - failed some style check.

**Comment by pfps** [comment]
Thanks.

**Comment by froblesmartin** [comment]
> Thanks.

Thanks to you for this nice software! :smiley:

**Pull request merged**
