### PR TITLE
Improve polish translations

### PR DESCRIPTION
**Pull request by aso824**
Added some missing polish translations and fixed typos in existing.

Unfortunately, my newest version of POEdit reformatted whole file.

### CODE REVIEW

**Comment by pfps** [comment]
As I don't speak Polish I can't comment on the actual translation.
A couple of changes:
- the version should be updated
- if your email isn't the one in the translation, please put yours in (if you are comfortable with that)

**Comment by aso824** [comment]
@pfps sure, updated & changed `Last-Translator`

**Comment by pfps** [comment]
Looks OK by me, but I have no idea whether the translation is correct.  (Cue Monty Python Hungarian translation skit.)
@FFY00 Do we do anything more here before merging?

**Comment by FFY00** [comment]
@pfps, in these cases you can just merge the changes. If you know someone who speaks the language you can ask them to just do a sanity check.

**Pull request merged**
