### PR TITLE
settings: use classes for settings

### PR DESCRIPTION
**Pull request by pfps**

### CODE REVIEW

**Comment by pfps** [comment]
A setting class has a validator_class class variable.
The validator_class has a kind class variable, which tells what kinds of values the setting takes
The possibilities are toggle, choice, range, map_choice, multiple_toggle, and multiple_range

toggle is a boolean, no more information is needed.
range is an integer range, look in the class or setting validator for min_value and max_value
choice is an element of a NamedInts?, look in the class for choices_universe and choices_extra
       	     	     	  	     look in the setting validator for choices
map_choice is a map from NamedInts to NamedInts?, look in the class for keys_universe and choices_universe
       	     	     	  	     look in the setting validator for choices
multiple_toggle is a map from elements of a list to booleans, look in the class for choices_universe
 		     	      look in the setting validator for options

multiple_range is complicated and not implemented

I think that NamedInts are used in most places indicated but maybe there are places where some oher set-like structure is used.
I have provided values for some of the universes.  A couple could end up being tricky.

**Comment by viniciusbm** [comment]
Running 239d766469752ec8a80470fc8a45dbe2b05ea6b0, the GUI shows no settings.

<details>

<summary>There are some errors in the log:</summary>

```$ ./bin/solaar -dd 
16:28:56,902     INFO [MainThread] root: language en_GB (UTF-8), translations path None
16:28:58,687     INFO [MainThread] logitech_receiver.diversion: loaded 3 rules from /home/vbm/.config/solaar/rules.yaml
16:28:58,862     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
16:28:59,044     INFO [MainThread] solaar.ui.notify: starting desktop notifications
16:28:59,582     INFO [MainThread] solaar.listener: starting receiver listening threads
16:28:59,597     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw1', vendor_id='046D', product_id='C52B', serial='', release=None, manufacturer=None, product=None, interface=2, driver='logitech-djreceiver', bus_id=3, isDevice=None)
16:28:59,597     INFO [MainThread] logitech_receiver.base: New lock 15
16:28:59,606     INFO [ReceiverListener:hidraw1] logitech_receiver.listener: started with <UnifyingReceiver(/dev/hidraw1,15)> (15)
16:28:59,607     INFO [ReceiverListener:hidraw1] solaar.listener: <UnifyingReceiver(/dev/hidraw1,15)>: notifications listener has started (15)
16:28:59,607     INFO [ReceiverListener:hidraw1] logitech_receiver.base: New lock <_ThreadedHandle(/dev/hidraw1)>
16:28:59,614     INFO [ReceiverListener:hidraw1] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,15)>: receiver notifications enabled => ('wireless', 'software present')
16:28:59,618     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,15)>: present, No paired devices. (0) 
16:28:59,632     INFO [ReceiverListener:hidraw1] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,15)>: found new device 1 (404D)
16:28:59,633     INFO [ReceiverListener:hidraw1] solaar.listener: connection Notification(10,1,41,04,314D40) for <Device(1,404D,Wireless Touch Keyboard K400 Plus,6DC5C81C)> (keyboard)
16:28:59,636     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,15)>: present, 1 paired device. (0) 
16:28:59,636     INFO [ReceiverListener:hidraw1] logitech_receiver.base: New lock 16
16:29:00,792     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <Device(1,404D,Wireless Touch Keyboard K400 Plus,6DC5C81C)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 90, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 50, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
16:29:00,832     INFO [ReceiverListener:hidraw1] logitech_receiver.device: <Device(1,404D,Wireless Touch Keyboard K400 Plus,6DC5C81C)>: unitId 641487CF does not match serial 6DC5C81C
16:29:00,872     INFO [ReceiverListener:hidraw1] logitech_receiver.settings_templates: check_feature fn-swap [NEW FN INVERSION] detected <Setting([feature:toggle] K400 Plus:fn-swap=None)>
16:29:01,338     INFO [ReceiverListener:hidraw1] logitech_receiver.settings_templates: check_feature divert-keys [REPROG CONTROLS V4] detected <Setting([feature:map choice] K400 Plus:divert-keys=None)>
16:29:01,379     INFO [ReceiverListener:hidraw1] logitech_receiver.settings_templates: check_feature disable-keyboard-keys [KEYBOARD DISABLE KEYS] detected <Setting([feature:multiple toggle] K400 Plus:disable-keyboard-keys=None)>
16:29:01,478     INFO [ReceiverListener:hidraw1] logitech_receiver.settings_templates: check_feature gesture2-gestures [GESTURE 2] detected <Setting([feature:multiple toggle] K400 Plus:gesture2-gestures=None)>
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
  File "/var/tmp/Solaar/lib/logitech_receiver/settings.py", line 331, in __str__
    self._rw.kind, self._validator.kind if self._validator else None, self._device.codename, self.name, self._value
AttributeError: 'tuple' object has no attribute 'kind'
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/var/tmp/Solaar/lib/logitech_receiver/listener.py", line 190, in run
    self._notifications_callback(n)
  File "/var/tmp/Solaar/lib/solaar/listener.py", line 263, in _notifications_handler
    _notifications.process(dev, n)
  File "/var/tmp/Solaar/lib/logitech_receiver/notifications.py", line 60, in process
    return _process_device_notification(device, status, notification)
  File "/var/tmp/Solaar/lib/logitech_receiver/notifications.py", line 175, in _process_device_notification
    return _process_hidpp10_notification(device, status, n)
  File "/var/tmp/Solaar/lib/logitech_receiver/notifications.py", line 285, in _process_hidpp10_notification
    status.changed(active=link_established)
  File "/var/tmp/Solaar/lib/logitech_receiver/status.py", line 312, in changed
    _log.info('%s pushing device settings %s', d, d.settings)
  File "/var/tmp/Solaar/lib/logitech_receiver/device.py", line 319, in settings
    self._feature_settings_checked = _check_feature_settings(self, self._settings)
  File "/var/tmp/Solaar/lib/logitech_receiver/settings_templates.py", line 1034, in check_feature_settings
    setting = check_feature(device, sclass)
  File "/var/tmp/Solaar/lib/logitech_receiver/settings_templates.py", line 1015, in check_feature
    _log.info('check_feature %s [%s] detected %s', sclass.name, sclass.feature, detected)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
  File "/var/tmp/Solaar/lib/logitech_receiver/settings.py", line 331, in __str__
    self._rw.kind, self._validator.kind if self._validator else None, self._device.codename, self.name, self._value
AttributeError: 'tuple' object has no attribute 'kind'
Call stack:
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/var/tmp/Solaar/lib/logitech_receiver/listener.py", line 190, in run
    self._notifications_callback(n)
  File "/var/tmp/Solaar/lib/solaar/listener.py", line 263, in _notifications_handler
    _notifications.process(dev, n)
  File "/var/tmp/Solaar/lib/logitech_receiver/notifications.py", line 60, in process
    return _process_device_notification(device, status, notification)
  File "/var/tmp/Solaar/lib/logitech_receiver/notifications.py", line 175, in _process_device_notification
    return _process_hidpp10_notification(device, status, n)
  File "/var/tmp/Solaar/lib/logitech_receiver/notifications.py", line 285, in _process_hidpp10_notification
    status.changed(active=link_established)
  File "/var/tmp/Solaar/lib/logitech_receiver/status.py", line 312, in changed
    _log.info('%s pushing device settings %s', d, d.settings)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
16:29:02,002  WARNING [ReceiverListener:hidraw1] logitech_receiver.settings: gesture2-params: error applying value {'4': {'scale': 258}} so ignore it (<Device(1,404D,Wireless Touch Keyboard K400 Plus,6DC5C81C)>)
16:29:02,002     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <Device(1,404D,Wireless Touch Keyboard K400 Plus,6DC5C81C)>: paired online, {'LINK ENCRYPTED': True, 'BATTERY LEVEL': 90, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'BATTERY NEXT LEVEL': 50, 'BATTERY VOLTAGE': None, 'BATTERY CHARGING': False, 'ERROR': None} (0) 
16:29:02,008     INFO [ReceiverListener:hidraw1] logitech_receiver.notifications: <Device(1,404D,Wireless Touch Keyboard K400 Plus,6DC5C81C)>: spurious BATTERY status Notification(11,1,06,10,0400C21C0A0000000000000000000000)
Traceback (most recent call last):
  File "/var/tmp/Solaar/lib/solaar/ui/window.py", line 396, in _device_selected
    _update_info_panel(device, full=True)
  File "/var/tmp/Solaar/lib/solaar/ui/window.py", line 795, in _update_info_panel
    _update_device_panel(device, _info._device, _info._buttons, full)
  File "/var/tmp/Solaar/lib/solaar/ui/window.py", line 766, in _update_device_panel
    _config_panel.update(device, is_online)
  File "/var/tmp/Solaar/lib/solaar/ui/config_panel.py", line 604, in update
    sbox = _items[k] = _create_sbox(s, device)
  File "/var/tmp/Solaar/lib/solaar/ui/config_panel.py", line 532, in _create_sbox
    raise Exception('NotImplemented')
Exception: NotImplemented
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_var_tmp_Solaar_bin_solaar.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/var/tmp/Solaar/lib/solaar/ui/window.py", line 396, in _device_selected
    _update_info_panel(device, full=True)
  File "/var/tmp/Solaar/lib/solaar/ui/window.py", line 795, in _update_info_panel
    _update_device_panel(device, _info._device, _info._buttons, full)
  File "/var/tmp/Solaar/lib/solaar/ui/window.py", line 766, in _update_device_panel
    _config_panel.update(device, is_online)
  File "/var/tmp/Solaar/lib/solaar/ui/config_panel.py", line 604, in update
    sbox = _items[k] = _create_sbox(s, device)
  File "/var/tmp/Solaar/lib/solaar/ui/config_panel.py", line 532, in _create_sbox
    raise Exception('NotImplemented')
Exception: NotImplemented
```

</details>

**Comment by viniciusbm** [comment]
`solaar show`

```
...
        13: GESTURE 2              {6501}   
            Gestures (saved): {'1': True, '10': True, '2': True, '30': True, '34': False, '42': True, '43': True, '45': False, '64': False, '65': False, '67': False, '84': False}
            Gestures        : {'1': True, '2': True, '30': True, '10': True, '45': False, '42': True, '43': True, '64': False, '65': False, '67': False, '84': False, '34': False}
            Gesture params (saved): {'4': {'scale': 258}}
solaar: error: Traceback (most recent call last):
  File "/var/tmp/Solaar/lib/solaar/cli/__init__.py", line 204, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/var/tmp/Solaar/lib/solaar/cli/show.py", line 289, in run
    _print_device(dev)
  File "/var/tmp/Solaar/lib/solaar/cli/show.py", line 237, in _print_device
    v = setting.read(False)
  File "/var/tmp/Solaar/lib/logitech_receiver/settings.py", line 455, in read
    for item in self._validator.items:
AttributeError: 'tuple' object has no attribute 'items'
```

**Comment by pfps** [comment]
OK, I think I fixed that bug.

**Comment by viniciusbm** [comment]
It's working now.

**Comment by viniciusbm** [comment]
A few issues: 

- To be consistent with the other settings, I think `ChangeHost.choices_universe` should be `NamedInts`. Since the names must be valid identifiers, how about `NamedInts(**{'Host ' + str(i + 1): i for i in range(3)})`?
- `DivertGkeys` does not extend `Setting` (is this right?), thus it doesn't have a `validator_class`.
- `LowresSmoothScroll.label` is currently a tuple due to an extra comma at the end of the line.

**Comment by pfps** [comment]
Thanks.  The two bugs should be fixed and I took your suggestion.

I think that adjustable dpi  and multiplatform are the only problematic settings.  Well, except for gesture2params but that doesn't have a Set implementation.

RegisterDpi might also be problematic but there is only one device that uses it so I just put that device's choices in the general class.

**Comment by pfps** [comment]
@barolo @sk8geek @mschilli87 This PR changes the code for all the GUI settings so it could use some testing.  To test, just run this PR and start up `bin/solaar -d`.  All the settings that used to be on your devices should still work and there should be no unusual errors or warnings.

**Comment by viniciusbm** [comment]
> Thanks. The two bugs should be fixed and I took your suggestion.

Thanks. I've just noticed that `DivertKeys.choices_universe` is also a list rather than `NamedInts`. 

Since it's already ready for testing, I can make that change in my PR if you want.

**Comment by viniciusbm** [comment]
> I think that adjustable dpi and multiplatform are the only problematic settings.

Shouldn't `AdjustableDpi` have `choices_universe`?

**Comment by pfps** [comment]
Go ahead and make changes for DivertKeys.

The problem with AdjustableDpi is that the dpis could be just about anything.  My MX Master 3 has a bunch of possibilities spread out from about 400 to about 4000.

**Comment by pfps** [comment]
Multiplatform is a strange mapping from OS, version, release to device behaviour.  Perhaps a reasonable universe would be NamedInts(**{'OS ' + str(i + 1): i for i in range(8)}).  That is probably more choices than any device has.

**Comment by viniciusbm** [comment]
> Perhaps a reasonable universe would be NamedInts(**{'OS ' + str(i + 1): i for i in range(8)}). That is probably more choices than any device has.

Thanks, I'll use that.

**Comment by pfps** [comment]
Looking good.  Here are a few issues.

Sensitivity (DPI) has too few choices, and the saved value looks unusual (maybe they come from the register version).  I think the problem here is that the setting name is shared between two settings that are quite different.   I think the best solution might be to break them apart by renaming the register one to something like 'dpi-old' 'Sensitivity (older mice)'.  Users with devices that use this setting will need to redo it.

The choices for SetOS contains both generic and device-specific choices.  I think that if there are device-specific choices only those should be available.

The range for Scroll Wheel Ratchet should be 0 to 50, I think.    This should already be available in both the setting class and in settings.

I don't like having two widgets for the device.  Would it be possible to have a widget that shows the current on-line devices plus a special value for originating device but also allows for serial/unit ID entry (8 hex digits)?  When an on-line device is selected only valid choices for that device's settings are allowed.

**Comment by viniciusbm** [comment]
`solaar config` seems to be broken in 99b98791a946f7c5c69f2fbe9210847ea6083dc0, but I fixed it in #1422 (which is based on this one and has your commit).

**Comment by pfps** [comment]
OK, thanks.

**Pull request merged**
