### PR TITLE
process hid report descriptors to identify hid++ devices

### LINKED ISSUE #1780: Logitech, Inc. PRO Gaming Keyboard not recognized
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): **1.1.5**
- Distribution: **RPM**
- Kernel version (ex. `uname -srmo`): **Linux 5.19.12-200.fc36.x86_64 x86_64 GNU/Linux**
- Output of `solaar show` for the target device (if applicable): **NA**

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Logitech, Inc. PRO Gaming Keyboard support added

### PR DESCRIPTION
**Pull request by pfps**
Fixes #1780

### CODE REVIEW

**Comment by pfps** [comment]
barolo @sk8geek @mschilli87 @viniciusbm  This PR changes how Solaar identifies devices and could use some testing.

To test, clone Solaar and download the PR.  Also install Python hid-tools via `pip install --user hid-tools`.  Then run Solaar as `bin/solaar -dd`.  Check that there are no warnings or errors and that all your devices show up correctly.   Post output of `bin/solaar -dd show`.  Thanks.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1783, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1783/head:pull_1783
git checkout pull_1783
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1783
git fetch origin pull/1783/head
git reset --hard FETCH_HEAD
```

**Comment by viniciusbm** [comment]
I see five warnings "hidapi.udev: Report Descriptor not processed for BID...", but I don't know if they're related to this PR:

[log1.txt](https://github.com/pwr-Solaar/Solaar/files/9720574/log1.txt)
[show1.txt](https://github.com/pwr-Solaar/Solaar/files/9720575/show1.txt)

**Comment by pfps** [comment]
@viniciusbm The warnings are definitiely relevant to this PR.  They are saying that processing the report descriptors ran into some problem.   I expect that the problem is that Solaar couldn't find the hidtools library.  Did you use pip to install hid-tools?  

I improved the warning message to show the actual exception.  Please download the PR and try again.  Thanks.

**Comment by viniciusbm** [comment]
> Did you use pip to install hid-tools?

Sorry, I've just checked that I had installed it in a different Python environment. 

Since the lack of that package doesn't seem to cause other issues, perhaps the warning should mention that missing hid-tools is a possible reason, so that the user can figure it out without asking. 

I tried it again (still in the old commit 108188551c88575bc4b99782804535a60ea96954) after installing hid-tools in the correct environment, and the warnings are gone, but now it finds a new unknown device:

image


[log2.txt](https://github.com/pwr-Solaar/Solaar/files/9723561/log2.txt)
[show2.txt](https://github.com/pwr-Solaar/Solaar/files/9723562/show2.txt)

After the new commit ff142e8c68bbc6554de0513d0832051fd1502ec3, it looks the same:

[log3.txt](https://github.com/pwr-Solaar/Solaar/files/9723584/log3.txt)
[show3.txt](https://github.com/pwr-Solaar/Solaar/files/9723585/show3.txt)


The unknown device corresponds to a Dell mouse (and it's no longer shown if I remove its receiver, which has nothing to do with the Logitech keyboard): 

```shell
$ lsusb | grep -i c535
Bus 002 Device 010: ID 046d:c535 Logitech, Inc. Dell Wireless Mouse WM123
```

Using `usb-devices`, it looks like the mouse was actually manufactured by Logitech:

```
T:  Bus=02 Lev=01 Prnt=01 Port=02 Cnt=03 Dev#= 10 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS= 8 #Cfgs=  1
P:  Vendor=046d ProdID=c535 Rev=31.00
S:  Manufacturer=Logitech
S:  Product=Dell Wireless Mouse WM123
C:  #Ifs= 2 Cfg#= 1 Atr=a0 MxPwr=98mA
I:  If#=0x0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=02 Driver=usbhid
I:  If#=0x1 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
```

It's a very simple mouse with no settings, so I don't think Solaar would be able to do anything with it (maybe the battery status could be shown in case it's reported by the device, but since the mouse has a small LED that changes colour depending on the battery level, it wouldn't be a useful feature anyway).

Is there something else I can test?

**Comment by pfps** [comment]
@viniciusbm The change to the PR is precisely to show whether hidtools is present.

As you have noticed, your mouse is actually made by Logitech and uses the Logitech HID++ protocol.  Solaar doesn't know about the receiver, so it thinks the receiver is a device and doesn't probe it for the devices connected through it.   Solaar might be able to do something with the receiver and device if I get more information.  

To find out more about the receiver from the Solaar download directory run
```
./tools/hidconsole /dev/hidrawN
```
and give it the commands `10ff8102000000`, `10ff83b5020000`, `10ff83b5200000`,  `10ff83b5300000`, and `10ff83b5400000`.  Grab the output and paste here.

/dev/hidrawN is the device node for the receiver.   One way to find out which node to use is to run
```
udevadm info -q path -n /dev/hidraw*
```
and see which line has the USB ID (0003:046D:C535) for the receiver.

**Comment by viniciusbm** [comment]
> As you have noticed, your mouse is actually made by Logitech and uses the Logitech HID++ protocol.

That was surprising, especially because it's a basic mouse I bought almost seven years ago.



> and give it the commands 10ff8102000000, 10ff83b5020000, 10ff83b5200000, 10ff83b5300000, and 10ff83b5400000. Grab the output and paste here.


```
?? Input: 10ff8102000000
<< (   2.952) [10 FF 8102 000000] b'\x10\xff\x81\x02\x00\x00\x00'
>> (   2.956) [10 FF 8102 00012C] b'\x10\xff\x81\x02\x00\x01,'
?? Input: 10ff83b5020000
<< (   6.737) [10 FF 83B5 020000] b'\x10\xff\x83\xb5\x02\x00\x00'
>> (   6.738) [11 FF 83B5 0231000001800A040000000000000000] b'\x11\xff\x83\xb5\x021\x00\x00\x01\x80\n\x04\x00\x00\x00\x00\x00\x00\x00\x00'
?? Input: 10ff83b5200000
<< (  12.022) [10 FF 83B5 200000] b'\x10\xff\x83\xb5 \x00\x00'
>> (  12.026) [11 FF 83B5 200708401B0400020600000000000000] b'\x11\xff\x83\xb5 \x07\x08@\x1b\x04\x00\x02\x06\x00\x00\x00\x00\x00\x00\x00'
?? Input: 10ff83b5300000
<< (  15.186) [10 FF 83B5 300000] b'\x10\xff\x83\xb50\x00\x00'
>> (  15.188) [11 FF 83B5 30D225825E0400000001000000000000] b'\x11\xff\x83\xb50\xd2%\x82^\x04\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00'
?? Input: 10ff83b5400000
<< (  19.130) [10 FF 83B5 400000] b'\x10\xff\x83\xb5@\x00\x00'
>> (  19.132) [11 FF 83B5 40000000000000000000000000000000] b'\x11\xff\x83\xb5@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'


```

**Comment by pfps** [comment]
@viniciusbm There are a number of Dell-branded mice and keyboards that are really Logitech devices.  Some of them even can be paired with any Unifying receiver and some of them are low-end devices like the Logitech M185.  I'm not sure whether your mouse can be paired with a Unifying receiver.  You could try to pair the mouse with your unifying receiver - if it doesn't work the most likely outcome is that the mouse stays paired with the Dell-branded receiver.  

I've added code to this PR to recognize your Dell receiver as a nano receiver.    Please download this PR again and try `bin/solaar show` and post the result.  Then try `bin/solaar probe XXX` where XXX is the name that shows up for the receiver and post the result. 

Thanks.

**Comment by viniciusbm** [comment]
> Please download this PR again and try bin/solaar show and post the result.

```
Solaar version 1.1.5

Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:C52B
  Serial       : BE57977A
    Firmware   : 24.11.B0036
    Bootloader : 02.09
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=71

  1: Wireless Touch Keyboard K400 Plus
     Device path  : /dev/hidraw2
     WPID         : 404D
     Codename     : K400 Plus
     Kind         : keyboard
     Protocol     : HID++ 2.0
     Polling rate : 8 ms (125Hz)
     Serial number: 6DC5C81C
     The power switch is located on the top edge.
     Battery: unknown (device is offline).

Nano Receiver
  Device path  : /dev/hidraw5
  USB id       : 046d:C535
  Serial       : 1F3F94FC
    Firmware   : 31.00.B0001
  Has 1 paired device(s) out of a maximum of 1.
  Has 39 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  1: Wireless Mouse M215 2nd Gen
     Device path  : None
     WPID         : 401B
     Codename     : Wireless
     Kind         : mouse
     Protocol     : HID++ 2.0
     Polling rate : 8 ms (125Hz)
     Serial number: D225825E
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RQM 27.12.B0029
     The power switch is located on the base.
     Supports 13 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V0     
            Firmware: Firmware RQM 27.12.B0029 401B
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         3: DEVICE NAME            {0005} V0     
            Name: Wireless Mouse M215 2nd Gen
            Kind: mouse
         4: BATTERY STATUS         {1000} V0     
            Battery: 90%, discharging, next level 5%.
         5: WIRELESS DEVICE STATUS {1D4B} V0     
         6: unknown:1DF3           {1DF3} V0    hidden 
         7: REPROG CONTROLS        {1B00} V0     
         8: REMAINING PAIRING      {1DF0} V0    hidden 
            Remaining Pairings: 126
         9: unknown:1F03           {1F03} V0    hidden 
        10: VERTICAL SCROLLING     {2100} V0     
            Roller type: standard
            Ratchet per turn: 24
            Scroll lines: 0
        11: HI RES SCROLLING       {2120} V0     
            Hi-res scrolling disabled
            Hi-res scrolling multiplier: 8
            Scroll Wheel High Resolution (saved): False
            Scroll Wheel High Resolution        : False
        12: MOUSE POINTER          {2200} V0     
            DPI: 800
            Acceleration: low
            Override OS ballistics
            No vertical tuning, standard mice
     Battery: 90%, discharging, next level 5%.

```

>  Then try bin/solaar probe XXX where XXX is the name that shows up for the receiver and post the result.

[probe.txt](https://github.com/pwr-Solaar/Solaar/files/9729809/probe.txt)

**Comment by pfps** [comment]
@viniciusbm So the mouse has some features that Solaar can control.

**Comment by viniciusbm** [comment]
> I'm not sure whether your mouse can be paired with a Unifying receiver. You could try to pair the mouse with your unifying receiver 

Out of curiosity, I unplugged the Dell receiver and tried to pair the mouse with the Logitech Unifying Receiver, but it always times out, so I guess it's not compatible.  

> if it doesn't work the most likely outcome is that the mouse stays paired with the Dell-branded receiver.

Indeed, it remains paired with its original receiver. 

> There are a number of Dell-branded mice and keyboards that are really Logitech devices.

image

The name on the left ("Wireless") is generic, but I'm not sure if it's obtained from the device itself. The name shown on the right seems to be correct, as the pictures of Logitech M215 I found online are identical to the Dell WM123 mouse except for the logo. 

> So the mouse has some features that Solaar can control.

Yes, it shows a setting related to the wheel, and in fact it can be changed by Solaar (the wheel becomes too fast if I enable it). It also shows the battery level. 

Thanks.

**Comment by pfps** [comment]
@viniciusbm The shorter name comes from the receiver.  Receivers are supposed to show decent short names but some of them don't.  Some devices provide a shorter name but this one doesn't.  The longer name comes from the device itself - you can see it in the output of `solaar show`.

This is a low-end device and low-end receiver which only allow a certain number of pairing changes, as you can also see in the output of `solaar show`.

**Comment by viniciusbm** [comment]
> This is a low-end device and low-end receiver 

Yes, that's why I didn't even think it would have settings and report the battery level, so it was an interesting surprise. 

> The shorter name comes from the receiver. Receivers are supposed to show decent short names but some of them don't. Some devices provide a shorter name but this one doesn't. The longer name comes from the device itself - you can see it in the output of solaar show.

Thank you for the information.

**Comment by pfps** [comment]
@viniciusbm Another change was made to the PR, this one to use a different, simpler system to parse report descriptors.  Run Solaar as `bin/solaar -dd`.  Check that all your devices show up.

**Comment by viniciusbm** [comment]
> Run Solaar as `bin/solaar -dd`. Check that all your devices show up.

At d4d6f3449a3845530d7d13161b55fb6eb1c702dd:

[log4.txt](https://github.com/pwr-Solaar/Solaar/files/9743043/log4.txt)

The devices show up normally, without warnings or errors.

**Comment by pfps** [comment]
Excellent.  Thanks.

**Comment by dvzrv** [comment]
@pfps [hid-parser is available on pypi.org](https://pypi.org/project/hid-parser/), why was it included as a git submodule? That's really quite anti to how libs are used in python land and now requires all downstreams to patch around this and remove this vendoring again. :confused: 
Why was this not required as a normal dependency instead?

**Pull request merged**
