### PR TITLE
docs: add supported feature for M330

### PR DESCRIPTION
**Pull request by svntjng**
Add HID++ version and DPI for M330.

### CODE REVIEW

**Comment by Klap-in** [comment]
A note: version 4.5 means actual protocol version 2.0. That was an improvement in the last documentation pull request, please see https://github.com/pwr-Solaar/Solaar/pull/639 for more info.

**Comment by FFY00** [comment]
Yes, please replace 4.5 with 2.0 :)

**Comment by pfps** [comment]
The recent updates to document require this PR to be updated.
@svntjng Are you still active?  If so, please update the PR.  
I'll try to fold this in to my next update to documentation if it hasn't been merged yet.

**Comment by pfps** [comment]
@svntjng Thanks for the quick response, but I'm going to be a nit-picker.

Instead of having two commits for this change, could you produce one commit only?
Because you are working on your master branch I think the easiest way for you to do this is
`git reset --hard master^`
Change devices.md. 
Amend your initial commit via
`git commit --amend --no-edit`
Force push this commit.  If your github repository is your upstream you can do this via
`git push --force upstream master`

(I hope I have this all right.)

Thanks,
peter

**Comment by pfps** [comment]
@FFY00 What has gone wrong here?  Did I ask @svntjng to do  something wrong?

**Comment by FFY00** [comment]
> @FFY00 What has gone wrong here? Did I ask @svntjng to do something wrong?

While I don't like the approach, it should squash the commits together. The issue here is that we made changes to that file in `master` so he needs to rebase it.

FWYI this how I would have done it:
```
git fetch origin
git rebase -i origin/master
```
Then replace the action in the last commit from `pick` to `s`/`squash` and close the editor.

**Comment by FFY00** [comment]
I pushed this directly to avoid more confusion.

**Pull request closed without merging**
