### PR TITLE
Refactor hidpp and introduce classes

### PR DESCRIPTION
**Pull request by MattHag**

### CODE REVIEW

**Comment by MattHag** [comment]
Next, 

- hidpp10 read_register and write_register could be moved into the device class.
- hidpp20 feature_request can be moved into device class.

**Comment by pfps** [comment]
There are errors:

<details>

```
idefix Solaar> bin/solaar -d
Exception in thread ReceiverListener:hidraw6:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/listener.py", line 132, in run
    self.has_started()
  File "/home/local/SoftwareDownloads/Solaar/lib/solaar/listener.py", line 70, in has_started
    nfs = self.receiver.enable_connection_notifications()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/receiver.py", line 127, in enable_connection_notifications
    ok = hidpp10.set_notification_flags(self, set_flag_bits)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logitech_receiver.hidpp10' has no attribute 'set_notification_flags'
Exception in thread ReceiverListener:hidraw7:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/listener.py", line 136, in run
    self.receiver.status.changed(True, reason="initialization")
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/status.py", line 243, in changed
    self.read_battery()
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/status.py", line 213, in read_battery
    battery = self._device.battery()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/device.py", line 323, in battery
    result = _hidpp20.get_battery(self, battery_feature)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/hidpp20.py", line 1519, in get_battery
    result = battery_function(device)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/hidpp20.py", line 1481, in get_battery_status
    return self.decipher_battery_status(report)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Hidpp20' object has no attribute 'decipher_battery_status'. Did you mean: 'get_battery_status'?
Traceback (most recent call last):
  File "/home/local/SoftwareDownloads/Solaar/lib/solaar/ui/window.py", line 396, in _device_selected
    _update_info_panel(device, full=True)
  File "/home/local/SoftwareDownloads/Solaar/lib/solaar/ui/window.py", line 803, in _update_info_panel
    _update_device_panel(device, _info._device, _info._buttons, full)
  File "/home/local/SoftwareDownloads/Solaar/lib/solaar/ui/window.py", line 690, in _update_device_panel
    device.status.read_battery()
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/status.py", line 213, in read_battery
    battery = self._device.battery()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/device.py", line 323, in battery
    result = _hidpp20.get_battery(self, battery_feature)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/hidpp20.py", line 1519, in get_battery
    result = battery_function(device)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/hidpp20.py", line 1481, in get_battery_status
    return self.decipher_battery_status(report)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Hidpp20' object has no attribute 'decipher_battery_status'. Did you mean: 'get_battery_status'?
Exception in thread ReceiverListener:hidraw10:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/listener.py", line 136, in run
    self.receiver.status.changed(True, reason="initialization")
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/status.py", line 243, in changed
    self.read_battery()
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/status.py", line 213, in read_battery
    battery = self._device.battery()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/device.py", line 323, in battery
    result = _hidpp20.get_battery(self, battery_feature)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/hidpp20.py", line 1519, in get_battery
    result = battery_function(device)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/hidpp20.py", line 1481, in get_battery_status
    return self.decipher_battery_status(report)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Hidpp20' object has no attribute 'decipher_battery_status'. Did you mean: 'get_battery_status'?
```

</details>

**Comment by pfps** [comment]
Still errors:

<details>

```
/home/local/SoftwareDownloads/Solaar 
idefix Solaar> pwd
/home/local/SoftwareDownloads/Solaar
idefix Solaar> bin/solaar 
Traceback (most recent call last):
  File "/home/local/SoftwareDownloads/Solaar/lib/solaar/ui/window.py", line 396, in _device_selected
    _update_info_panel(device, full=True)
  File "/home/local/SoftwareDownloads/Solaar/lib/solaar/ui/window.py", line 803, in _update_info_panel
    _update_device_panel(device, _info._device, _info._buttons, full)
  File "/home/local/SoftwareDownloads/Solaar/lib/solaar/ui/window.py", line 690, in _update_device_panel
    device.status.read_battery()
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/status.py", line 213, in read_battery
    battery = self._device.battery()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/SoftwareDownloads/Solaar/lib/logitech_receiver/device.py", line 319, in battery
    return hidpp10.get_battery(self)
           ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logitech_receiver.hidpp10' has no attribute 'get_battery'
```
</details>

As there are only a few identifiers that remain in hidpp10, just search throughout the code base for users of hidpp10 that are not any of these.  The same should be done for hidpp20.

**Comment by pfps** [comment]
Git diff works badly here.  It is the case that the vast majority of changes in hidpp10 and hidpp20 are just reindentation?

**Comment by MattHag** [comment]
Basically it is but I'd call it switch to Hidpp classes.

**Comment by pfps** [comment]
Sorry, I meant "textual" changes.

**Comment by MattHag** [comment]
Yes, there's no change in behaviour and all the lines are as before.

**Pull request merged**
