### PR TITLE
use 0xFF for direct-connected devices

### LINKED ISSUE #1225: G102 LIGHTSYNC mouse support?
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): solaar 1.0.6
- Distribution: NixOS
- Kernel version (ex. `uname -srmo`): Linux 5.10.52 x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):

**Is your feature request related to a problem? Please describe.**

I'm using [Logitech G102 LIGHTSYNC](https://www.logitechg.com/en-in/products/gaming-mice/g102-lightsync-rgb-gaming-mouse.910-005803.html) wired mouse. I want to adjust DPI of it on Linux, and found this project.

I tried `solaar show` but it said it cannot find devices. When I plugged the mouse, there are two devices `/dev/hidraw5` and `/dev/hidraw6`. Then I tried `solaar -D /dev/hidraw5 show` (or hidraw6) but still show the same result.
I also tried my M590 (which is using bluetooth), and `solaar` is working well.

Is G102 not supported yet, or is there some issue handling it?
is there anything I can do to help supporting it?

### PR DESCRIPTION
**Pull request by pfps**
Fixed #1225

### CODE REVIEW

**Comment by oxalica** [comment]
Seems it still have trouble detecting features.

```
> ./bin/solaar -dd show
16:02:20,174    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Down"
16:02:20,174    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Up"
16:02:20,180    DEBUG [MainThread] solaar.ui.tray: using StatusIcon
16:02:20,220    DEBUG [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C092 INTERFACE 0 FILTER 1
16:02:20,220    DEBUG [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C092 INTERFACE 1 FILTER 1
16:02:20,221    DEBUG [MainThread] solaar.cli: [/dev/hidraw5] => <Device(255,C092,G102 Lightsync Mouse,?)>
Wired Devices
16:02:20,222    DEBUG [MainThread] logitech_receiver.base: (10) pinging device 255
16:02:20,223     INFO [MainThread] logitech_receiver.base: New lock 10
16:02:20,223    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 001E 000041]
16:02:20,226    DEBUG [MainThread] logitech_receiver.base: (10) => r[11 FF 001E 04024100000000000000000000000000]
  1: G102 Lightsync Mouse
     Device path  : /dev/hidraw5
     USB id       : 046d:C092
     Codename     : G102
     Kind         : mouse
     Protocol     : HID++ 4.2
     Serial number: ?
solaar: error: Traceback (most recent call last):
  File "/home/oxa/repo/tmp/Solaar/lib/solaar/cli/__init__.py", line 207, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/home/oxa/repo/tmp/Solaar/lib/solaar/cli/show.py", line 292, in run
    _print_device(d, num=dev_num)
  File "/home/oxa/repo/tmp/Solaar/lib/solaar/cli/show.py", line 238, in _print_device
    if dev.online and dev.keys:
  File "/home/oxa/repo/tmp/Solaar/lib/logitech_receiver/device.py", line 318, in keys
    self._keys = _hidpp20.get_keys(self) or ()
  File "/home/oxa/repo/tmp/Solaar/lib/logitech_receiver/hidpp20.py", line 1212, in get_keys
    if FEATURE.REPROG_CONTROLS in device.features:
TypeError: argument of type 'NoneType' is not iterable
```

And the GUI shows only `Battery` and `Wireless Link` on the right side panel, which are both not available for G102.
```
> ./bin/solaar -dd
16:06:15,452     INFO [MainThread] solaar.listener: starting receiver listening threads
16:06:15,465    DEBUG [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C092 INTERFACE 0 FILTER 1
16:06:15,465    DEBUG [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C092 INTERFACE 1 FILTER 1
16:06:15,466     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path='/dev/hidraw5', vendor_id='046D', product_id='C092', serial='205C346B5442', release=None, manufacturer=None, product=None, interface=1, driver='hid-generic', bus_id=3, isDevice=True)
16:06:15,466    DEBUG [MainThread] solaar.configuration: load => {}
16:06:15,467     INFO [MainThread] solaar.configuration: saved {'_version': '1.0.6'} to /home/oxa/.config/solaar/config.json
16:06:15,467     INFO [MainThread] logitech_receiver.status: <Device(255,C092,G102 Lightsync Mouse,?)> pushing device settings []
16:06:15,467     INFO [MainThread] logitech_receiver.base: New lock 17
16:06:15,467    DEBUG [MainThread] logitech_receiver.base: (17) <= w[10 FF 810D 000000]
16:06:15,471    DEBUG [MainThread] logitech_receiver.base: (17) => r[10 FF 8F81 0D0100]
16:06:15,471    DEBUG [MainThread] logitech_receiver.base: (17) device 0xFF error on request {810D}: 1 = invalid SubID/command
16:06:15,472    DEBUG [MainThread] logitech_receiver.base: (17) <= w[10 FF 8107 000000]
16:06:15,475    DEBUG [MainThread] logitech_receiver.base: (17) => r[10 FF 8F81 070100]
16:06:15,475    DEBUG [MainThread] logitech_receiver.base: (17) device 0xFF error on request {8107}: 1 = invalid SubID/command
16:06:15,475     INFO [MainThread] solaar.listener: status_changed <Device(255,C092,G102 Lightsync Mouse,?)>: paired online, {'NOTIFICATION FLAGS': False} (0)
16:06:15,476     INFO [ReceiverListener:hidraw5] logitech_receiver.listener: started with <Device(255,C092,G102 Lightsync Mouse,?)> (17)
16:06:15,476     INFO [ReceiverListener:hidraw5] solaar.listener: <Device(255,C092,G102 Lightsync Mouse,?)>: notifications listener has started (17)
16:06:15,476     INFO [ReceiverListener:hidraw5] solaar.listener: status_changed <Device(255,C092,G102 Lightsync Mouse,?)>: paired online, {'NOTIFICATION FLAGS': False} (0)
16:06:15,476    DEBUG [MainThread] solaar.ui: activate
16:06:15,495    DEBUG [MainThread] solaar.ui: status changed: <Device(255,C092,G102 Lightsync Mouse,?)> (NONE) None
16:06:15,495  WARNING [MainThread] solaar.ui.icons: icon battery-missing not found in current theme
16:06:15,496    DEBUG [MainThread] solaar.ui.tray: picked device with lowest battery: None
16:06:15,497    DEBUG [MainThread] solaar.ui.window: new device row ('/dev/hidraw5', 255, True, 'G102', None, None, None, <Device(255,C092,G102 Lightsync Mouse,?)>) at index 0
16:06:15,498     INFO [MainThread] logitech_receiver.base: New lock 18
16:06:15,498    DEBUG [MainThread] logitech_receiver.base: (18) <= w[10 FF 810D 000000]
16:06:15,502    DEBUG [MainThread] logitech_receiver.base: (18) => r[10 FF 8F81 0D0100]
16:06:15,502    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (17) => r[10 FF 8F81 0D0100]
16:06:15,502    DEBUG [MainThread] logitech_receiver.base: (18) device 0xFF error on request {810D}: 1 = invalid SubID/command
16:06:15,503    DEBUG [MainThread] logitech_receiver.base: (18) <= w[10 FF 8107 000000]
16:06:15,506    DEBUG [MainThread] logitech_receiver.base: (18) => r[10 FF 8F81 070100]
16:06:15,506    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (17) => r[10 FF 8F81 070100]
16:06:15,506    DEBUG [MainThread] logitech_receiver.base: (18) device 0xFF error on request {8107}: 1 = invalid SubID/command
16:06:15,506  WARNING [MainThread] solaar.ui.icons: icon battery-missing not found in current theme
16:06:15,508    DEBUG [MainThread] solaar.ui: status changed: <Device(255,C092,G102 Lightsync Mouse,?)> (NONE) None
16:06:15,508  WARNING [MainThread] solaar.ui.icons: icon battery-missing not found in current theme
16:06:15,508    DEBUG [MainThread] solaar.ui.tray: picked device with lowest battery: None
16:06:15,509    DEBUG [MainThread] logitech_receiver.base: (18) <= w[10 FF 810D 000000]
16:06:15,512    DEBUG [MainThread] logitech_receiver.base: (18) => r[10 FF 8F81 0D0100]
16:06:15,512    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (17) => r[10 FF 8F81 0D0100]
16:06:15,512    DEBUG [MainThread] logitech_receiver.base: (18) device 0xFF error on request {810D}: 1 = invalid SubID/command
16:06:15,512    DEBUG [MainThread] logitech_receiver.base: (18) <= w[10 FF 8107 000000]
16:06:15,516    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (17) => r[10 FF 8F81 070100]
16:06:15,517    DEBUG [MainThread] logitech_receiver.base: (18) => r[10 FF 8F81 070100]
16:06:15,517    DEBUG [MainThread] logitech_receiver.base: (18) device 0xFF error on request {8107}: 1 = invalid SubID/command
16:06:15,517  WARNING [MainThread] solaar.ui.icons: icon battery-missing not found in current theme
16:06:17,481    DEBUG [MainThread] solaar.ui: shutdown
16:06:17,481     INFO [MainThread] solaar.listener: stopping receiver listening threads [<ReceiverListener(ReceiverListener:hidraw5, started daemon 140680982689344)>]
16:06:17,482     INFO [MainThread] solaar.configuration: saved {'_version': '1.0.6', 'None:?': {'_name': 'G102 Lightsync Mouse'}} to /home/oxa/.config/solaar/config.json
16:06:17,519     INFO [ReceiverListener:hidraw5] solaar.listener: <Device(255,C092,G102 Lightsync Mouse,?)>: notifications listener has stopped
16:06:17,519    DEBUG [ReceiverListener:hidraw5] logitech_receiver.listener: <_ThreadedHandle(/dev/hidraw5)> closing [17, 18]
16:06:17,519    DEBUG [AsyncUI] solaar.tasks: stopped
16:06:17,520    DEBUG [MainThread] solaar.ui: status changed: <Device(255,C092,G102 Lightsync Mouse,?)> (NONE) None
```

**Comment by pfps** [comment]
Oops.  I put an interface 1.0 directive in for the G102, which causes lots of problems.  Please try again.

**Comment by oxalica** [comment]
It works. :tada: 
GUI now shows DPI and polling rate and they can both be changed without issue.

The mouse has also a RGB LED, which is configurable in Logitech G Hub. Can we also support LED configuration?

```
> ./bin/solaar show
Wired Devices
  1: G102 Lightsync Mouse
     Device path  : /dev/hidraw5
     USB id       : 046d:C092
     Codename     : G102
     Kind         : mouse
     Protocol     : HID++ 4.2
     Polling rate : 1 ms (1000Hz)
     Serial number: ?
     Model ID:      C09200000000
     Unit ID:       36002500
        Bootloader: BL1 17.00.B0005
          Firmware: U1  52.00.B0010
          Firmware:  00.00
             Other:
             Other:
     Supports 19 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: DEVICE FW VERSION      {0003}
            Firmware: Bootloader BL1 17.00.B0005 AAFD
            Firmware: Firmware U1  52.00.B0010 C092
            Firmware: Firmware  00.00
            Firmware: Other
            Firmware: Other
            Unit ID: 36002500  Model ID: C09200000000  Transport IDs: {'usbid': 'C092'}
         3: DEVICE NAME            {0005}
            Name: G102 LIGHTSYNC Gaming Mouse
            Kind: mouse
         4: unknown:1801           {1801}   internal, hidden
         5: DEVICE RESET           {1802}   internal, hidden
         6: CONFIG DEVICE PROPS    {1806}   internal, hidden
         7: unknown:1E00           {1E00}   hidden
         8: unknown:1E22           {1E22}   internal, hidden
         9: unknown:1EB0           {1EB0}   internal, hidden
        10: ADJUSTABLE DPI         {2201}
            Sensitivity (DPI) (saved): 3000
            Sensitivity (DPI)        : 3000
        11: unknown:18B1           {18B1}   internal, hidden
        12: DFUCONTROL SIGNED      {00C2}
        13: REPORT RATE            {8060}
            Polling Rate (ms): 1
            Polling Rate (ms) (saved): 1
            Polling Rate (ms)        : 1
        14: RGB EFFECTS            {8071}
        15: ONBOARD PROFILES       {8100}
            Device Mode: Host
        16: MOUSE BUTTON SPY       {8110}
        17: unknown:18A1           {18A1}   internal, hidden
        18: PER KEY LIGHTING V2    {8081}
     Battery status unavailable.
```

**Comment by pfps** [comment]
It's possible to support this, but not high priority.
Put in an enhancement request and  mention features 8070 8071 8080 and 8081.
Also include `solaar show` for your mouse;

**Comment by pfps** [comment]
@barolo @sk8geek @mschilli87  This change could use some more testing, even though it has been merged.  If you have a device that doesn't use a receiver please update to the current version of Solaar here and check whether Solaar handles the device correctly.

**Comment by sk8geek** [comment]
Apologies for the late reply. I connect using a unifying receiver. (Old laptop has old Bluetooth that doesn't see the keyboard.)

**Pull request merged**
