### PR TITLE
Partial support for macOS and Windows

### PR DESCRIPTION
**Pull request by markopy**
This PR is related to #1244 and #1586 and adds support for macOS and potentially Windows (untested, see below) by using a platform independent library (https://github.com/libusb/hidapi) for device access. Solaar will be able to pair and configure devices but the rule and diversion system will not work because it is Linux specific and not really portable.

## macOS
For macOS all dependencies can be installed via homebrew: `brew install hidapi gtk+3 pygobject3`

## Windows
This PR should also support Windows without any further changes but I don't have the environment to test this. If someone wants to give this a try the first step would be to obtain the hdiapi DLL from https://github.com/libusb/hidapi/releases and check that the command line interface works.

Getting the GUI to work requires GTK which seems non-trivial to install on windows. The starting point for this would be https://pygobject.readthedocs.io/en/latest/getting_started.html#windows-getting-started

### CODE REVIEW

**Comment by pfps** [comment]
Please fix up the style errors caught by the pre-commit scripts.  Ideally you should set up git to run them when you check in changes on your machine.

**Comment by pfps** [comment]
It would be useful to see whether this port can detect devices on USB and Bluetooth and devices that are not described in lib/logitech_receiver/descriptors.py

**Comment by markopy** [comment]
> It would be useful to see whether this port can detect devices on USB and Bluetooth and devices that are not described in lib/logitech_receiver/descriptors.py.

I removed my devices from `descriptors.py` and they were still picked up while being connected to the receiver which I guess is unsurprising since it doesn't involve the OS.

If I remove my receiver from `base_usb.py` it still gets picked up correctly as "unknown receiver" in `filter_receivers()`.

Unfortunately I cannot pair my devices directly via bluetooth (seems to be a known issue for my particular MAC) so we will need someone else to test direct Bluetooth and USB connections.

**Comment by pfps** [comment]
One thing to try is to start up Solaar with the receiver disconnected, assuming you can do this, and then plug in the receiver.   Will Solaar pick up the receiver?

**Comment by markopy** [comment]
> One thing to try is to start up Solaar with the receiver disconnected, assuming you can do this, and then plug in the receiver. Will Solaar pick up the receiver?

Yes, this works. There is a random delay of up to 5 seconds of course, until the next check for new devices happens.

**Comment by pfps** [comment]
Recognition of newly active devices is done without a timed loop in the current version of Solaar.  Where did you add the timed loop?

**Comment by markopy** [comment]
It's in the `_DeviceMonitor` class in `hdiapi.py`. I consider this a platform specific implementation detail and once the hdiapi library supports native notifications we can remove the separate monitoring thread.
From Solaar's point of view everything works as it does with `udev.py` by registering a callback via `monitor_glib()`.

**Comment by pfps** [comment]
Solaar requires R/W access to the raw interface for receivers and devices.   How are permissions given to Solaar to allow it to do this?

**Comment by pfps** [comment]
Some parts of rules should work in MacOS.

**Comment by markopy** [comment]
> Solaar requires R/W access to the raw interface for receivers and devices. How are permissions given to Solaar to allow it to do this?

On macOS only keyboard and mouse input devices have special protection. Trying to open them causes a popup with the option to give the application access. I don't think Solaar actually needs to access the keyboard and mouse input though so I have added a check which filters these devices out. No special permissions are then needed to run Solaar and it can still access the Logitech HID++ usage pages.

**Comment by markopy** [comment]
> Some parts of rules should work in MacOS. As far as I can tell the "only" thing that doesn't work but that works under Wayland is simulating user input. Of course this is a big gap.

I think that's right. I haven't really looked into the rules code because I didn't have an immediate need for it but it might be possible to support most or even all of it without much effort. I might look into this when I have a bit more time.

**Comment by pfps** [comment]
It would be good to have someone else run this PR on a mac.

**Comment by barrett7212** [comment]
I can look into running this on my M2 Mac. However, I haven't contributed to this project yet, so might be a while. Still need to learn how to build it from source, install, etc since I have never used this software before.

Are there specific pieces of functionality to test with this? Just connecting a mouse and seeing if it works? I assume I would not want Logitech Options running, or even uninstall it for the test? I have an MX Master 3S to test with.

Thanks in advance. Looking forward to contribute to this due to the privacy concerns with Logitech Options :)

**Comment by mahfoozm** [comment]
When trying to run the PR on a mac (M2 air, 13.1), I would receive the following error:

`solaar: missing required system package python3-pyudev`

After [adding a platform check before loading the module](https://github.com/mahfoozm/Solaar-macOS-support/commit/a8bde60ae33307c945de50a3e8439b34008b12df), it appears that basic functionality is working on Mac.

Screenshot 2023-02-19 at 6 40 24 PM

I can change DPI, enable/disable onboard profiles, and change polling rate. Battery Level also matches up with values reported on Linux and in G Hub. Devices are discovered as they are plugged in and disappear when removed from the system, seamlessly.

**Comment by pfps** [comment]
Excellent.

**Comment by Dak0r** [comment]
Hi, I just tried @mahfoozm s fork on an Intel MacBook.

I installed the mentioned dependencies via brew, but when I run the CLI (like `solaar -dd config "MX Keys" change-host 1`, I'm getting: `ModuleNotFoundError: No module named 'hidapi.hidapi'`

I tried resolving by installing hidapi via pip3 (`pip3 install hidapi`), but that made no difference.

I tried the same version Windows11, ending up with the same error, am I missing something?

**Comment by Dak0r** [comment]
Hi, I just gave it a shot.
With the current version, I also get the `solaar: missing required system package python3-pyudev` error on my Intel Mac.
@mahfoozm s fork is broken for me, due to a missing hidapi.py file in the hidapi lib folder.

So I quickly hacked together, his platform checks with this branch and now the CLI is working fine for me :)
I didn't go far enough to get the UI, running, yet.

**Comment by pfps** [comment]
@markopy I have a suggested change to leave the rules button in, as rules will partly work.

**Comment by mahfoozm** [comment]
> Hi, I just gave it a shot. With the current version, I also get the `solaar: missing required system package python3-pyudev` error on my Intel Mac. @mahfoozm s fork is broken for me, due to a missing hidapi.py file in the hidapi lib folder.
> 
> So I quickly hacked together, his platform checks with this branch and now the CLI is working fine for me :) I didn't go far enough to get the UI, running, yet.

- Oops, forgot to track that file before committing. [Fixed.](https://github.com/markopy/Solaar/pull/1)

**Comment by Dak0r** [comment]
@mahfoozm fork is now working fine!

The CLI & Ui now seems to work right away on macOS with devices connected via a unifying receiver.
It currently doesn't seem to pick up the same devices if connected via Bluetooth (MX Keys and original MX Master).

To get the UI working, I had to install psutil via pip `pip3 install psutil`.
If I switch my devices between bluetooth and unifying receiver, i can see the ui being updated in real time.
Battery level seems to work, and I can also edit settings and see them take effect right away.

**Comment by pfps** [comment]
Solaar detects devices connected to a Logitech receiver by means of messages the receiver emits, so Solaar can see these devices as soon as they are connected.   Solaar on Linux detects receivers and devices that connect via USB or Bluetooth by listening for udev notifications.  This Mac port uses polling for this and may only poll USB connections, not Bluetooth.

Please try removing and reinserting your receiver and see whether it is removed after a short delay and then reappears, again after a short delay.

**Comment by Dak0r** [comment]
> Please try removing and reinserting your receiver and see whether it is removed after a short delay and then reappears, again after a short delay.

This works as you described it, the receiver disappears and re-appears almost immediately after I reconnected it. I can then also see my kb & mouse reconnecting in the ui

**Comment by pfps** [comment]
Good.

But Bluetooth devices don't show up at all in Solaar even if they are actually working on your Mac?

**Comment by pfps** [comment]
The Windows problem will probably have to be investigated by @markopy

**Comment by Dak0r** [comment]
> But Bluetooth devices don't show up at all in Solaar even if they are actually working on your Mac?

that is correct, I just ran `solaar -ddd show` to see it maybe picks them up but errors out and Ineed got some errors, at least for the MX Keys:

```
➜  bin git:(84c15b7) ✗ solaar -ddd show
2023-02-22 13:26:24,006,006     INFO [MainThread] hidapi.hidapi: Found device BID 3 VID 05AC PID 8102 HID++ False False
2023-02-22 13:26:24,013,013     INFO [MainThread] hidapi.hidapi: Found device BID 3 VID 05AC PID 8103 HID++ False False
2023-02-22 13:26:24,070,070     INFO [MainThread] hidapi.hidapi: Found device BID 3 VID 05AC PID 027E HID++ False False
2023-02-22 13:26:24,115,115     INFO [MainThread] hidapi.hidapi: Found device BID 3 VID 05AC PID 8302 HID++ False False
2023-02-22 13:26:24,123,123     INFO [MainThread] hidapi.hidapi: Found device BID 3 VID 05AC PID 8262 HID++ False False
2023-02-22 13:26:24,129,129     INFO [MainThread] hidapi.hidapi: Found device BID 3 VID 05AC PID 8102 HID++ False False
2023-02-22 13:26:24,170,170     INFO [MainThread] hidapi.hidapi: Found device BID 3 VID 05AC PID 027E HID++ False False
2023-02-22 13:26:24,179,179     INFO [MainThread] hidapi.hidapi: Found device BID 3 VID 05AC PID 027E HID++ False False
2023-02-22 13:26:24,189,189     INFO [MainThread] hidapi.hidapi: Found device BID 3 VID 05AC PID 027E HID++ False False
2023-02-22 13:26:24,222,222     INFO [MainThread] hidapi.hidapi: Found device BID 5 VID 046D PID B35B HID++ False False
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: %X format: an integer is required, not NoneType
Call stack:
  File "/usr/local/bin/solaar", line 55, in <module>
    solaar.gtk.main()
  File "/Users/danielkorgel/Dev/Solaar/lib/solaar/gtk.py", line 149, in main
    return _cli.run(args.action, args.hidraw_path)
  File "/Users/danielkorgel/Dev/Solaar/lib/solaar/cli/__init__.py", line 202, in run
    c = list(_receivers_and_devices(hidraw_path))
  File "/Users/danielkorgel/Dev/Solaar/lib/solaar/cli/__init__.py", line 120, in _receivers_and_devices
    for dev_info in receivers_and_devices():
  File "/Users/danielkorgel/Dev/Solaar/lib/logitech_receiver/base.py", line 139, in receivers_and_devices
    yield from _hid.enumerate(filter)
  File "/Users/danielkorgel/Dev/Solaar/lib/hidapi/hidapi.py", line 349, in enumerate
    d_info = _match('add', device, filterfn)
  File "/Users/danielkorgel/Dev/Solaar/lib/hidapi/hidapi.py", line 265, in _match
    _log.info(
Message: 'Found device BID %X VID %04X PID %04X HID++ %s %s'
Arguments: (None, 1452, 34304, False, False)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: %X format: an integer is required, not NoneType
Call stack:
  File "/usr/local/bin/solaar", line 55, in <module>
    solaar.gtk.main()
  File "/Users/danielkorgel/Dev/Solaar/lib/solaar/gtk.py", line 149, in main
    return _cli.run(args.action, args.hidraw_path)
  File "/Users/danielkorgel/Dev/Solaar/lib/solaar/cli/__init__.py", line 202, in run
    c = list(_receivers_and_devices(hidraw_path))
  File "/Users/danielkorgel/Dev/Solaar/lib/solaar/cli/__init__.py", line 120, in _receivers_and_devices
    for dev_info in receivers_and_devices():
  File "/Users/danielkorgel/Dev/Solaar/lib/logitech_receiver/base.py", line 139, in receivers_and_devices
    yield from _hid.enumerate(filter)
  File "/Users/danielkorgel/Dev/Solaar/lib/hidapi/hidapi.py", line 349, in enumerate
    d_info = _match('add', device, filterfn)
  File "/Users/danielkorgel/Dev/Solaar/lib/hidapi/hidapi.py", line 265, in _match
    _log.info(
Message: 'Found device BID %X VID %04X PID %04X HID++ %s %s'
Arguments: (None, 1452, 34304, False, False)
2023-02-22 13:26:24,264,264     INFO [MainThread] hidapi.hidapi: Found device BID 3 VID 413C PID B06E HID++ False False
2023-02-22 13:26:24,275,275     INFO [MainThread] hidapi.hidapi: Found device BID 3 VID 05AC PID 027E HID++ False False
2023-02-22 13:26:24,279,279     INFO [MainThread] hidapi.hidapi: Found device BID 3 VID 0D8C PID 0134 HID++ False False
2023-02-22 13:26:24,281,281     INFO [MainThread] hidapi.hidapi: Found device BID 3 VID 413C PID B06F HID++ False False
2023-02-22 13:26:24,314,314     INFO [MainThread] hidapi.hidapi: Found device BID 5 VID 046D PID B01E HID++ False False
solaar: error: Traceback (most recent call last):
  File "/Users/danielkorgel/Dev/Solaar/lib/solaar/cli/__init__.py", line 206, in run
    raise Exception('No devices found')
Exception: No devices found
```

046D B353B is the MX Keys and 046D B01E is the original MX Master. Both are present in the list, and they disappear from the list if I turn them off.

**Comment by pfps** [comment]
OK, a bug in the code from @markopy that needs to be fixed.  Hopefully he can quickly fix it.  What do you see from `solaar show`?  (The bug appears to be in debugging code.)

**Comment by Dak0r** [comment]
With debugging disabled, and the receiver disconnected, it's just showing the `No devices found error`:

```
solaar: error: Traceback (most recent call last):
  File "/Users/danielkorgel/Dev/Solaar/lib/solaar/cli/__init__.py", line 206, in run
    raise Exception('No devices found')
Exception: No devices found
```

With the receiver connected, it's listing the devices paired to the receiver, as expected, but not mentioning the bluetooth devices at all

**Comment by pfps** [comment]
This PR will likely be updated and merged in the near future but more testing would be useful.

**Comment by pfps** [comment]
@DaPutzy You probably should be using the macos_support branch.  But maybe @markopy has some information on this.

**Comment by markopy** [comment]
Sorry guys, haven't had time to work on this further yet. The `UnboundLocalError` error should indeed already be fixed in in the macos_support branch.

@Dak0r Is the new error you are getting that `python3-pyudev` is missing? I have added a fix for his, please try again if you can.

**Comment by markopy** [comment]
@Dak0r I have fixed the error you reported and added more logging. Can you run `solaar -ddd show` again with your devices connected via bluetooth?

**Comment by pfps** [comment]
Output of `solaar -dd show` and a screenshot would still be useful.

**Comment by pfps** [comment]
Start the GUI via `solaar`.

**Comment by pfps** [comment]
The logging errors in show.txt may have been fixed.   Please download the PR again.

**Comment by pfps** [comment]
@DaPutzy Thanks.  That's looking quite good.

**Comment by pfps** [comment]
@markopy Can you provide @sndri with instructions for Windows?

**Comment by markopy** [comment]
I don't have any specific instructions for Windows beyond the starting points in my initial message for this PR. I don't use Windows and haven't run it there myself.

**Comment by rafalbednarczuk** [comment]
One thing that doesn't work for me on MacOS is `--restart-on-wake-up` option. 
When I execute `solaar --restart-on-wake-up config 1 fn-swap 0` and the computer sleeps and wakes up, after I login into my profile the config is reverted to default.
Is there any way to fix it on MacOS?

**Comment by pfps** [comment]
`--restart-on-wake-up` should only be used for the Solaar GUI.

If you are not running the GUI then devices will reset to their default state whenever they come back from a power-saving mode.    What you should be doing is running `solaar` and using the Solaar main window to change settings.  As long as the Solaar GUI is running, Solaar should monitor devices and push settings to them when they reconnect after going into power-saving modes.

**Comment by rafalbednarczuk** [comment]
> `--restart-on-wake-up` should only be used for the Solaar GUI.
> 
> If you are not running the GUI then devices will reset to their default state whenever they come back from a power-saving mode. What you should be doing is running `solaar` and using the Solaar main window to change settings. As long as the Solaar GUI is running, Solaar should monitor devices and push settings to them when they reconnect after going into power-saving modes.

Thanks, I solved my issue by executing Solaar twice on startup, first time without GUI to switch my setting and second time  with `--window=hide` to keep it running in the background.

**Comment by pfps** [comment]
It should be the case that only the GUI should be needed as the GUI remembers the last value for settings and applies them at startup and at other points where this might be needed.

**Comment by pfps** [comment]
Unfortunately I don't have a Mac to try this PR out on so I can only provide limited assistance.

The messages output do show attempts to connect to various devices but they are failing for some reason that I do not understand.

You might want to try `solaar -ddd show` to get even more messages.

**Comment by vdurante** [comment]
@pfps thanks for the help. Yeah, it shows the same errors with -ddd. I will maybe attempt to debug the code locally later.

**Comment by alexey-chernikov** [comment]
PR is works fine for me with Unifying Receiver (devices MX Keys keyboard, M720 Triathlon mouse).
But Solaar doesn't show devices if they are connected via Bluetooth, not via Unifying Receiver

**Comment by pfps** [comment]
The interface that is used is only for USB.  As I didn't do the port, I don't know what would be required to add Bluetooth support.
I expect that the port will be merged in in the near future so maybe that will get some attention and someone will add Bluetooth support.

**Comment by pfps** [comment]
OK I finally got around to checking that this PR doesn't do anything bad on Linux and then merged it.

**Comment by WWWFWWW** [comment]
Can't get it to build on Mac OS (Sonoma, M1).

Cloned the repo, tried `pip3 install --user '.[report-descriptor,git-commit]'`

and it broke on _patchelf_:

            [ 11%] Creating directories for 'build_patchelf'
            [ 22%] No download step for 'build_patchelf'
            [ 33%] No update step for 'build_patchelf'
            [ 44%] Performing patch step for 'build_patchelf'
            ./bootstrap.sh: line 2: autoreconf: command not found
            make[2]: *** [build_patchelf-prefix/src/build_patchelf-stamp/build_patchelf-patch] Error 127
            make[1]: *** [CMakeFiles/build_patchelf.dir/all] Error 2
            make: *** [all] Error 2
            Traceback (most recent call last):
              File "/private/var/folders/r5/.../T/pip-build-env-hvendzem/overlay/lib/python3.12/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
                cmkr.make(make_args, install_target=cmake_install_target, env=env)
              File "/private/var/folders/r5/g48wy3597sb5pk1y078hdjy80000gn/T/pip-build-env-hvendzem/overlay/lib/python3.12/site-packages/skbuild/cmaker.py", line 697, in make
                self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
              File "/private/var/folders/r5/g48wy3597sb5pk1y078hdjy80000gn/T/pip-build-env-hvendzem/overlay/lib/python3.12/site-packages/skbuild/cmaker.py", line 742, in make_impl
                raise SKBuildError(msg)
                  An error occurred while building with CMake.
              Command:
                /opt/homebrew/bin/cmake --build . --target install --config Release --
              Install target:
                install
              Source directory:
                /private/var/folders/r5/g48wy3597sb5pk1y078hdjy80000gn/T/pip-install-hoouzb5t/patchelf_bd2d5cc251d44de581a28ab6c415bcbf
              Working directory:
                /private/var/folders/r5/g48wy3597sb5pk1y078hdjy80000gn/T/pip-install-hoouzb5t/patchelf_bd2d5cc251d44de581a28ab6c415bcbf/_skbuild/macosx-14.0-arm64-3.12/cmake-build
            Please check the install target is valid and see CMake's output for more information.
      
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for patchelf
      Failed to build patchelf
      ERROR: Could not build wheels for patchelf, which is required to install pyproject.toml-based projects
      [end of output]

Am I doing something wrong? I even tried it in a completely clean Sonoma virtual install, with just Homebrew and Python, no change. Cheers.

**Comment by pfps** [comment]
@markopy Can you figure out what is going wrong here?

**Comment by alexey-chernikov** [comment]
> Can't get it to build on Mac OS (Sonoma, M1).
> 
> Cloned the main repo, tried `pip3 install --user '.[report-descriptor,git-commit]'`
>   ... 
>         ./bootstrap.sh: line 2: autoreconf: command not found
>         make[2]: *** [build_patchelf-prefix/src/build_patchelf-stamp/build_patchelf-patch] Error 127
>         make[1]: *** [CMakeFiles/build_patchelf.dir/all] Error 2
>        ....
> ```
> 
> Am I doing something wrong? I even tried it in a completely clean Sonoma virtual install, with just Homebrew and Python, no change. Cheers.

You are missing autoreconf command on your machine, 
```
brew install automake
``` 
should help with it

**Comment by WWWFWWW** [comment]
> @WWWFWWW You are missing autoreconf command on your machine,
> 
> ```
> brew install automake autoconf
> ```
> 
> should help with it

@alexey-chernikov 

Thanks, but I am still at a loss. Even after that, I get errors with patchelf:

foo.c:5:65: error: argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and section separated by a comma

**Comment by barrett7212** [comment]
@WWWFWWW 
> Thanks, but I am still at a loss. Even after that, I get errors with patchelf:
> 
> foo.c:5:65: error: argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and section separated by a comma
> 
I'm seeing the same on an M2 Max running Sonoma 14.2.1.

If anyone needs me to test a fix, let me know, but also hit a speed bump here.

**Comment by kocoman2** [comment]
what to dl for windows? thx

**Comment by pfps** [comment]
Someone will have to do some work to get the windows port working.   See PR #2165 for more information.

**Comment by widewing** [comment]
> > @WWWFWWW You are missing autoreconf command on your machine,
> > ```
> > brew install automake autoconf
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > should help with it
> 
> @alexey-chernikov
> 
> Thanks, but I am still at a loss. Even after that, I get errors with patchelf:
> 
> foo.c:5:65: error: argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and section separated by a comma
> 
> I'd pretty much love to get it working, as I suspect plenty of Mac users would love using Solaar (the Logitech app for Mac is really abysmal, and that's an understatement). Yet I think the few people here who apparently got it working are not running a default environment, but are devs so their homebrew and python installed packages might somewhat differ.
> 
> I'd love to help testing it and getting it to run, but at this point I am simply at a dead end, sorry.

I'm in the same boat.

**Comment by MattHag** [comment]
I'll play around with with extending the GitHub CI tests to run on Mac, which has the nice side effect, that necessary dependencies are documented. The installation can be simplified to a make command at the same.

**Comment by MattHag** [comment]
@markopy Was there a reason not to use the [pyhidapi package](https://pypi.org/project/hid/) besides the little bit different interface of the Linux udev implementation?

**Comment by mattprintz** [comment]
As detailed in [this comment](https://github.com/pwr-Solaar/Solaar/issues/1586#issuecomment-3038243159) on the Windows port issue (#1586), I am able to confirm that I was able to get Solaar to run on Windows with decent but not full functionality.

**Pull request merged**
